import type { AgentOverride } from "../types";

/** content category agent overrides. See ./index.ts for how these merge. */
export const CONTENT_OVERRIDES: Record<string, AgentOverride> = {
  // ── 210. 社群月曆生成器 ──────────────────────────────────────────────────
  socialcalendar: {
    inputs: [
      { key: "brand", label: "品牌資訊", labelEn: "Brand Info", type: "textarea", required: true, placeholder: "品牌、行業、受眾、行銷目標", placeholderEn: "Brand, industry, audience, marketing goals" },
      { key: "platforms", label: "經營平台", labelEn: "Platforms", type: "text", required: true, placeholder: "例：IG、FB、LinkedIn、Threads、YouTube", placeholderEn: "e.g. IG, FB, LinkedIn, Threads, YouTube" },
      { key: "theme", label: "本月主題 / 活動（選填）", labelEn: "Monthly Theme / Events (optional)", type: "text", required: false, placeholder: "例：週年慶、新品、節慶檔期", placeholderEn: "e.g. anniversary, new product, seasonal campaign" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位社群內容策略師，規劃高互動的月度社群月曆。",
      "", `品牌：${v.brand}`, `平台：${v.platforms}`,
      v.theme ? `主題：${v.theme}` : "",
      "", "### 1. 月度主題框架",
      "本月核心訊息 / 4 個週主題 / 內容支柱比例",
      "輸出 ```chart 圓餅圖顯示內容支柱比例。",
      "", "### 2. 完整內容日曆",
      "4 週每週 3-4 篇，用表格：週/日期/平台/貼文類型/標題/文案重點/Hashtag/視覺建議",
      "每週至少 1 篇互動型貼文。",
      "", "### 3. 各平台優化策略",
      "每個平台的最佳發文時間 / 格式偏好 / 演算法要點 / 互動技巧",
      "", "### 4. 成效追蹤",
      "各平台關鍵指標 + 內容優化建議。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a social content strategist planning a high-engagement monthly social calendar.",
      "", `Brand: ${v.brand}`, `Platforms: ${v.platforms}`,
      v.theme ? `Theme: ${v.theme}` : "",
      "", "### 1. Monthly Theme Framework — core message / 4 weekly themes / content pillar ratios. ```chart pie chart.",
      "### 2. Full Content Calendar — 4 weeks × 3–4 posts, table: week/date/platform/type/title/copy points/hashtags/visual. At least 1 interactive post per week.",
      "### 3. Platform Optimization — best posting times / format preferences / algorithm tips / engagement tactics per platform",
      "### 4. Performance Tracking — key metrics per platform + content optimization. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 214. 產品發布公告生成器 ──────────────────────────────────────────────
  launchannouncement: {
    inputs: [
      { key: "product", label: "產品資訊", labelEn: "Product Info", type: "textarea", required: true, placeholder: "產品名稱、核心功能、亮點、目標用戶", placeholderEn: "Product name, core features, highlights, target users" },
      { key: "date", label: "發布日期", labelEn: "Launch Date", type: "text", required: true, placeholder: "例：2026-07-01", placeholderEn: "e.g. 2026-07-01" },
      { key: "audience", label: "受眾 / 渠道（選填）", labelEn: "Audience / Channels (optional)", type: "text", required: false, placeholder: "現有用戶、媒體、潛在客戶", placeholderEn: "Existing users, media, prospects" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位產品公關文案師,產出完整的發布公告套件。",
      "", `產品：${v.product}`, `發布日：${v.date}`,
      v.audience ? `受眾/渠道：${v.audience}` : "",
      "", "### 1. 新聞稿",
      "標題 / 副標 / 電頭 / 首段（Who/What/Why/When）/ 正文 / 引言 / 公司簡介。400-500字。",
      "", "### 2. 社群公告",
      "Facebook/IG 貼文（≤200字）/ LinkedIn（≤400字）/ Twitter/X（≤280字）",
      "", "### 3. Email 序列",
      "預告信 / 發布日通知 / 跟進信，各附主旨 + 正文重點",
      "", "### 4. 發布策略",
      "用 ```mermaid gantt 規劃發布前後時程（預熱→發布日→跟進）+ 渠道優先序。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a product PR copywriter producing a complete launch announcement kit.",
      "", `Product: ${v.product}`, `Launch date: ${v.date}`,
      v.audience ? `Audience/channels: ${v.audience}` : "",
      "", "### 1. Press Release — headline / subheadline / dateline / lead (Who/What/Why/When) / body / quote / boilerplate. 400–500 words.",
      "### 2. Social Announcements — Facebook/IG (≤200 words) / LinkedIn (≤400) / Twitter/X (≤280)",
      "### 3. Email Sequence — teaser / launch-day notice / follow-up, each with subject + body points",
      "### 4. Launch Strategy — ```mermaid gantt of pre/post-launch timeline (warm-up→launch→follow-up) + channel priority. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 218. SEO 關鍵字研究 ──────────────────────────────────────────────────
  seokeywordresearch: {
    inputs: [
      { key: "business", label: "業務資訊", labelEn: "Business Info", type: "textarea", required: true, placeholder: "公司、產品/服務、目標客戶", placeholderEn: "Company, product/service, target customers" },
      { key: "market", label: "目標市場 / 語言", labelEn: "Target Market / Language", type: "text", required: true, placeholder: "例：台灣繁中、美國英文", placeholderEn: "e.g. Taiwan Traditional Chinese, US English" },
      { key: "competitors", label: "競品網站（選填）", labelEn: "Competitor Sites (optional)", type: "text", required: false, placeholder: "競品網域,用於缺口分析", placeholderEn: "Competitor domains for gap analysis" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位 SEO 關鍵字研究師,找到最高 ROI 的搜尋流量機會。",
      "", `業務：${v.business}`, `市場/語言：${v.market}`,
      v.competitors ? `競品：${v.competitors}` : "",
      "", "### 1. 核心關鍵字",
      "20 個核心關鍵字,用表格：關鍵字/月搜量估算/競爭度/商業意圖/優先度",
      "輸出 ```chart 長條圖顯示各意圖類別關鍵字數量。",
      "", "### 2. 長尾機會",
      "15 個高潛力長尾關鍵字（低競爭、明確意圖）+ 建議內容類型",
      "", "### 3. 競爭缺口",
      v.competitors ? "分析競品關鍵字優勢,找出 5 個可搶佔的缺口" : "識別行業內 5 個未充分競爭的關鍵字機會",
      "", "### 4. 6 個月內容日曆",
      "依關鍵字機會規劃 12-18 篇文章（標題/目標關鍵字/類型/月份）。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are an SEO keyword researcher finding the highest-ROI search traffic opportunities.",
      "", `Business: ${v.business}`, `Market/language: ${v.market}`,
      v.competitors ? `Competitors: ${v.competitors}` : "",
      "", "### 1. Core Keywords — 20 keywords, table: keyword/monthly volume/competition/intent/priority. ```chart bar chart by intent.",
      "### 2. Long-tail Opportunities — 15 high-potential long-tails (low competition, clear intent) + suggested content type",
      v.competitors ? "### 3. Competitive Gap — analyze competitor keyword strengths, find 5 capturable gaps" : "### 3. Competitive Gap — 5 undercompeted keyword opportunities",
      "### 4. 6-Month Content Calendar — 12–18 articles (title/target keyword/type/month). Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 227. 內容創作 Brief 生成器 ───────────────────────────────────────────
  contentbrief: {
    inputs: [
      { key: "topic", label: "文章主題", labelEn: "Article Topic", type: "textarea", required: true, placeholder: "主題、目標、想傳達的核心訊息", placeholderEn: "Topic, goal, core message to convey" },
      { key: "audience", label: "目標讀者", labelEn: "Target Reader", type: "text", required: true, placeholder: "讀者類型、程度、關注點", placeholderEn: "Reader type, level, interests" },
      { key: "keyword", label: "目標關鍵字（選填）", labelEn: "Target Keyword (optional)", type: "text", required: false, placeholder: "想排名的 SEO 關鍵字", placeholderEn: "SEO keyword to rank for" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位內容策略師,為寫手產出清晰、可執行的內容 Brief。",
      "", `主題：${v.topic}`, `讀者：${v.audience}`,
      v.keyword ? `關鍵字：${v.keyword}` : "",
      "", "### 1. SEO 策略",
      v.keyword ? "主關鍵字 + 相關關鍵字 + 搜尋意圖分析 + 競爭內容缺口" : "建議目標關鍵字 + 搜尋意圖 + 內容角度",
      "", "### 2. 文章大綱",
      "標題建議(3個)+ H2/H3 結構 + 各段落要點 + 字數建議",
      "", "### 3. 差異化角度",
      "如何與既有內容不同 / 獨特觀點或數據 / 鉤子設計",
      "", "### 4. 完整 Brief",
      "目標 / 讀者 / 關鍵訊息 / 結構 / 語調 / CTA / 內外連結建議 / 視覺建議。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a content strategist producing clear, actionable content briefs for writers.",
      "", `Topic: ${v.topic}`, `Reader: ${v.audience}`,
      v.keyword ? `Keyword: ${v.keyword}` : "",
      "", v.keyword ? "### 1. SEO Strategy — primary + related keywords + search intent + competitive content gap" : "### 1. SEO Strategy — recommended keywords + search intent + content angle",
      "### 2. Article Outline — 3 title options + H2/H3 structure + paragraph points + word count",
      "### 3. Differentiation Angle — how to differ from existing content / unique view or data / hook design",
      "### 4. Complete Brief — goal / reader / key message / structure / tone / CTA / internal-external links / visuals. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 231. 影音策略規劃師 ──────────────────────────────────────────────────
  videoStrategy: {
    inputs: [
      { key: "brand", label: "品牌描述", labelEn: "Brand Description", type: "textarea", required: true, placeholder: "品牌、行業、目標受眾、現有影音現況", placeholderEn: "Brand, industry, target audience, current video presence" },
      { key: "goal", label: "影音目標", labelEn: "Video Goal", type: "text", required: true, placeholder: "例：品牌知名度、獲客、教育、變現", placeholderEn: "e.g. brand awareness, acquisition, education, monetization" },
      { key: "resources", label: "製作資源（選填）", labelEn: "Production Resources (optional)", type: "text", required: false, placeholder: "團隊、設備、預算、頻率", placeholderEn: "Team, equipment, budget, frequency" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位影音內容策略師,規劃 YouTube 與短影音的成長策略。",
      "", `品牌：${v.brand}`, `目標：${v.goal}`,
      v.resources ? `資源：${v.resources}` : "",
      "", "### 1. 影音策略定位",
      "頻道定位 / 目標受眾 / 內容支柱(4個)/ 長影音 vs 短影音配比",
      "輸出 ```chart 圓餅圖顯示內容支柱比例。",
      "", "### 2. 內容企劃",
      "10 個影片點子(標題+鉤子+格式)/ 系列化建議 / 縮圖與標題策略",
      "", "### 3. 製作計畫",
      "製作流程(企劃→拍攝→剪輯→發布)/ 批量製作建議 / 平台優化(YouTube SEO/短影音演算法)",
      "", "### 4. 成長路徑",
      "訂閱與觀看成長策略 + 變現路徑 + 90 天行動計畫。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a video content strategist planning YouTube and short-video growth.",
      "", `Brand: ${v.brand}`, `Goal: ${v.goal}`,
      v.resources ? `Resources: ${v.resources}` : "",
      "", "### 1. Video Strategy — channel positioning / audience / 4 content pillars / long vs short ratio. ```chart pie chart of pillars.",
      "### 2. Content Planning — 10 video ideas (title+hook+format) / series suggestions / thumbnail & title strategy",
      "### 3. Production Plan — workflow (plan→shoot→edit→publish) / batch production / platform optimization (YouTube SEO/short-video algorithm)",
      "### 4. Growth Path — subscriber & view growth + monetization + 90-day action plan. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 234. 本地化策略師 ────────────────────────────────────────────────────
  localizationAdvisor: {
    inputs: [
      { key: "content", label: "內容 / 產品描述", labelEn: "Content / Product Description", type: "textarea", required: true, placeholder: "要本地化的產品/內容、現有語言、規模", placeholderEn: "Product/content to localize, current language, scale" },
      { key: "markets", label: "目標市場", labelEn: "Target Markets", type: "text", required: true, placeholder: "例：日本、東南亞、拉美、中東", placeholderEn: "e.g. Japan, SEA, LatAm, Middle East" },
      { key: "constraints", label: "限制（選填）", labelEn: "Constraints (optional)", type: "text", required: false, placeholder: "預算、時程、團隊語言能力", placeholderEn: "Budget, timeline, team language capability" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位本地化策略顧問,協助產品/內容成功進入新語言市場。",
      "", `內容/產品：${v.content}`, `目標市場：${v.markets}`,
      v.constraints ? `限制：${v.constraints}` : "",
      "", "### 1. 市場文化適應",
      "各目標市場的文化差異關鍵點 / 需調整的內容(視覺/用語/範例/禁忌)/ 在地化優先順序",
      "", "### 2. 翻譯管理",
      "翻譯策略(機翻+審校/在地譯者/眾包)/ 術語表與風格指南 / 品質把關機制",
      "", "### 3. 技術本地化",
      "i18n 技術考量(日期/貨幣/排版/RTL)/ 內容管理流程 / 持續本地化建議",
      "", "### 4. 在地化執行計畫",
      "用 ```mermaid gantt 規劃本地化時程 + 各市場上線優先序 + 成效衡量。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a localization strategy consultant helping products/content succeed in new language markets.",
      "", `Content/product: ${v.content}`, `Target markets: ${v.markets}`,
      v.constraints ? `Constraints: ${v.constraints}` : "",
      "", "### 1. Cultural Adaptation — key cultural differences per market / content to adjust (visuals/terms/examples/taboos) / localization priority",
      "### 2. Translation Management — strategy (MT+review/local translators/crowdsource) / glossary & style guide / QA mechanism",
      "### 3. Technical Localization — i18n considerations (date/currency/layout/RTL) / content management workflow / continuous localization",
      "### 4. Execution Plan — ```mermaid gantt of localization timeline + market launch priority + measurement. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 235. 部落格文章生成器 ────────────────────────────────────────────────
  blogWriter: {
    inputs: [
      { key: "topic", label: "文章主題", labelEn: "Article Topic", type: "textarea", required: true, placeholder: "主題、想傳達的核心觀點", placeholderEn: "Topic, core point to convey" },
      { key: "audience", label: "目標受眾", labelEn: "Target Audience", type: "text", required: true, placeholder: "讀者類型、程度、關注點", placeholderEn: "Reader type, level, interests" },
      { key: "keyword", label: "SEO 關鍵字 / 語調（選填）", labelEn: "SEO Keyword / Tone (optional)", type: "text", required: false, placeholder: "目標關鍵字、期望語調", placeholderEn: "Target keyword, desired tone" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位部落格寫手,產出結構清晰、引人入勝、SEO 友善的文章。",
      "", `主題：${v.topic}`, `受眾：${v.audience}`,
      v.keyword ? `關鍵字/語調：${v.keyword}` : "",
      "", "### 1. 吸睛標題",
      "5 個標題選項(不同角度：數字型/疑問型/利益型/反差型)",
      "", "### 2. 文章結構",
      "完整大綱(引言鉤子 / H2 段落 / 結論 + CTA)",
      "", "### 3. 完整文章",
      "依大綱撰寫完整文章內容(800-1200字),用 Markdown 排版,適度使用清單與重點標示",
      "", "### 4. SEO 優化建議",
      "Meta description / 關鍵字布局 / 內外連結建議 / 圖片 Alt 建議。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a blog writer producing well-structured, engaging, SEO-friendly articles.",
      "", `Topic: ${v.topic}`, `Audience: ${v.audience}`,
      v.keyword ? `Keyword/tone: ${v.keyword}` : "",
      "", "### 1. Compelling Titles — 5 options (different angles: number/question/benefit/contrast)",
      "### 2. Article Structure — full outline (intro hook / H2 sections / conclusion + CTA)",
      "### 3. Full Article — write complete content (800–1200 words) in Markdown with lists and emphasis where helpful",
      "### 4. SEO Optimization — meta description / keyword placement / internal-external links / image alt suggestions. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 324. 白皮書撰寫師 ────────────────────────────────────────────────────
  whitepaperWriter: {
    inputs: [
      { key: "topic", label: "白皮書主題", labelEn: "Whitepaper Topic", type: "textarea", required: true, placeholder: "主題、核心觀點、想證明什麼、目標讀者", placeholderEn: "Topic, core thesis, what to prove, target reader" },
      { key: "goal", label: "行銷目標", labelEn: "Marketing Goal", type: "text", required: true, placeholder: "例：建立思想領導、潛在客戶、教育市場", placeholderEn: "e.g. thought leadership, lead generation, market education" },
      { key: "audience", label: "目標讀者", labelEn: "Target Reader", type: "text", required: true, placeholder: "讀者類型、專業程度、關注點", placeholderEn: "Reader type, expertise level, interests" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位 B2B 內容策略師,撰寫具說服力與權威感的白皮書。",
      "", `主題：${v.topic}`, `行銷目標：${v.goal}`, `目標讀者：${v.audience}`,
      "", "### 1. 主題定位",
      "白皮書的核心論點 / 獨特觀點 / 為何此刻重要 / 與既有內容的差異",
      "", "### 2. 研究框架",
      "支撐論點所需的論據類型(數據/案例/趨勢/專家)+ 該引用的資料方向",
      "", "### 3. 白皮書結構",
      "完整大綱(執行摘要/問題/分析/解決方案/案例/結論/行動呼籲)+ 各章節要點與篇幅",
      "", "### 4. 論點發展 + 行銷策略",
      "核心章節的論述展開示範 + 白皮書的散布與轉換策略(Gated/推廣/再利用)。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a B2B content strategist writing persuasive, authoritative whitepapers.",
      "", `Topic: ${v.topic}`, `Marketing goal: ${v.goal}`, `Target reader: ${v.audience}`,
      "", "### 1. Topic Positioning — core thesis / unique view / why it matters now / differentiation from existing content",
      "### 2. Research Framework — types of evidence needed (data/cases/trends/experts) + sources to cite",
      "### 3. Whitepaper Structure — full outline (executive summary/problem/analysis/solution/case/conclusion/CTA) + key points and length per section",
      "### 4. Argument Development + Marketing Strategy — sample argument development for core sections + distribution and conversion strategy (gated/promotion/repurposing). Respond in English.",
    ].filter(Boolean).join("\n"),
  },
};
