import type { AgentOverride } from "../types";
import { bilingual, field } from "./helpers";

/** content category agent overrides. See ./index.ts for how these merge. */
export const CONTENT_OVERRIDES: Record<string, AgentOverride> = {
  // ── 210. 社群月曆生成器 ──────────────────────────────────────────────────
  socialcalendar: {
    inputs: [
      { key: "brand", label: "品牌資訊", labelEn: "Brand Info", type: "textarea", required: true, placeholder: "品牌、行業、受眾、行銷目標", placeholderEn: "Brand, industry, audience, marketing goals" },
      { key: "platforms", label: "經營平台", labelEn: "Platforms", type: "text", required: true, placeholder: "例：IG、FB、LinkedIn、Threads、YouTube", placeholderEn: "e.g. IG, FB, LinkedIn, Threads, YouTube" },
      { key: "theme", label: "本月主題 / 活動（選填）", labelEn: "Monthly Theme / Events (optional)", type: "text", required: false, placeholder: "例：週年慶、新品、節慶檔期", placeholderEn: "e.g. anniversary, new product, seasonal campaign" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位社群內容策略師，規劃高互動的月度社群月曆。",
      "", `品牌：${v.brand}`, `平台：${v.platforms}`,
      v.theme ? `主題：${v.theme}` : "",
      "", "### 1. 月度主題框架",
      "本月核心訊息 / 4 個週主題 / 內容支柱比例",
      "輸出 ```chart 圓餅圖顯示內容支柱比例。",
      "", "### 2. 完整內容日曆",
      "4 週每週 3-4 篇，用表格：週/日期/平台/貼文類型/標題/文案重點/Hashtag/視覺建議",
      "每週至少 1 篇互動型貼文。",
      "", "### 3. 各平台優化策略",
      "每個平台的最佳發文時間 / 格式偏好 / 演算法要點 / 互動技巧",
      "", "### 4. 成效追蹤",
      "各平台關鍵指標 + 內容優化建議。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a social content strategist planning a high-engagement monthly social calendar.",
      "", `Brand: ${v.brand}`, `Platforms: ${v.platforms}`,
      v.theme ? `Theme: ${v.theme}` : "",
      "", "### 1. Monthly Theme Framework — core message / 4 weekly themes / content pillar ratios. ```chart pie chart.",
      "### 2. Full Content Calendar — 4 weeks × 3–4 posts, table: week/date/platform/type/title/copy points/hashtags/visual. At least 1 interactive post per week.",
      "### 3. Platform Optimization — best posting times / format preferences / algorithm tips / engagement tactics per platform",
      "### 4. Performance Tracking — key metrics per platform + content optimization. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 214. 產品發布公告生成器 ──────────────────────────────────────────────
  launchannouncement: {
    inputs: [
      { key: "product", label: "產品資訊", labelEn: "Product Info", type: "textarea", required: true, placeholder: "產品名稱、核心功能、亮點、目標用戶", placeholderEn: "Product name, core features, highlights, target users" },
      { key: "date", label: "發布日期", labelEn: "Launch Date", type: "text", required: true, placeholder: "例：2026-07-01", placeholderEn: "e.g. 2026-07-01" },
      { key: "audience", label: "受眾 / 渠道（選填）", labelEn: "Audience / Channels (optional)", type: "text", required: false, placeholder: "現有用戶、媒體、潛在客戶", placeholderEn: "Existing users, media, prospects" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位產品公關文案師,產出完整的發布公告套件。",
      "", `產品：${v.product}`, `發布日：${v.date}`,
      v.audience ? `受眾/渠道：${v.audience}` : "",
      "", "### 1. 新聞稿",
      "標題 / 副標 / 電頭 / 首段（Who/What/Why/When）/ 正文 / 引言 / 公司簡介。400-500字。",
      "", "### 2. 社群公告",
      "Facebook/IG 貼文（≤200字）/ LinkedIn（≤400字）/ Twitter/X（≤280字）",
      "", "### 3. Email 序列",
      "預告信 / 發布日通知 / 跟進信，各附主旨 + 正文重點",
      "", "### 4. 發布策略",
      "用 ```mermaid gantt 規劃發布前後時程（預熱→發布日→跟進）+ 渠道優先序。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a product PR copywriter producing a complete launch announcement kit.",
      "", `Product: ${v.product}`, `Launch date: ${v.date}`,
      v.audience ? `Audience/channels: ${v.audience}` : "",
      "", "### 1. Press Release — headline / subheadline / dateline / lead (Who/What/Why/When) / body / quote / boilerplate. 400–500 words.",
      "### 2. Social Announcements — Facebook/IG (≤200 words) / LinkedIn (≤400) / Twitter/X (≤280)",
      "### 3. Email Sequence — teaser / launch-day notice / follow-up, each with subject + body points",
      "### 4. Launch Strategy — ```mermaid gantt of pre/post-launch timeline (warm-up→launch→follow-up) + channel priority. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 218. SEO 關鍵字研究 ──────────────────────────────────────────────────
  seokeywordresearch: {
    inputs: [
      { key: "business", label: "業務資訊", labelEn: "Business Info", type: "textarea", required: true, placeholder: "公司、產品/服務、目標客戶", placeholderEn: "Company, product/service, target customers" },
      { key: "market", label: "目標市場 / 語言", labelEn: "Target Market / Language", type: "text", required: true, placeholder: "例：台灣繁中、美國英文", placeholderEn: "e.g. Taiwan Traditional Chinese, US English" },
      { key: "competitors", label: "競品網站（選填）", labelEn: "Competitor Sites (optional)", type: "text", required: false, placeholder: "競品網域,用於缺口分析", placeholderEn: "Competitor domains for gap analysis" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位 SEO 關鍵字研究師,找到最高 ROI 的搜尋流量機會。",
      "", `業務：${v.business}`, `市場/語言：${v.market}`,
      v.competitors ? `競品：${v.competitors}` : "",
      "", "### 1. 核心關鍵字",
      "20 個核心關鍵字,用表格：關鍵字/月搜量估算/競爭度/商業意圖/優先度",
      "輸出 ```chart 長條圖顯示各意圖類別關鍵字數量。",
      "", "### 2. 長尾機會",
      "15 個高潛力長尾關鍵字（低競爭、明確意圖）+ 建議內容類型",
      "", "### 3. 競爭缺口",
      v.competitors ? "分析競品關鍵字優勢,找出 5 個可搶佔的缺口" : "識別行業內 5 個未充分競爭的關鍵字機會",
      "", "### 4. 6 個月內容日曆",
      "依關鍵字機會規劃 12-18 篇文章（標題/目標關鍵字/類型/月份）。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are an SEO keyword researcher finding the highest-ROI search traffic opportunities.",
      "", `Business: ${v.business}`, `Market/language: ${v.market}`,
      v.competitors ? `Competitors: ${v.competitors}` : "",
      "", "### 1. Core Keywords — 20 keywords, table: keyword/monthly volume/competition/intent/priority. ```chart bar chart by intent.",
      "### 2. Long-tail Opportunities — 15 high-potential long-tails (low competition, clear intent) + suggested content type",
      v.competitors ? "### 3. Competitive Gap — analyze competitor keyword strengths, find 5 capturable gaps" : "### 3. Competitive Gap — 5 undercompeted keyword opportunities",
      "### 4. 6-Month Content Calendar — 12–18 articles (title/target keyword/type/month). Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 227. 內容創作 Brief 生成器 ───────────────────────────────────────────
  contentbrief: {
    inputs: [
      { key: "topic", label: "文章主題", labelEn: "Article Topic", type: "textarea", required: true, placeholder: "主題、目標、想傳達的核心訊息", placeholderEn: "Topic, goal, core message to convey" },
      { key: "audience", label: "目標讀者", labelEn: "Target Reader", type: "text", required: true, placeholder: "讀者類型、程度、關注點", placeholderEn: "Reader type, level, interests" },
      { key: "keyword", label: "目標關鍵字（選填）", labelEn: "Target Keyword (optional)", type: "text", required: false, placeholder: "想排名的 SEO 關鍵字", placeholderEn: "SEO keyword to rank for" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位內容策略師,為寫手產出清晰、可執行的內容 Brief。",
      "", `主題：${v.topic}`, `讀者：${v.audience}`,
      v.keyword ? `關鍵字：${v.keyword}` : "",
      "", "### 1. SEO 策略",
      v.keyword ? "主關鍵字 + 相關關鍵字 + 搜尋意圖分析 + 競爭內容缺口" : "建議目標關鍵字 + 搜尋意圖 + 內容角度",
      "", "### 2. 文章大綱",
      "標題建議(3個)+ H2/H3 結構 + 各段落要點 + 字數建議",
      "", "### 3. 差異化角度",
      "如何與既有內容不同 / 獨特觀點或數據 / 鉤子設計",
      "", "### 4. 完整 Brief",
      "目標 / 讀者 / 關鍵訊息 / 結構 / 語調 / CTA / 內外連結建議 / 視覺建議。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a content strategist producing clear, actionable content briefs for writers.",
      "", `Topic: ${v.topic}`, `Reader: ${v.audience}`,
      v.keyword ? `Keyword: ${v.keyword}` : "",
      "", v.keyword ? "### 1. SEO Strategy — primary + related keywords + search intent + competitive content gap" : "### 1. SEO Strategy — recommended keywords + search intent + content angle",
      "### 2. Article Outline — 3 title options + H2/H3 structure + paragraph points + word count",
      "### 3. Differentiation Angle — how to differ from existing content / unique view or data / hook design",
      "### 4. Complete Brief — goal / reader / key message / structure / tone / CTA / internal-external links / visuals. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 231. 影音策略規劃師 ──────────────────────────────────────────────────
  videoStrategy: {
    inputs: [
      { key: "brand", label: "品牌描述", labelEn: "Brand Description", type: "textarea", required: true, placeholder: "品牌、行業、目標受眾、現有影音現況", placeholderEn: "Brand, industry, target audience, current video presence" },
      { key: "goal", label: "影音目標", labelEn: "Video Goal", type: "text", required: true, placeholder: "例：品牌知名度、獲客、教育、變現", placeholderEn: "e.g. brand awareness, acquisition, education, monetization" },
      { key: "resources", label: "製作資源（選填）", labelEn: "Production Resources (optional)", type: "text", required: false, placeholder: "團隊、設備、預算、頻率", placeholderEn: "Team, equipment, budget, frequency" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位影音內容策略師,規劃 YouTube 與短影音的成長策略。",
      "", `品牌：${v.brand}`, `目標：${v.goal}`,
      v.resources ? `資源：${v.resources}` : "",
      "", "### 1. 影音策略定位",
      "頻道定位 / 目標受眾 / 內容支柱(4個)/ 長影音 vs 短影音配比",
      "輸出 ```chart 圓餅圖顯示內容支柱比例。",
      "", "### 2. 內容企劃",
      "10 個影片點子(標題+鉤子+格式)/ 系列化建議 / 縮圖與標題策略",
      "", "### 3. 製作計畫",
      "製作流程(企劃→拍攝→剪輯→發布)/ 批量製作建議 / 平台優化(YouTube SEO/短影音演算法)",
      "", "### 4. 成長路徑",
      "訂閱與觀看成長策略 + 變現路徑 + 90 天行動計畫。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a video content strategist planning YouTube and short-video growth.",
      "", `Brand: ${v.brand}`, `Goal: ${v.goal}`,
      v.resources ? `Resources: ${v.resources}` : "",
      "", "### 1. Video Strategy — channel positioning / audience / 4 content pillars / long vs short ratio. ```chart pie chart of pillars.",
      "### 2. Content Planning — 10 video ideas (title+hook+format) / series suggestions / thumbnail & title strategy",
      "### 3. Production Plan — workflow (plan→shoot→edit→publish) / batch production / platform optimization (YouTube SEO/short-video algorithm)",
      "### 4. Growth Path — subscriber & view growth + monetization + 90-day action plan. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 234. 本地化策略師 ────────────────────────────────────────────────────
  localizationAdvisor: {
    inputs: [
      { key: "content", label: "內容 / 產品描述", labelEn: "Content / Product Description", type: "textarea", required: true, placeholder: "要本地化的產品/內容、現有語言、規模", placeholderEn: "Product/content to localize, current language, scale" },
      { key: "markets", label: "目標市場", labelEn: "Target Markets", type: "text", required: true, placeholder: "例：日本、東南亞、拉美、中東", placeholderEn: "e.g. Japan, SEA, LatAm, Middle East" },
      { key: "constraints", label: "限制（選填）", labelEn: "Constraints (optional)", type: "text", required: false, placeholder: "預算、時程、團隊語言能力", placeholderEn: "Budget, timeline, team language capability" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位本地化策略顧問,協助產品/內容成功進入新語言市場。",
      "", `內容/產品：${v.content}`, `目標市場：${v.markets}`,
      v.constraints ? `限制：${v.constraints}` : "",
      "", "### 1. 市場文化適應",
      "各目標市場的文化差異關鍵點 / 需調整的內容(視覺/用語/範例/禁忌)/ 在地化優先順序",
      "", "### 2. 翻譯管理",
      "翻譯策略(機翻+審校/在地譯者/眾包)/ 術語表與風格指南 / 品質把關機制",
      "", "### 3. 技術本地化",
      "i18n 技術考量(日期/貨幣/排版/RTL)/ 內容管理流程 / 持續本地化建議",
      "", "### 4. 在地化執行計畫",
      "用 ```mermaid gantt 規劃本地化時程 + 各市場上線優先序 + 成效衡量。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a localization strategy consultant helping products/content succeed in new language markets.",
      "", `Content/product: ${v.content}`, `Target markets: ${v.markets}`,
      v.constraints ? `Constraints: ${v.constraints}` : "",
      "", "### 1. Cultural Adaptation — key cultural differences per market / content to adjust (visuals/terms/examples/taboos) / localization priority",
      "### 2. Translation Management — strategy (MT+review/local translators/crowdsource) / glossary & style guide / QA mechanism",
      "### 3. Technical Localization — i18n considerations (date/currency/layout/RTL) / content management workflow / continuous localization",
      "### 4. Execution Plan — ```mermaid gantt of localization timeline + market launch priority + measurement. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 235. 部落格文章生成器 ────────────────────────────────────────────────
  blogWriter: {
    inputs: [
      { key: "topic", label: "文章主題", labelEn: "Article Topic", type: "textarea", required: true, placeholder: "主題、想傳達的核心觀點", placeholderEn: "Topic, core point to convey" },
      { key: "audience", label: "目標受眾", labelEn: "Target Audience", type: "text", required: true, placeholder: "讀者類型、程度、關注點", placeholderEn: "Reader type, level, interests" },
      { key: "keyword", label: "SEO 關鍵字 / 語調（選填）", labelEn: "SEO Keyword / Tone (optional)", type: "text", required: false, placeholder: "目標關鍵字、期望語調", placeholderEn: "Target keyword, desired tone" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位部落格寫手,產出結構清晰、引人入勝、SEO 友善的文章。",
      "", `主題：${v.topic}`, `受眾：${v.audience}`,
      v.keyword ? `關鍵字/語調：${v.keyword}` : "",
      "", "### 1. 吸睛標題",
      "5 個標題選項(不同角度：數字型/疑問型/利益型/反差型)",
      "", "### 2. 文章結構",
      "完整大綱(引言鉤子 / H2 段落 / 結論 + CTA)",
      "", "### 3. 完整文章",
      "依大綱撰寫完整文章內容(800-1200字),用 Markdown 排版,適度使用清單與重點標示",
      "", "### 4. SEO 優化建議",
      "Meta description / 關鍵字布局 / 內外連結建議 / 圖片 Alt 建議。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a blog writer producing well-structured, engaging, SEO-friendly articles.",
      "", `Topic: ${v.topic}`, `Audience: ${v.audience}`,
      v.keyword ? `Keyword/tone: ${v.keyword}` : "",
      "", "### 1. Compelling Titles — 5 options (different angles: number/question/benefit/contrast)",
      "### 2. Article Structure — full outline (intro hook / H2 sections / conclusion + CTA)",
      "### 3. Full Article — write complete content (800–1200 words) in Markdown with lists and emphasis where helpful",
      "### 4. SEO Optimization — meta description / keyword placement / internal-external links / image alt suggestions. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 324. 白皮書撰寫師 ────────────────────────────────────────────────────
  whitepaperWriter: {
    inputs: [
      { key: "topic", label: "白皮書主題", labelEn: "Whitepaper Topic", type: "textarea", required: true, placeholder: "主題、核心觀點、想證明什麼、目標讀者", placeholderEn: "Topic, core thesis, what to prove, target reader" },
      { key: "goal", label: "行銷目標", labelEn: "Marketing Goal", type: "text", required: true, placeholder: "例：建立思想領導、潛在客戶、教育市場", placeholderEn: "e.g. thought leadership, lead generation, market education" },
      { key: "audience", label: "目標讀者", labelEn: "Target Reader", type: "text", required: true, placeholder: "讀者類型、專業程度、關注點", placeholderEn: "Reader type, expertise level, interests" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位 B2B 內容策略師,撰寫具說服力與權威感的白皮書。",
      "", `主題：${v.topic}`, `行銷目標：${v.goal}`, `目標讀者：${v.audience}`,
      "", "### 1. 主題定位",
      "白皮書的核心論點 / 獨特觀點 / 為何此刻重要 / 與既有內容的差異",
      "", "### 2. 研究框架",
      "支撐論點所需的論據類型(數據/案例/趨勢/專家)+ 該引用的資料方向",
      "", "### 3. 白皮書結構",
      "完整大綱(執行摘要/問題/分析/解決方案/案例/結論/行動呼籲)+ 各章節要點與篇幅",
      "", "### 4. 論點發展 + 行銷策略",
      "核心章節的論述展開示範 + 白皮書的散布與轉換策略(Gated/推廣/再利用)。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a B2B content strategist writing persuasive, authoritative whitepapers.",
      "", `Topic: ${v.topic}`, `Marketing goal: ${v.goal}`, `Target reader: ${v.audience}`,
      "", "### 1. Topic Positioning — core thesis / unique view / why it matters now / differentiation from existing content",
      "### 2. Research Framework — types of evidence needed (data/cases/trends/experts) + sources to cite",
      "### 3. Whitepaper Structure — full outline (executive summary/problem/analysis/solution/case/conclusion/CTA) + key points and length per section",
      "### 4. Argument Development + Marketing Strategy — sample argument development for core sections + distribution and conversion strategy (gated/promotion/repurposing). Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  technicalWriting: {
    inputs: [
      field("subject", ["產品 / 系統描述", "Product / System Description"], { required: true, placeholder: ["要文件化的產品/API/系統、目標讀者", "Product/API/system to document, target reader"] }),
      field("type", ["文件類型", "Document Type"], { type: "text", required: true, placeholder: ["例：API 文件、使用手冊、技術說明", "e.g. API docs, user manual, technical spec"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位技術文件撰寫師,產出清晰、結構化的技術文件。",
        "", `產品/系統：${v.subject}`, `文件類型：${v.type}`,
        "", "### 1. 文件架構",
        "依文件類型設計章節結構 + 各章節目的 + 讀者導向",
        "", "### 2. 內容大綱",
        "完整大綱(概覽/快速開始/核心內容/範例/疑難排解/參考)+ 各段重點",
        "", "### 3. 範例與程式碼",
        "關鍵範例設計(可運作的程式碼片段/步驟說明)",
        "", "### 4. 可用性",
        "可讀性原則 + 圖表建議 + 維護與版本機制。全程使用繁體中文(程式術語用英文)。",
      ],
      en: (v) => [
        "You are a technical documentation writer producing clear, structured docs.",
        "", `Product/system: ${v.subject}`, `Document type: ${v.type}`,
        "", "### 1. Document Architecture — section structure per doc type + purpose of each + reader orientation",
        "### 2. Content Outline — full outline (overview/quick start/core content/examples/troubleshooting/reference) + key points",
        "### 3. Examples & Code — key example design (working code snippets/step-by-step)",
        "### 4. Usability — readability principles + diagram suggestions + maintenance and versioning. Respond in English.",
      ],
    }),
  },
  pressReleaseWriter: {
    inputs: [
      field("event", ["發布事件描述", "Launch Event Description"], { required: true, placeholder: ["要發布的事件、公司、亮點、引言對象", "Event to announce, company, highlights, quote source"] }),
      field("audience", ["目標媒體 / 受眾（選填）", "Target Media / Audience (optional)"], { type: "text", placeholder: ["例：科技媒體、財經、一般大眾", "e.g. tech media, financial, general public"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位新聞稿撰寫師,產出專業且有媒體吸引力的新聞稿。",
        "", `發布事件：${v.event}`,
        v.audience && `目標媒體/受眾：${v.audience}`,
        "", "### 1. 新聞稿架構",
        "標題 / 副標 / 電頭 / 首段(Who/What/Why/When)/ 正文 / 引言 / 公司簡介,400-600字",
        "", "### 2. 媒體訴求設計",
        "新聞價值角度 + 標題的吸引力 + 為何記者會報導",
        "", "### 3. SEO 優化版本",
        "含關鍵字的標題與描述 + 適合線上發布的版本",
        "", "### 4. 配套素材",
        "媒體接觸建議 + 社群短版 + 預測媒體問題。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a press release writer producing professional, media-worthy releases.",
        "", `Launch event: ${v.event}`,
        v.audience && `Target media/audience: ${v.audience}`,
        "", "### 1. Press Release Structure — headline / subheadline / dateline / lead (Who/What/Why/When) / body / quote / boilerplate, 400-600 words",
        "### 2. Media Angle — news value angle + headline appeal + why journalists would cover it",
        "### 3. SEO-Optimized Version — keyword-rich title and description + online-publishing version",
        "### 4. Companion Assets — media outreach suggestions + short social version + predicted media questions. Respond in English.",
      ],
    }),
  },
  thoughtLeadership: {
    inputs: [
      field("expertise", ["專業領域", "Expertise Area"], { required: true, placeholder: ["專業領域、獨特觀點、目標受眾、平台", "Expertise, unique perspective, target audience, platform"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：建立權威、吸引客戶、人才", "e.g. build authority, attract clients, talent"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位思想領導力內容策略師。",
        "", `專業領域：${v.expertise}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 內容策略",
        "獨特觀點定位(POV)+ 內容支柱(3-4個)+ 與眾不同的角度",
        "", "### 2. 文章主題規劃",
        "12 個高價值文章主題(標題+角度)+ 系列化建議",
        "", "### 3. 傳播渠道設計",
        "各渠道(部落格/LinkedIn/演講/Podcast)的角色與內容改編",
        "", "### 4. 權威建立計畫",
        "建立思想領導地位的 90 天計畫 + 衡量指標。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a thought leadership content strategist.",
        "", `Expertise area: ${v.expertise}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Content Strategy — unique POV positioning + content pillars (3-4) + differentiated angle",
        "### 2. Article Topic Planning — 12 high-value topics (title+angle) + series suggestions",
        "### 3. Distribution Channel Design — role and adaptation per channel (blog/LinkedIn/speaking/podcast)",
        "### 4. Authority Building — 90-day plan to establish thought leadership + metrics. Respond in English.",
      ],
    }),
  },
  newsletterWriter: {
    inputs: [
      field("topic", ["主題與受眾", "Topic and Audience"], { required: true, placeholder: ["電子報主題、目標讀者、品牌、目的", "Newsletter topic, target reader, brand, purpose"] }),
      field("tone", ["語調（選填）", "Tone (optional)"], { type: "text", placeholder: ["例：專業、親切、有趣", "e.g. professional, friendly, fun"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位電子報撰寫師,產出高開信率、高互動的電子報。",
        "", `主題與受眾：${v.topic}`,
        v.tone && `語調：${v.tone}`,
        "", "### 1. 主旨與結構",
        "主旨行(5個高開信率版本)+ Preview 文字 + 整體結構設計",
        "", "### 2. 完整內容",
        "依結構撰寫完整電子報內容(開場鉤子/主體/重點段落)",
        "", "### 3. 號召行動",
        "主要 CTA 設計(3個版本)+ 放置時機 + 次要 CTA",
        "", "### 4. 成效優化",
        "提升開信/點擊的技巧 + 該追蹤的指標。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a newsletter writer producing high-open-rate, high-engagement newsletters.",
        "", `Topic and audience: ${v.topic}`,
        v.tone && `Tone: ${v.tone}`,
        "", "### 1. Subject & Structure — subject line (5 high-open-rate versions) + preview text + overall structure",
        "### 2. Full Content — write the full newsletter per structure (hook opener/body/key sections)",
        "### 3. Call to Action — primary CTA (3 versions) + placement + secondary CTA",
        "### 4. Performance Optimization — techniques to boost open/click + metrics to track. Respond in English.",
      ],
    }),
  },
  copyEditingAdvisor: {
    inputs: [
      field("copy", ["文案內容", "Copy Content"], { required: true, placeholder: ["貼上要潤稿的文案", "Paste the copy to edit"] }),
      field("context", ["品牌 / 目的（選填）", "Brand / Purpose (optional)"], { type: "text", placeholder: ["品牌語調、目標受眾、目的", "Brand voice, target audience, purpose"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位文案潤稿優化師。",
        "", `文案內容：\n${v.copy}`,
        v.context && `品牌/目的：${v.context}`,
        "", "### 1. 清晰度診斷",
        "找出冗詞/模糊/被動/結構問題 + 整體評分",
        "", "### 2. 說服力強化",
        "Before/After 改寫(強化鉤子/利益/具體性)+ 改寫原則",
        "", "### 3. 品牌語調一致",
        "語調是否一致 + 調整建議",
        "", "### 4. 行動號召優化",
        "CTA 改寫(3 版本)+ 放置建議。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a copy editing and optimization advisor.",
        "", `Copy content:\n${v.copy}`,
        v.context && `Brand/purpose: ${v.context}`,
        "", "### 1. Clarity Diagnostic — find wordiness/vagueness/passive voice/structure issues + overall score",
        "### 2. Persuasiveness Enhancement — Before/After rewrites (stronger hook/benefit/specificity) + rewrite principles",
        "### 3. Brand Voice Consistency — whether tone is consistent + adjustments",
        "### 4. CTA Optimization — CTA rewrites (3 versions) + placement advice. Respond in English.",
      ],
    }),
  },
  scriptwriterAdvisor: {
    inputs: [
      field("brief", ["影片 / 腳本需求", "Video / Script Brief"], { required: true, placeholder: ["影片類型、長度、平台、目標、受眾、核心訊息", "Video type, length, platform, goal, audience, core message"] }),
      field("tone", ["風格（選填）", "Tone (optional)"], { type: "text", placeholder: ["例：幽默、專業、感性、教學", "e.g. humorous, professional, emotional, educational"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位影片腳本編劇。",
        "", `腳本需求：${v.brief}`,
        v.tone && `風格：${v.tone}`,
        "", "### 1. 結構設計",
        "依平台/長度的腳本結構(鉤子→鋪陳→高潮→CTA)+ 節奏規劃",
        "", "### 2. 完整腳本",
        "可直接拍攝的腳本(分鏡/旁白/對白/畫面提示),用表格呈現(時間軸/畫面/旁白)",
        "", "### 3. 開場鉤子",
        "3 個前 3 秒抓住注意力的開場方案",
        "", "### 4. 優化建議",
        "提升完播與互動的技巧 + A/B 測試點。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a video scriptwriter.",
        "", `Script brief: ${v.brief}`,
        v.tone && `Tone: ${v.tone}`,
        "", "### 1. Structure Design — script structure by platform/length (hook→build→climax→CTA) + pacing",
        "### 2. Full Script — shoot-ready script (shots/voiceover/dialogue/visual cues), table (timeline/visual/voiceover)",
        "### 3. Opening Hook — 3 first-3-seconds attention-grabbing opening options",
        "### 4. Optimization — techniques to boost completion and engagement + A/B test points. Respond in English.",
      ],
    }),
  },
  contentLocalizationAdvisor: {
    inputs: [
      field("context", ["在地化需求描述", "Localization Need Description"], { required: true, placeholder: ["內容類型、目標語言/市場、現有內容、品牌調性", "Content type, target languages/markets, current content, brand tone"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：進入新市場、文化適配、規模化", "e.g. enter new market, cultural fit, scale"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位內容在地化顧問。",
        "", `在地化需求：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 多語言內容策略",
        "在地化 vs 翻譯 vs 創譯的策略選擇,用表格呈現各市場做法",
        "", "### 2. 文化適配分析",
        "文化差異/禁忌/慣用語/視覺的適配重點",
        "", "### 3. 執行流程",
        "在地化流程(翻譯→在地→審校→測試),用 ```mermaid flowchart 呈現",
        "", "### 4. 品質與規模",
        "品質把關 + 詞彙庫/風格指南 + 規模化機制。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a content localization advisor.",
        "", `Localization need: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Multilingual Content Strategy — strategy choice of localization vs translation vs transcreation, table of approach per market",
        "### 2. Cultural Adaptation Analysis — adaptation focus on cultural differences/taboos/idioms/visuals",
        "### 3. Execution Process — localization process (translate→localize→review→test), ```mermaid flowchart",
        "### 4. Quality & Scale — quality control + glossary/style guide + scaling mechanism. Respond in English.",
      ],
    }),
  },
  longformContentRepurposer: {
    inputs: [
      field("content", ["長文內容描述", "Long-form Content Description"], { required: true, placeholder: ["原文主題、長度、重點、目標渠道", "Source topic, length, key points, target channels"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：社群短文、電子報、影音腳本", "e.g. social posts, newsletter, video scripts"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位長文內容再利用引擎。",
        "", `長文內容：${v.content}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 內容拆解",
        "從長文萃取可獨立成篇的重點與金句,用表格呈現",
        "", "### 2. 多格式改寫",
        "改寫成各格式(社群貼文/Thread/電子報/短影音腳本/圖卡文案),各附範例",
        "", "### 3. 渠道適配",
        "各渠道的調性與長度調整,用 ```mermaid flowchart 呈現再利用流程",
        "", "### 4. 發布排程",
        "內容矩陣與發布節律建議。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a long-form content repurposer engine.",
        "", `Long-form content: ${v.content}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Content Breakdown — extract standalone key points and quotable lines, table",
        "### 2. Multi-Format Rewrite — rewrite into each format (social post/thread/newsletter/short-video script/carousel copy) with examples",
        "### 3. Channel Adaptation — tone and length adjustment per channel, ```mermaid flowchart of repurposing flow",
        "### 4. Publishing Schedule — content matrix and cadence recommendations. Respond in English.",
      ],
    }),
  },
  multiModalAdCreator: {
    inputs: [
      field("brief", ["廣告需求描述", "Ad Brief"], { required: true, placeholder: ["產品、受眾、平台、品牌指南、核心訊息", "Product, audience, platform, brand guide, core message"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：轉換、觸及、品牌、A/B 測試", "e.g. conversion, reach, brand, A/B test"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位多模態廣告素材生成師(提供文案與視覺方向,非實際出圖)。",
        "", `廣告需求：${v.brief}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 素材組合設計",
        "圖文並茂的廣告組合(主視覺方向+標題+內文+CTA),用表格呈現各版本",
        "", "### 2. 視覺方向",
        "符合品牌指南的視覺概念(構圖/色彩/風格)描述",
        "", "### 3. A/B 測試版本",
        "不同角度的測試變體(訊息/視覺/CTA)+ 測試假設",
        "", "### 4. 平台適配",
        "各平台尺寸與規格建議 + 投放重點。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a multi-modal ad creator (copy and visual direction, not actual image generation).",
        "", `Ad brief: ${v.brief}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Ad Bundle Design — visual+copy ad bundles (key-visual direction + headline + body + CTA), table of variants",
        "### 2. Visual Direction — brand-aligned visual concept (composition/colour/style) descriptions",
        "### 3. A/B Test Variants — test variants from different angles (message/visual/CTA) + test hypotheses",
        "### 4. Platform Adaptation — size and spec recommendations per platform + delivery focus. Respond in English.",
      ],
    }),
  },
  localizationQAEngine: {
    inputs: [
      field("content", ["在地化內容描述", "Localized Content Description"], { required: true, placeholder: ["語言/市場、內容類型、品牌調性、現有問題", "Languages/markets, content type, brand tone, current issues"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：文化適切、語調一致、品質", "e.g. cultural fit, tone consistency, quality"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位本地化品質審查引擎。",
        "", `在地化內容：${v.content}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 審查維度",
        "從準確性/文化適切/語調一致/格式/在地慣例審查,用表格呈現",
        "", "### 2. 文化適切性",
        "文化禁忌/慣用語/敏感點的檢查重點",
        "", "### 3. 品牌語調一致",
        "與品牌調性的一致性 + 偏離與修正",
        "", "### 4. 品質流程",
        "QA 流程,用 ```mermaid flowchart 呈現 + 詞彙庫/風格指南。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a localization QA engine.",
        "", `Localized content: ${v.content}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Review Dimensions — review by accuracy/cultural fit/tone consistency/formatting/local conventions, table",
        "### 2. Cultural Appropriateness — checks for taboos/idioms/sensitive points",
        "### 3. Brand Tone Consistency — consistency with brand tone + deviations and fixes",
        "### 4. Quality Process — QA process, ```mermaid flowchart + glossary/style guide. Respond in English.",
      ],
    }),
  },
  contentComplianceReviewer: {
    inputs: [
      field("content", ["待審內容描述", "Content to Review Description"], { required: true, placeholder: ["內容類型、行業、適用法規、品牌安全標準", "Content type, industry, applicable regulations, brand safety standards"] }),
      field("concern", ["關注（選填）", "Concern (optional)"], { type: "text", placeholder: ["例：廣告法、個資、智財、品牌安全", "e.g. ad law, privacy, IP, brand safety"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位內容合規審查助手。",
        "⚠️ 此為一般性建議,法規疑慮請諮詢法務。",
        "", `待審內容：${v.content}`,
        v.concern && `關注：${v.concern}`,
        "", "### 1. 合規審查",
        "從法規(廣告/個資/智財)與品牌安全審查,用表格呈現風險項",
        "", "### 2. 風險標記",
        "高風險用語/宣稱/素材 + 風險等級",
        "", "### 3. 修正建議",
        "各風險項的合規改寫建議",
        "", "### 4. 審查機制",
        "發布前檢查清單 + 留存 + 流程。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a content compliance reviewer.",
        "⚠️ General guidance only — consult legal for regulatory concerns.",
        "", `Content to review: ${v.content}`,
        v.concern && `Concern: ${v.concern}`,
        "", "### 1. Compliance Review — review by regulations (advertising/privacy/IP) and brand safety, table of risk items",
        "### 2. Risk Flagging — high-risk wording/claims/assets + risk level",
        "### 3. Revision Recommendations — compliant rewrite suggestions per risk item",
        "### 4. Review Mechanism — pre-publish checklist + retention + process. Respond in English.",
      ],
    }),
  },
  technicalDocSynthesizer: {
    inputs: [
      field("context", ["技術文件需求", "Technical Doc Need"], { required: true, placeholder: ["產品/API、讀者、現有資料、文件類型", "Product/API, audience, existing material, doc type"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：API 文件、整合指南、開發手冊", "e.g. API docs, integration guide, developer handbook"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位技術文件合成助手。",
        "", `技術文件需求：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 文件結構",
        "依文件類型的結構(總覽/快速開始/參考/範例/錯誤),用表格呈現",
        "", "### 2. 範例內容",
        "關鍵章節的範例內容(含程式碼/請求回應範例)",
        "", "### 3. 開發者體驗",
        "易用性 / 可掃描 / 漸進揭露 + 常見問題",
        "", "### 4. 維護機制",
        "文件即程式碼 + 與發版同步 + 防過時。全程使用繁體中文(技術詞用英文)。",
      ],
      en: (v) => [
        "You are a technical doc synthesizer.",
        "", `Technical doc need: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Doc Structure — structure by doc type (overview/quickstart/reference/examples/errors), table",
        "### 2. Sample Content — sample content for key sections (with code/request-response examples)",
        "### 3. Developer Experience — usability / scannability / progressive disclosure + FAQs",
        "### 4. Maintenance Mechanism — docs-as-code + sync with releases + prevent staleness. Respond in English.",
      ],
    }),
  },
  brandVoiceConsistencyAI: {
    inputs: [
      field("content", ["跨渠道內容描述", "Cross-Channel Content Description"], { required: true, placeholder: ["渠道、內容樣本、品牌語調、現有問題", "Channels, content samples, brand voice, current issues"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：語調一致、跨團隊、品質", "e.g. tone consistency, cross-team, quality"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位品牌聲音一致性 AI。",
        "", `跨渠道內容：${v.content}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 一致性分析",
        "各渠道內容的語調/風格一致性評估,用表格呈現",
        "輸出 ```chart 長條圖顯示各渠道語調一致性評分。",
        "", "### 2. 偏離識別",
        "偏離品牌聲音之處 + 影響",
        "", "### 3. 校準建議",
        "各偏離的校準方向 + 改寫範例(前/後)",
        "", "### 4. 維持機制",
        "風格指南 + 檢核 + 團隊賦能。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a brand voice consistency AI.",
        "", `Cross-channel content: ${v.content}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Consistency Analysis — tone/style consistency assessment per channel, table. ```chart bar chart of voice consistency score per channel.",
        "### 2. Deviation Identification — deviations from brand voice + impact",
        "### 3. Calibration Recommendations — calibration direction per deviation + rewrite examples (before/after)",
        "### 4. Maintenance Mechanism — style guide + review + team enablement. Respond in English.",
      ],
    }),
  },
  seoQualityAuditor: {
    inputs: [
      field("content", ["網頁 / 內容描述", "Webpage / Content Description"], { required: true, placeholder: ["頁面、目標關鍵字、現有 SEO、痛點", "Page, target keywords, current SEO, pain points"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：提升排名、結構優化、可讀", "e.g. improve ranking, structure, readability"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位 SEO 品質稽核助手。",
        "", `網頁/內容：${v.content}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. SEO 結構稽核",
        "標題層級/Meta/關鍵字/內鏈/結構化資料稽核,用表格呈現",
        "輸出 ```chart 長條圖顯示各 SEO 面向評分。",
        "", "### 2. 內容品質",
        "搜尋意圖匹配 / E-E-A-T / 可讀性 / 原創性",
        "", "### 3. 優化行動清單",
        "依影響排序的優化行動",
        "", "### 4. 衡量",
        "追蹤指標 + 優化節律。全程使用繁體中文(關鍵字用原文)。",
      ],
      en: (v) => [
        "You are an SEO quality auditor.",
        "", `Webpage/content: ${v.content}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. SEO Structure Audit — audit heading hierarchy/meta/keywords/internal links/structured data, table. ```chart bar chart of score per SEO aspect.",
        "### 2. Content Quality — search intent match / E-E-A-T / readability / originality",
        "### 3. Optimization Action List — optimization actions ranked by impact",
        "### 4. Measurement — tracking metrics + optimization cadence. Respond in English.",
      ],
    }),
  },
  userguideAutoGenerator: {
    inputs: [
      field("context", ["產品 / 功能描述", "Product / Feature Description"], { required: true, placeholder: ["產品、功能、變更、終端用戶、現有文件", "Product, feature, changes, end users, current docs"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：新功能指南、更新、降客服量", "e.g. new feature guide, updates, reduce support load"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位使用指南自動生成器。",
        "", `產品/功能：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 指南結構",
        "終端用戶指南結構(情境任務導向),用表格呈現章節",
        "", "### 2. 步驟內容",
        "關鍵任務的逐步操作說明(含提示與注意事項)",
        "", "### 3. 易懂設計",
        "用詞淺白 / 視覺輔助建議 / 常見問題",
        "", "### 4. 更新機制",
        "依功能變更更新 + 版本 + 多語。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a user guide auto-generator.",
        "", `Product/feature: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Guide Structure — end-user guide structure (task/scenario-oriented), table of sections",
        "### 2. Step Content — step-by-step instructions for key tasks (with tips and cautions)",
        "### 3. Clarity Design — plain language / visual aid suggestions / FAQs",
        "### 4. Update Mechanism — update on feature changes + versioning + multilingual. Respond in English.",
      ],
    }),
  },
  editorialWorkflowGuide: {
    inputs: [
      field("context", ["內容生產現況描述", "Content Production Status Description"], { required: true, placeholder: ["團隊、內容量、現有流程、瓶頸", "Team, content volume, current process, bottlenecks"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：減審批、加速發布、品質", "e.g. fewer approvals, faster publishing, quality"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位編輯工作流程顧問。",
        "", `內容生產現況：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 流程診斷",
        "從構思到發布的流程診斷與瓶頸,用 ```mermaid flowchart 呈現現況流程",
        "", "### 2. 審批優化",
        "減少審批環節 + 角色職責釐清 + 並行化",
        "", "### 3. 發布加速",
        "縮短發布延遲的行動 + 範本與自動化",
        "", "### 4. 落地與衡量",
        "優化後流程 + 週期時間指標 + 持續改善。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are an editorial workflow advisor.",
        "", `Content production status: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Process Diagnostic — diagnose ideation-to-publish flow and bottlenecks, ```mermaid flowchart of current process",
        "### 2. Approval Optimization — reduce approval cycles + clarify roles + parallelization",
        "### 3. Publishing Acceleration — actions to shorten publishing delay + templates and automation",
        "### 4. Implementation & Measurement — optimized process + cycle-time metrics + continuous improvement. Respond in English.",
      ],
    }),
  },
  localizedContentTester: {
    inputs: [
      field("content", ["本地化內容描述", "Localized Content Description"], { required: true, placeholder: ["語言/市場、內容類型、格式需求、現有問題", "Languages/markets, content type, formatting needs, current issues"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：格式正確、文化相容、品質", "e.g. formatting correctness, cultural compatibility, quality"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位本地化內容測試器。",
        "", `本地化內容：${v.content}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 格式測試",
        "格式正確性測試(日期/數字/貨幣/斷行/字元/版面),用表格呈現檢查項",
        "", "### 2. 文化相容性",
        "市場文化相容性測試重點(圖像/色彩/慣例/敏感)",
        "", "### 3. 功能測試",
        "在地化後的功能/連結/動態內容測試",
        "", "### 4. 測試流程",
        "測試案例 + 流程,用 ```mermaid flowchart 呈現。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a localized content tester.",
        "", `Localized content: ${v.content}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Formatting Test — formatting correctness tests (date/number/currency/line breaks/characters/layout), table of checks",
        "### 2. Cultural Compatibility — cultural compatibility test focus (imagery/colour/conventions/sensitivities)",
        "### 3. Functional Test — post-localization function/link/dynamic-content testing",
        "### 4. Test Process — test cases + process, ```mermaid flowchart. Respond in English.",
      ],
    }),
  },
  knowledgeBaseRefreshAI: {
    inputs: [
      field("context", ["知識庫描述", "Knowledge Base Description"], { required: true, placeholder: ["知識庫規模、主題、更新頻率、痛點", "KB size, topics, update frequency, pain points"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：找過期、更新、提升正確", "e.g. find outdated, update, improve accuracy"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位知識庫更新優化 AI。",
        "", `知識庫：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 過期識別",
        "依時效/瀏覽/反饋/關聯變更識別過期條目,用表格呈現",
        "", "### 2. 更新優先序",
        "依影響(瀏覽量 x 過期風險)排序待更新條目",
        "輸出 ```chart 長條圖顯示各主題的更新急迫度。",
        "", "### 3. 更新草稿方向",
        "高優先條目的更新內容方向與重點",
        "", "### 4. 維護機制",
        "定期審查 + 過期偵測 + 擁有者制。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a knowledge base refresh AI.",
        "", `Knowledge base: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Staleness Identification — identify outdated entries by recency/views/feedback/related changes, table",
        "### 2. Update Priority — rank entries to update by impact (views x staleness risk). ```chart bar chart of update urgency per topic.",
        "### 3. Update Draft Direction — update content direction and focus for high-priority entries",
        "### 4. Maintenance Mechanism — periodic review + staleness detection + ownership. Respond in English.",
      ],
    }),
  },
  contentPlagiarismGuard: {
    inputs: [
      field("content", ["內容描述", "Content Description"], { required: true, placeholder: ["內容類型、來源、發布渠道、關注", "Content type, sources, publishing channels, concerns"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：抄襲風險、原創性、重複率", "e.g. plagiarism risk, originality, duplication"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位內容抄襲防護顧問。",
        "", `內容：${v.content}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 風險識別",
        "潛在抄襲/重複風險點(直接複製/改寫不足/未引用)識別,用表格呈現",
        "", "### 2. 原創性評估",
        "原創性與重複率的評估方向 + 自我抄襲(跨頁重複)",
        "", "### 3. 修正建議",
        "高風險段落的改寫/引用建議",
        "", "### 4. 防護流程",
        "發布前查核流程,用 ```mermaid flowchart 呈現 + 引用規範。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a content plagiarism guard advisor.",
        "", `Content: ${v.content}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Risk Identification — identify potential plagiarism/duplication risk points (direct copy/insufficient paraphrase/uncited), table",
        "### 2. Originality Assessment — originality and duplication assessment direction + self-plagiarism (cross-page duplication)",
        "### 3. Revision Recommendations — rewrite/citation suggestions for high-risk passages",
        "### 4. Guard Process — pre-publish check process, ```mermaid flowchart + citation standards. Respond in English.",
      ],
    }),
  },
  thoughtLeadershipPlanner: {
    inputs: [
      field("context", ["高管 / 主題描述", "Executive / Topic Description"], { required: true, placeholder: ["高管角色、專業領域、受眾、平台、目標", "Executive role, expertise area, audience, platforms, goals"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：產業影響力、個人品牌、商機", "e.g. industry influence, personal brand, pipeline"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位思想領導規劃顧問。",
        "", `高管/主題：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 觀點定位", "獨特的思想領導觀點與支柱主題,用表格呈現",
        "", "### 2. 內容日曆", "高管內容日曆(主題/格式/平台/節律),用 ```mermaid gantt 呈現",
        "", "### 3. 內容形式", "各平台的內容形式與切角",
        "", "### 4. 影響力建立", "互動/擴散/影響力指標。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a thought leadership planner.",
        "", `Executive/topic: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. POV Positioning — unique thought leadership POV and pillar themes, table",
        "### 2. Content Calendar — executive content calendar (topic/format/platform/cadence), ```mermaid gantt",
        "### 3. Content Formats — content formats and angles per platform",
        "### 4. Influence Building — engagement/reach/influence metrics. Respond in English.",
      ],
    }),
  },
  caseStudyAutoBuilder: {
    inputs: [
      field("context", ["客戶成功描述", "Customer Success Description"], { required: true, placeholder: ["客戶、問題、方案、成果數據、引言", "Customer, problem, solution, results data, quotes"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：高轉換案例、銷售素材", "e.g. high-converting case study, sales collateral"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位客戶案例自動化建構師。",
        "", `客戶成功：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 案例結構", "高轉換案例結構(挑戰→方案→成果→引言)+ 各段重點",
        "", "### 2. 成果呈現", "量化成果的有力呈現,用表格呈現(指標/前/後)",
        "輸出 ```chart 長條圖顯示關鍵成果前後對比。",
        "", "### 3. 完整草稿", "可直接用的案例草稿",
        "", "### 4. 多格式", "官網/銷售/社群版本。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a case study auto-builder.",
        "", `Customer success: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Case Structure — high-converting structure (challenge→solution→results→quote) + focus per section",
        "### 2. Results Presentation — compelling presentation of quantified results, table (metric/before/after). ```chart bar chart of key results before vs after.",
        "### 3. Full Draft — ready-to-use case study draft",
        "### 4. Multi-Format — website/sales/social versions. Respond in English.",
      ],
    }),
  },
};
