import type { AgentOverride } from "../types";

/** finance category agent overrides. See ./index.ts for how these merge. */
export const FINANCE_OVERRIDES: Record<string, AgentOverride> = {
  // ── 5. ROI 試算 ───────────────────────────────────────────────────────────
  roi: {
    inputs: [
      {
        key: "company",
        label: "公司名稱 / 規模 / 產業",
        labelEn: "Company Name / Size / Industry",
        type: "text",
        required: true,
        placeholder: "例：某製造業，員工 80 人，年營收約 1.2 億",
        placeholderEn: "e.g. Manufacturing company, 80 employees, annual revenue ~NT$120M",
      },
      {
        key: "processes",
        label: "目前主要流程（想導入 AI 的環節）",
        labelEn: "Current Processes (areas to automate with AI)",
        type: "textarea",
        required: true,
        placeholder: "例：客服回覆（每天 200 封信）、報表整理（每週 8 小時）、採購詢報價",
        placeholderEn: "e.g. Customer replies (200 emails/day), Report prep (8h/week), Procurement RFQ",
      },
      {
        key: "budget",
        label: "預估導入預算（選填）",
        labelEn: "Estimated AI Adoption Budget (optional)",
        type: "text",
        required: false,
        placeholder: "例：年度 50 萬、月費 3 萬、不確定",
        placeholderEn: "e.g. NT$500K/year, NT$30K/month, unsure",
      },
    ],
    prompt: (v, lang) =>
      lang === "zh"
        ? [
            "你是一位企業 AI 導入效益評估顧問，擅長以具體數字量化投資回報。",
            "",
            `公司資訊：${v.company}`,
            `目標流程：${v.processes}`,
            v.budget ? `預算：${v.budget}` : "",
            "",
            "請依以下架構輸出 ROI 試算報告：",
            "",
            "### 1. 現況成本估算",
            "針對每個流程：目前耗費人時（人/小時/月）× 時薪成本 = 月成本",
            "用 Markdown 表格列出，最下方加總。",
            "",
            "### 2. 導入 AI 後的效益估算",
            "每個流程的自動化率（保守 / 樂觀 / 激進）三情境，以表格呈現節省的人時與金額。",
            "輸出一個 ```chart 長條圖，比較三種情境的月節省金額。",
            "",
            "### 3. 導入成本估算",
            "硬體/訂閱/開發/訓練/維運 各項費用預估（依提供預算調整）",
            "",
            "### 4. ROI 計算",
            "公式：ROI = (年節省 - 年導入成本) / 年導入成本 × 100%",
            "三情境的回收期（月）用表格顯示。",
            "輸出一個 ```chart 折線圖，顯示 12 個月累積投資回收曲線（三情境）。",
            "",
            "### 5. 建議優先導入順序",
            "依 ROI 高低排序，列出 1-3 個最值得優先啟動的流程。",
            "全程使用繁體中文。",
          ]
            .filter(Boolean)
            .join("\n")
        : [
            "You are an enterprise AI adoption ROI consultant who quantifies returns with concrete numbers.",
            "",
            `Company: ${v.company}`,
            `Target Processes: ${v.processes}`,
            v.budget ? `Budget: ${v.budget}` : "",
            "",
            "Deliver an ROI analysis report:",
            "",
            "### 1. Current Cost Baseline",
            "Per process: current labor hours (people × hrs/month) × hourly cost = monthly cost. Markdown table with totals.",
            "",
            "### 2. AI-Enabled Savings",
            "Automation rate × 3 scenarios (conservative / realistic / aggressive). Table of hours saved and dollar value. Output a ```chart bar chart comparing monthly savings across scenarios.",
            "",
            "### 3. Adoption Cost Estimate",
            "Hardware / subscriptions / development / training / maintenance — itemized.",
            "",
            "### 4. ROI Calculation",
            "Formula: ROI = (Annual savings − Annual cost) / Annual cost × 100%. Payback period (months) per scenario in a table. Output a ```chart line chart showing 12-month cumulative ROI curve (3 scenarios).",
            "",
            "### 5. Priority Recommendation",
            "Top 1–3 processes to start first, ranked by ROI.",
            "Respond entirely in English.",
          ]
            .filter(Boolean)
            .join("\n"),
  },
  // ── 14. Pitch Deck 故事 ───────────────────────────────────────────────────
  pitchdeck: {
    inputs: [
      { key: "startup", label: "公司名稱 / 產品簡述", labelEn: "Company / Product Summary", type: "textarea", required: true, placeholder: "公司名稱、解決什麼問題、怎麼解決", placeholderEn: "Company name, what problem you solve, how" },
      { key: "traction", label: "牽引力數據", labelEn: "Traction Data", type: "textarea", required: true, placeholder: "用戶數、營收、成長率、重要里程碑…", placeholderEn: "Users, revenue, growth rate, key milestones…" },
      { key: "ask", label: "融資金額 / 用途", labelEn: "Funding Ask / Use of Funds", type: "text", required: true, placeholder: "例：求融 500 萬美元，30% 產品、40% 銷售、30% 運營", placeholderEn: "e.g. Raising $5M: 30% product, 40% sales, 30% ops" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位創業投資簡報策略師，擅長將創業故事轉化為打動投資人的 Pitch Deck。",
      "", `公司：${v.startup}`, `牽引力：${v.traction}`, `融資：${v.ask}`,
      "", "請逐張輸出 Pitch Deck 腳本（10張投影片）：",
      "1. **封面** — 公司名稱、一句話描述、聯絡資訊",
      "2. **問題** — 痛點描述（市場現狀的3個問題），配統計數據",
      "3. **解決方案** — 你如何解決、核心差異化（3點）",
      "4. **產品** — 主要功能、使用流程（用 ```mermaid flowchart 畫用戶旅程）",
      "5. **市場規模** — TAM/SAM/SOM 計算，配 ```chart 泡泡圖替代方案（長條圖）",
      "6. **商業模式** — 收費方式、單位經濟學（LTV/CAC）",
      "7. **牽引力** — 關鍵指標成長（配 ```chart 折線圖）",
      "8. **競爭格局** — 競爭矩陣，我方優勢",
      "9. **團隊** — 核心成員背景（為何是你們？）",
      "10. **融資計畫** — 金額、用途分配、18個月里程碑",
      "", "最後：預測投資人會問的TOP 5問題，附建議回答。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a pitch deck strategist who transforms startup stories into investor-ready presentations.",
      "", `Company: ${v.startup}`, `Traction: ${v.traction}`, `Ask: ${v.ask}`,
      "", "Script all 10 slides:",
      "1. Cover | 2. Problem (3 pain points + stats) | 3. Solution (3 differentiators) | 4. Product (user flow in ```mermaid flowchart) | 5. Market (TAM/SAM/SOM + ```chart bar) | 6. Business Model (LTV/CAC) | 7. Traction (```chart line chart) | 8. Competition matrix | 9. Team | 10. Funding plan + 18-month milestones",
      "", "Finally: Top 5 investor questions with recommended answers. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 23. 財務健康掃描器 ───────────────────────────────────────────────────
  financial: {
    inputs: [
      { key: "company", label: "公司名稱 / 行業 / 規模", labelEn: "Company / Industry / Size", type: "text", required: true, placeholder: "例：台灣餐飲連鎖，30 家門市，年營收 1.5 億", placeholderEn: "e.g. Taiwan F&B chain, 30 locations, annual revenue NT$150M" },
      { key: "revenue", label: "近期財務數據", labelEn: "Recent Financial Data", type: "textarea", required: true, placeholder: "月營收/年營收、毛利率、淨利率、主要費用類別", placeholderEn: "Monthly/annual revenue, gross margin, net margin, main expense categories" },
      { key: "cashflow", label: "現金流狀況（選填）", labelEn: "Cash Flow Situation (optional)", type: "textarea", required: false, placeholder: "現金餘額、應收帳款、燒錢率、是否有資金缺口", placeholderEn: "Cash balance, AR, burn rate, funding gap if any" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位企業財務健康診斷顧問，擅長從有限數據中快速識別財務風險和改善機會。",
      "", `公司：${v.company}`, `財務數據：${v.revenue}`,
      v.cashflow ? `現金流：${v.cashflow}` : "",
      "", "### 1. 財務健康儀表板",
      "評估以下指標（依提供數據計算或估算），用表格呈現：",
      "營收成長率 / 毛利率 / 淨利率 / EBITDA 估算 / 現金轉換週期 / 應收帳款天數",
      "每項指標：數值 / 行業標竿 / 評級（🟢健康/🟡警示/🔴危險）",
      "輸出 ```chart 長條圖顯示各指標評分。",
      "", "### 2. 現金流分析",
      "現金流現況評估 / 主要現金流風險 / 燒錢率分析（若有）/ 現金跑道估算",
      "", "### 3. 成本結構優化",
      "識別主要成本類別 / 指出 3 個最有潛力的降本機會（附估算節省金額）",
      "", "### 4. 成長融資選項",
      "適合當前階段的 3 種融資方式，每種：融資工具 / 適用條件 / 優缺點 / 預估成本",
      "", "### 5. 90 天財務改善計畫",
      "用表格：週次 / 行動項目 / 負責角色 / 預期效益。",
      "用 ```mermaid gantt 呈現。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a financial health diagnostician who identifies risks and opportunities from limited data.",
      "", `Company: ${v.company}`, `Financial Data: ${v.revenue}`,
      v.cashflow ? `Cash Flow: ${v.cashflow}` : "",
      "", "### 1. Financial Health Dashboard — table: Metric / Value / Industry benchmark / Rating (🟢/🟡/🔴) for: Revenue growth / Gross margin / Net margin / EBITDA / Cash conversion cycle / AR days. Output ```chart bar chart.",
      "### 2. Cash Flow Analysis — current situation / key risks / burn rate / runway estimate",
      "### 3. Cost Structure — 3 highest-potential cost reduction opportunities with estimated savings",
      "### 4. Financing Options — 3 suitable instruments: Tool / Eligibility / Pros & cons / Estimated cost",
      "### 5. 90-Day Improvement Plan — table + ```mermaid gantt. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 30. 定價實驗設計師 ───────────────────────────────────────────────────
  pricinglab: {
    inputs: [
      { key: "product", label: "產品 / 服務", labelEn: "Product / Service", type: "textarea", required: true, placeholder: "產品名稱、主要功能、目前定價（若有）", placeholderEn: "Product name, main features, current pricing if any" },
      { key: "segments", label: "目標客群", labelEn: "Target Customer Segments", type: "text", required: true, placeholder: "例：個人用戶、中小企業、大型企業", placeholderEn: "e.g. individual users, SMEs, enterprise" },
      { key: "goal", label: "定價目標", labelEn: "Pricing Goal", type: "text", required: false, placeholder: "例：提升 MRR、增加 LTV、擴大用戶數", placeholderEn: "e.g. increase MRR, improve LTV, grow user base" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位定價策略師，擅長設計數據驅動的定價實驗和可持續的定價架構。",
      "", `產品：${v.product}`, `客群：${v.segments}`,
      v.goal ? `目標：${v.goal}` : "",
      "", "### 1. 定價策略選項分析",
      "比較 4 種定價模式（訂閱制/用量計費/免費增值/一次性），用表格：模式/適用場景/優點/缺點/建議採用條件。",
      "", "### 2. 各客群支付意願（WTP）估算",
      "每個客群：WTP 範圍估算 / 價格敏感指標 / 最大化收益的建議定價點",
      "輸出 ```chart 長條圖顯示各客群建議定價。",
      "", "### 3. A/B 定價實驗設計",
      "設計 3 個可執行的定價實驗：假設 / 測試方法 / 樣本量估算 / 評估指標 / 執行期間",
      "", "### 4. 方案架構建議（Tier Design）",
      "設計 3 個訂閱方案（Free/Pro/Business 或類似），每個方案：名稱/定價/包含功能/目標客群/轉換策略",
      "", "### 5. 6 個月定價手冊",
      "月份 / 定價行動 / 評估指標 / 調整觸發條件，用 Markdown 表格呈現。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a pricing strategist who designs data-driven pricing experiments and sustainable pricing structures.",
      "", `Product: ${v.product}`, `Segments: ${v.segments}`,
      v.goal ? `Goal: ${v.goal}` : "",
      "", "### 1. Pricing Model Comparison — table: Model (subscription/usage/freemium/one-time) / Use case / Pros / Cons / When to use",
      "### 2. WTP by Segment — WTP range / price sensitivity / revenue-maximizing price point per segment + ```chart bar chart",
      "### 3. A/B Experiment Design — 3 experiments: hypothesis / test method / sample size / metric / duration",
      "### 4. Tier Design — 3 plans (e.g. Free/Pro/Business): name / price / features / target segment / upgrade strategy",
      "### 5. 6-Month Pricing Playbook — table: Month / Pricing action / Metrics / Adjustment triggers. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 32. 投資人更新信 ──────────────────────────────────────────────────────
  investorupdate: {
    inputs: [
      { key: "company", label: "公司名稱", labelEn: "Company Name", type: "text", required: true, placeholder: "公司名稱", placeholderEn: "Company name" },
      { key: "period", label: "報告期間", labelEn: "Reporting Period", type: "text", required: true, placeholder: "例：2026 年 5 月 / Q2 2026", placeholderEn: "e.g. May 2026 / Q2 2026" },
      { key: "highlights", label: "本期亮點 / 數據", labelEn: "Period Highlights / Metrics", type: "textarea", required: true, placeholder: "收入成長、用戶數、重要里程碑、新客戶、產品更新…", placeholderEn: "Revenue growth, user count, milestones, new clients, product updates…" },
      { key: "challenges", label: "挑戰 / 風險 / 求助事項", labelEn: "Challenges / Risks / Ask", type: "textarea", required: false, placeholder: "目前面臨的挑戰、投資人可協助的事項", placeholderEn: "Current challenges and how investors can help" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位擅長撰寫投資人更新信的創業顧問，信件應清晰、誠實、令人信任。",
      "", `公司：${v.company}`, `期間：${v.period}`,
      `亮點：${v.highlights}`,
      v.challenges ? `挑戰：${v.challenges}` : "",
      "", "請輸出完整投資人更新信：",
      "", "**主旨**：[公司] [月份] 更新 — [一個最重要的亮點]",
      "", "**正文結構**：",
      "### TL;DR（3個 bullet points，每條≤20字）",
      "### 牽引力數據",
      "用表格：指標 / 本期數值 / 上期數值 / 月增率，輸出 ```chart 折線圖顯示最重要指標趨勢。",
      "### 產品與里程碑",
      "本期完成什麼 / 下期計畫什麼（各 3-5 條）",
      "### 挑戰與學習",
      v.challenges ? v.challenges : "誠實揭露本期最大挑戰及應對方式",
      "### 投資人請求（Ask）",
      "明確列出 2-3 個具體的投資人協助需求（引介/建議/資源）",
      "### 下期預告",
      "2-3 個下期關鍵目標",
      "全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a startup advisor who writes clear, honest, trust-building investor update letters.",
      "", `Company: ${v.company}`, `Period: ${v.period}`,
      `Highlights: ${v.highlights}`,
      v.challenges ? `Challenges: ${v.challenges}` : "",
      "", "Output a complete investor update letter:",
      "Subject: [Company] [Month] Update — [single most important highlight]",
      "### TL;DR — 3 bullet points (≤15 words each)",
      "### Traction Metrics — table: Metric / This period / Last period / MoM% + ```chart line chart of key metric",
      "### Product & Milestones — done this period / planned next (3–5 each)",
      `### Challenges & Learnings — ${v.challenges || "honest disclosure of top challenge and response"}`,
      "### Ask — 2–3 specific requests from investors (intro / advice / resource)",
      "### Next Period Preview — 2–3 key targets. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 37. 董事會簡報 ─────────────────────────────────────────────────────────
  boarddeck: {
    inputs: [
      { key: "company", label: "公司名稱 / 階段", labelEn: "Company / Stage", type: "text", required: true, placeholder: "公司名稱、目前發展階段（種子/A輪/成長期）", placeholderEn: "Company name, current stage (seed/Series A/growth)" },
      { key: "period", label: "報告期間 / 財務重點", labelEn: "Period / Financial Highlights", type: "textarea", required: true, placeholder: "Q幾 / 年月、主要財務數據（收入/支出/現金）", placeholderEn: "Quarter/period, key financials (revenue/expenses/cash)" },
      { key: "agenda", label: "本次議程主題", labelEn: "Agenda Topics", type: "textarea", required: true, placeholder: "例：財務報告、融資進展、策略調整、風險討論", placeholderEn: "e.g. financial review, fundraising update, strategy pivot, risk discussion" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位董事會簡報策略顧問，協助 CEO 準備清晰、數據驅動、能促進決策的董事會報告。",
      "", `公司：${v.company}`, `財務重點：${v.period}`, `議程：${v.agenda}`,
      "", "### 董事會簡報腳本（逐張投影片）",
      "1. **開場 / 執行摘要**：本期最重要的 3 件事（1句話/件）",
      "2. **財務儀表板**：關鍵指標表格（收入/EBITDA/現金/燒錢率）+ ```chart 折線圖顯示收入趨勢",
      "3. **業務進展**：里程碑達成度（用 ✅/⚠️/❌ 標示計畫 vs 實際）",
      "4. **策略更新**：本期策略決策與理由",
      "5. **風險 & 機會**：TOP 3 風險（含緩解措施）+ TOP 3 機會",
      "6. **下期計畫**：下一季 OKR 或關鍵目標",
      "7. **董事會決議需求**：需要董事會核准或意見的具體事項（若有）",
      "", "### 預測提問 & 建議回答",
      "預測董事會成員最可能問的 TOP 7 問題，每題附：問題 / CEO 建議回答要點（3-5條）",
      "全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a board presentation advisor helping CEOs prepare clear, data-driven board reports that facilitate decisions.",
      "", `Company: ${v.company}`, `Financial Highlights: ${v.period}`, `Agenda: ${v.agenda}`,
      "", "### Board Deck Script (slide by slide)",
      "1. Executive Summary — 3 most important things this period (1 sentence each)",
      "2. Financial Dashboard — key metrics table (revenue/EBITDA/cash/burn) + ```chart line chart of revenue trend",
      "3. Business Progress — milestone scorecard (✅/⚠️/❌ plan vs actual)",
      "4. Strategy Update — key strategic decisions and rationale",
      "5. Risks & Opportunities — top 3 risks (with mitigations) + top 3 opportunities",
      "6. Next Quarter Plan — OKRs or key targets",
      "7. Board Decisions Required — specific items needing board approval or input",
      "### Predicted Q&A — top 7 questions board members will likely ask + CEO response talking points (3–5 per question). Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 41. 融資準備評估師 ───────────────────────────────────────────────────
  fundraising: {
    inputs: [
      { key: "company", label: "公司名稱 / 行業 / 階段", labelEn: "Company / Industry / Stage", type: "text", required: true, placeholder: "例：SaaS B2B，種子輪後，準備 A 輪", placeholderEn: "e.g. B2B SaaS, post-seed, preparing for Series A" },
      { key: "traction", label: "牽引力數據", labelEn: "Traction Data", type: "textarea", required: true, placeholder: "ARR/MRR、用戶數、成長率、客戶名單、產品里程碑", placeholderEn: "ARR/MRR, users, growth rate, key clients, product milestones" },
      { key: "ask", label: "融資目標（選填）", labelEn: "Fundraising Target (optional)", type: "text", required: false, placeholder: "例：A 輪 300 萬美元，18 個月跑道", placeholderEn: "e.g. Series A $3M, 18-month runway" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位創投融資顧問，協助創業者評估融資準備度並制定 90 天衝刺計畫。",
      "", `公司：${v.company}`, `牽引力：${v.traction}`,
      v.ask ? `目標：${v.ask}` : "",
      "", "### 1. 牽引力評估（Traction Review）",
      "依以下維度評分（1-10）：收入成長率 / ARR 絕對值 / 客戶留存率 / 用戶成長速度 / 產品成熟度",
      "用表格呈現，附每項具體改進建議。輸出 ```chart 雷達圖替代方案（長條圖）。",
      "", "### 2. 市場評估",
      "TAM/SAM/SOM 估算 / 市場時機評分 / 為何現在是對的時間點",
      "", "### 3. 團隊評估（依提供資訊）",
      "團隊配置完整性 / 關鍵缺口 / 建議補強方式",
      "", "### 4. 投委會決議模擬",
      "模擬投資委員會視角：支持理由（3條）/ 反對疑慮（3條）/ 初步投資建議（強烈建議/有條件/不建議）",
      "", "### 5. 90 天融資衝刺計畫",
      "用 ```mermaid gantt 規劃：數據補強 / 投資人接觸 / 材料準備 / Due Diligence 準備 / 目標融資完成。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a venture fundraising advisor assessing fundraising readiness and designing a 90-day sprint plan.",
      "", `Company: ${v.company}`, `Traction: ${v.traction}`,
      v.ask ? `Target: ${v.ask}` : "",
      "", "### 1. Traction Review — scorecard (1–10): Revenue growth / ARR absolute / Retention / User growth / Product maturity. Table + improvement notes + ```chart bar chart.",
      "### 2. Market Assessment — TAM/SAM/SOM / market timing score / why now",
      "### 3. Team Assessment — completeness / key gaps / how to fill them",
      "### 4. Investment Committee Simulation — 3 support reasons / 3 concerns / initial recommendation (Strong yes / Conditional / Pass)",
      "### 5. 90-Day Fundraising Sprint — ```mermaid gantt: data strengthening / investor outreach / materials prep / DD prep / target close. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 63. 加速器申請書生成器 ───────────────────────────────────────────────
  acceleratorapply: {
    inputs: [
      { key: "startup", label: "新創名稱 / 產品 / 階段", labelEn: "Startup Name / Product / Stage", type: "textarea", required: true, placeholder: "公司名稱、核心產品、目前發展階段", placeholderEn: "Company name, core product, current development stage" },
      { key: "accelerator", label: "目標加速器名稱 / 特色", labelEn: "Target Accelerator / Focus", type: "text", required: true, placeholder: "例：Y Combinator、500 Startups、SOSV、台灣 AppWorks", placeholderEn: "e.g. Y Combinator, 500 Startups, SOSV, AppWorks" },
      { key: "traction", label: "牽引力數據", labelEn: "Traction Data", type: "textarea", required: true, placeholder: "用戶數、收入、成長率、重要里程碑、知名客戶", placeholderEn: "Users, revenue, growth rate, milestones, notable clients" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位加速器申請書輔導顧問，協助優秀新創展現最強實力。",
      "", `新創：${v.startup}`, `加速器：${v.accelerator}`, `牽引力：${v.traction}`,
      "", "### 1. 申請書評估",
      "針對目標加速器的評選邏輯，分析申請的優勢（3條）/ 弱點（3條）/ 必須強調的差異化點",
      "", "### 2. 核心應用材料",
      "**One-liner**：一句話描述（≤15字，模仿「Airbnb for X」格式）",
      "**問題陳述**（100字以內）：市場痛點 + 規模 + 迫切性",
      "**解決方案**（150字以內）：你的解法 + 為何更好 + 技術護城河",
      "**市場規模**：TAM/SAM/SOM 計算",
      "**商業模式**（100字以內）：如何賺錢 + 單位經濟學",
      "**牽引力**：用最強的 3-5 個數據呈現",
      "**創辦人故事**（150字以內）：為什麼是你們解決這個問題",
      "", "### 3. 常見申請問題回答",
      "準備 5 個加速器最愛問的問題，每個附建議回答（100-150字）",
      "", "### 4. 面試準備",
      "10 分鐘 Demo Day Pitch 結構 / 評審最可能問的 5 個刁鑽問題 + 應對策略。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are an accelerator application coach helping strong startups present their best case.",
      "", `Startup: ${v.startup}`, `Accelerator: ${v.accelerator}`, `Traction: ${v.traction}`,
      "", "### 1. Application Assessment — vs this accelerator's selection criteria: 3 strengths / 3 weaknesses / must-emphasize differentiators",
      "### 2. Core Application Materials",
      "One-liner (≤12 words, 'Airbnb for X' format) / Problem (≤100 words: pain + scale + urgency) / Solution (≤150 words: approach + why better + tech moat) / Market size (TAM/SAM/SOM) / Business model (≤100 words: revenue + unit economics) / Traction (top 3–5 metrics) / Founder story (≤150 words: why you)",
      "### 3. Common Questions — 5 frequently asked accelerator questions with recommended answers (100–150 words each)",
      "### 4. Interview Prep — 10-min Demo Day pitch structure / 5 tough evaluator questions with response strategies. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 67. Term Sheet 分析師 ─────────────────────────────────────────────────
  termsheet: {
    inputs: [
      { key: "termsheet", label: "Term Sheet 全文 / 關鍵條款", labelEn: "Term Sheet Content / Key Terms", type: "textarea", required: true, placeholder: "貼上 Term Sheet 全文，或列出關鍵條款（估值、股份、優先清算權等）", placeholderEn: "Paste full term sheet or list key terms (valuation, shares, liquidation preference, etc.)" },
      { key: "stage", label: "融資輪次 / 金額", labelEn: "Funding Round / Amount", type: "text", required: true, placeholder: "例：Pre-A 輪，融資 500 萬美元，Pre-money 估值 2000 萬", placeholderEn: "e.g. Pre-Series A, raising $5M, pre-money valuation $20M" },
      { key: "role", label: "你是創辦人還是投資人", labelEn: "Your Role", type: "text", required: true, placeholder: "創辦人 / 投資人 / 律師（影響分析角度）", placeholderEn: "Founder / Investor / Legal counsel (affects analysis angle)" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位創投法律顧問，協助創辦人（或投資人）理解 Term Sheet 每個條款的實際影響。",
      "⚠️ 以下為參考分析，正式決策前請諮詢持牌律師。",
      "", `Term Sheet：\n${v.termsheet}`, `輪次：${v.stage}`, `角色：${v.role}`,
      "", "### 1. 逐條解讀",
      "針對每個重要條款：條款名稱 / 白話解釋（1-2句）/ 對創辦人的影響 / 對投資人的保護 / 是否為行業標準（✅標準/⚠️偏投資方/🔴不利）",
      "", "### 2. 稀釋計算",
      "本輪融資後的股權結構（假設全行使）：創辦人持股% / 投資人持股% / 期權池%。",
      "若有里程碑分批投資，各批稀釋情況。",
      "輸出 ```chart 圓餅圖顯示融資後股權結構。",
      "", "### 3. 投資方保護條款評估",
      "優先清算權（倍數/參與型態）/ 反稀釋條款（加權平均/棘輪）/ 董事席位安排 / 拖帶權 / 優先購買權",
      "每個條款：對創辦人的實際影響（最壞情況下）",
      "", "### 4. 創辦人保護建議",
      "3-5 個建議要求的保護條款或修改意見（附談判話術）",
      "", "### 5. 整體評估",
      "此 Term Sheet 的友善度評分（1-10，依角色分析）/ 是否建議接受 / 優先談判項目。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a venture capital legal advisor helping founders (or investors) understand the real impact of each term sheet clause.",
      "⚠️ Reference analysis only — consult a licensed attorney before making decisions.",
      "", `Term Sheet:\n${v.termsheet}`, `Round: ${v.stage}`, `Role: ${v.role}`,
      "", "### 1. Clause-by-Clause Analysis — per key term: plain English explanation / founder impact / investor protection / industry standard (✅standard/⚠️investor-favored/🔴unfavorable)",
      "### 2. Dilution Calculation — post-round cap table: founder % / investor % / option pool %. If milestone tranches, dilution per tranche. ```chart pie chart of post-money ownership.",
      "### 3. Investor Protection Assessment — liquidation preference (multiple/participating) / anti-dilution (weighted average/ratchet) / board seats / drag-along / pro-rata. Worst-case founder impact per term.",
      "### 4. Founder Protection Recommendations — 3–5 clauses to request or modify (with negotiation talking points)",
      "### 5. Overall Assessment — friendliness score (1–10) / recommend accept or not / priority negotiation items. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 72. 盡職調查清單生成器 ───────────────────────────────────────────────
  duediligence: {
    inputs: [
      { key: "deal", label: "交易描述", labelEn: "Deal Description", type: "textarea", required: true, placeholder: "交易類型、規模、對象、初步了解的資訊", placeholderEn: "Deal type, size, target, initial information known" },
      { key: "target", label: "目標公司描述", labelEn: "Target Company Description", type: "text", required: true, placeholder: "行業、規模、年齡、商業模式", placeholderEn: "Industry, size, company age, business model" },
      { key: "dealtype", label: "交易類型", labelEn: "Deal Type", type: "text", required: true, placeholder: "M&A / VC 投資 / PE 收購 / 合夥 / 授權", placeholderEn: "M&A / VC investment / PE buyout / partnership / licensing" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位交易分析師，協助投資方或收購方進行全面的盡職調查。",
      "", `交易：${v.deal}`, `目標：${v.target}`, `類型：${v.dealtype}`,
      "", "### 1. 法律盡職調查清單",
      "公司架構與股權 / 合約與承諾 / 智財保護 / 訴訟與爭議 / 監管合規 / 勞工事項。",
      "每項：調查重點（3-5條）/ 主要風險信號 / 建議文件清單",
      "", "### 2. 財務盡職調查清單",
      "歷史財務報表 / 收入品質 / 成本結構 / 現金流 / 負債與或有負債 / 稅務事項。",
      "每項：調查重點（3-5條）/ 主要風險信號",
      "", "### 3. 市場與業務盡職調查清單",
      "市場定位 / 客戶集中度 / 競爭格局 / 產品/技術可持續性 / 管理團隊。",
      "每項：調查重點（3-5條）/ 主要風險信號",
      "", "### 4. 優先調查清單（TOP 10）",
      "依風險重要性排序，列出最必須優先確認的 10 個問題，每個附：問題 / 為何重要 / 如何取得資訊",
      "", "### 5. 決策摘要框架",
      "DD 完成後的投資建議模板（繼續/有條件繼續/暫停/放棄）+ 交割條件建議。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a deal analyst helping investors or acquirers conduct comprehensive due diligence.",
      "", `Deal: ${v.deal}`, `Target: ${v.target}`, `Type: ${v.dealtype}`,
      "", "### 1. Legal DD Checklist — corporate structure & ownership / contracts & commitments / IP protection / litigation / regulatory compliance / labor. Per area: 3–5 investigation focus points + red flags + document request list.",
      "### 2. Financial DD Checklist — historical financials / revenue quality / cost structure / cash flow / liabilities & contingencies / tax. Per area: 3–5 focus points + red flags.",
      "### 3. Market & Business DD Checklist — market positioning / customer concentration / competitive landscape / product sustainability / management team. Per area: 3–5 focus points + red flags.",
      "### 4. Priority Issues (Top 10) — ranked by risk importance: issue / why it matters / how to obtain information",
      "### 5. Decision Summary Framework — post-DD investment recommendation template (proceed/conditional/pause/abandon) + closing conditions. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 76. 投資人壓力測試 ───────────────────────────────────────────────────
  investorpressure: {
    inputs: [
      { key: "pitch", label: "Pitch 摘要 / 核心訴求", labelEn: "Pitch Summary / Core Claims", type: "textarea", required: true, placeholder: "你的商業模式、市場機會、競爭優勢、牽引力數據", placeholderEn: "Your business model, market opportunity, competitive advantages, traction data" },
      { key: "stage", label: "融資輪次 / 目標金額", labelEn: "Round / Fundraising Target", type: "text", required: true, placeholder: "例：Pre-A 輪，目標 300 萬美元", placeholderEn: "e.g. Pre-Series A, targeting $3M" },
      { key: "financials", label: "關鍵財務數據", labelEn: "Key Financial Data", type: "textarea", required: true, placeholder: "ARR、MRR、成長率、CAC、LTV、燒錢率、跑道", placeholderEn: "ARR, MRR, growth rate, CAC, LTV, burn rate, runway" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你將模擬 4 種不同類型投資人對這份 Pitch 的犀利審問，讓創辦人提前做好最充分準備。",
      "", `Pitch：${v.pitch}`, `輪次：${v.stage}`, `財務：${v.financials}`,
      "", "### VC（機構創投）審問",
      "最在乎：可擴展性 / 市場規模 / 10x 回報路徑",
      "3 個VC最刁鑽的問題 + 建議回答框架",
      "", "### 天使投資人審問",
      "最在乎：創辦人特質 / 早期牽引力 / 個人化了解",
      "3 個天使最犀利的問題 + 建議回答框架",
      "", "### CVC（企業創投）審問",
      "最在乎：策略協同 / 競爭影響 / 獨家談判空間",
      "3 個CVC最策略性的問題 + 建議回答框架",
      "", "### PE（私募股權）審問",
      "最在乎：財務健康 / 控制權 / 退出路徑",
      "3 個PE最嚴苛的財務問題 + 建議回答框架",
      "", "### 投委會整體評估",
      "整體評分（1-10）/ 最強3點 / 最弱3點 / 建議優化的TOP 5項目（附具體改善方向）",
      "輸出 ```chart 長條圖顯示四種投資人的興趣度評分。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "Simulate 4 types of investors grilling this pitch so founders can prepare thoroughly.",
      "", `Pitch: ${v.pitch}`, `Round: ${v.stage}`, `Financials: ${v.financials}`,
      "", "### VC Grilling — focus: scalability / market size / 10x return path. 3 toughest VC questions + recommended answer frameworks",
      "### Angel Grilling — focus: founder character / early traction / personal understanding. 3 sharp questions + frameworks",
      "### CVC Grilling — focus: strategic synergy / competitive impact / exclusivity room. 3 strategic questions + frameworks",
      "### PE Grilling — focus: financial health / control / exit path. 3 stringent financial questions + frameworks",
      "### Investment Committee Summary — overall score (1–10) / top 3 strengths / top 3 weaknesses / top 5 improvements with specific direction. ```chart bar chart of investor interest by type. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 83. 投資論點生成器 ───────────────────────────────────────────────────
  investmentthesis: {
    inputs: [
      { key: "company", label: "目標投資公司描述", labelEn: "Target Investment Company", type: "textarea", required: true, placeholder: "公司名稱、行業、商業模式、規模、階段", placeholderEn: "Company name, industry, business model, size, stage" },
      { key: "sector", label: "行業 / 細分市場", labelEn: "Sector / Subsector", type: "text", required: true, placeholder: "例：B2B SaaS / 台灣健康科技 / 東南亞電商", placeholderEn: "e.g. B2B SaaS / Taiwan healthtech / Southeast Asia e-commerce" },
      { key: "thesis", label: "初步投資論點（選填）", labelEn: "Initial Investment Thesis (optional)", type: "textarea", required: false, placeholder: "你對這筆投資的初步判斷或假設", placeholderEn: "Your initial judgment or hypothesis about this investment" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位投資研究分析師，生成嚴謹、平衡的投資論點報告。",
      "", `公司：${v.company}`, `行業：${v.sector}`,
      v.thesis ? `初步論點：${v.thesis}` : "",
      "", "### 多頭論點（Bull Case）",
      "3-5 個強力做多理由，每個附：論點 / 支持證據 / 潛在上行幅度估算",
      "", "### 空頭論點（Bear Case）",
      "3-5 個做空顧慮，每個附：論點 / 如何識別（Leading Indicator）/ 下行風險估算",
      "", "### 護城河分析（Moat Analysis）",
      "護城河類型（網絡效應/轉換成本/規模效益/品牌/專利）/ 護城河寬度（強/中/弱）/ 可持續性評估",
      "", "### 時機評估（Timing）",
      "為什麼現在是投資的好時機？或為什麼要等？催化劑事件識別（3個）",
      "", "### 整體投資評級",
      "投資評級（強烈看好/看好/中性/看空/強烈看空）",
      "核心假設清單（如果這些假設錯了，論點就崩塌）",
      "關鍵監控指標（6-8個，附評估頻率）",
      "輸出 ```chart 長條圖顯示多/空論點各自的強度評分。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are an investment research analyst generating rigorous, balanced investment thesis reports.",
      "", `Company: ${v.company}`, `Sector: ${v.sector}`,
      v.thesis ? `Initial Thesis: ${v.thesis}` : "",
      "", "### Bull Case — 3–5 strong buy arguments: argument / supporting evidence / upside estimate",
      "### Bear Case — 3–5 concerns: argument / how to identify (leading indicator) / downside risk",
      "### Moat Analysis — moat type (network effects/switching costs/scale/brand/patents) / width (strong/medium/weak) / sustainability",
      "### Timing — why now is a good entry point (or why wait?) + 3 catalyst events",
      "### Investment Rating — rating (Strong buy/Buy/Neutral/Sell/Strong sell) + core assumption list (if these break, the thesis collapses) + 6–8 KPIs with monitoring frequency. ```chart bar chart of bull vs bear argument strength. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 90. 營收預測引擎 ─────────────────────────────────────────────────────
  revenueforecast: {
    inputs: [
      { key: "company", label: "公司 / 產品 / 商業模式", labelEn: "Company / Product / Business Model", type: "textarea", required: true, placeholder: "公司名稱、主要收入來源、定價方式", placeholderEn: "Company name, main revenue streams, pricing model" },
      { key: "current", label: "現有收入數據 / 基準", labelEn: "Current Revenue Data / Baseline", type: "textarea", required: true, placeholder: "月收入/年收入、用戶數、成長率、主要指標", placeholderEn: "Monthly/annual revenue, users, growth rate, key metrics" },
      { key: "drivers", label: "主要收入驅動因素", labelEn: "Key Revenue Drivers", type: "textarea", required: true, placeholder: "新客戶獲取速度、現有客戶擴充、留存率、定價改變", placeholderEn: "New customer acquisition pace, existing customer expansion, retention rate, pricing changes" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位財務建模分析師，建立嚴謹的三情境營收預測模型。",
      "", `公司：${v.company}`, `基準：${v.current}`, `驅動因素：${v.drivers}`,
      "", "### 1. 基準分析",
      "當前收入健康診斷：收入品質 / 成長可持續性 / 集中度風險",
      "", "### 2. 三情境預測（12個月）",
      "用表格逐月呈現：",
      "**悲觀情境（P10）**：主要驅動因素假設 + 月度 MRR/ARR 預測",
      "**基本情境（P50）**：主要驅動因素假設 + 月度 MRR/ARR 預測",
      "**樂觀情境（P90）**：主要驅動因素假設 + 月度 MRR/ARR 預測",
      "每個情境的：第 12 個月收入 / 年增率 / 達成可能性（%）",
      "輸出 ```chart 折線圖顯示三情境的 12 個月收入曲線。",
      "", "### 3. 成長槓桿分析",
      "識別 5 個最高影響力的收入成長槓桿，每個附：",
      "槓桿名稱 / 預估收入影響（+X%）/ 實施難度 / 見效時間",
      "", "### 4. 風險因素",
      "可能讓實際收入低於悲觀情境的 3 個下行風險 + 監控指標",
      "", "### 5. 月度追蹤儀表板",
      "建議追蹤的 8 個收入 KPI（含計算公式和評估頻率）。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a financial modeling analyst building rigorous three-scenario revenue forecasts.",
      "", `Company: ${v.company}`, `Baseline: ${v.current}`, `Drivers: ${v.drivers}`,
      "", "### 1. Baseline Analysis — revenue health: quality / growth sustainability / concentration risk",
      "### 2. Three-Scenario Forecast (12 months) — monthly table: Pessimistic (P10): driver assumptions + monthly MRR/ARR / Base (P50): same / Optimistic (P90): same. Per scenario: Month 12 revenue / YoY growth / probability (%). ```chart line chart of 3-scenario revenue curves.",
      "### 3. Growth Lever Analysis — 5 highest-impact revenue growth levers: lever / estimated revenue impact (+X%) / implementation difficulty / time to impact",
      "### 4. Downside Risks — 3 factors that could push below pessimistic scenario + monitoring indicators",
      "### 5. Monthly Tracking Dashboard — 8 revenue KPIs with calculation formulas and review frequency. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 93. 天使投資人 Pitch 模擬器 ──────────────────────────────────────────
  angelpitch: {
    inputs: [
      { key: "pitch", label: "Pitch 摘要 / Deck 描述", labelEn: "Pitch Summary / Deck Description", type: "textarea", required: true, placeholder: "描述你的商業模式、市場、競爭優勢、牽引力、融資需求", placeholderEn: "Describe business model, market, competitive advantage, traction, funding ask" },
      { key: "stage", label: "融資階段 / 目標金額", labelEn: "Stage / Target Amount", type: "text", required: true, placeholder: "例：Pre-seed，目標 100 萬美元，股權 10%", placeholderEn: "e.g. Pre-seed, targeting $1M at 10% equity" },
      { key: "angel_type", label: "目標天使投資人類型（選填）", labelEn: "Target Angel Type (optional)", type: "text", required: false, placeholder: "例：行業專家、成功創業者、財務型天使", placeholderEn: "e.g. industry expert, successful entrepreneur, financial angel" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你將模擬 3 位風格各異的天使投資人對這份 Pitch 的反應，幫創辦人提前準備。",
      "", `Pitch：${v.pitch}`, `階段：${v.stage}`,
      v.angel_type ? `天使類型：${v.angel_type}` : "",
      "", "### 犀利問題集（15題）",
      "模擬天使投資人最常問的 15 個問題（不同難度：5個基礎/5個中級/5個高難），每題附建議回答要點（3條）",
      "", "### 優勢亮點",
      "這份 Pitch 最強的 3 個部分（附為何會吸引天使）",
      "", "### 改善建議（TOP 5）",
      "最需要改善的 5 個地方，每個附：問題描述 / 改善方向 / 改善後的示範語句",
      "", "### 三位天使的第一印象",
      "**行業天使**（業界資深人士）：第一反應 / 投資意願（1-10）/ 最在意的1個問題",
      "**創業者天使**（曾創業的投資人）：第一反應 / 投資意願 / 最在意的1個問題",
      "**財務天使**（以回報為主）：第一反應 / 投資意願 / 最在意的1個問題",
      "輸出 ```chart 長條圖顯示三種天使的投資意願分數。",
      "", "### Pitch 整體評分",
      "總分（1-10）/ 最可能成功的場景 / 一句話給創辦人的建議。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "Simulate 3 different angel investor reactions to help founders prepare thoroughly.",
      "", `Pitch: ${v.pitch}`, `Stage: ${v.stage}`,
      v.angel_type ? `Angel type: ${v.angel_type}` : "",
      "", "### Tough Questions (15) — 5 basic/5 intermediate/5 hard, each with 3-point recommended answer framework",
      "### Strength Highlights — top 3 strongest parts of this pitch with why they attract angels",
      "### Top 5 Improvements — problem / improvement direction / sample improved language",
      "### Three Angel First Impressions — Industry Angel (sector veteran): reaction / investment intent (1–10) / top concern / Entrepreneur Angel: same / Financial Angel: same. ```chart bar chart of intent scores.",
      "### Overall Score — total (1–10) / most likely success scenario / one-sentence advice for the founder. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 94. 新創估值計算師 ───────────────────────────────────────────────────
  startupvaluation: {
    inputs: [
      { key: "company", label: "公司 / 行業 / 階段", labelEn: "Company / Industry / Stage", type: "text", required: true, placeholder: "公司名稱、行業、融資輪次（種子/A輪/B輪）", placeholderEn: "Company name, industry, funding round (seed/Series A/B)" },
      { key: "financials", label: "財務數據", labelEn: "Financial Data", type: "textarea", required: true, placeholder: "ARR/MRR、YoY 成長率、毛利率、EBITDA（若有）、預計下一年收入", placeholderEn: "ARR/MRR, YoY growth rate, gross margin, EBITDA (if any), projected next-year revenue" },
      { key: "comps", label: "可比公司（選填）", labelEn: "Comparable Companies (optional)", type: "text", required: false, placeholder: "類似上市公司或近期融資案例名稱", placeholderEn: "Similar public companies or recent funding round comparables" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位新創估值顧問，使用多種方法提供合理的估值範圍，協助創辦人在融資談判中有所依據。",
      "", `公司：${v.company}`, `財務：${v.financials}`,
      v.comps ? `可比公司：${v.comps}` : "",
      "", "### 1. DCF 估值法（折現現金流）",
      "設定關鍵假設：收入成長率 / 毛利率改善 / Terminal Growth Rate / 折現率（WACC）",
      "5 年 FCF 預測 + Terminal Value + DCF 估值範圍（悲觀/基本/樂觀）",
      "", "### 2. 可比公司/交易估值法",
      "主要估值倍數：Revenue Multiple / ARR Multiple / EBITDA Multiple",
      v.comps ? `依 ${v.comps} 的倍數推算估值範圍` : "依行業標準倍數推算估值範圍",
      "呈現倍數表格（低端/中位/高端）",
      "", "### 3. VC 法（投資人視角）",
      "設定假設：目標退出時 ARR / 退出倍數 / 投資人目標 IRR / 未來稀釋",
      "反推現在合理的 Post-money 估值",
      "", "### 4. 估值綜合結論",
      "三種方法的估值範圍彙整表（低/中/高）",
      "輸出 ```chart 長條圖比較三種方法的估值中位數。",
      "建議在融資談判中使用的估值錨定策略（什麼時候說哪個數字）",
      "", "### 5. 估值提升路徑",
      "未來 12 個月可提升估值倍數的 3 個關鍵里程碑。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a startup valuation advisor using multiple methods to provide a reasonable valuation range for fundraising negotiations.",
      "", `Company: ${v.company}`, `Financials: ${v.financials}`,
      v.comps ? `Comparables: ${v.comps}` : "",
      "", "### 1. DCF Valuation — key assumptions: revenue growth / margin improvement / terminal growth rate / WACC. 5-year FCF projection + terminal value + DCF range (pessimistic/base/optimistic)",
      `### 2. Comparable Company/Transaction Method — key multiples: Revenue Multiple / ARR Multiple / EBITDA Multiple. ${v.comps ? "Apply " + v.comps + " multiples" : "Apply industry standard multiples"}. Table: low / median / high.`,
      "### 3. VC Method — assumptions: exit ARR / exit multiple / target IRR / future dilution. Back-calculate reasonable current post-money valuation.",
      "### 4. Consolidated Conclusion — summary table of all three methods (low/mid/high). ```chart bar chart of median valuations. Recommended anchoring strategy for fundraising negotiations.",
      "### 5. Valuation Improvement Path — 3 key milestones in the next 12 months to improve valuation multiples. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 123. 商業計畫書生成器 ────────────────────────────────────────────────
  bizplan: {
    inputs: [
      { key: "idea", label: "創業構想", labelEn: "Business Concept", type: "textarea", required: true, placeholder: "解決什麼問題、如何解決、目標市場、商業模式", placeholderEn: "What problem, how to solve, target market, business model" },
      { key: "stage", label: "融資目標 / 用途", labelEn: "Funding Target / Use", type: "text", required: true, placeholder: "例：求融 300 萬，60% 產品、40% 行銷", placeholderEn: "e.g. raising NT$3M: 60% product, 40% marketing" },
      { key: "traction", label: "現有牽引力（選填）", labelEn: "Current Traction (optional)", type: "text", required: false, placeholder: "用戶數、收入、合作夥伴、重要里程碑", placeholderEn: "Users, revenue, partners, key milestones" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位商業計畫書顧問，撰寫能通過投資人審核的專業計畫書架構。",
      "", `構想：${v.idea}`, `目標：${v.stage}`,
      v.traction ? `牽引力：${v.traction}` : "",
      "", "### 1. 執行摘要（Executive Summary）",
      "公司使命（1句）/ 核心問題 / 解決方案 / 目標市場（TAM）/ 商業模式 / 牽引力 / 融資需求。≤300字。",
      "", "### 2. 市場與競爭分析",
      "市場規模（TAM/SAM/SOM）/ 競爭格局（5力分析或競品表格）/ 差異化優勢",
      "", "### 3. 產品與技術",
      "產品描述 / 技術護城河（若有）/ 產品路線圖（6個月 Milestone）",
      "", "### 4. 財務模型",
      "3年收入預測（按月展開第1年，按季展開第2-3年）",
      "關鍵假設 / 損益預測（收入/毛利/EBITDA）",
      "輸出 ```chart 折線圖顯示3年收入預測。",
      "", "### 5. 融資規劃",
      "本輪融資詳情（金額/估值/用途分配）/ 未來融資路徑（A輪/B輪條件）",
      "18個月重要里程碑清單。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a business plan advisor writing professional plan structures that pass investor review.",
      "", `Concept: ${v.idea}`, `Funding Target: ${v.stage}`,
      v.traction ? `Traction: ${v.traction}` : "",
      "", "### 1. Executive Summary — mission (1 sentence) / core problem / solution / TAM / business model / traction / funding ask. ≤300 words.",
      "### 2. Market & Competitive Analysis — TAM/SAM/SOM / competitive landscape (Porter's 5 forces or competitor table) / differentiation",
      "### 3. Product & Technology — description / tech moat (if any) / product roadmap (6-month milestones)",
      "### 4. Financial Model — 3-year revenue forecast (monthly Year 1, quarterly Year 2–3) / key assumptions / P&L (revenue/gross margin/EBITDA). ```chart line chart.",
      "### 5. Funding Plan — this round details (amount/valuation/use of proceeds) / future funding path / 18-month milestone list. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 126. Pitch Deck 投資評分師 ───────────────────────────────────────────
  pitchscorer: {
    inputs: [
      { key: "pitch", label: "Pitch 內容描述", labelEn: "Pitch Content Description", type: "textarea", required: true, placeholder: "描述 Pitch Deck 各投影片的內容（或貼上摘要）", placeholderEn: "Describe each slide's content or paste a summary" },
      { key: "stage", label: "融資輪次 / 行業", labelEn: "Stage / Industry", type: "text", required: true, placeholder: "例：種子輪，EdTech SaaS", placeholderEn: "e.g. Seed round, EdTech SaaS" },
      { key: "ask", label: "融資金額 / 估值", labelEn: "Funding Ask / Valuation", type: "text", required: true, placeholder: "例：求融 100 萬美元，Pre-money 估值 500 萬", placeholderEn: "e.g. raising $1M, pre-money $5M" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你將扮演一位挑剔的 VC 合夥人，對這份 Pitch Deck 進行全面的投資評分。",
      "", `Pitch：${v.pitch}`, `輪次：${v.stage}`, `金額：${v.ask}`,
      "", "### VC 裁決評分（10 個維度，各 1-10 分）",
      "1. 問題清晰度 2. 解決方案差異化 3. 市場規模吸引力 4. 商業模式可行性",
      "5. 牽引力說服力 6. 競爭護城河 7. 團隊能力（依描述推斷）8. 財務合理性",
      "9. 投資回報潛力 10. Pitch 呈現品質",
      "用表格呈現，附每項具體評語（1-2句）。",
      "輸出 ```chart 長條圖顯示十維評分。",
      "", "### 整體裁決",
      "總分（滿分100）/ 投資建議（立即推進/有條件推進/需要重大改善/Pass）/ 推薦理由（3條）/ 反對理由（3條）",
      "", "### 多維度深度分析",
      "最強的 3 個投影片（說明為何有效）/ 最弱的 3 個投影片（說明問題所在）",
      "", "### 優化修改建議",
      "TOP 5 最高優先的修改建議，每個附：目前問題 / 具體改法 / 預期分數提升。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "Act as a demanding VC partner conducting a comprehensive investment scoring of this pitch deck.",
      "", `Pitch: ${v.pitch}`, `Stage: ${v.stage}`, `Ask: ${v.ask}`,
      "", "### VC Verdict Score (10 dimensions, 1–10 each) — 1. Problem clarity 2. Solution differentiation 3. Market attractiveness 4. Business model viability 5. Traction strength 6. Competitive moat 7. Team capability 8. Financial soundness 9. Return potential 10. Presentation quality. Table with 1–2 sentence comment per dimension. ```chart bar chart.",
      "### Overall Verdict — total score (out of 100) / recommendation (Invest now/Conditional/Major improvement needed/Pass) / 3 reasons for / 3 reasons against",
      "### Deep Analysis — 3 strongest slides (why they work) / 3 weakest slides (what's wrong)",
      "### Optimization Recommendations — top 5 improvements: current problem / specific fix / expected score lift. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 133. 投資人接觸信生成器 ──────────────────────────────────────────────
  investoroutreach: {
    inputs: [
      { key: "startup", label: "新創資訊", labelEn: "Startup Info", type: "textarea", required: true, placeholder: "公司名稱、行業、牽引力數據、融資目標", placeholderEn: "Company name, industry, traction data, funding target" },
      { key: "investor", label: "目標投資人描述", labelEn: "Target Investor Description", type: "text", required: true, placeholder: "例：台灣早期 VC、關注 SaaS 的天使投資人、行業策略投資人", placeholderEn: "e.g. Taiwan early-stage VC, SaaS-focused angel, industry strategic investor" },
      { key: "intro", label: "引薦關係（選填）", labelEn: "Warm Introduction (optional)", type: "text", required: false, placeholder: "是否有共同聯絡人？引薦人是誰？", placeholderEn: "Any mutual contact? Who's making the intro?" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位融資溝通顧問，撰寫能讓投資人打開、閱讀並回覆的接觸信。",
      "", `新創：${v.startup}`, `投資人：${v.investor}`,
      v.intro ? `引薦：${v.intro}` : "",
      "", "### 1. 冷信（Cold Email）",
      "主旨（3個版本，≤60字元）/ 正文（≤200字）：",
      "- 個人化鉤子（為何選擇這位投資人）",
      "- 一句話公司描述（Airbnb for X 格式）",
      "- 最有說服力的 3 個數字/里程碑",
      "- 清晰的下一步 CTA（15分鐘 Zoom）",
      "", "### 2. LinkedIn 訊息版本",
      "≤300字元，更簡短、更直接，適合 InMail",
      "", "### 3. 跟進序列",
      "若無回覆：D+4 / D+10 / D+20 的跟進訊息（每個≤100字）",
      "", "### 4. 會議準備指南",
      "若對方同意會議：",
      "- 投資人背景研究清單（5個應了解的事）",
      "- 前 5 分鐘破冰話術",
      "- 預測的 TOP 5 問題 + 回答要點",
      "", "### 5. 跟蹤管理建議",
      "100個投資人外展的管道策略 + CRM 追蹤方法。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a fundraising communications advisor writing outreach messages investors will open, read, and reply to.",
      "", `Startup: ${v.startup}`, `Investor: ${v.investor}`,
      v.intro ? `Intro: ${v.intro}` : "",
      "", "### 1. Cold Email — 3 subject lines (≤60 chars each) / body (≤200 words): personalized hook (why this investor) + one-liner description + 3 compelling numbers/milestones + clear CTA (15-min Zoom)",
      "### 2. LinkedIn Message — ≤300 chars, shorter and more direct for InMail",
      "### 3. Follow-up Sequence — if no reply: D+4 / D+10 / D+20 messages (each ≤100 words)",
      "### 4. Meeting Prep Guide — if they agree: 5 things to research about the investor / first 5-minute icebreaker / top 5 predicted questions + answer talking points",
      "### 5. Outreach Management — strategy for 100-investor campaign + CRM tracking method. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 136. 融資資料室準備師 ────────────────────────────────────────────────
  dataroomprep: {
    inputs: [
      { key: "company", label: "公司描述", labelEn: "Company Description", type: "textarea", required: true, placeholder: "公司名稱、行業、融資輪次、主要投資人類型", placeholderEn: "Company name, industry, funding round, target investor types" },
      { key: "stage", label: "融資階段", labelEn: "Funding Stage", type: "text", required: true, placeholder: "例：種子輪、A 輪、上市前", placeholderEn: "e.g. seed, Series A, pre-IPO" },
      { key: "gaps", label: "已知文件缺口（選填）", labelEn: "Known Document Gaps (optional)", type: "text", required: false, placeholder: "哪些文件目前還沒準備好？", placeholderEn: "Which documents aren't ready yet?" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位融資資料室顧問，協助新創在 Due Diligence 中留下最好印象。",
      "", `公司：${v.company}`, `階段：${v.stage}`,
      v.gaps ? `已知缺口：${v.gaps}` : "",
      "", "### 1. 盡調文件清單（分優先度）",
      "🔴 必備（投資人第一天要求）/ 🟡 重要（DD 深化期需要）/ 🟢 加分（展現專業度）",
      "每類文件：名稱 / 說明 / 準備難度（高/中/低）/ 建議格式",
      "", "### 2. 投資敘事框架",
      "資料室的「故事線」設計：投資人進入資料室後，應該按什麼順序閱讀？每份文件如何支撐整體投資論點？",
      "", "### 3. 財務文件深化",
      "財務模型的 5 個必備要素 / 最容易被質疑的 3 個假設 + 如何提前說明 / 財務陳述的常見錯誤",
      "", "### 4. DD 問答預測",
      "投資人最常問的 20 個 DD 問題（按類別：法律/財務/業務/技術/團隊）+ 建議回答方向",
      "", "### 5. 資料室管理建議",
      "資料夾結構設計 / 存取權限管理 / 版本控制 / 建議的資料室平台（3個）。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a data room advisor helping startups make the best impression during due diligence.",
      "", `Company: ${v.company}`, `Stage: ${v.stage}`,
      v.gaps ? `Known gaps: ${v.gaps}` : "",
      "", "### 1. Document Checklist (by priority) — 🔴 Must-have (Day 1 requests) / 🟡 Important (deeper DD) / 🟢 Nice-to-have (showcase professionalism). Per document: name / description / preparation difficulty / recommended format.",
      "### 2. Investment Narrative Framework — data room story arc: what order should investors read documents? How does each document support the overall investment thesis?",
      "### 3. Financial Document Deep-Dive — 5 must-have elements in financial model / 3 most-challenged assumptions + how to proactively address / common financial presentation mistakes",
      "### 4. DD Q&A Predictions — 20 most common DD questions (legal/financial/business/tech/team) + recommended answer direction",
      "### 5. Data Room Management — folder structure / access control / version control / 3 recommended platforms. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 143. 募資財務模型師 ──────────────────────────────────────────────────
  fundraisingmodel: {
    inputs: [
      { key: "startup", label: "新創描述", labelEn: "Startup Description", type: "textarea", required: true, placeholder: "公司名稱、商業模式、目前牽引力、行業", placeholderEn: "Company name, business model, current traction, industry" },
      { key: "round", label: "本輪融資詳情", labelEn: "This Round Details", type: "text", required: true, placeholder: "融資金額、輪次、目前估值（若有）、目標投資人類型", placeholderEn: "Amount, round, current valuation (if any), target investor types" },
      { key: "use", label: "資金用途", labelEn: "Use of Funds", type: "text", required: true, placeholder: "例：60% 研發、30% 銷售行銷、10% 運營", placeholderEn: "e.g. 60% R&D, 30% sales & marketing, 10% operations" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位融資財務顧問，協助新創建立清晰、可信的融資財務論述。",
      "", `新創：${v.startup}`, `本輪：${v.round}`, `用途：${v.use}`,
      "", "### 1. 估值框架",
      "用 3 種方法估算合理估值範圍：",
      "**牽引力倍數法**：ARR/GMV × 行業倍數",
      "**可比交易法**：類似階段/行業的融資案例參考",
      "**DCF 法**：3年預測收入的折現估值",
      "綜合推薦估值範圍（Pre-money）",
      "輸出 ```chart 長條圖比較三種方法的估值結果。",
      "", "### 2. 財務預測",
      "18 個月月度財務預測（收入/毛利/費用/EBITDA/現金餘額）",
      "關鍵假設（3個最重要的）",
      "", "### 3. 資金用途說明",
      "資金分配的策略說明（為什麼這樣分配）/ 每項用途的預期 ROI / 18個月里程碑",
      "", "### 4. 投資人接觸策略",
      "目標投資人名單類型 / 接觸優先順序 / 融資時程規劃（4-6個月）",
      "", "### 5. 常見財務問題準備",
      "投資人最常問的 10 個財務問題 + 建議回答要點。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a fundraising financial advisor helping startups build clear, credible financial narratives for fundraising.",
      "", `Startup: ${v.startup}`, `Round: ${v.round}`, `Use: ${v.use}`,
      "", "### 1. Valuation Framework — 3 methods: Traction multiple (ARR/GMV × industry multiple) / Comparable transactions / DCF (discounted 3-year forecast). Recommended pre-money range. ```chart bar chart comparing three valuations.",
      "### 2. Financial Projections — 18-month monthly P&L (revenue/gross margin/expenses/EBITDA/cash balance) + 3 key assumptions",
      "### 3. Use of Funds Explanation — strategic rationale for each allocation / expected ROI per category / 18-month milestones",
      "### 4. Investor Outreach Strategy — target investor types / outreach priority / fundraising timeline (4–6 months)",
      "### 5. Common Financial Q&A — 10 most common investor financial questions + answer talking points. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 148. 政府補助申請顧問 ────────────────────────────────────────────────
  grantsearch: {
    inputs: [
      { key: "company", label: "公司描述", labelEn: "Company Description", type: "textarea", required: true, placeholder: "公司名稱、行業、規模、主要業務、核心技術/創新點", placeholderEn: "Company name, industry, size, main business, core tech/innovation" },
      { key: "needs", label: "補助需求", labelEn: "Grant Needs", type: "text", required: true, placeholder: "例：研發補助、數位化補助、出口補助、人才補助", placeholderEn: "e.g. R&D grant, digitalization subsidy, export assistance, talent subsidy" },
      { key: "region", label: "地區（選填）", labelEn: "Region (optional)", type: "text", required: false, placeholder: "例：台灣（中央/地方）、歐盟、新加坡", placeholderEn: "e.g. Taiwan (central/local), EU, Singapore" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位政府補助顧問，協助企業找到最適合的補助計畫並提高申請成功率。",
      "", `公司：${v.company}`, `需求：${v.needs}`,
      v.region ? `地區：${v.region}` : "地區：台灣",
      "", "### 1. 適合補助計畫清單",
      "推薦 5-8 個最適合的補助計畫（台灣為主），每個附：",
      "計畫名稱 / 主辦單位 / 補助金額上限 / 申請資格 / 申請時程 / 適合理由",
      "用表格呈現，依「適合度」排序。",
      "", "### 2. TOP 1 補助深度分析",
      "最推薦的補助計畫詳細分析：",
      "評分標準解讀 / 最常被淘汰的原因 / 成功申請者的共同特徵",
      "", "### 3. 申請文件策略",
      "必備文件清單（按優先度）/ 最容易忽略的 3 個細節 / 審查委員最在乎的 3 個重點",
      "", "### 4. 獲補成功率提升技巧",
      "5 個提升通過率的具體技巧（附案例說明）/ 常見加分項目",
      "", "### 5. 申請時程規劃",
      "從決定申請到送件的 8 週準備計畫，用表格呈現每週任務。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a government grant advisor helping companies find the best grant programs and improve application success rates.",
      "", `Company: ${v.company}`, `Needs: ${v.needs}`,
      v.region ? `Region: ${v.region}` : "Region: Taiwan",
      "", "### 1. Matching Grant Programs — 5–8 most suitable programs, table: program name / administering body / max grant / eligibility / application timeline / why it fits. Sorted by fit.",
      "### 2. Top Pick Deep Analysis — scoring criteria interpretation / most common rejection reasons / common traits of successful applicants",
      "### 3. Application Document Strategy — required documents (by priority) / 3 most overlooked details / 3 things reviewers care about most",
      "### 4. Success Rate Improvement — 5 specific techniques with examples / common bonus points",
      "### 5. Application Timeline — 8-week preparation plan from decision to submission. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 154. 投資人 Pitch 準備師 ─────────────────────────────────────────────
  investorpitch: {
    inputs: [
      { key: "startup", label: "新創描述", labelEn: "Startup Description", type: "textarea", required: true, placeholder: "公司、產品、商業模式、牽引力、團隊", placeholderEn: "Company, product, business model, traction, team" },
      { key: "round", label: "融資輪次 / 金額", labelEn: "Round / Amount", type: "text", required: true, placeholder: "例：種子輪，募 100 萬美元", placeholderEn: "e.g. seed round, raising $1M" },
      { key: "investor", label: "目標投資人類型（選填）", labelEn: "Target Investor Type (optional)", type: "text", required: false, placeholder: "例：早期 VC、天使、策略投資人", placeholderEn: "e.g. early-stage VC, angel, strategic investor" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位 Pitch 準備教練，協助創辦人講出讓投資人買單的故事。",
      "", `新創：${v.startup}`, `輪次：${v.round}`,
      v.investor ? `投資人：${v.investor}` : "",
      "", "### 1. 故事線設計",
      "用「問題→洞察→解法→證明→願景」框架設計 Pitch 主線，每段 2-3 句核心敘事",
      "", "### 2. Pitch Deck 結構",
      "逐張投影片建議（10-12張）：每張的標題 / 核心訊息 / 必備數據 / 視覺建議",
      "用 ```mermaid flowchart 呈現產品/商業流程（其中一張投影片）。",
      "", "### 3. 關鍵數據呈現",
      "最該強調的 3-5 個數據 + 呈現方式建議",
      "輸出 ```chart 折線圖顯示成長軌跡（範例）。",
      "", "### 4. 刁難問題回應",
      "投資人最可能問的 10 個刁難問題 + 建議回答框架（每個 3 個要點）",
      "", "### 5. Pitch 演練建議",
      "開場 30 秒腳本 / 時間分配 / 肢體與語氣提醒 / 常見失誤清單。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a pitch preparation coach helping founders tell stories investors buy into.",
      "", `Startup: ${v.startup}`, `Round: ${v.round}`,
      v.investor ? `Investor: ${v.investor}` : "",
      "", "### 1. Storyline Design — 'problem→insight→solution→proof→vision' framework, 2–3 sentences of core narrative per section",
      "### 2. Pitch Deck Structure — slide-by-slide (10–12 slides): title / core message / must-have data / visual suggestion. ```mermaid flowchart of product/business flow (one slide).",
      "### 3. Key Data Presentation — top 3–5 numbers to emphasize + presentation approach. ```chart line chart of growth trajectory (example).",
      "### 4. Tough Question Responses — 10 most likely tough questions + answer frameworks (3 points each)",
      "### 5. Pitch Rehearsal — 30-second opening script / time allocation / delivery reminders / common mistakes. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 166. 收入模式優化師 ──────────────────────────────────────────────────
  revenuemodel: {
    inputs: [
      { key: "business", label: "業務描述", labelEn: "Business Description", type: "textarea", required: true, placeholder: "公司、產品/服務、目前收費方式、主要收入來源", placeholderEn: "Company, product/service, current pricing, main revenue streams" },
      { key: "current", label: "現有收入數據", labelEn: "Current Revenue Data", type: "text", required: true, placeholder: "月/年營收、毛利率、客戶數、客單價", placeholderEn: "Monthly/annual revenue, gross margin, customer count, ARPU" },
      { key: "goal", label: "優化目標（選填）", labelEn: "Optimization Goal (optional)", type: "text", required: false, placeholder: "例：提升毛利、增加經常性收入、降低集中度", placeholderEn: "e.g. improve margin, grow recurring revenue, reduce concentration" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位收入模式策略師，協助企業建立更健康、更多元的收入結構。",
      "", `業務：${v.business}`, `現有數據：${v.current}`,
      v.goal ? `目標：${v.goal}` : "",
      "", "### 1. 商業模式健診",
      "現有收入結構分析 / 收入品質評估（經常性 vs 一次性）/ 集中度風險 / 毛利結構",
      "輸出 ```chart 圓餅圖顯示現有收入來源分布。",
      "", "### 2. 多元收入流設計",
      "推薦 3-5 個新增/優化的收入流，每個：模式 / 適用性 / 預估貢獻 / 啟動難度",
      "", "### 3. 定價優化",
      "現有定價的問題 / 優化方向（分層/捆綁/用量/訂閱）/ 漲價可行性評估",
      "", "### 4. 財務預測",
      "優化後 12 個月收入預測（保守/基本/樂觀）",
      "輸出 ```chart 折線圖顯示三情境收入曲線。",
      "", "### 5. 實施路線圖",
      "收入模式優化的優先順序與 90 天行動。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a revenue model strategist helping companies build healthier, more diversified revenue structures.",
      "", `Business: ${v.business}`, `Current data: ${v.current}`,
      v.goal ? `Goal: ${v.goal}` : "",
      "", "### 1. Business Model Health Check — revenue structure analysis / quality (recurring vs one-time) / concentration risk / margin structure. ```chart pie chart of current revenue sources.",
      "### 2. Diversified Revenue Stream Design — 3–5 new/optimized streams: model / fit / estimated contribution / launch difficulty",
      "### 3. Pricing Optimization — current pricing problems / optimization direction (tiering/bundling/usage/subscription) / price increase feasibility",
      "### 4. Financial Forecast — 12-month post-optimization forecast (conservative/base/optimistic). ```chart line chart.",
      "### 5. Implementation Roadmap — priority and 90-day actions. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 189. 融資策略顧問 ────────────────────────────────────────────────────
  fundingstrategy: {
    inputs: [
      { key: "business", label: "業務描述", labelEn: "Business Description", type: "textarea", required: true, placeholder: "公司、階段、商業模式、牽引力、現有財務", placeholderEn: "Company, stage, business model, traction, current financials" },
      { key: "need", label: "資金需求 / 用途", labelEn: "Funding Need / Use", type: "text", required: true, placeholder: "需要多少錢、做什麼、希望多久到位", placeholderEn: "How much, for what, desired timeline" },
      { key: "preference", label: "融資偏好（選填）", labelEn: "Funding Preference (optional)", type: "text", required: false, placeholder: "例：股權/債權/補助、是否介意稀釋", placeholderEn: "e.g. equity/debt/grant, dilution sensitivity" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位融資策略顧問，協助企業選擇最佳融資路徑並準備成功募資。",
      "", `業務：${v.business}`, `需求：${v.need}`,
      v.preference ? `偏好：${v.preference}` : "",
      "", "### 1. 融資準備度評估",
      "評估（1-10）：牽引力 / 財務健康 / 團隊 / 市場 / 故事完整度 → 整體準備度與最該補強處",
      "輸出 ```chart 長條圖顯示準備度各維度。",
      "", "### 2. 融資工具比較",
      "比較適合的融資選項（股權/可轉債/銀行貸款/補助/營收基礎融資），用表格：工具 / 適用性 / 成本 / 稀釋 / 速度 / 風險",
      "", "### 3. 投資人策略",
      "目標投資人類型 + 估值區間建議 + 募資時程規劃（4-6個月）",
      "", "### 4. 融資簡報重點",
      "Pitch 的核心敘事 + 最該強調的 3 個亮點 + 預測的 5 個刁難問題與回應",
      "", "### 5. 募資執行計畫",
      "從準備到 close 的行動清單 + 常見陷阱。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a funding strategy consultant helping companies choose the best funding path and prepare for successful raises.",
      "", `Business: ${v.business}`, `Need: ${v.need}`,
      v.preference ? `Preference: ${v.preference}` : "",
      "", "### 1. Funding Readiness — score (1–10): traction / financial health / team / market / story completeness → overall readiness and top gaps. ```chart bar chart.",
      "### 2. Funding Instrument Comparison — table: instrument (equity/convertible/bank loan/grant/revenue-based) / fit / cost / dilution / speed / risk",
      "### 3. Investor Strategy — target investor types + valuation range + raise timeline (4–6 months)",
      "### 4. Pitch Highlights — core narrative + top 3 highlights to emphasize + 5 predicted tough questions with responses",
      "### 5. Raise Execution Plan — action list from prep to close + common pitfalls. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 197. 定價審計師 ──────────────────────────────────────────────────────
  pricingaudit: {
    inputs: [
      { key: "product", label: "產品 / 現有定價", labelEn: "Product / Current Pricing", type: "textarea", required: true, placeholder: "產品、現有方案與價格、目標客群、成本結構", placeholderEn: "Product, current plans and prices, target customers, cost structure" },
      { key: "metrics", label: "定價相關數據（選填）", labelEn: "Pricing-Related Data (optional)", type: "text", required: false, placeholder: "轉換率、客單價、流失、各方案佔比", placeholderEn: "Conversion rate, ARPU, churn, plan distribution" },
      { key: "goal", label: "目標（選填）", labelEn: "Goal (optional)", type: "text", required: false, placeholder: "例：提升營收、減少流失、簡化方案", placeholderEn: "e.g. grow revenue, reduce churn, simplify plans" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位定價策略審計師，找出隱藏的收入漏洞並設計優化方案。",
      "", `產品/定價：${v.product}`,
      v.metrics ? `數據：${v.metrics}` : "",
      v.goal ? `目標：${v.goal}` : "",
      "", "### 1. 收入漏洞診斷",
      "識別 5 個定價層面的收入漏洞（定價過低/方案混亂/缺少高階方案/折扣失控/未抓價值），每個附影響估算",
      "輸出 ```chart 長條圖顯示各漏洞的潛在收入影響。",
      "", "### 2. 定價架構重設計",
      "優化後的方案架構（名稱/價格/功能/目標客群/高亮）+ 推薦方案標示策略",
      "", "### 3. 價值錨定",
      "如何更好地傳達價值（價值指標定價/分層邏輯/錨定設計）",
      "", "### 4. 漲價實驗",
      "若該漲價：漲幅建議 / 漲價對象 / 溝通策略 / 既有客戶處理 / 風險控制",
      "", "### 5. 實施與監控",
      "定價變更的實施步驟 + 該追蹤的指標 + A/B 測試建議。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a pricing strategy auditor finding hidden revenue leaks and designing optimization.",
      "", `Product/Pricing: ${v.product}`,
      v.metrics ? `Data: ${v.metrics}` : "",
      v.goal ? `Goal: ${v.goal}` : "",
      "", "### 1. Revenue Leak Diagnostic — 5 pricing leaks (underpricing/plan confusion/missing premium tier/discount creep/value not captured) with impact estimate. ```chart bar chart of potential revenue impact.",
      "### 2. Pricing Structure Redesign — optimized plans (name/price/features/target/highlight) + recommended-plan strategy",
      "### 3. Value Anchoring — better value communication (value-metric pricing/tiering logic/anchoring design)",
      "### 4. Price Increase Experiment — if warranted: increase amount / who / communication / existing customer handling / risk control",
      "### 5. Implementation & Monitoring — rollout steps + metrics to track + A/B test recommendations. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 204. 財務健康分析師 ──────────────────────────────────────────────────
  financialhealth: {
    inputs: [
      { key: "overview", label: "財務概況", labelEn: "Financial Overview", type: "textarea", required: true, placeholder: "公司、行業、營收、毛利率、主要成本、現金狀況", placeholderEn: "Company, industry, revenue, margin, main costs, cash position" },
      { key: "concern", label: "主要財務顧慮", labelEn: "Main Financial Concern", type: "text", required: true, placeholder: "例：現金吃緊、毛利下滑、成本失控、成長停滯", placeholderEn: "e.g. cash crunch, margin decline, cost overrun, stalled growth" },
      { key: "goal", label: "目標（選填）", labelEn: "Goal (optional)", type: "text", required: false, placeholder: "想達成的財務目標", placeholderEn: "Financial goal to achieve" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位 CFO 等級的財務健康分析師，提供診斷與可執行的改善計畫。",
      "", `財務概況：${v.overview}`, `顧慮：${v.concern}`,
      v.goal ? `目標：${v.goal}` : "",
      "", "### 1. 財務健康診斷",
      "評估關鍵指標（營收成長/毛利率/淨利率/現金轉換週期/負債比），各附數值 / 行業標竿 / 評級（🟢🟡🔴）",
      "輸出 ```chart 長條圖顯示各指標健康評分。",
      "", "### 2. 現金流分析",
      "現金流現況 / 主要風險 / 現金跑道估算",
      "", "### 3. 成本優化",
      "3 個最有潛力的降本機會 + 估算節省",
      "", "### 4. 90 天 CFO 計畫",
      "用 ```mermaid gantt 規劃 90 天財務改善行動（每週重點 + 預期效益）。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a CFO-level financial health analyst providing diagnostics and executable improvement plans.",
      "", `Financial overview: ${v.overview}`, `Concern: ${v.concern}`,
      v.goal ? `Goal: ${v.goal}` : "",
      "", "### 1. Financial Health Diagnostic — key metrics (revenue growth/gross margin/net margin/cash conversion cycle/debt ratio): value / benchmark / rating (🟢🟡🔴). ```chart bar chart.",
      "### 2. Cash Flow Analysis — current state / key risks / runway estimate",
      "### 3. Cost Optimization — 3 highest-potential reductions + estimated savings",
      "### 4. 90-Day CFO Plan — ```mermaid gantt of financial improvement actions (weekly focus + expected benefit). Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 242. 現金流規劃師 ────────────────────────────────────────────────────
  cashflowPlanner: {
    inputs: [
      { key: "financial", label: "財務描述", labelEn: "Financial Description", type: "textarea", required: true, placeholder: "營收、成本、現金餘額、應收應付、季節性", placeholderEn: "Revenue, costs, cash balance, AR/AP, seasonality" },
      { key: "concern", label: "現金流顧慮", labelEn: "Cash Flow Concern", type: "text", required: true, placeholder: "例：季節性缺口、應收太慢、擴張燒錢", placeholderEn: "e.g. seasonal gap, slow AR, expansion burn" },
      { key: "horizon", label: "規劃期間（選填）", labelEn: "Planning Horizon (optional)", type: "text", required: false, placeholder: "例：6 個月、12 個月", placeholderEn: "e.g. 6 months, 12 months" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位現金流規劃顧問,協助企業維持健康的流動性。",
      "", `財務：${v.financial}`, `顧慮：${v.concern}`,
      v.horizon ? `期間：${v.horizon}` : "",
      "", "### 1. 現金流預測",
      "逐月現金流預測(現金流入/流出/淨現金/期末餘額),三情境(保守/基本/樂觀)",
      "輸出 ```chart 折線圖顯示三情境現金餘額曲線。",
      "", "### 2. 流動性管理",
      "現金跑道估算 / 最低安全現金水位 / 季節性緩衝建議",
      "", "### 3. 缺口應對策略",
      "若有缺口:加速應收 / 延後應付 / 削減成本 / 融資選項,各附可行性與影響",
      "", "### 4. 監控機制",
      "現金流關鍵指標 + 預警觸發點 + 每週/每月檢視節律。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a cash flow planning advisor helping companies maintain healthy liquidity.",
      "", `Financial: ${v.financial}`, `Concern: ${v.concern}`,
      v.horizon ? `Horizon: ${v.horizon}` : "",
      "", "### 1. Cash Flow Forecast — monthly forecast (inflow/outflow/net/ending balance), 3 scenarios (conservative/base/optimistic). ```chart line chart of ending balance.",
      "### 2. Liquidity Management — runway estimate / minimum safe cash level / seasonal buffer",
      "### 3. Gap Response — if gap: accelerate AR / delay AP / cut costs / financing options, each with feasibility and impact",
      "### 4. Monitoring — key cash flow metrics + alert triggers + weekly/monthly review cadence. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 251. 損益平衡分析師 ──────────────────────────────────────────────────
  breakEvenAnalyst: {
    inputs: [
      { key: "costs", label: "成本結構", labelEn: "Cost Structure", type: "textarea", required: true, placeholder: "固定成本、變動成本、單位售價、目前銷量", placeholderEn: "Fixed costs, variable costs, unit price, current volume" },
      { key: "product", label: "產品 / 業務", labelEn: "Product / Business", type: "text", required: true, placeholder: "產品類型、商業模式", placeholderEn: "Product type, business model" },
      { key: "goal", label: "分析目標（選填）", labelEn: "Analysis Goal (optional)", type: "text", required: false, placeholder: "例：評估漲價、新產品定價、產能決策", placeholderEn: "e.g. evaluate price increase, new product pricing, capacity decision" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位財務分析師，提供精準的損益平衡分析與定價建議。",
      "", `成本結構：${v.costs}`, `產品：${v.product}`,
      v.goal ? `目標：${v.goal}` : "",
      "", "### 1. 損益平衡計算",
      "貢獻邊際 / 損益平衡點(數量與金額)/ 安全邊際,附計算過程",
      "", "### 2. 情境敏感度",
      "成本/售價/銷量變動 ±10%/±20% 對損益平衡的影響,用表格呈現",
      "輸出 ```chart 長條圖顯示各情境的損益平衡點變化。",
      "", "### 3. 目標利潤分析",
      "達成目標利潤所需的銷量 / 不同利潤目標的所需銷量對照",
      "", "### 4. 定價建議",
      "基於分析的定價策略建議 + 提升貢獻邊際的 3 個方向。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a financial analyst providing precise break-even analysis and pricing recommendations.",
      "", `Cost structure: ${v.costs}`, `Product: ${v.product}`,
      v.goal ? `Goal: ${v.goal}` : "",
      "", "### 1. Break-Even Calculation — contribution margin / break-even point (units and revenue) / margin of safety, with workings",
      "### 2. Scenario Sensitivity — impact of ±10%/±20% changes in cost/price/volume on break-even, table. ```chart bar chart.",
      "### 3. Target Profit Analysis — volume needed for target profit / volume table for different profit goals",
      "### 4. Pricing Recommendations — pricing strategy + 3 ways to improve contribution margin. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 260. 年度預算規劃師 ──────────────────────────────────────────────────
  budgetForecaster: {
    inputs: [
      { key: "company", label: "公司 / 財務概況", labelEn: "Company / Financial Overview", type: "textarea", required: true, placeholder: "公司、行業、營收、主要成本、部門結構", placeholderEn: "Company, industry, revenue, main costs, department structure" },
      { key: "goal", label: "年度目標", labelEn: "Annual Goals", type: "text", required: true, placeholder: "例：成長 30%、改善獲利、控制成本", placeholderEn: "e.g. grow 30%, improve profit, control costs" },
      { key: "assumptions", label: "關鍵假設（選填）", labelEn: "Key Assumptions (optional)", type: "text", required: false, placeholder: "成長率、市場、人力擴張", placeholderEn: "Growth rate, market, headcount expansion" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位財務規劃顧問,建立務實且有彈性的年度預算。",
      "", `公司：${v.company}`, `年度目標：${v.goal}`,
      v.assumptions ? `關鍵假設：${v.assumptions}` : "",
      "", "### 1. 收支預測",
      "年度收入預測(分季)+ 主要成本預測 + 預期損益,三情境(保守/基本/樂觀)",
      "輸出 ```chart 折線圖顯示三情境營收。",
      "", "### 2. 部門預算分配",
      "各部門預算建議與佔比 + 分配邏輯,用表格呈現",
      "輸出 ```chart 圓餅圖顯示部門預算分配。",
      "", "### 3. 成本控管策略",
      "彈性成本 vs 固定成本管理 / 關鍵成本科目控管 / 撙節機會",
      "", "### 4. 預算監控機制",
      "預算 vs 實際追蹤節律 + 預警閾值 + 調整觸發條件。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a financial planning consultant building pragmatic, flexible annual budgets.",
      "", `Company: ${v.company}`, `Annual goals: ${v.goal}`,
      v.assumptions ? `Key assumptions: ${v.assumptions}` : "",
      "", "### 1. Revenue & Expense Forecast — annual revenue (quarterly) + main cost forecast + expected P&L, 3 scenarios. ```chart line chart.",
      "### 2. Department Budget Allocation — budget per department with share + allocation logic, table. ```chart pie chart.",
      "### 3. Cost Control Strategy — flexible vs fixed cost management / key cost line control / savings opportunities",
      "### 4. Budget Monitoring — budget vs actual cadence + alert thresholds + adjustment triggers. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 278. VC 融資準備度診斷師 ─────────────────────────────────────────────
  vcReadiness: {
    inputs: [
      { key: "company", label: "公司描述", labelEn: "Company Description", type: "textarea", required: true, placeholder: "公司、商業模式、牽引力、團隊、目標輪次", placeholderEn: "Company, business model, traction, team, target round" },
      { key: "metrics", label: "關鍵數據", labelEn: "Key Metrics", type: "textarea", required: true, placeholder: "ARR/MRR、成長率、CAC/LTV、燒錢率、跑道", placeholderEn: "ARR/MRR, growth rate, CAC/LTV, burn rate, runway" },
      { key: "ask", label: "募資目標（選填）", labelEn: "Fundraising Target (optional)", type: "text", required: false, placeholder: "金額、估值、用途", placeholderEn: "Amount, valuation, use of funds" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你將以 VC 視角診斷這家公司的融資準備度,毫不留情地指出弱點。",
      "", `公司：${v.company}`, `關鍵數據：${v.metrics}`,
      v.ask ? `募資目標：${v.ask}` : "",
      "", "### 1. 投資人視角評分",
      "從 VC 角度評分(1-10)：團隊 / 市場 / 牽引力 / 商業模式 / 競爭壁壘 / 單位經濟 / 募資合理性",
      "輸出 ```chart 長條圖顯示各維度評分。",
      "", "### 2. 弱點修補清單",
      "最可能被 VC 質疑的 5 個弱點 + 每個的修補建議 + 修補後的預期改善",
      "", "### 3. 投資亮點與風險",
      "最強的 3 個投資亮點 / 最大的 3 個投資風險(誠實)",
      "", "### 4. 募資節奏建議",
      "是否該現在募 / 該補強什麼再募 / 建議的募資時程與投資人類型 / 整體準備度結論。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You will diagnose this company's fundraising readiness from a VC's perspective, bluntly flagging weaknesses.",
      "", `Company: ${v.company}`, `Key metrics: ${v.metrics}`,
      v.ask ? `Fundraising target: ${v.ask}` : "",
      "", "### 1. Investor Perspective Scoring — VC view (1–10): team / market / traction / business model / moat / unit economics / raise reasonableness. ```chart bar chart.",
      "### 2. Weakness Fix List — 5 weaknesses VCs will likely challenge + fix recommendations + expected improvement",
      "### 3. Investment Highlights & Risks — top 3 highlights / top 3 risks (honest)",
      "### 4. Fundraising Timing — raise now or strengthen first / what to fix / recommended timeline and investor types / overall readiness verdict. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 288. 部門預算優化師 ──────────────────────────────────────────────────
  budgetOptimizer: {
    inputs: [
      { key: "budget", label: "預算描述", labelEn: "Budget Description", type: "textarea", required: true, placeholder: "部門、現有預算結構、主要支出項目", placeholderEn: "Department, current budget structure, main expense items" },
      { key: "goal", label: "優化目標", labelEn: "Optimization Goal", type: "text", required: true, placeholder: "例：削減 15%、提升效益、重配置", placeholderEn: "e.g. cut 15%, improve ROI, reallocate" },
      { key: "constraints", label: "限制（選填）", labelEn: "Constraints (optional)", type: "text", required: false, placeholder: "不可削減的項目、合約綁定", placeholderEn: "Non-cuttable items, contractual commitments" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位預算優化顧問,協助部門以最少資源達成最大效益。",
      "", `預算：${v.budget}`, `目標：${v.goal}`,
      v.constraints ? `限制：${v.constraints}` : "",
      "", "### 1. 成本效益診斷",
      "各支出項目的效益評估(必要性×回報)+ 分類(高效益/可優化/低效益)",
      "輸出 ```chart 長條圖顯示各項目的效益評分。",
      "", "### 2. 削減建議",
      "可削減項目 + 削減幅度 + 對營運的影響評估 + 優先序",
      "", "### 3. 資源重配置策略",
      "從低效益移到高效益的重配置建議 + 預期效益提升",
      "", "### 4. 執行與監控",
      "優化後預算分配 + 執行步驟 + 監控指標。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a budget optimization consultant helping departments achieve maximum impact with minimal resources.",
      "", `Budget: ${v.budget}`, `Goal: ${v.goal}`,
      v.constraints ? `Constraints: ${v.constraints}` : "",
      "", "### 1. Cost-Effectiveness Diagnostic — ROI per expense (necessity × return) + classification (high-ROI/optimizable/low-ROI). ```chart bar chart of ROI scores.",
      "### 2. Reduction Recommendations — cuttable items + reduction amount + operational impact + priority",
      "### 3. Reallocation Strategy — reallocate from low to high ROI + expected improvement",
      "### 4. Execution & Monitoring — optimized allocation + execution steps + monitoring metrics. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 298. 股權結構顧問 ────────────────────────────────────────────────────
  capTableAdvisor: {
    inputs: [
      { key: "captable", label: "股權結構描述", labelEn: "Cap Table Description", type: "textarea", required: true, placeholder: "現有股東與持股、期權池、已募輪次", placeholderEn: "Current shareholders and holdings, option pool, rounds raised" },
      { key: "scenario", label: "情境 / 問題", labelEn: "Scenario / Question", type: "text", required: true, placeholder: "例:新一輪融資、發期權、創辦人分股、稀釋擔憂", placeholderEn: "e.g. new round, granting options, founder split, dilution concern" },
      { key: "goal", label: "目標（選填）", labelEn: "Goal (optional)", type: "text", required: false, placeholder: "想達成的股權結果", placeholderEn: "Desired equity outcome" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位股權結構顧問,協助創辦人理解並優化股權決策。",
      "⚠️ 涉及法律與稅務,正式決策前請諮詢律師與會計師。",
      "", `股權結構：${v.captable}`, `情境/問題：${v.scenario}`,
      v.goal ? `目標：${v.goal}` : "",
      "", "### 1. 股權分配診斷",
      "現有股權結構分析 / 是否健康(創辦人持股/期權池/投資人比例)/ 潛在問題",
      "輸出 ```chart 圓餅圖顯示現有股權分布。",
      "", "### 2. 稀釋情境模擬",
      "依情境模擬稀釋後的股權結構(全行使)+ 各方持股變化,用表格呈現",
      "", "### 3. 投資輪次影響分析",
      "本次決策對創辦人控制權/未來募資/員工激勵的影響",
      "", "### 4. 建議",
      "股權結構優化建議 + 該避免的陷阱 + 談判要點。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a cap table advisor helping founders understand and optimize equity decisions.",
      "⚠️ Involves legal and tax — consult an attorney and accountant before decisions.",
      "", `Cap table: ${v.captable}`, `Scenario/question: ${v.scenario}`,
      v.goal ? `Goal: ${v.goal}` : "",
      "", "### 1. Equity Distribution Diagnostic — current structure analysis / health (founder stake/option pool/investor ratio) / potential problems. ```chart pie chart of current distribution.",
      "### 2. Dilution Scenario Simulation — post-scenario structure (fully diluted) + ownership changes per party, table",
      "### 3. Investment Round Impact — impact on founder control / future fundraising / employee incentives",
      "### 4. Recommendations — structure optimization + pitfalls to avoid + negotiation points. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 308. 債務重組顧問 ────────────────────────────────────────────────────
  debtRestructuring: {
    inputs: [
      { key: "situation", label: "債務狀況", labelEn: "Debt Situation", type: "textarea", required: true, placeholder: "債務總額、結構、到期、現金流、營運狀況", placeholderEn: "Total debt, structure, maturities, cash flow, operations" },
      { key: "goal", label: "目標", labelEn: "Goal", type: "text", required: true, placeholder: "例：降低利息、延長期限、避免違約、改善現金流", placeholderEn: "e.g. lower interest, extend terms, avoid default, improve cash flow" },
      { key: "creditors", label: "債權人情況（選填）", labelEn: "Creditor Situation (optional)", type: "text", required: false, placeholder: "主要債權人類型與態度", placeholderEn: "Main creditor types and attitudes" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位企業財務重組顧問,協助企業改善債務結構與流動性。",
      "⚠️ 涉及法律與財務,正式決策前請諮詢專業顧問。",
      "", `債務狀況：${v.situation}`, `目標：${v.goal}`,
      v.creditors ? `債權人情況：${v.creditors}` : "",
      "", "### 1. 債務診斷",
      "債務結構分析(到期/利率/擔保)+ 償債能力評估 + 風險等級",
      "輸出 ```chart 圓餅圖顯示債務結構分布。",
      "", "### 2. 重組策略選項",
      "可行的重組方式(展延/降息/債轉股/再融資/部分清償)比較,用表格附可行性與影響",
      "", "### 3. 債權人談判指引",
      "各類債權人的利益與談判策略 / 重組方案的說服重點 / 談判順序",
      "", "### 4. 執行與監控",
      "重組執行步驟 + 現金流改善追蹤 + 避免再陷困境的財務紀律。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a corporate financial restructuring advisor helping improve debt structure and liquidity.",
      "⚠️ Involves legal and financial — consult professionals before decisions.",
      "", `Debt situation: ${v.situation}`, `Goal: ${v.goal}`,
      v.creditors ? `Creditor situation: ${v.creditors}` : "",
      "", "### 1. Debt Diagnostic — structure analysis (maturity/rate/collateral) + debt service capacity + risk level. ```chart pie chart of debt structure.",
      "### 2. Restructuring Options — feasible approaches (extension/rate cut/debt-to-equity/refinance/partial repayment) comparison table with feasibility and impact",
      "### 3. Creditor Negotiation Guide — interests and strategy per creditor type / persuasion points / negotiation order",
      "### 4. Execution & Monitoring — execution steps + cash flow improvement tracking + financial discipline to avoid relapse. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 318. 營運資金管理師 ──────────────────────────────────────────────────
  workingCapitalAdvisor: {
    inputs: [
      { key: "financial", label: "財務描述", labelEn: "Financial Description", type: "textarea", required: true, placeholder: "營收、應收/應付、存貨、現金週期、季節性", placeholderEn: "Revenue, AR/AP, inventory, cash cycle, seasonality" },
      { key: "concern", label: "主要問題", labelEn: "Main Concern", type: "text", required: true, placeholder: "例：現金週轉緊、應收太慢、存貨積壓", placeholderEn: "e.g. tight cash, slow AR, inventory buildup" },
      { key: "goal", label: "目標（選填）", labelEn: "Goal (optional)", type: "text", required: false, placeholder: "想改善的資金效率", placeholderEn: "Capital efficiency to improve" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位營運資金管理顧問,協助企業提升資金效率與流動性。",
      "", `財務：${v.financial}`, `問題：${v.concern}`,
      v.goal ? `目標：${v.goal}` : "",
      "", "### 1. 流動性診斷",
      "現金轉換週期分析(DSO/DIO/DPO)+ 與行業比較 + 資金卡在哪裡",
      "輸出 ```chart 長條圖顯示現金週期各環節天數。",
      "", "### 2. 應收應付優化",
      "加速應收(收款條件/催收/折扣)+ 優化應付(帳期談判)+ 平衡建議",
      "", "### 3. 存貨優化",
      "存貨週轉提升 / 安全庫存優化 / 呆滯處理",
      "", "### 4. 資金效率策略",
      "整體營運資金釋放潛力估算 + 90 天改善行動 + 監控指標。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a working capital management advisor helping improve capital efficiency and liquidity.",
      "", `Financial: ${v.financial}`, `Concern: ${v.concern}`,
      v.goal ? `Goal: ${v.goal}` : "",
      "", "### 1. Liquidity Diagnostic — cash conversion cycle (DSO/DIO/DPO) + vs industry + where cash is trapped. ```chart bar chart of cycle days by component.",
      "### 2. AR/AP Optimization — accelerate AR (payment terms/collection/discounts) + optimize AP (term negotiation) + balance",
      "### 3. Inventory Optimization — turnover improvement / safety stock optimization / dead stock handling",
      "### 4. Capital Efficiency — total working capital release potential + 90-day actions + monitoring metrics. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 328. 併購估值分析師 ──────────────────────────────────────────────────
  mergerValuation: {
    inputs: [
      { key: "target", label: "目標公司描述", labelEn: "Target Company Description", type: "textarea", required: true, placeholder: "目標公司、行業、財務(營收/獲利/成長)、資產", placeholderEn: "Target company, industry, financials (revenue/profit/growth), assets" },
      { key: "acquirer", label: "收購方 / 綜效", labelEn: "Acquirer / Synergies", type: "text", required: true, placeholder: "收購方、預期綜效、收購目的", placeholderEn: "Acquirer, expected synergies, acquisition purpose" },
      { key: "comps", label: "可比交易（選填）", labelEn: "Comparable Deals (optional)", type: "text", required: false, placeholder: "類似併購案或上市可比公司", placeholderEn: "Similar M&A deals or public comparables" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位併購估值分析師,提供多方法論的估值與出價建議。",
      "⚠️ 此為參考分析,正式決策前請諮詢財務顧問。",
      "", `目標公司：${v.target}`, `收購方/綜效：${v.acquirer}`,
      v.comps ? `可比交易：${v.comps}` : "",
      "", "### 1. 多方法估值",
      "用 3 種方法估值：DCF / 可比公司倍數 / 可比交易,各附假設與估值區間",
      "輸出 ```chart 長條圖比較三種方法的估值。",
      "", "### 2. 綜效價值",
      "收入綜效 + 成本綜效的估算 + 綜效實現的風險與時程",
      "", "### 3. 出價建議",
      "建議出價區間(獨立價值 + 部分綜效)/ 出價結構(現金/股票/earn-out)/ 議價空間",
      "", "### 4. 風險與盡調重點",
      "估值的關鍵風險 + 該在盡調驗證的假設。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are an M&A valuation analyst providing multi-method valuation and bid recommendations.",
      "⚠️ Reference analysis only — consult a financial advisor before decisions.",
      "", `Target company: ${v.target}`, `Acquirer/synergies: ${v.acquirer}`,
      v.comps ? `Comparable deals: ${v.comps}` : "",
      "", "### 1. Multi-Method Valuation — 3 methods: DCF / comparable company multiples / comparable transactions, each with assumptions and range. ```chart bar chart comparing valuations.",
      "### 2. Synergy Value — revenue + cost synergy estimate + realization risk and timeline",
      "### 3. Bid Recommendation — bid range (standalone value + partial synergy) / structure (cash/stock/earn-out) / negotiation room",
      "### 4. Risks & DD Focus — key valuation risks + assumptions to verify in due diligence. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 336. 單位經濟優化師 ──────────────────────────────────────────────────
  unitEconomicsOptimizer: {
    inputs: [
      { key: "model", label: "商業模式描述", labelEn: "Business Model Description", type: "textarea", required: true, placeholder: "商業模式、定價、客戶取得方式、現有單位經濟", placeholderEn: "Business model, pricing, acquisition method, current unit economics" },
      { key: "metrics", label: "現有數據", labelEn: "Current Metrics", type: "text", required: true, placeholder: "CAC、LTV、毛利率、回收期、流失率", placeholderEn: "CAC, LTV, gross margin, payback, churn" },
      { key: "goal", label: "目標（選填）", labelEn: "Goal (optional)", type: "text", required: false, placeholder: "想改善的單位經濟指標", placeholderEn: "Unit economics metric to improve" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位單位經濟分析顧問,協助企業建立可持續的成長經濟模型。",
      "", `商業模式：${v.model}`, `現有數據：${v.metrics}`,
      v.goal ? `目標：${v.goal}` : "",
      "", "### 1. 單位經濟診斷",
      "計算/評估 LTV、CAC、LTV:CAC、回收期、貢獻邊際 + 與健康基準比較",
      "輸出 ```chart 長條圖顯示各指標現況 vs 基準。",
      "", "### 2. LTV 優化策略",
      "提升 LTV 的槓桿(留存/客單/交叉銷售/漲價)+ 各槓桿的預期影響",
      "", "### 3. CAC 降低計畫",
      "降低 CAC 的方向(管道優化/轉換提升/有機成長/推薦)+ 預期效果",
      "", "### 4. 毛利提升路線圖",
      "毛利率改善機會 + 整體單位經濟改善的優先序與行動。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a unit economics consultant helping build a sustainable growth economic model.",
      "", `Business model: ${v.model}`, `Current metrics: ${v.metrics}`,
      v.goal ? `Goal: ${v.goal}` : "",
      "", "### 1. Unit Economics Diagnostic — calculate/assess LTV, CAC, LTV:CAC, payback, contribution margin + vs healthy benchmarks. ```chart bar chart current vs benchmark.",
      "### 2. LTV Optimization — levers to raise LTV (retention/AOV/cross-sell/price increase) + expected impact per lever",
      "### 3. CAC Reduction — directions to lower CAC (channel optimization/conversion lift/organic/referral) + expected effect",
      "### 4. Gross Margin Roadmap — margin improvement opportunities + priority and actions for overall unit economics improvement. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 346. IPO 上市準備師 ──────────────────────────────────────────────────
  ipoReadiness: {
    inputs: [
      { key: "company", label: "公司描述", labelEn: "Company Description", type: "textarea", required: true, placeholder: "公司、行業、規模、財務、上市企圖", placeholderEn: "Company, industry, size, financials, IPO ambition" },
      { key: "market", label: "目標市場 / 時程", labelEn: "Target Market / Timeline", type: "text", required: true, placeholder: "例：台灣上市/上櫃、美股、預計時程", placeholderEn: "e.g. TWSE/TPEx, US listing, expected timeline" },
      { key: "concern", label: "已知顧慮（選填）", labelEn: "Known Concerns (optional)", type: "text", required: false, placeholder: "已意識到的準備缺口", placeholderEn: "Known readiness gaps" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位 IPO 上市準備顧問,協助企業評估上市準備度並規劃路線圖。",
      "⚠️ 涉及法律與財務,正式決策請諮詢承銷商與律師。",
      "", `公司：${v.company}`, `目標市場/時程：${v.market}`,
      v.concern ? `已知顧慮：${v.concern}` : "",
      "", "### 1. 上市準備度評估",
      "從財務稽核 / 法規合規 / 公司治理 / 投資者關係四面向評分,指出主要缺口",
      "輸出 ```chart 長條圖顯示各面向準備度。",
      "", "### 2. 財務與合規準備",
      "財報合規要求 / 內控建置 / 法規門檻 / 該補強的財務指標",
      "", "### 3. 公司治理與 IR",
      "董事會與治理結構建議 / 投資者關係準備 / 上市故事(Equity Story)",
      "", "### 4. 上市路線圖",
      "用 ```mermaid gantt 規劃上市準備時程(輔導→申請→承銷→掛牌)+ 關鍵里程碑。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are an IPO readiness advisor helping companies assess readiness and plan the roadmap.",
      "⚠️ Involves legal and financial — consult underwriters and attorneys for decisions.",
      "", `Company: ${v.company}`, `Target market/timeline: ${v.market}`,
      v.concern ? `Known concerns: ${v.concern}` : "",
      "", "### 1. IPO Readiness Assessment — score across financial audit / regulatory compliance / corporate governance / investor relations, main gaps. ```chart bar chart.",
      "### 2. Financial & Compliance Prep — financial reporting requirements / internal controls / regulatory thresholds / financial metrics to strengthen",
      "### 3. Governance & IR — board and governance structure / investor relations prep / equity story",
      "### 4. IPO Roadmap — ```mermaid gantt of IPO preparation timeline (advisory→filing→underwriting→listing) + key milestones. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
};
