import type { AgentOverride } from "../types";
import { bilingual, field } from "./helpers";

/** legal category agent overrides. See ./index.ts for how these merge. */
export const LEGAL_OVERRIDES: Record<string, AgentOverride> = {
  // ── 20. 補助申請書產生器 ──────────────────────────────────────────────────
  grantwriter: {
    inputs: [
      { key: "org", label: "申請機構 / 計畫名稱", labelEn: "Applicant Organization / Project Name", type: "text", required: true, placeholder: "例：美樂信科技 / 中小企業 AI 轉型加速計畫", placeholderEn: "e.g. MLTech / SME AI Acceleration Project" },
      { key: "program", label: "補助方案 / 主辦單位", labelEn: "Grant Program / Grantor", type: "text", required: true, placeholder: "例：經濟部中小企業處數位轉型補助、SBIR", placeholderEn: "e.g. Ministry of Economic Affairs SME digitalization grant, SBIR" },
      { key: "budget", label: "申請金額 / 預算規劃（選填）", labelEn: "Amount Requested / Budget Breakdown (optional)", type: "textarea", required: false, placeholder: "申請總額及主要支出項目", placeholderEn: "Total requested and main expense categories" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位政府補助申請書撰寫專家，熟悉台灣各類補助計畫的評核邏輯與寫作慣例。",
      "", `申請機構：${v.org}`, `補助方案：${v.program}`,
      v.budget ? `預算：${v.budget}` : "",
      "", "請輸出完整補助申請書架構：",
      "", "### 1. 計畫摘要（Executive Summary）",
      "300字以內，涵蓋：計畫目標、預期效益、申請金額、執行時程。",
      "", "### 2. 問題陳述與需求分析",
      "說明為何需要此計畫，附市場數據或現況統計佐證。",
      "", "### 3. 計畫內容與執行方法",
      "分階段說明（用 Markdown 表格：階段/時程/工作項目/負責人/里程碑）",
      "用 ```mermaid gantt 繪製執行時程。",
      "", "### 4. 預算明細",
      v.budget ? `依 ${v.budget} 分配，` : "" + "用表格呈現：項目/數量/單價/小計/說明，最後加總。",
      "", "### 5. 預期效益與影響力",
      "量化效益（KPI）/ 質化效益 / 可複製性與擴散性",
      "", "### 6. 合規性自我審查清單",
      "常見不合規原因（10項）逐一對照本計畫是否符合（✅/⚠️/❌）。",
      "全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are an expert grant writer familiar with government and foundation grant evaluation criteria.",
      "", `Organization: ${v.org}`, `Grant Program: ${v.program}`,
      v.budget ? `Budget: ${v.budget}` : "",
      "", "### 1. Executive Summary (≤300 words) — objectives, expected impact, amount requested, timeline",
      "### 2. Problem Statement — why this project is needed, with supporting data",
      "### 3. Project Plan — phased table (Phase/Timeline/Activities/Owner/Milestones) + ```mermaid gantt",
      `### 4. Budget Breakdown — table: Item / Qty / Unit cost / Subtotal / Notes${v.budget ? ` based on ${v.budget}` : ""}`,
      "### 5. Expected Impact — quantitative KPIs + qualitative benefits + scalability",
      "### 6. Compliance Self-Check — 10 common disqualification reasons vs this proposal (✅/⚠️/❌). Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 24. 法律文件起草助手 ─────────────────────────────────────────────────
  legal: {
    inputs: [
      { key: "doctype", label: "文件類型", labelEn: "Document Type", type: "text", required: true, placeholder: "例：保密協議(NDA)、服務合約、合夥協議、勞動契約", placeholderEn: "e.g. NDA, Service Agreement, Partnership Agreement, Employment Contract" },
      { key: "parties", label: "締約雙方", labelEn: "Contracting Parties", type: "text", required: true, placeholder: "例：甲方：美樂信科技 / 乙方：客戶公司名稱", placeholderEn: "e.g. Party A: MLTech / Party B: Client Company" },
      { key: "keyterms", label: "關鍵條款 / 特殊需求", labelEn: "Key Terms / Special Requirements", type: "textarea", required: true, placeholder: "合約期限、金額、特殊保護條款、地點/法律管轄…", placeholderEn: "Contract term, amount, special protections, jurisdiction…" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位擁有商業法實務經驗的法律顧問，擅長起草清晰、平衡、具保護性的商業文件。",
      "⚠️ 以下為參考草稿，正式簽署前請諮詢持牌律師。",
      "", `文件類型：${v.doctype}`, `締約方：${v.parties}`, `關鍵條款：${v.keyterms}`,
      "", "### 1. 文件架構說明",
      "此類文件的標準章節結構 / 各章節功能說明 / 本次特殊注意事項",
      "", "### 2. 核心條款草稿",
      "依文件類型輸出主要條款（定義、範圍、義務、期限、付款、終止）的具體文字。",
      "", "### 3. 保護條款",
      "依當事人利益，加入：保密義務 / 智財保護 / 責任限制 / 免責聲明 / 爭議解決",
      "", "### 4. 風險識別報告",
      "指出 5 個常見遺漏或模糊地帶，每個附：風險描述 / 建議條款補強方式",
      "", "### 5. 完整文件草稿",
      "輸出可直接參考的完整合約草稿（含所有章節編號、甲乙方佔位符）。",
      "全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a commercial law consultant experienced in drafting clear, balanced, and protective business documents.",
      "⚠️ The following is a reference draft — consult a licensed attorney before signing.",
      "", `Document Type: ${v.doctype}`, `Parties: ${v.parties}`, `Key Terms: ${v.keyterms}`,
      "", "### 1. Document Structure — standard sections for this document type + notes on special considerations",
      "### 2. Core Clauses Draft — definitions / scope / obligations / term / payment / termination with specific language",
      "### 3. Protective Clauses — confidentiality / IP protection / limitation of liability / disclaimers / dispute resolution",
      "### 4. Risk Report — 5 commonly missed or ambiguous areas with recommended clause additions",
      "### 5. Complete Draft — full contract draft with all sections numbered and party placeholders. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 27. ESG 永續報告 ──────────────────────────────────────────────────────
  esg: {
    inputs: [
      { key: "company", label: "公司名稱 / 行業 / 規模", labelEn: "Company / Industry / Size", type: "text", required: true, placeholder: "例：台灣製造業，員工 200 人，年營收 5 億", placeholderEn: "e.g. Taiwan manufacturer, 200 employees, NT$500M revenue" },
      { key: "current", label: "現有 ESG 措施（選填）", labelEn: "Current ESG Initiatives (optional)", type: "textarea", required: false, placeholder: "已採取的環境/社會/治理相關措施", placeholderEn: "Existing environmental, social, governance initiatives" },
      { key: "goals", label: "永續目標 / 驅動因素", labelEn: "Sustainability Goals / Drivers", type: "text", required: true, placeholder: "例：2030 碳中和、供應商要求、上市準備、投資人要求", placeholderEn: "e.g. carbon neutral by 2030, supplier requirements, IPO prep, investor pressure" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位 ESG 永續報告顧問，熟悉 GRI、TCFD、SASB 等主流框架。",
      "", `公司：${v.company}`, `現有措施：${v.current || "未提供"}`, `目標：${v.goals}`,
      "", "### E — 環境面",
      "碳排放基線估算（Scope 1/2/3）/ 主要環境衝擊 / 氣候風險與機會（TCFD 框架）/ 減碳路徑建議",
      "", "### S — 社會面",
      "員工福利現況評估 / 多元包容指標 / 供應鏈社會責任 / 社區影響 / 改善建議",
      "", "### G — 治理面",
      "董事會結構評估 / 反貪腐機制 / 資訊揭露品質 / 利害關係人參與 / 改善建議",
      "", "### 重大性矩陣",
      "識別 10 個重大 ESG 議題（對利害關係人的影響 × 對公司的影響），用文字描述四象限定位。",
      "輸出 ```chart 長條圖顯示各議題的綜合重大性分數。",
      "", "### 路線圖",
      `針對 ${v.goals}，用 \`\`\`mermaid gantt 規劃 3 年 ESG 行動路線圖。`,
      "", "### GRI/SASB 對應建議",
      "建議優先採用的 GRI 標準 / SASB 行業標準（依行業）/ 首次揭露建議架構。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are an ESG sustainability report consultant familiar with GRI, TCFD, and SASB frameworks.",
      "", `Company: ${v.company}`, `Current Initiatives: ${v.current || "not provided"}`, `Goals: ${v.goals}`,
      "", "### E — Environmental — Scope 1/2/3 baseline estimate / key impacts / TCFD climate risks & opportunities / decarbonization pathway",
      "### S — Social — employee wellbeing / DEI metrics / supply chain responsibility / community impact / improvements",
      "### G — Governance — board structure / anti-corruption / disclosure quality / stakeholder engagement / improvements",
      `### Materiality Matrix — 10 material ESG topics (stakeholder impact × business impact), text quadrant analysis. Output \`\`\`chart bar chart of materiality scores.`,
      `### Roadmap — \`\`\`mermaid gantt for 3-year ESG action plan toward ${v.goals}`,
      "### GRI/SASB Alignment — recommended standards and first-report disclosure structure. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 51. 法規合規審查師 ───────────────────────────────────────────────────
  compliance: {
    inputs: [
      { key: "company", label: "公司名稱 / 行業 / 規模", labelEn: "Company / Industry / Size", type: "text", required: true, placeholder: "例：台灣科技新創，30 人，處理用戶個資", placeholderEn: "e.g. Taiwan tech startup, 30 employees, handles user data" },
      { key: "operations", label: "主要業務活動", labelEn: "Main Business Activities", type: "textarea", required: true, placeholder: "主要業務、資料處理方式、僱用員工類型、產品/服務性質", placeholderEn: "Main operations, data handling, employee types, product/service nature" },
      { key: "jurisdiction", label: "法律管轄 / 目標市場", labelEn: "Jurisdiction / Target Markets", type: "text", required: false, placeholder: "例：台灣、歐盟（GDPR）、美國（CCPA）", placeholderEn: "e.g. Taiwan, EU (GDPR), US (CCPA)" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位企業法規合規顧問，協助公司識別合規缺口並制定優先改善計畫。",
      "⚠️ 以下為參考分析，正式法律意見請諮詢持牌律師。",
      "", `公司：${v.company}`, `業務：${v.operations}`,
      v.jurisdiction ? `管轄：${v.jurisdiction}` : "",
      "", "### 1. 適用法規篩查",
      "依業務特性，識別最相關的法規類別（個資保護/勞工法規/公司商法/行業特定法規/稅務）及具體法規名稱。用表格：法規名稱 / 適用原因 / 合規優先度（高/中/低）。",
      "", "### 2. 個資保護審查",
      "資料蒐集合法性 / 同意機制 / 資料保存與刪除 / 第三方共享 / 主要缺口（依適用法規）",
      "", "### 3. 勞工法規審查",
      "僱用合規 / 工時與薪資 / 職場安全 / 遠距/約聘合規 / 主要缺口",
      "", "### 4. 公司商法審查",
      "公司治理 / 智財保護 / 合約合規 / 競業條款 / 主要缺口",
      "", "### 5. 優先行動計畫",
      "用表格：行動項目 / 對應法規 / 緊急度（🔴立即/🟡3個月/🟢6個月） / 負責單位 / 預估工時。",
      "輸出 ```chart 長條圖顯示各法規類別的合規缺口數量。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a corporate regulatory compliance advisor who identifies compliance gaps and prioritizes remediation.",
      "⚠️ The following is reference analysis — consult a licensed attorney for formal legal advice.",
      "", `Company: ${v.company}`, `Operations: ${v.operations}`,
      v.jurisdiction ? `Jurisdiction: ${v.jurisdiction}` : "",
      "", "### 1. Applicable Regulations Screening — table: Regulation / Why it applies / Priority (H/M/L) covering data protection/labor/corporate law/sector-specific/tax",
      "### 2. Data Protection Review — data collection lawfulness / consent / retention & deletion / third-party sharing / key gaps",
      "### 3. Labor Law Review — employment compliance / working hours & pay / workplace safety / remote/contractor compliance / key gaps",
      "### 4. Corporate Law Review — governance / IP protection / contract compliance / non-compete clauses / key gaps",
      "### 5. Priority Action Plan — table: Action / Regulation / Urgency (🔴Immediate/🟡3mo/🟢6mo) / Owner / Estimated effort + ```chart bar chart of gaps by category. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 112. 法規合規檢查師 ──────────────────────────────────────────────────
  compliancecheck: {
    inputs: [
      { key: "business", label: "業務描述", labelEn: "Business Description", type: "textarea", required: true, placeholder: "公司名稱、主要業務、處理的數據類型、目標市場", placeholderEn: "Company name, main business, data types handled, target markets" },
      { key: "regulation", label: "特定法規（選填）", labelEn: "Specific Regulation (optional)", type: "text", required: false, placeholder: "例：GDPR、CCPA、個人資料保護法、PCI DSS", placeholderEn: "e.g. GDPR, CCPA, Taiwan PDPA, PCI DSS" },
      { key: "current", label: "現有合規措施（選填）", labelEn: "Current Compliance Measures (optional)", type: "text", required: false, placeholder: "已採取的合規措施，方便進行缺口分析", placeholderEn: "Existing compliance measures, for gap analysis" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位法規合規顧問，協助企業快速識別合規缺口並制定改善路徑。",
      "⚠️ 正式法律意見請諮詢持牌律師。",
      "", `業務：${v.business}`,
      v.regulation ? `法規：${v.regulation}` : "",
      v.current ? `現有措施：${v.current}` : "",
      "", "### 1. 適用法規識別",
      "依業務特性，識別最相關的 5-8 個法規（含條文名稱/適用理由/管轄機關）",
      "", "### 2. 合規缺口分析",
      "逐法規評估：合規要求 / 現況評估（✅符合/⚠️部分/❌缺口）/ 缺口說明",
      "輸出 ```chart 長條圖顯示各法規類別的缺口嚴重程度。",
      "", "### 3. 個資保護建議",
      "隱私政策要求 / 同意機制 / 資料主體權利回應 / 資安事件通報義務",
      "", "### 4. 修正路線圖",
      "緊急（立即）/ 短期（1-3月）/ 中期（3-6月）的修正行動清單，每項附估計工時",
      "", "### 5. 合規健康評分",
      "整體合規健康評分（0-100）/ 各類別分項分數 / 改善後預期分數。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a regulatory compliance advisor helping companies quickly identify compliance gaps and improvement paths.",
      "⚠️ Consult a licensed attorney for formal legal advice.",
      "", `Business: ${v.business}`,
      v.regulation ? `Regulation: ${v.regulation}` : "",
      v.current ? `Current measures: ${v.current}` : "",
      "", "### 1. Applicable Regulation Identification — 5–8 most relevant regulations (name / why applicable / governing body)",
      "### 2. Compliance Gap Analysis — per regulation: requirement / current status (✅/⚠️/❌) / gap description. ```chart bar chart of gap severity by category.",
      "### 3. Data Protection Recommendations — privacy policy requirements / consent mechanisms / data subject rights / breach notification obligations",
      "### 4. Correction Roadmap — urgent (immediate) / short-term (1–3mo) / medium-term (3–6mo) action list with estimated effort",
      "### 5. Compliance Health Score — overall score (0–100) / category sub-scores / projected score after improvements. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 141. 合約談判準備師 ──────────────────────────────────────────────────
  contractnegotiation: {
    inputs: [
      { key: "contract", label: "合約描述 / 草稿", labelEn: "Contract Description / Draft", type: "textarea", required: true, placeholder: "合約類型、主要條款、爭議點、目前草稿（若有）", placeholderEn: "Contract type, main terms, disputed points, current draft (if any)" },
      { key: "role", label: "你的角色", labelEn: "Your Role", type: "text", required: true, placeholder: "甲方（買方/客戶）/ 乙方（賣方/供應商）/ 雙方顧問", placeholderEn: "Party A (buyer/client) / Party B (seller/vendor) / neutral advisor" },
      { key: "priority", label: "最重要的談判目標", labelEn: "Most Important Negotiation Goals", type: "text", required: true, placeholder: "最在乎什麼？例：降低違約風險、增加支付靈活性、保護智財", placeholderEn: "What matters most? e.g. lower breach risk, payment flexibility, IP protection" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位合約談判顧問，協助當事人在合約談判中保護自身利益。",
      "⚠️ 正式法律意見請諮詢持牌律師。",
      "", `合約：${v.contract}`, `角色：${v.role}`, `目標：${v.priority}`,
      "", "### 1. 風險分析",
      "從你的角色出發，識別合約中 TOP 5 風險條款：",
      "條款名稱 / 具體風險 / 嚴重程度（🔴/🟡/🟢）/ 建議修改方向",
      "", "### 2. 談判策略",
      "你的籌碼評估（強/中/弱）/ 對方可能的優先考量 / 最佳談判順序（先易後難）",
      "", "### 3. 條款修改建議",
      "針對每個高風險條款，提供：",
      "原條款問題 / 建議修改語言 / 理由（附雙方接受的合理解釋）",
      "", "### 4. 談判話術",
      "3 個最難談的條款的談判策略：",
      "開場話術 / 讓步計畫 / 成交語言",
      "", "### 5. 談判清單",
      "談判前的準備清單（10條）/ 談判中的注意事項 / 簽約前的最後確認清單。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a contract negotiation advisor helping parties protect their interests.",
      "⚠️ Consult a licensed attorney for formal legal advice.",
      "", `Contract: ${v.contract}`, `Role: ${v.role}`, `Priority: ${v.priority}`,
      "", "### 1. Risk Analysis — from your role's perspective, identify top 5 risky clauses: clause name / specific risk / severity (🔴/🟡/🟢) / recommended modification direction",
      "### 2. Negotiation Strategy — your leverage (strong/medium/weak) / counterpart's likely priorities / optimal negotiation sequence (easy first)",
      "### 3. Clause Modification Recommendations — per high-risk clause: original problem / suggested language / rationale (with mutually acceptable framing)",
      "### 4. Negotiation Scripts — for the 3 hardest clauses: opening / concession plan / closing language",
      "### 5. Negotiation Checklist — pre-negotiation prep (10 items) / during-negotiation watch-outs / pre-signing final verification. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 156. 企業合規顧問 ────────────────────────────────────────────────────
  legalcompliance: {
    inputs: [
      { key: "business", label: "業務描述", labelEn: "Business Description", type: "textarea", required: true, placeholder: "公司名稱、行業、規模、主要業務活動、所在地", placeholderEn: "Company name, industry, size, main activities, location" },
      { key: "focus", label: "關注領域（選填）", labelEn: "Focus Area (optional)", type: "text", required: false, placeholder: "例：勞動法、稅務、產業特許、智財", placeholderEn: "e.g. labor law, tax, industry licensing, IP" },
      { key: "current", label: "現有合規措施（選填）", labelEn: "Current Compliance (optional)", type: "text", required: false, placeholder: "已採取的合規措施", placeholderEn: "Compliance measures already in place" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位企業合規顧問，協助企業建立系統性的合規體系。",
      "⚠️ 正式法律意見請諮詢持牌律師。",
      "", `業務：${v.business}`,
      v.focus ? `關注：${v.focus}` : "",
      v.current ? `現有措施：${v.current}` : "",
      "", "### 1. 風險掃描",
      "依業務識別最相關的合規領域（公司治理/勞動/稅務/產業特許/智財/個資/反貪），每個附風險等級（🔴/🟡/🟢）",
      "輸出 ```chart 長條圖顯示各領域風險程度。",
      "", "### 2. 合規自查清單",
      "依優先度的合規檢查清單（每項：檢查點 / 法規依據 / 自查方法 / 符合與否欄位）",
      "", "### 3. 缺口優先排序",
      "識別 TOP 5 最急迫的合規缺口 + 不合規後果 + 改善建議",
      "", "### 4. 合規建設路線圖",
      "立即（0-1月）/ 短期（1-3月）/ 中期（3-6月）的合規建設行動，用表格呈現。",
      "", "### 5. 持續合規機制",
      "合規負責人設置 / 定期稽核頻率 / 員工培訓計畫 / 法規更新追蹤方法。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a corporate compliance advisor helping companies build systematic compliance programs.",
      "⚠️ Consult a licensed attorney for formal legal advice.",
      "", `Business: ${v.business}`,
      v.focus ? `Focus: ${v.focus}` : "",
      v.current ? `Current measures: ${v.current}` : "",
      "", "### 1. Risk Scan — most relevant compliance areas (governance/labor/tax/licensing/IP/data privacy/anti-corruption) with risk level (🔴/🟡/🟢). ```chart bar chart.",
      "### 2. Compliance Self-Audit Checklist — prioritized checklist (checkpoint / legal basis / self-check method / compliant Y/N column)",
      "### 3. Gap Prioritization — top 5 urgent gaps + consequences of non-compliance + remediation",
      "### 4. Compliance Roadmap — immediate (0–1mo) / short-term (1–3mo) / medium-term (3–6mo) actions, table",
      "### 5. Ongoing Compliance Mechanism — compliance owner / audit frequency / training plan / regulation update tracking. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 157. 資料隱私評估師 ──────────────────────────────────────────────────
  dataprivacy: {
    inputs: [
      { key: "product", label: "產品描述", labelEn: "Product Description", type: "textarea", required: true, placeholder: "產品類型、蒐集哪些用戶資料、如何使用、是否與第三方共享", placeholderEn: "Product type, what user data collected, how used, third-party sharing" },
      { key: "market", label: "目標市場 / 適用法規", labelEn: "Target Market / Applicable Law", type: "text", required: true, placeholder: "例：台灣個資法、GDPR、CCPA", placeholderEn: "e.g. Taiwan PDPA, GDPR, CCPA" },
      { key: "concerns", label: "特定隱私顧慮（選填）", labelEn: "Specific Privacy Concerns (optional)", type: "text", required: false, placeholder: "例：兒童資料、健康資料、跨境傳輸", placeholderEn: "e.g. children's data, health data, cross-border transfer" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位資料隱私顧問，協助產品建立合規且值得信任的隱私實踐。",
      "⚠️ 正式法律意見請諮詢持牌律師。",
      "", `產品：${v.product}`, `市場/法規：${v.market}`,
      v.concerns ? `特定顧慮：${v.concerns}` : "",
      "", "### 1. 隱私風險評估",
      "資料流盤點（蒐集→儲存→使用→共享→刪除）+ 各環節風險點 + 整體風險評級",
      "用 ```mermaid flowchart 呈現資料生命週期。",
      "", "### 2. 合規要求對照",
      "依適用法規列出關鍵合規要求 + 現況評估（✅/⚠️/❌）+ 缺口",
      "", "### 3. 隱私政策框架",
      "隱私政策必備章節 + 各章節要點 / 同意機制設計 / 資料主體權利回應流程",
      "", "### 4. 技術保護措施",
      "建議的技術防護（加密/去識別化/存取控制/留存期限/稽核日誌），每項附實施優先度",
      "", "### 5. 隱私事件應變",
      "資料外洩通報流程 / 通報時限 / 應變團隊角色。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a data privacy advisor helping products build compliant, trustworthy privacy practices.",
      "⚠️ Consult a licensed attorney for formal legal advice.",
      "", `Product: ${v.product}`, `Market/Law: ${v.market}`,
      v.concerns ? `Specific concerns: ${v.concerns}` : "",
      "", "### 1. Privacy Risk Assessment — data flow inventory (collect→store→use→share→delete) + risk points per stage + overall risk rating. ```mermaid flowchart of data lifecycle.",
      "### 2. Compliance Requirement Mapping — key requirements per applicable law + current status (✅/⚠️/❌) + gaps",
      "### 3. Privacy Policy Framework — required sections + key points / consent mechanism / data subject rights response process",
      "### 4. Technical Safeguards — recommended protections (encryption/de-identification/access control/retention/audit logs) with implementation priority",
      "### 5. Privacy Incident Response — breach notification process / timeline / response team roles. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 229. 智慧財產顧問 ────────────────────────────────────────────────────
  ipAdvisor: {
    inputs: [
      { key: "creation", label: "創作 / 資產描述", labelEn: "Creation / Asset Description", type: "textarea", required: true, placeholder: "要保護的發明、品牌、作品、商業機密", placeholderEn: "Invention, brand, work, or trade secret to protect" },
      { key: "business", label: "業務背景", labelEn: "Business Context", type: "text", required: true, placeholder: "行業、市場、競爭情況", placeholderEn: "Industry, market, competitive situation" },
      { key: "region", label: "目標地區（選填）", labelEn: "Target Regions (optional)", type: "text", required: false, placeholder: "例：台灣、美國、中國、歐盟", placeholderEn: "e.g. Taiwan, US, China, EU" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位智慧財產顧問,協助企業以最佳策略保護無形資產。",
      "⚠️ 正式法律意見請諮詢專利商標律師。",
      "", `創作/資產：${v.creation}`, `業務：${v.business}`,
      v.region ? `地區：${v.region}` : "",
      "", "### 1. IP 盤點與分類",
      "識別可保護的 IP 類型(專利/商標/著作權/營業秘密/設計),各附適用性",
      "", "### 2. 保護策略",
      "每類 IP 的建議保護方式 / 申請優先序 / 預估成本與時程,用表格呈現",
      "", "### 3. 風險評估",
      "侵權風險 / 被搶註風險 / 洩密風險 + 防範建議",
      "", "### 4. 保護行動計畫",
      "立即/短期/中期的 IP 保護行動 + 維權機制建議。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are an intellectual property advisor helping companies protect intangible assets with the best strategy.",
      "⚠️ Consult a patent/trademark attorney for formal legal advice.",
      "", `Creation/asset: ${v.creation}`, `Business: ${v.business}`,
      v.region ? `Regions: ${v.region}` : "",
      "", "### 1. IP Inventory & Classification — protectable IP types (patent/trademark/copyright/trade secret/design) with applicability",
      "### 2. Protection Strategy — recommended protection per IP type / filing priority / estimated cost & timeline, table",
      "### 3. Risk Assessment — infringement / pre-emptive registration / leakage risks + safeguards",
      "### 4. Protection Action Plan — immediate/short/medium-term IP actions + enforcement mechanism. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 238. 勞動法規顧問 ────────────────────────────────────────────────────
  employmentLaw: {
    inputs: [
      { key: "scenario", label: "雇主情境", labelEn: "Employer Scenario", type: "textarea", required: true, placeholder: "遇到的勞動相關情境(招募/解僱/工時/爭議等)", placeholderEn: "Labor-related scenario (hiring/termination/hours/dispute, etc.)" },
      { key: "company", label: "公司背景", labelEn: "Company Context", type: "text", required: true, placeholder: "規模、行業、所在地、僱用類型", placeholderEn: "Size, industry, location, employment types" },
      { key: "concern", label: "具體顧慮（選填）", labelEn: "Specific Concern (optional)", type: "text", required: false, placeholder: "最擔心的法律風險", placeholderEn: "Biggest legal risk concern" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位勞動法規顧問,協助雇主合規並降低勞動爭議風險。",
      "⚠️ 以下為參考分析,正式法律意見請諮詢勞動法律師。",
      "", `情境：${v.scenario}`, `公司：${v.company}`,
      v.concern ? `顧慮：${v.concern}` : "",
      "", "### 1. 法規適用分析",
      "此情境適用的勞動法規(勞基法相關條文/特別法)+ 關鍵法律要求",
      "", "### 2. 勞動合規建議",
      "合規做法 / 應避免的違法地雷 / 必備文件與程序",
      "", "### 3. 風險評估",
      "潛在勞動爭議風險(機率×影響)+ 可能的法律後果 + 預防措施",
      "", "### 4. 行動計畫",
      "立即該做的合規行動 + 制度面改善建議 + 爭議發生時的應對原則。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are an employment law advisor helping employers stay compliant and reduce labor dispute risk.",
      "⚠️ Reference analysis only — consult a labor attorney for formal legal advice.",
      "", `Scenario: ${v.scenario}`, `Company: ${v.company}`,
      v.concern ? `Concern: ${v.concern}` : "",
      "", "### 1. Applicable Regulations — relevant labor laws for this scenario + key legal requirements",
      "### 2. Compliance Recommendations — compliant practices / pitfalls to avoid / required documents and procedures",
      "### 3. Risk Assessment — potential dispute risk (probability×impact) + possible legal consequences + prevention",
      "### 4. Action Plan — immediate compliance actions + systemic improvements + dispute response principles. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 244. 隱私政策生成師 ──────────────────────────────────────────────────
  privacyPolicyWriter: {
    inputs: [
      { key: "product", label: "產品描述", labelEn: "Product Description", type: "textarea", required: true, placeholder: "產品、蒐集哪些資料、如何使用、是否第三方共享", placeholderEn: "Product, data collected, how used, third-party sharing" },
      { key: "market", label: "適用地區 / 法規", labelEn: "Applicable Region / Law", type: "text", required: true, placeholder: "例：台灣個資法、GDPR、CCPA", placeholderEn: "e.g. Taiwan PDPA, GDPR, CCPA" },
      { key: "type", label: "產品類型（選填）", labelEn: "Product Type (optional)", type: "text", required: false, placeholder: "例：App、SaaS、電商、含兒童資料", placeholderEn: "e.g. app, SaaS, e-commerce, handles children's data" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位隱私合規顧問,撰寫合規且用戶友善的隱私政策。",
      "⚠️ 以下為參考草稿,正式採用前請諮詢律師。",
      "", `產品：${v.product}`, `地區/法規：${v.market}`,
      v.type ? `產品類型：${v.type}` : "",
      "", "### 1. 資料蒐集清單",
      "盤點蒐集的資料類型 / 蒐集目的 / 法律依據 / 保存期限,用表格呈現",
      "", "### 2. 法規合規框架",
      "依適用法規的關鍵要求對照 + 必備條款清單 + 同意機制建議",
      "", "### 3. 用戶友善隱私政策草稿",
      "完整隱私政策草稿(白話、分章節:蒐集什麼/為何/如何使用/共享/用戶權利/安全/聯絡)",
      "", "### 4. 實施建議",
      "Cookie 同意 / 資料主體權利回應流程 / 政策更新通知機制。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a privacy compliance advisor writing compliant, user-friendly privacy policies.",
      "⚠️ Reference draft only — consult an attorney before adoption.",
      "", `Product: ${v.product}`, `Region/law: ${v.market}`,
      v.type ? `Product type: ${v.type}` : "",
      "", "### 1. Data Collection Inventory — data types collected / purpose / legal basis / retention, table",
      "### 2. Compliance Framework — key requirements per applicable law + required clauses checklist + consent mechanism",
      "### 3. User-Friendly Privacy Policy Draft — complete draft (plain language, sectioned: what collected/why/how used/sharing/user rights/security/contact)",
      "### 4. Implementation — cookie consent / data subject rights process / policy update notification. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 254. 保密協議生成器 ──────────────────────────────────────────────────
  ndaGenerator: {
    inputs: [
      { key: "context", label: "合作情境", labelEn: "Collaboration Context", type: "textarea", required: true, placeholder: "保密目的、雙方關係、要保護的資訊類型", placeholderEn: "Purpose, party relationship, types of info to protect" },
      { key: "parties", label: "締約雙方", labelEn: "Parties", type: "text", required: true, placeholder: "甲方 / 乙方(含類型)", placeholderEn: "Disclosing / Receiving party (with type)" },
      { key: "type", label: "保密類型（選填）", labelEn: "NDA Type (optional)", type: "text", required: false, placeholder: "單向 / 雙向 / 多方", placeholderEn: "Unilateral / mutual / multilateral" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位商業合約顧問,起草清晰、平衡的保密協議。",
      "⚠️ 此為參考草稿,正式簽署前請諮詢律師。",
      "", `合作情境：${v.context}`, `締約方：${v.parties}`,
      v.type ? `類型：${v.type}` : "",
      "", "### 1. 保密範圍設計",
      "機密資訊定義 / 排除條款 / 保密義務範圍 / 期限建議",
      "", "### 2. 核心保密條款",
      "保密義務 / 使用限制 / 返還或銷毀 / 不招攬條款(若需要)的具體文字",
      "", "### 3. 違約風險條款",
      "違約救濟 / 損害賠償 / 禁制令 / 爭議解決,各附說明",
      "", "### 4. 完整 NDA 草稿 + 簽署指引",
      "輸出可參考的完整保密協議草稿 + 簽署注意事項。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a commercial contracts advisor drafting clear, balanced NDAs.",
      "⚠️ Reference draft only — consult an attorney before signing.",
      "", `Context: ${v.context}`, `Parties: ${v.parties}`,
      v.type ? `Type: ${v.type}` : "",
      "", "### 1. Confidentiality Scope — definition of confidential info / exclusions / obligation scope / term",
      "### 2. Core Clauses — confidentiality obligations / use restrictions / return or destruction / non-solicitation (if needed) with specific language",
      "### 3. Breach Risk Terms — remedies / damages / injunction / dispute resolution, with notes",
      "### 4. Complete NDA Draft + Signing Guide — full reference NDA + signing notes. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 263. 勞動合約起草師 ──────────────────────────────────────────────────
  employmentContract: {
    inputs: [
      { key: "role", label: "職位 / 僱用情境", labelEn: "Role / Employment Context", type: "textarea", required: true, placeholder: "職位、僱用類型(全職/兼職/約聘)、薪資結構、特殊條款需求", placeholderEn: "Role, employment type (FT/PT/contract), compensation, special terms" },
      { key: "company", label: "公司 / 地區", labelEn: "Company / Jurisdiction", type: "text", required: true, placeholder: "公司類型、所在地(影響法規)", placeholderEn: "Company type, location (affects regulations)" },
      { key: "concern", label: "特別保護需求（選填）", labelEn: "Special Protection Needs (optional)", type: "text", required: false, placeholder: "例：競業禁止、保密、智財歸屬", placeholderEn: "e.g. non-compete, confidentiality, IP assignment" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位勞動法律顧問,起草合規且平衡的勞動合約。",
      "⚠️ 此為參考草稿,正式採用前請諮詢勞動法律師。",
      "", `職位/情境：${v.role}`, `公司/地區：${v.company}`,
      v.concern ? `特別需求：${v.concern}` : "",
      "", "### 1. 合約條款設計",
      "核心條款架構(職務/工時/薪資/福利/期限/終止)+ 各條款要點",
      "", "### 2. 法規合規確認",
      "依當地勞動法的合規檢查(工時/加班/特休/資遣)+ 常見違法地雷",
      "", "### 3. 保護條款建議",
      v.concern ? `針對 ${v.concern} 的條款設計 + 可執行性提醒` : "競業禁止 / 保密 / 智財歸屬條款建議 + 可執行性提醒",
      "", "### 4. 完整合約草稿",
      "輸出可參考的完整勞動合約草稿(含各條款編號)。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a labor law advisor drafting compliant, balanced employment contracts.",
      "⚠️ Reference draft only — consult a labor attorney before adoption.",
      "", `Role/context: ${v.role}`, `Company/jurisdiction: ${v.company}`,
      v.concern ? `Special needs: ${v.concern}` : "",
      "", "### 1. Contract Clause Design — core structure (duties/hours/compensation/benefits/term/termination) + key points",
      "### 2. Compliance Check — per local labor law (hours/overtime/leave/severance) + common violation pitfalls",
      v.concern ? `### 3. Protective Clauses — clauses for ${v.concern} + enforceability notes` : "### 3. Protective Clauses — non-compete / confidentiality / IP assignment + enforceability notes",
      "### 4. Complete Contract Draft — full reference employment contract (numbered clauses). Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 281. IP 組合策略顧問 ─────────────────────────────────────────────────
  ipPortfolio: {
    inputs: [
      { key: "innovation", label: "創新 / 資產描述", labelEn: "Innovation / Asset Description", type: "textarea", required: true, placeholder: "核心技術、品牌資產、創作、現有 IP", placeholderEn: "Core technology, brand assets, creations, existing IP" },
      { key: "business", label: "業務 / 市場", labelEn: "Business / Market", type: "text", required: true, placeholder: "行業、市場、競爭、商業化方向", placeholderEn: "Industry, market, competition, commercialization direction" },
      { key: "region", label: "目標地區（選填）", labelEn: "Target Regions (optional)", type: "text", required: false, placeholder: "例：台灣、美國、中國、歐盟", placeholderEn: "e.g. Taiwan, US, China, EU" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位 IP 組合策略顧問,協助企業以 IP 建立競爭壁壘與收益。",
      "⚠️ 正式法律意見請諮詢專利商標律師。",
      "", `創新/資產：${v.innovation}`, `業務/市場：${v.business}`,
      v.region ? `地區：${v.region}` : "",
      "", "### 1. 專利地圖分析",
      "可申請的專利方向 / 競爭者專利態勢推估 / 專利布局策略(核心+外圍)",
      "", "### 2. 商標保護策略",
      "應保護的商標項目 / 類別與地區建議 / 防搶註與監控",
      "", "### 3. IP 組合規劃",
      "整體 IP 組合配置(專利/商標/著作權/營業秘密)+ 優先序與成本,用表格呈現",
      "", "### 4. 授權收益規劃",
      "IP 變現模式(授權/交叉授權/訴訟/標準必要)+ 估算潛在收益 + 維權機制。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are an IP portfolio strategy advisor helping companies build moats and revenue with IP.",
      "⚠️ Consult a patent/trademark attorney for formal legal advice.",
      "", `Innovation/asset: ${v.innovation}`, `Business/market: ${v.business}`,
      v.region ? `Regions: ${v.region}` : "",
      "", "### 1. Patent Landscape — patentable directions / estimated competitor patent posture / patent strategy (core + peripheral)",
      "### 2. Trademark Protection — marks to protect / classes and regions / anti-squatting and monitoring",
      "### 3. IP Portfolio Planning — overall portfolio allocation (patent/trademark/copyright/trade secret) + priority and cost, table",
      "### 4. Licensing Revenue — monetization models (licensing/cross-licensing/litigation/SEP) + estimated revenue + enforcement. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 291. 服務條款生成師 ──────────────────────────────────────────────────
  termsOfService: {
    inputs: [
      { key: "product", label: "產品描述", labelEn: "Product Description", type: "textarea", required: true, placeholder: "產品類型、服務內容、收費模式、用戶類型", placeholderEn: "Product type, service content, pricing model, user types" },
      { key: "market", label: "適用地區 / 法規", labelEn: "Applicable Region / Law", type: "text", required: true, placeholder: "例：台灣、美國;消保法、電子簽章", placeholderEn: "e.g. Taiwan, US; consumer protection, e-signature" },
      { key: "concern", label: "特別考量（選填）", labelEn: "Special Considerations (optional)", type: "text", required: false, placeholder: "例：訂閱自動續約、UGC、退款", placeholderEn: "e.g. auto-renewal, UGC, refunds" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位法務顧問,起草清晰、合規且保護雙方的服務條款。",
      "⚠️ 此為參考草稿,正式採用前請諮詢律師。",
      "", `產品：${v.product}`, `地區/法規：${v.market}`,
      v.concern ? `特別考量：${v.concern}` : "",
      "", "### 1. 條款架構",
      "服務條款應包含的章節清單 + 各章節功能 + 此產品的特殊條款需求",
      "", "### 2. 法規合規確認",
      "依適用法規的關鍵要求(消保/電子契約/自動續約揭露)+ 必備條款",
      "", "### 3. 用戶保護條款",
      "責任限制 / 免責聲明 / 終止與退款 / 爭議解決 / 修改通知,各附說明",
      "", "### 4. 完整服務條款草稿",
      "輸出可參考的完整 ToS 草稿(白話、分章節)。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a legal advisor drafting clear, compliant, mutually protective terms of service.",
      "⚠️ Reference draft only — consult an attorney before adoption.",
      "", `Product: ${v.product}`, `Region/law: ${v.market}`,
      v.concern ? `Special considerations: ${v.concern}` : "",
      "", "### 1. Terms Structure — section list + function of each + special clause needs for this product",
      "### 2. Compliance Check — key requirements per applicable law (consumer protection/e-contracts/auto-renewal disclosure) + required clauses",
      "### 3. User Protection Clauses — limitation of liability / disclaimers / termination & refunds / dispute resolution / change notification, with notes",
      "### 4. Complete ToS Draft — full reference ToS (plain language, sectioned). Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 301. 個資法合規顧問 ──────────────────────────────────────────────────
  gdprCompliance: {
    inputs: [
      { key: "process", label: "資料處理流程", labelEn: "Data Processing Flow", type: "textarea", required: true, placeholder: "蒐集哪些個資、如何處理、儲存、共享、保存期限", placeholderEn: "What personal data collected, how processed, stored, shared, retention" },
      { key: "market", label: "適用法規", labelEn: "Applicable Law", type: "text", required: true, placeholder: "例：台灣個資法、GDPR、CCPA", placeholderEn: "e.g. Taiwan PDPA, GDPR, CCPA" },
      { key: "current", label: "現有措施（選填）", labelEn: "Current Measures (optional)", type: "text", required: false, placeholder: "已採取的個資保護措施", placeholderEn: "Existing data protection measures" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位個資法合規顧問,協助企業合規處理個人資料。",
      "⚠️ 正式法律意見請諮詢律師。",
      "", `資料處理流程：${v.process}`, `適用法規：${v.market}`,
      v.current ? `現有措施：${v.current}` : "",
      "", "### 1. 資料處理流程審查",
      "盤點資料生命週期(蒐集→處理→儲存→共享→刪除)+ 各環節的法律依據與風險,用 ```mermaid flowchart 呈現",
      "", "### 2. 合規缺口分析",
      "依適用法規逐項對照(告知同意/目的限定/資料安全/當事人權利)+ 現況評級(✅/⚠️/❌)",
      "輸出 ```chart 長條圖顯示各合規領域缺口程度。",
      "", "### 3. 修補行動計畫",
      "緊急/短期/中期的修補行動,每項附負責角色與優先序",
      "", "### 4. 持續合規機制",
      "同意管理 / 當事人權利回應流程 / 資料外洩通報 / 定期稽核。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a data privacy compliance advisor helping companies process personal data lawfully.",
      "⚠️ Consult an attorney for formal legal advice.",
      "", `Data processing flow: ${v.process}`, `Applicable law: ${v.market}`,
      v.current ? `Current measures: ${v.current}` : "",
      "", "### 1. Data Processing Review — data lifecycle (collect→process→store→share→delete) + legal basis and risk per stage, ```mermaid flowchart",
      "### 2. Compliance Gap Analysis — item-by-item per applicable law (notice & consent/purpose limitation/data security/subject rights) + status (✅/⚠️/❌). ```chart bar chart of gaps by area.",
      "### 3. Remediation Action Plan — urgent/short/medium-term actions with owner and priority",
      "### 4. Ongoing Compliance — consent management / subject rights process / breach notification / periodic audit. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 311. 職場政策設計師 ──────────────────────────────────────────────────
  workplacePolicyAdvisor: {
    inputs: [
      { key: "company", label: "公司描述 + 需求", labelEn: "Company Description + Needs", type: "textarea", required: true, placeholder: "公司規模、行業、所在地、需要的政策領域", placeholderEn: "Company size, industry, location, policy areas needed" },
      { key: "focus", label: "重點政策", labelEn: "Focus Policies", type: "text", required: true, placeholder: "例：出勤、遠距、行為準則、申訴、騷擾防治", placeholderEn: "e.g. attendance, remote, conduct, grievance, harassment prevention" },
      { key: "culture", label: "公司文化（選填）", labelEn: "Company Culture (optional)", type: "text", required: false, placeholder: "希望政策反映的文化", placeholderEn: "Culture the policies should reflect" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位職場政策顧問,建立合規、清晰、符合文化的職場政策。",
      "⚠️ 正式採用前請確認符合當地勞動法規。",
      "", `公司+需求：${v.company}`, `重點政策：${v.focus}`,
      v.culture ? `文化：${v.culture}` : "",
      "", "### 1. 政策架構",
      "建議的職場政策清單與分類 + 各政策的目的 + 優先建立順序",
      "", "### 2. 員工手冊框架",
      "員工手冊應含章節 + 各章節摘要 + 撰寫原則(清楚、可執行)",
      "", "### 3. 重點政策草稿",
      "針對重點領域撰寫可參考的政策條文草稿",
      "", "### 4. 法規合規確認",
      "各政策的法規對照 + 常見違法地雷 + 落地溝通建議。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a workplace policy advisor building compliant, clear, culture-aligned workplace policies.",
      "⚠️ Verify local labor law compliance before adoption.",
      "", `Company+needs: ${v.company}`, `Focus policies: ${v.focus}`,
      v.culture ? `Culture: ${v.culture}` : "",
      "", "### 1. Policy Architecture — recommended policy list and categories + purpose of each + priority order",
      "### 2. Employee Handbook Framework — sections + summaries + writing principles (clear, actionable)",
      "### 3. Focus Policy Drafts — reference policy text for focus areas",
      "### 4. Compliance Check — legal mapping per policy + common pitfalls + rollout communication. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 321. 智慧財產稽核師 ──────────────────────────────────────────────────
  intellectualPropertyAudit: {
    inputs: [
      { key: "company", label: "公司 / 資產描述", labelEn: "Company / Asset Description", type: "textarea", required: true, placeholder: "公司、行業、現有 IP(專利/商標/著作權/營業秘密)", placeholderEn: "Company, industry, existing IP (patents/trademarks/copyrights/trade secrets)" },
      { key: "purpose", label: "稽核目的", labelEn: "Audit Purpose", type: "text", required: true, placeholder: "例：融資盡調、IP 盤點、侵權風險、併購", placeholderEn: "e.g. fundraising DD, IP inventory, infringement risk, M&A" },
      { key: "concern", label: "特定顧慮（選填）", labelEn: "Specific Concern (optional)", type: "text", required: false, placeholder: "已知的 IP 問題或風險", placeholderEn: "Known IP issues or risks" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位智慧財產稽核顧問,協助企業盤點 IP 並識別風險。",
      "⚠️ 正式法律意見請諮詢專利商標律師。",
      "", `公司/資產：${v.company}`, `稽核目的：${v.purpose}`,
      v.concern ? `特定顧慮：${v.concern}` : "",
      "", "### 1. IP 資產盤點",
      "盤點各類 IP(專利/商標/著作權/營業秘密/網域)+ 權利狀態 + 價值評估,用表格呈現",
      "", "### 2. 侵權風險識別",
      "我方侵權他人風險 / 他人侵權我方風險 / 權利瑕疵(未登記/到期/歸屬不清)",
      "輸出 ```chart 長條圖顯示各 IP 類別的風險程度。",
      "", "### 3. 保護缺口",
      "應保護但未保護的資產 + 各缺口的風險與建議行動",
      "", "### 4. 保護計畫",
      "IP 保護優先行動 + 維護機制 + 監控與維權建議。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are an IP audit consultant helping companies inventory IP and identify risks.",
      "⚠️ Consult a patent/trademark attorney for formal legal advice.",
      "", `Company/assets: ${v.company}`, `Audit purpose: ${v.purpose}`,
      v.concern ? `Specific concern: ${v.concern}` : "",
      "", "### 1. IP Asset Inventory — inventory by type (patents/trademarks/copyrights/trade secrets/domains) + rights status + value, table",
      "### 2. Infringement Risk — risk of us infringing others / others infringing us / rights defects (unregistered/expired/unclear ownership). ```chart bar chart of risk per IP category.",
      "### 3. Protection Gaps — assets that should be protected but aren't + risk and recommended action per gap",
      "### 4. Protection Plan — priority IP protection actions + maintenance mechanism + monitoring and enforcement. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 330. 合約生命週期管理師 ──────────────────────────────────────────────
  contractLifecycleManager: {
    inputs: [
      { key: "current", label: "合約現況診斷", labelEn: "Contract Status", type: "textarea", required: true, placeholder: "合約類型、數量、現有管理方式、痛點", placeholderEn: "Contract types, volume, current management, pain points" },
      { key: "goal", label: "目標", labelEn: "Goal", type: "text", required: true, placeholder: "例：避免漏續約、加快審批、降低風險", placeholderEn: "e.g. avoid missed renewals, faster approval, reduce risk" },
      { key: "scale", label: "規模 / 團隊（選填）", labelEn: "Scale / Team (optional)", type: "text", required: false, placeholder: "合約量、法務/採購團隊規模", placeholderEn: "Contract volume, legal/procurement team size" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位合約生命週期管理(CLM)顧問,建立完整的合約管理體系。",
      "", `合約現況：${v.current}`, `目標：${v.goal}`,
      v.scale ? `規模/團隊：${v.scale}` : "",
      "", "### 1. 現況診斷",
      "合約管理各階段(起草/審批/簽署/履行/續約/歸檔)的問題盤點 + 風險點",
      "", "### 2. 生命週期流程設計",
      "用 ```mermaid flowchart 呈現完整合約生命週期 + 各階段的關鍵控制點",
      "", "### 3. 管理體系",
      "範本庫 / 審批流程 / 條款庫 / 風險條款檢核 / 期限提醒機制",
      "", "### 4. 治理與工具",
      "合約 KPI(週期/風險/續約率)+ CLM 工具建議 + 導入路線圖。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a Contract Lifecycle Management (CLM) consultant building a complete contract management system.",
      "", `Contract status: ${v.current}`, `Goal: ${v.goal}`,
      v.scale ? `Scale/team: ${v.scale}` : "",
      "", "### 1. Status Diagnostic — problems and risk points across stages (drafting/approval/signing/performance/renewal/archiving)",
      "### 2. Lifecycle Process Design — ```mermaid flowchart of full contract lifecycle + key control points per stage",
      "### 3. Management System — template library / approval workflow / clause library / risk clause checklist / deadline reminders",
      "### 4. Governance & Tools — contract KPIs (cycle/risk/renewal rate) + CLM tool recommendations + adoption roadmap. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 339. 加盟合約顧問 ────────────────────────────────────────────────────
  franchiseAgreementAdvisor: {
    inputs: [
      { key: "model", label: "加盟模式描述", labelEn: "Franchise Model Description", type: "textarea", required: true, placeholder: "加盟業態、加盟金/權利金結構、加盟商支援、地區", placeholderEn: "Franchise type, fee/royalty structure, franchisee support, region" },
      { key: "role", label: "你的角色", labelEn: "Your Role", type: "text", required: true, placeholder: "加盟總部 / 加盟商(影響保護角度)", placeholderEn: "Franchisor / franchisee (affects protection angle)" },
      { key: "concern", label: "重點顧慮（選填）", labelEn: "Key Concerns (optional)", type: "text", required: false, placeholder: "例：品牌控管、終止、競業、糾紛", placeholderEn: "e.g. brand control, termination, non-compete, disputes" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位加盟合約顧問,協助設計平衡且合規的加盟合約。",
      "⚠️ 此為參考分析,正式簽署前請諮詢律師。",
      "", `加盟模式：${v.model}`, `角色：${v.role}`,
      v.concern ? `重點顧慮：${v.concern}` : "",
      "", "### 1. 合約條款設計",
      "核心條款架構(授權範圍/費用/期限/區域/支援/品牌標準)+ 各條款要點",
      "", "### 2. 加盟商保護機制",
      "依角色,平衡雙方利益的條款建議(總部控管 vs 加盟商保障)",
      "", "### 3. 風險條款",
      "終止與續約 / 競業禁止 / 違約處理 / 糾紛解決 + 各條款的可執行性提醒",
      "", "### 4. 法規合規確認",
      "加盟相關法規對照(揭露義務/公平交易)+ 必備揭露事項 + 常見地雷。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a franchise agreement advisor helping design balanced, compliant franchise agreements.",
      "⚠️ Reference analysis only — consult an attorney before signing.",
      "", `Franchise model: ${v.model}`, `Role: ${v.role}`,
      v.concern ? `Key concerns: ${v.concern}` : "",
      "", "### 1. Agreement Clause Design — core structure (license scope/fees/term/territory/support/brand standards) + key points",
      "### 2. Franchisee Protection — balanced clauses per role (franchisor control vs franchisee protection)",
      "### 3. Risk Clauses — termination & renewal / non-compete / breach handling / dispute resolution + enforceability notes",
      "### 4. Compliance Check — franchise regulation mapping (disclosure obligations/fair trade) + required disclosures + common pitfalls. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 349. 勞資爭議顧問 ────────────────────────────────────────────────────
  laborDisputeAdvisor: {
    inputs: [
      { key: "dispute", label: "爭議描述", labelEn: "Dispute Description", type: "textarea", required: true, placeholder: "爭議內容、雙方立場、發生經過、目前狀態", placeholderEn: "Dispute content, both positions, what happened, current status" },
      { key: "role", label: "你的角色", labelEn: "Your Role", type: "text", required: true, placeholder: "雇主 / 員工 / HR / 管理者", placeholderEn: "Employer / employee / HR / manager" },
      { key: "goal", label: "期望結果（選填）", labelEn: "Desired Outcome (optional)", type: "text", required: false, placeholder: "希望如何解決", placeholderEn: "How you hope to resolve it" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位勞資爭議顧問,協助以合規且務實的方式化解爭議。",
      "⚠️ 此為參考分析,正式法律意見請諮詢勞動法律師。",
      "", `爭議：${v.dispute}`, `角色：${v.role}`,
      v.goal ? `期望結果：${v.goal}` : "",
      "", "### 1. 爭議評估",
      "爭議性質與類型 / 各方立場與利益 / 法律風險評估 / 升級可能性",
      "", "### 2. 法規分析",
      "適用的勞動法規 / 各方的法律權利義務 / 我方的有利與不利點",
      "", "### 3. 調解策略",
      "建議的解決途徑(內部協商/調解/仲裁/訴訟)比較 + 調解話術 + 可接受方案",
      "", "### 4. 解決路線圖",
      "解決步驟與時程 + 風險控管 + 預防類似爭議的制度建議。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a labor dispute advisor helping resolve disputes compliantly and pragmatically.",
      "⚠️ Reference analysis only — consult a labor attorney for formal legal advice.",
      "", `Dispute: ${v.dispute}`, `Role: ${v.role}`,
      v.goal ? `Desired outcome: ${v.goal}` : "",
      "", "### 1. Dispute Assessment — nature and type / each party's position and interests / legal risk / escalation likelihood",
      "### 2. Legal Analysis — applicable labor laws / rights and obligations of each party / our favorable and unfavorable points",
      "### 3. Mediation Strategy — resolution paths (internal negotiation/mediation/arbitration/litigation) comparison + mediation scripts + acceptable options",
      "### 4. Resolution Roadmap — steps and timeline + risk control + systemic recommendations to prevent similar disputes. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  regulatoryStrategy: {
    inputs: [
      field("industry", ["行業描述", "Industry Description"], { required: true, placeholder: ["行業、業務、所在地、監管環境", "Industry, business, location, regulatory environment"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：進入受監管市場、應對新法規", "e.g. enter regulated market, respond to new regulation"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位監管策略顧問,協助企業在受監管環境中佔據有利位置。",
        "⚠️ 正式法律意見請諮詢律師。",
        "", `行業：${v.industry}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 監管環境分析",
        "適用的主要監管 + 趨勢方向 + 對業務的影響",
        "", "### 2. 合規路線圖",
        "達成合規的階段化路線 + 優先事項,用 ```mermaid gantt 呈現",
        "", "### 3. 監管關係策略",
        "與監管機關建立關係的策略 + 主動參與規則制定的機會",
        "", "### 4. 風險與機會",
        "監管風險 + 合規可轉化的競爭優勢。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a regulatory strategy advisor helping companies position well in regulated environments.",
        "⚠️ Consult an attorney for formal legal advice.",
        "", `Industry: ${v.industry}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Regulatory Landscape — key applicable regulations + trend direction + business impact",
        "### 2. Compliance Roadmap — phased path to compliance + priorities, ```mermaid gantt",
        "### 3. Regulator Relationship Strategy — strategy to build relationships + opportunities to shape rule-making",
        "### 4. Risks & Opportunities — regulatory risks + compliance-as-competitive-advantage. Respond in English.",
      ],
    }),
  },
  ipLicensingAdvisor: {
    inputs: [
      field("ip", ["智財描述", "IP Description"], { required: true, placeholder: ["要授權的專利/商標/技術/內容", "Patent/trademark/tech/content to license"] }),
      field("goal", ["授權目標", "Licensing Goal"], { type: "text", required: true, placeholder: ["例：收益最大化、擴大採用、策略合作", "e.g. maximize revenue, expand adoption, strategic partnership"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位智財授權策略顧問。",
        "⚠️ 正式法律意見請諮詢律師。",
        "", `智財：${v.ip}`, `授權目標：${v.goal}`,
        "", "### 1. 授權模式設計",
        "適用授權模式(獨家/非獨家/地區/領域)比較 + 推薦",
        "", "### 2. 費率結構",
        "費率模式(權利金/一次金/里程碑/分潤)+ 行情區間建議",
        "輸出 ```chart 長條圖比較不同費率模式的預估收益。",
        "", "### 3. 協議條款建議",
        "關鍵條款(範圍/期限/品質控管/終止/稽核)的要點",
        "", "### 4. 授權策略",
        "授權對象篩選 + 談判要點 + 風險控管。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are an IP licensing strategy advisor.",
        "⚠️ Consult an attorney for formal legal advice.",
        "", `IP: ${v.ip}`, `Licensing goal: ${v.goal}`,
        "", "### 1. Licensing Model — model comparison (exclusive/non-exclusive/territory/field) + recommendation",
        "### 2. Royalty Structure — fee model (royalty/lump-sum/milestone/rev-share) + market range. ```chart bar chart of estimated revenue per model.",
        "### 3. Agreement Clauses — key clauses (scope/term/quality control/termination/audit)",
        "### 4. Licensing Strategy — licensee selection + negotiation points + risk control. Respond in English.",
      ],
    }),
  },
  employeeHandbookBuilder: {
    inputs: [
      field("company", ["公司政策輸入", "Company Policies Input"], { required: true, placeholder: ["公司、規模、所在地、現有政策、文化", "Company, size, location, existing policies, culture"] }),
      field("focus", ["重點章節（選填）", "Focus Sections (optional)"], { type: "text", placeholder: ["例：出勤、行為、福利、申訴", "e.g. attendance, conduct, benefits, grievance"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位 HR 政策顧問,撰寫合規且清晰的員工手冊。",
        "⚠️ 正式採用前請確認符合當地勞動法規。",
        "", `公司政策：${v.company}`,
        v.focus && `重點章節：${v.focus}`,
        "", "### 1. 手冊架構",
        "員工手冊應含章節清單 + 各章節摘要 + 優先順序",
        "", "### 2. 行為準則",
        "核心行為準則(職場行為/利益衝突/保密/騷擾防治)草稿要點",
        "", "### 3. 重點章節草稿",
        "針對重點章節撰寫可參考的條文",
        "", "### 4. 法規合規確認",
        "各章節的法規對照 + 必備法定事項 + 落地建議。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are an HR policy advisor writing a compliant, clear employee handbook.",
        "⚠️ Verify local labor law compliance before adoption.",
        "", `Company policies: ${v.company}`,
        v.focus && `Focus sections: ${v.focus}`,
        "", "### 1. Handbook Architecture — section list + summaries + priority",
        "### 2. Code of Conduct — draft points for core conduct (workplace behavior/conflict of interest/confidentiality/harassment prevention)",
        "### 3. Focus Section Drafts — reference text for focus sections",
        "### 4. Compliance Check — legal mapping per section + required statutory items + rollout. Respond in English.",
      ],
    }),
  },
  termsNegotiator: {
    inputs: [
      field("contract", ["合約描述", "Contract Description"], { required: true, placeholder: ["合約類型、主要條款、爭議點", "Contract type, main terms, disputed points"] }),
      field("role", ["你的角色", "Your Role"], { type: "text", required: true, placeholder: ["甲方/乙方;最在意什麼", "Party A/B; top priority"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位合約條款談判顧問。",
        "⚠️ 正式法律意見請諮詢律師。",
        "", `合約：${v.contract}`, `角色：${v.role}`,
        "", "### 1. 不利條款識別",
        "從你的角色找出 TOP 5 不利條款 + 風險等級(🔴🟡🟢)",
        "", "### 2. 談判優先序",
        "依風險與可談性排列談判優先序,用表格呈現",
        "", "### 3. 反建議條款",
        "針對不利條款的反建議文字 + 雙方可接受的折中",
        "", "### 4. 談判策略",
        "讓步計畫 + 不可退讓底線 + 談判話術。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a contract terms negotiation advisor.",
        "⚠️ Consult an attorney for formal legal advice.",
        "", `Contract: ${v.contract}`, `Role: ${v.role}`,
        "", "### 1. Unfavorable Clause Identification — top 5 unfavorable clauses from your role + risk level (🔴🟡🟢)",
        "### 2. Negotiation Priority — ranked by risk and negotiability, table",
        "### 3. Counter-Clauses — counter-proposal language for unfavorable clauses + mutually acceptable middle ground",
        "### 4. Negotiation Strategy — concession plan + non-negotiable limits + scripts. Respond in English.",
      ],
    }),
  },
  ipRegistrationAdvisor: {
    inputs: [
      field("innovation", ["創新描述", "Innovation Description"], { required: true, placeholder: ["發明/品牌/設計、業務背景", "Invention/brand/design, business context"] }),
      field("region", ["目標地區（選填）", "Target Regions (optional)"], { type: "text", placeholder: ["例：台灣、美國、中國、歐盟", "e.g. Taiwan, US, China, EU"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位智財申請策略顧問。",
        "⚠️ 正式法律意見請諮詢專利商標律師。",
        "", `創新：${v.innovation}`,
        v.region && `目標地區：${v.region}`,
        "", "### 1. 可申請性分析",
        "適合的保護類型(專利/商標/設計/著作權)+ 可申請性評估",
        "", "### 2. 申請策略設計",
        "申請範圍與佈局(核心+外圍)+ 時程 + 成本估算",
        "", "### 3. 國際保護優先",
        "依市場重要性排列申請地區優先序 + PCT/馬德里等途徑建議",
        "", "### 4. 行動清單",
        "申請前準備 + 常見駁回原因預防 + 維權準備。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are an IP registration strategy advisor.",
        "⚠️ Consult a patent/trademark attorney for formal legal advice.",
        "", `Innovation: ${v.innovation}`,
        v.region && `Target regions: ${v.region}`,
        "", "### 1. Patentability/Registrability — suitable protection type (patent/trademark/design/copyright) + assessment",
        "### 2. Application Strategy — scope and portfolio (core + peripheral) + timeline + cost estimate",
        "### 3. International Priority — application region priority by market importance + PCT/Madrid route recommendations",
        "### 4. Action Checklist — pre-filing prep + common rejection prevention + enforcement readiness. Respond in English.",
      ],
    }),
  },
  freelanceContract: {
    inputs: [
      field("project", ["案件描述", "Project Description"], { required: true, placeholder: ["接案內容、報酬、交付、雙方", "Work scope, fee, deliverables, parties"] }),
      field("role", ["你的角色", "Your Role"], { type: "text", required: true, placeholder: ["接案方 / 發案方", "Freelancer / client"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位自由接案合約顧問。",
        "⚠️ 此為參考草稿,正式簽署前請諮詢律師。",
        "", `案件：${v.project}`, `角色：${v.role}`,
        "", "### 1. 合約條款起草",
        "核心條款(範圍/報酬/時程/驗收/智財/修改次數)的要點",
        "", "### 2. 付款保護機制",
        "付款里程碑 / 訂金 / 逾期條款 / 範圍蔓延防護(依角色)",
        "", "### 3. 爭議解決條款",
        "終止條款 / 爭議解決 / 責任限制",
        "", "### 4. 完整合約草稿",
        "可參考的完整接案合約草稿。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a freelance contract advisor.",
        "⚠️ Reference draft only — consult an attorney before signing.",
        "", `Project: ${v.project}`, `Role: ${v.role}`,
        "", "### 1. Contract Clauses — core clauses (scope/fee/timeline/acceptance/IP/revision limits)",
        "### 2. Payment Protection — payment milestones / deposit / late terms / scope creep protection (by role)",
        "### 3. Dispute Resolution Clauses — termination / dispute resolution / limitation of liability",
        "### 4. Complete Contract Draft — full reference freelance contract. Respond in English.",
      ],
    }),
  },
  mergerLegalAdvisor: {
    inputs: [
      field("deal", ["交易描述", "Deal Description"], { required: true, placeholder: ["併購對象、規模、結構、行業", "Target, size, structure, industry"] }),
      field("role", ["你的角色（選填）", "Your Role (optional)"], { type: "text", placeholder: ["收購方 / 被收購方", "Acquirer / target"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位併購法務盡職調查顧問。",
        "⚠️ 此為參考分析,正式決策前請諮詢律師。",
        "", `交易：${v.deal}`,
        v.role && `角色：${v.role}`,
        "", "### 1. 法律盡調清單",
        "法律 DD 檢查清單(公司/合約/智財/訴訟/勞動/合規),用表格附查核重點",
        "", "### 2. 風險條款識別",
        "交易中的高風險法律事項(或有負債/重大合約/變更控制條款)",
        "輸出 ```chart 長條圖顯示各法律領域風險。",
        "", "### 3. 合約保護建議",
        "SPA 關鍵條款建議(陳述保證/賠償/價金調整/交割條件)",
        "", "### 4. 決策摘要",
        "法律風險總評 + 該談判的保護 + 後續步驟。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a merger legal due diligence advisor.",
        "⚠️ Reference analysis only — consult an attorney before decisions.",
        "", `Deal: ${v.deal}`,
        v.role && `Role: ${v.role}`,
        "", "### 1. Legal DD Checklist — legal due diligence checklist (corporate/contracts/IP/litigation/labor/compliance), table with focus points",
        "### 2. Risk Clause Identification — high-risk legal items (contingent liabilities/material contracts/change-of-control clauses). ```chart bar chart of risk per legal area.",
        "### 3. Contract Protection — key SPA clauses (representations & warranties/indemnification/price adjustment/closing conditions)",
        "### 4. Decision Summary — overall legal risk + protections to negotiate + next steps. Respond in English.",
      ],
    }),
  },
  shareholderAgreement: {
    inputs: [
      field("structure", ["公司結構描述", "Company Structure Description"], { required: true, placeholder: ["股東組成、持股、董事會、現有協議", "Shareholders, holdings, board, existing agreement"] }),
      field("concern", ["重點顧慮（選填）", "Key Concerns (optional)"], { type: "text", placeholder: ["例：控制權、退出、僵局、稀釋", "e.g. control, exit, deadlock, dilution"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位股東協議起草顧問。",
        "⚠️ 此為參考草稿,正式簽署前請諮詢律師。",
        "", `公司結構：${v.structure}`,
        v.concern && `重點顧慮：${v.concern}`,
        "", "### 1. 股東條款設計",
        "核心條款(股權/表決/分紅/資訊權/轉讓限制)的要點",
        "", "### 2. 控制權條款",
        "董事席位 / 否決權 / 重大事項決議門檻 / 反稀釋",
        "", "### 3. 退出與僵局",
        "優先購買/共同出售/拖帶權 + 僵局解決機制 + 退出條款",
        "", "### 4. 協議草稿要點",
        "完整股東協議的章節架構與關鍵條文要點。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a shareholder agreement advisor.",
        "⚠️ Reference draft only — consult an attorney before signing.",
        "", `Company structure: ${v.structure}`,
        v.concern && `Key concerns: ${v.concern}`,
        "", "### 1. Shareholder Clauses — core clauses (equity/voting/dividends/information rights/transfer restrictions)",
        "### 2. Control Provisions — board seats / veto rights / supermajority thresholds / anti-dilution",
        "### 3. Exit & Deadlock — ROFR/tag-along/drag-along + deadlock resolution + exit clauses",
        "### 4. Agreement Draft — section architecture and key clause points of a full shareholder agreement. Respond in English.",
      ],
    }),
  },
  trademarkSearchAdvisor: {
    inputs: [
      field("mark", ["商標描述", "Trademark Description"], { required: true, placeholder: ["商標名稱/圖樣、行業、使用範圍", "Mark name/design, industry, usage scope"] }),
      field("region", ["目標地區（選填）", "Target Regions (optional)"], { type: "text", placeholder: ["例：台灣、美國、歐盟", "e.g. Taiwan, US, EU"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位商標搜索與保護顧問。",
        "⚠️ 此為參考分析,正式申請前請諮詢商標律師。",
        "", `商標：${v.mark}`,
        v.region && `目標地區：${v.region}`,
        "", "### 1. 近似性分析",
        "潛在近似商標風險評估 + 識別性強弱 + 申請類別建議",
        "", "### 2. 申請策略設計",
        "申請類別與範圍 + 地區優先序 + 時程與成本估算",
        "", "### 3. 品牌保護建議",
        "防搶註 / 監控 / 網域與社群帳號保護 / 使用證據保存",
        "", "### 4. 行動清單",
        "申請前準備 + 常見駁回預防。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a trademark search and protection advisor.",
        "⚠️ Reference analysis only — consult a trademark attorney before filing.",
        "", `Trademark: ${v.mark}`,
        v.region && `Target regions: ${v.region}`,
        "", "### 1. Similarity Analysis — potential confusingly-similar mark risk + distinctiveness + class recommendations",
        "### 2. Application Strategy — classes and scope + region priority + timeline and cost estimate",
        "### 3. Brand Protection — anti-squatting / monitoring / domain and social handle protection / use evidence retention",
        "### 4. Action Checklist — pre-filing prep + common rejection prevention. Respond in English.",
      ],
    }),
  },
  employmentAgreementAdvisor: {
    inputs: [
      field("role", ["職位 / 僱用情境", "Role / Employment Context"], { required: true, placeholder: ["職位、僱用類型、薪酬、特殊需求", "Role, employment type, compensation, special needs"] }),
      field("jurisdiction", ["公司 / 地區", "Company / Jurisdiction"], { type: "text", required: true, placeholder: ["公司型態、所在地", "Entity type, location"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位勞動協議設計顧問,保護雇主權益並合規。",
        "⚠️ 此為參考草稿,正式採用前請諮詢勞動法律師。",
        "", `職位/情境：${v.role}`, `公司/地區：${v.jurisdiction}`,
        "", "### 1. 合約條款審查",
        "核心條款(職務/工時/薪酬/福利/期限/終止)要點 + 雇主保護重點",
        "", "### 2. 保護條款",
        "競業禁止 / 保密 / 智財歸屬 / 招攬禁止 + 可執行性提醒",
        "", "### 3. 法規合規",
        "依當地勞動法的合規檢查 + 常見違法地雷",
        "", "### 4. 完整協議草稿",
        "可參考的完整勞動協議草稿。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are an employment agreement advisor protecting employer interests while staying compliant.",
        "⚠️ Reference draft only — consult a labor attorney before adoption.",
        "", `Role/context: ${v.role}`, `Company/jurisdiction: ${v.jurisdiction}`,
        "", "### 1. Clause Review — core clauses (duties/hours/compensation/benefits/term/termination) + employer protection focus",
        "### 2. Protective Clauses — non-compete / confidentiality / IP assignment / non-solicitation + enforceability notes",
        "### 3. Compliance — compliance check per local labor law + common violation pitfalls",
        "### 4. Complete Agreement Draft — full reference employment agreement. Respond in English.",
      ],
    }),
  },
  mergerComplianceAdvisor: {
    inputs: [
      field("deal", ["交易描述", "Deal Description"], { required: true, placeholder: ["併購對象、規模、市佔、行業、地區", "Target, size, market share, industry, region"] }),
      field("concern", ["關注（選填）", "Concern (optional)"], { type: "text", placeholder: ["例：反壟斷、產業特許、外資", "e.g. antitrust, sector licensing, foreign investment"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位併購合規審查顧問。",
        "⚠️ 此為參考分析,正式申報前請諮詢律師。",
        "", `交易：${v.deal}`,
        v.concern && `關注：${v.concern}`,
        "", "### 1. 交易合規掃描",
        "適用的合規領域(反壟斷/產業特許/外資/勞動)+ 風險評級",
        "輸出 ```chart 長條圖顯示各合規領域風險。",
        "", "### 2. 監管申報策略",
        "需申報的主管機關 + 時程 + 申報重點",
        "", "### 3. 反壟斷風險評估",
        "市場集中度分析 + 反壟斷風險 + 可能的補救措施(剝離/承諾)",
        "", "### 4. 合規行動計畫",
        "交割前合規步驟 + 風險緩解。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a merger compliance advisor.",
        "⚠️ Reference analysis only — consult an attorney before filing.",
        "", `Deal: ${v.deal}`,
        v.concern && `Concern: ${v.concern}`,
        "", "### 1. Transaction Compliance Scan — applicable areas (antitrust/sector licensing/foreign investment/labor) + risk rating. ```chart bar chart.",
        "### 2. Regulatory Filing Strategy — authorities to file with + timeline + filing focus",
        "### 3. Antitrust Risk Assessment — market concentration analysis + antitrust risk + possible remedies (divestiture/commitments)",
        "### 4. Compliance Action Plan — pre-closing compliance steps + risk mitigation. Respond in English.",
      ],
    }),
  },
  jointVentureAdvisor: {
    inputs: [
      field("structure", ["合作結構描述", "Partnership Structure Description"], { required: true, placeholder: ["合資雙方、出資、目的、控制權", "JV parties, contributions, purpose, control"] }),
      field("concern", ["重點顧慮（選填）", "Key Concerns (optional)"], { type: "text", placeholder: ["例：治理、僵局、退出、IP", "e.g. governance, deadlock, exit, IP"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位合資企業設計顧問。",
        "⚠️ 此為參考草稿,正式簽署前請諮詢律師。",
        "", `合作結構：${v.structure}`,
        v.concern && `重點顧慮：${v.concern}`,
        "", "### 1. 合資協議條款",
        "核心條款(出資/股權/治理/利潤/IP)的要點",
        "", "### 2. 治理機制",
        "董事會 / 決策權 / 重大事項門檻 / 僵局解決",
        "", "### 3. 退出機制",
        "退出選項(賣出/買斷/清算)+ 估值方法 + 競業限制",
        "", "### 4. 協議草稿要點",
        "完整合資協議的章節架構與關鍵條文。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a joint venture agreement advisor.",
        "⚠️ Reference draft only — consult an attorney before signing.",
        "", `Partnership structure: ${v.structure}`,
        v.concern && `Key concerns: ${v.concern}`,
        "", "### 1. JV Agreement Clauses — core clauses (contributions/equity/governance/profit/IP)",
        "### 2. Governance Mechanism — board / decision rights / supermajority thresholds / deadlock resolution",
        "### 3. Exit Mechanism — exit options (sell/buyout/liquidation) + valuation method + non-compete",
        "### 4. Agreement Draft — section architecture and key clauses of a full JV agreement. Respond in English.",
      ],
    }),
  },
  ipProtectionAdvisor: {
    inputs: [
      field("assets", ["商業資產描述", "Business Asset Description"], { required: true, placeholder: ["核心技術、品牌、創作、營業秘密", "Core tech, brand, creations, trade secrets"] }),
      field("region", ["目標地區（選填）", "Target Regions (optional)"], { type: "text", placeholder: ["例：台灣、美國、中國、歐盟", "e.g. Taiwan, US, China, EU"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位智慧財產保護顧問。",
        "⚠️ 此為參考分析,正式申請前請諮詢律師。",
        "", `商業資產：${v.assets}`,
        v.region && `目標地區：${v.region}`,
        "", "### 1. IP 資產盤點",
        "可保護的 IP 類型(專利/商標/著作權/營業秘密)+ 優先度",
        "", "### 2. 申請策略",
        "專利商標申請策略 + 範圍與佈局 + 地區優先序",
        "", "### 3. IP 組合保護",
        "整體 IP 組合保護計畫 + 營業秘密管理 + 成本",
        "", "### 4. 維權與監控",
        "侵權監控 + 維權準備 + 行動清單。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are an intellectual property protection advisor.",
        "⚠️ Reference analysis only — consult an attorney before filing.",
        "", `Business assets: ${v.assets}`,
        v.region && `Target regions: ${v.region}`,
        "", "### 1. IP Asset Inventory — protectable IP types (patent/trademark/copyright/trade secret) + priority",
        "### 2. Application Strategy — patent and trademark strategy + scope and portfolio + region priority",
        "### 3. IP Portfolio Protection — overall portfolio protection plan + trade secret management + cost",
        "### 4. Enforcement & Monitoring — infringement monitoring + enforcement readiness + action checklist. Respond in English.",
      ],
    }),
  },
  dataRetentionAdvisor: {
    inputs: [
      field("data", ["資料類別描述", "Data Category Description"], { required: true, placeholder: ["資料類型、用途、適用法規、現有政策", "Data types, purposes, applicable law, current policy"] }),
      field("market", ["適用法規（選填）", "Applicable Law (optional)"], { type: "text", placeholder: ["例：個資法、GDPR", "e.g. PDPA, GDPR"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位資料保留政策顧問。",
        "⚠️ 此為參考分析,正式採用前請諮詢律師。",
        "", `資料類別：${v.data}`,
        v.market && `適用法規：${v.market}`,
        "", "### 1. 合規保留期限",
        "各資料類別的合規保留期限設計(法定/業務需求),用表格呈現",
        "", "### 2. 刪除流程",
        "資料刪除/去識別化流程,用 ```mermaid flowchart 呈現",
        "", "### 3. 稽核機制",
        "保留政策的稽核與合規確認 + 例外處理",
        "", "### 4. 政策落地",
        "資料保留政策草稿要點 + 落地與系統建議。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a data retention policy advisor.",
        "⚠️ Reference analysis only — consult an attorney before adoption.",
        "", `Data categories: ${v.data}`,
        v.market && `Applicable law: ${v.market}`,
        "", "### 1. Compliant Retention Schedule — compliant retention period per data category (statutory/business need), table",
        "### 2. Deletion Workflow — data deletion/de-identification workflow, ```mermaid flowchart",
        "### 3. Audit Mechanism — retention policy audit and compliance confirmation + exception handling",
        "### 4. Policy Implementation — data retention policy draft points + rollout and system recommendations. Respond in English.",
      ],
    }),
  },
  privacyImpactAssessment: {
    inputs: [
      field("activity", ["資料處理活動", "Data Processing Activity"], { required: true, placeholder: ["處理活動、資料類型、目的、對象、技術", "Processing activity, data types, purpose, subjects, technology"] }),
      field("market", ["適用法規（選填）", "Applicable Law (optional)"], { type: "text", placeholder: ["例：GDPR、個資法", "e.g. GDPR, PDPA"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位隱私影響評估(DPIA)顧問。",
        "⚠️ 此為參考分析,正式評估請諮詢律師/DPO。",
        "", `資料處理活動：${v.activity}`,
        v.market && `適用法規：${v.market}`,
        "", "### 1. DPIA 評估",
        "處理活動的隱私風險評估(必要性/比例性/對當事人風險)",
        "輸出 ```chart 長條圖顯示各風險項評級。",
        "", "### 2. 風險識別",
        "主要隱私風險 + 對資料當事人的影響",
        "", "### 3. 緩解行動計畫",
        "各風險的緩解措施(技術/組織)+ 殘餘風險評估",
        "", "### 4. 合規確認",
        "合規檢查清單 + 是否需諮詢主管機關 + 文件化。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a Privacy Impact Assessment (DPIA) advisor.",
        "⚠️ Reference analysis only — consult an attorney/DPO for formal assessment.",
        "", `Data processing activity: ${v.activity}`,
        v.market && `Applicable law: ${v.market}`,
        "", "### 1. DPIA Assessment — privacy risk assessment of the activity (necessity/proportionality/risk to subjects). ```chart bar chart of risk ratings.",
        "### 2. Risk Identification — main privacy risks + impact on data subjects",
        "### 3. Mitigation Action Plan — mitigation per risk (technical/organizational) + residual risk assessment",
        "### 4. Compliance Confirmation — compliance checklist + whether to consult the authority + documentation. Respond in English.",
      ],
    }),
  },
  complianceCalendar: {
    inputs: [
      field("business", ["業務 / 法規描述", "Business / Regulatory Description"], { required: true, placeholder: ["公司、行業、適用法規、申報義務", "Company, industry, applicable regulations, filing obligations"] }),
      field("region", ["地區（選填）", "Region (optional)"], { type: "text", placeholder: ["例：台灣、多地", "e.g. Taiwan, multi-region"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位合規行事曆規劃顧問。",
        "⚠️ 此為參考,實際申報期限請以主管機關公告為準。",
        "", `業務/法規：${v.business}`,
        v.region && `地區：${v.region}`,
        "", "### 1. 申報期限整合",
        "適用的法規申報義務與期限,用表格:項目/主管機關/頻率/期限",
        "", "### 2. 自動提醒機制",
        "提前提醒設計(前置天數)+ 負責角色 + 升級機制",
        "", "### 3. 合規節奏",
        "用 ```mermaid gantt 呈現年度合規行事曆",
        "", "### 4. 治理建議",
        "合規負責人 + 文件留存 + 法規更新追蹤。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a compliance calendar planning advisor.",
        "⚠️ Reference only — verify actual deadlines with the authorities.",
        "", `Business/regulatory: ${v.business}`,
        v.region && `Region: ${v.region}`,
        "", "### 1. Filing Deadline Integration — applicable filing obligations and deadlines, table: item/authority/frequency/deadline",
        "### 2. Automated Reminder Mechanism — advance reminders (lead days) + responsible role + escalation",
        "### 3. Compliance Rhythm — ```mermaid gantt of annual compliance calendar",
        "### 4. Governance — compliance owner + document retention + regulation update tracking. Respond in English.",
      ],
    }),
  },
  softwareLicensing: {
    inputs: [
      field("context", ["軟體 / 使用情境", "Software / Usage Context"], { required: true, placeholder: ["使用的開源/商業軟體、商業模式、分發方式", "Open source/commercial software used, business model, distribution"] }),
      field("concern", ["關注（選填）", "Concern (optional)"], { type: "text", placeholder: ["例：GPL 污染、商用合規、再分發", "e.g. GPL contamination, commercial compliance, redistribution"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位軟體授權策略顧問。",
        "⚠️ 此為參考分析,正式合規請諮詢律師。",
        "", `軟體/使用情境：${v.context}`,
        v.concern && `關注：${v.concern}`,
        "", "### 1. 授權選型分析",
        "開源 vs 商業授權的適配 + 常見授權類型(MIT/Apache/GPL/商用)比較",
        "", "### 2. 合規使用風險",
        "使用風險評估(著佐權/再分發義務/專利條款)+ 高風險項目",
        "輸出 ```chart 長條圖顯示各授權的合規風險。",
        "", "### 3. 授權管理策略",
        "授權盤點 + SBOM + 合規檢查流程",
        "", "### 4. 行動建議",
        "降低授權風險的行動 + 政策建立。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a software licensing strategy advisor.",
        "⚠️ Reference analysis only — consult an attorney for compliance.",
        "", `Software/usage: ${v.context}`,
        v.concern && `Concern: ${v.concern}`,
        "", "### 1. License Selection Analysis — open source vs commercial fit + common license types (MIT/Apache/GPL/commercial) comparison",
        "### 2. Compliance Risk — usage risk assessment (copyleft/redistribution obligations/patent clauses) + high-risk items. ```chart bar chart of compliance risk per license.",
        "### 3. License Management Strategy — license inventory + SBOM + compliance check process",
        "### 4. Recommendations — actions to reduce licensing risk + policy establishment. Respond in English.",
      ],
    }),
  },
  vendorContractReviewer: {
    inputs: [
      field("contract", ["供應商合約描述", "Vendor Contract Description"], { required: true, placeholder: ["合約類型、供應商、主要條款、金額", "Contract type, vendor, main terms, value"] }),
      field("concern", ["關注（選填）", "Concern (optional)"], { type: "text", placeholder: ["例：SLA、責任、終止、漲價", "e.g. SLA, liability, termination, price increase"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位供應商合約審查顧問。",
        "⚠️ 此為參考分析,正式簽署前請諮詢律師。",
        "", `供應商合約：${v.contract}`,
        v.concern && `關注：${v.concern}`,
        "", "### 1. 風險條款識別",
        "從買方視角找出 TOP 5 風險條款 + 風險等級(🔴🟡🟢)",
        "", "### 2. 談判要點",
        "各風險條款的談判優先序 + 換取條件",
        "", "### 3. 保護性修改建議",
        "建議的條款修改文字(SLA/責任限制/終止/漲價上限)",
        "", "### 4. 審查清單",
        "簽約前確認清單 + 必爭條款。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a vendor contract review advisor.",
        "⚠️ Reference analysis only — consult an attorney before signing.",
        "", `Vendor contract: ${v.contract}`,
        v.concern && `Concern: ${v.concern}`,
        "", "### 1. Risk Clause Identification — top 5 risky clauses from the buyer's view + risk level (🔴🟡🟢)",
        "### 2. Negotiation Points — negotiation priority per risk clause + trade-offs",
        "### 3. Protective Amendments — suggested clause language (SLA/liability limits/termination/price cap)",
        "### 4. Review Checklist — pre-signing confirmation + must-win clauses. Respond in English.",
      ],
    }),
  },
  antiCorruptionAdvisor: {
    inputs: [
      field("business", ["企業描述", "Business Description"], { required: true, placeholder: ["公司、行業、營運地區、現有政策", "Company, industry, regions, current policies"] }),
      field("concern", ["關注（選填）", "Concern (optional)"], { type: "text", placeholder: ["例：第三方、禮品、海外、招標", "e.g. third parties, gifts, overseas, bidding"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位反腐敗合規顧問。",
        "⚠️ 此為參考分析,正式合規請諮詢律師。",
        "", `企業：${v.business}`,
        v.concern && `關注：${v.concern}`,
        "", "### 1. 廉潔風險評估",
        "依營運場景評估貪腐風險(第三方/禮品招待/海外/招標),用表格附風險等級",
        "輸出 ```chart 長條圖顯示各風險領域。",
        "", "### 2. 反貪腐政策設計",
        "政策架構(禁止行為/禮品標準/第三方盡調/利益衝突)要點",
        "", "### 3. 舉報機制",
        "舉報管道設計 + 保護機制 + 調查流程",
        "", "### 4. 落地與培訓",
        "政策推行 + 員工培訓 + 監控稽核。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are an anti-corruption compliance advisor.",
        "⚠️ Reference analysis only — consult an attorney for compliance.",
        "", `Business: ${v.business}`,
        v.concern && `Concern: ${v.concern}`,
        "", "### 1. Integrity Risk Assessment — assess corruption risk by scenario (third parties/gifts & hospitality/overseas/bidding), table with risk level. ```chart bar chart of risk areas.",
        "### 2. Anti-Corruption Policy Design — policy architecture (prohibited conduct/gift standards/third-party DD/conflict of interest)",
        "### 3. Whistleblower Mechanism — reporting channels + protection + investigation process",
        "### 4. Rollout & Training — policy rollout + employee training + monitoring and audit. Respond in English.",
      ],
    }),
  },
  vendorAgreementDrafter: {
    inputs: [
      field("context", ["供應商 / 服務描述", "Vendor / Service Description"], { required: true, placeholder: ["供應商類型、服務內容、規模、特殊需求", "Vendor type, service scope, scale, special needs"] }),
      field("priority", ["重點（選填）", "Priority (optional)"], { type: "text", placeholder: ["例：SLA、罰則、保密、退場", "e.g. SLA, penalties, confidentiality, exit"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位供應商協議起草顧問。",
        "⚠️ 此為參考草稿,正式簽署前請諮詢律師。",
        "", `供應商/服務：${v.context}`,
        v.priority && `重點：${v.priority}`,
        "", "### 1. 協議條款起草",
        "核心條款(範圍/價格/付款/期限/終止)的要點",
        "", "### 2. 服務等級協議(SLA)",
        "SLA 指標設計 + 罰則 + 服務不達標處理",
        "", "### 3. 違約保護機制",
        "違約救濟 / 責任限制 / 保密 / 退場條款",
        "", "### 4. 完整協議草稿",
        "可參考的完整供應商協議草稿。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a vendor agreement drafter.",
        "⚠️ Reference draft only — consult an attorney before signing.",
        "", `Vendor/service: ${v.context}`,
        v.priority && `Priority: ${v.priority}`,
        "", "### 1. Agreement Clause Drafting — core clauses (scope/price/payment/term/termination)",
        "### 2. Service Level Agreement (SLA) — SLA metric design + penalties + service shortfall handling",
        "### 3. Breach Protection — remedies / liability limits / confidentiality / exit clauses",
        "### 4. Complete Agreement Draft — full reference vendor agreement. Respond in English.",
      ],
    }),
  },
  commercialLeaseAdvisor: {
    inputs: [
      field("lease", ["租約情境描述", "Lease Situation Description"], { required: true, placeholder: ["物件類型、面積、租期、租金、條款重點", "Property type, area, term, rent, key terms"] }),
      field("concern", ["關注（選填）", "Concern (optional)"], { type: "text", placeholder: ["例：續約、提前解約、修繕責任", "e.g. renewal, early termination, repair liability"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位商業租賃顧問。",
        "⚠️ 此為一般性說明,簽約前請諮詢律師。",
        "", `租約情境：${v.lease}`,
        v.concern && `關注：${v.concern}`,
        "", "### 1. 關鍵條款檢視",
        "租期/租金調整/押金/修繕/轉租/解約等關鍵條款的重點與風險,用表格呈現",
        "", "### 2. 風險與陷阱",
        "對承租方不利的條款 + 容易忽略的隱藏成本",
        "", "### 3. 談判要點",
        "可爭取的條件 + 談判策略 + 替代方案",
        "", "### 4. 行動清單",
        "簽約前確認清單 + 該諮詢律師的事項。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a commercial lease advisor.",
        "⚠️ General explanation only — consult a lawyer before signing.",
        "", `Lease situation: ${v.lease}`,
        v.concern && `Concern: ${v.concern}`,
        "", "### 1. Key Term Review — focus and risks of key terms (term/rent escalation/deposit/repairs/sublease/termination), table",
        "### 2. Risks & Pitfalls — unfavorable clauses for the tenant + hidden costs easily overlooked",
        "### 3. Negotiation Points — terms to push for + negotiation strategy + alternatives",
        "### 4. Action Checklist — pre-signing checklist + items to consult a lawyer. Respond in English.",
      ],
    }),
  },
  workplaceIncidentAdvisor: {
    inputs: [
      field("incident", ["事件描述", "Incident Description"], { required: true, placeholder: ["事件類型、發生經過、涉及人員、現場處置", "Incident type, what happened, people involved, on-site response"] }),
      field("context", ["背景（選填）", "Context (optional)"], { type: "text", placeholder: ["行業、規模、地區", "Industry, size, region"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位職場事件處理顧問。",
        "⚠️ 此為一般性流程建議,具體個案請諮詢律師與專業人員。",
        "", `事件描述：${v.incident}`,
        v.context && `背景：${v.context}`,
        "", "### 1. 即時處置",
        "事件當下的優先處置(安全/醫療/保全現場/通報)",
        "", "### 2. 調查與記錄",
        "調查步驟 + 該記錄的事證 + 訪談原則,用 ```mermaid flowchart 呈現處理流程",
        "", "### 3. 合規與通報",
        "法定通報義務 + 時限 + 文件保存",
        "", "### 4. 後續與預防",
        "後續處置 + 預防措施 + 政策更新。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a workplace incident handling advisor.",
        "⚠️ General process guidance — consult a lawyer and professionals for specific cases.",
        "", `Incident: ${v.incident}`,
        v.context && `Context: ${v.context}`,
        "", "### 1. Immediate Response — priority actions (safety/medical/preserve scene/notification)",
        "### 2. Investigation & Documentation — investigation steps + evidence to record + interview principles, ```mermaid flowchart of handling process",
        "### 3. Compliance & Reporting — statutory reporting duties + deadlines + document retention",
        "### 4. Follow-up & Prevention — follow-up + preventive measures + policy update. Respond in English.",
      ],
    }),
  },
  partnershipAgreementDrafter: {
    inputs: [
      field("partnership", ["合夥情境描述", "Partnership Description"], { required: true, placeholder: ["合夥人、出資、分工、利潤分配、退出機制需求", "Partners, capital, roles, profit split, exit needs"] }),
      field("concern", ["關注（選填）", "Concern (optional)"], { type: "text", placeholder: ["例：股權、決策權、退出", "e.g. equity, decision rights, exit"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位合夥協議起草顧問。",
        "⚠️ 此為一般性框架,正式協議請由律師審閱。",
        "", `合夥情境：${v.partnership}`,
        v.concern && `關注：${v.concern}`,
        "", "### 1. 核心條款框架",
        "出資/股權/分工/利潤分配/決策機制等核心條款建議,用表格呈現",
        "", "### 2. 風險防範條款",
        "僵局打破/退出機制/競業/保密/違約處理",
        "", "### 3. 情境條款",
        "新增/退出合夥人、爭議解決、解散清算的處理",
        "", "### 4. 檢視清單",
        "起草檢查清單 + 該由律師確認的重點。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a partnership agreement drafting advisor.",
        "⚠️ General framework only — have a lawyer review the formal agreement.",
        "", `Partnership: ${v.partnership}`,
        v.concern && `Concern: ${v.concern}`,
        "", "### 1. Core Term Framework — core terms (capital/equity/roles/profit split/decision-making), table",
        "### 2. Risk Protection Clauses — deadlock-breaking/exit mechanism/non-compete/confidentiality/breach handling",
        "### 3. Scenario Clauses — adding/exiting partners, dispute resolution, dissolution/liquidation",
        "### 4. Review Checklist — drafting checklist + key points for lawyer confirmation. Respond in English.",
      ],
    }),
  },
  breachResponseAdvisor: {
    inputs: [
      field("breach", ["資安事件描述", "Breach Description"], { required: true, placeholder: ["事件類型、影響範圍、資料類型、發現時間", "Breach type, scope, data types, discovery time"] }),
      field("context", ["背景（選填）", "Context (optional)"], { type: "text", placeholder: ["行業、地區、適用法規", "Industry, region, applicable regulations"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位資料外洩應變顧問。",
        "⚠️ 此為一般性應變框架,法定義務請諮詢律師。",
        "", `資安事件：${v.breach}`,
        v.context && `背景：${v.context}`,
        "", "### 1. 即時控制",
        "止血與遏制步驟(隔離/保全/評估範圍),用 ```mermaid flowchart 呈現應變流程",
        "", "### 2. 評估與通報",
        "影響評估 + 法定通報義務(GDPR/個資法)+ 時限(如 72 小時)",
        "", "### 3. 溝通計畫",
        "對受影響者/監管/內部的溝通 + 訊息要點",
        "", "### 4. 復原與強化",
        "復原步驟 + 根因修復 + 後續強化。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a data breach response advisor.",
        "⚠️ General response framework — consult a lawyer for legal obligations.",
        "", `Breach: ${v.breach}`,
        v.context && `Context: ${v.context}`,
        "", "### 1. Immediate Containment — stop-the-bleed steps (isolate/preserve/assess scope), ```mermaid flowchart of response process",
        "### 2. Assessment & Notification — impact assessment + statutory notification duties (GDPR/privacy law) + deadlines (e.g. 72 hours)",
        "### 3. Communication Plan — communication to affected parties/regulators/internal + key messages",
        "### 4. Recovery & Hardening — recovery steps + root-cause fix + post-incident hardening. Respond in English.",
      ],
    }),
  },
  contractTemplateBuilder: {
    inputs: [
      field("contract", ["合約需求描述", "Contract Need Description"], { required: true, placeholder: ["合約類型、雙方、標的、關鍵條件", "Contract type, parties, subject, key conditions"] }),
      field("context", ["背景（選填）", "Context (optional)"], { type: "text", placeholder: ["行業、地區、常見情境", "Industry, region, common scenarios"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位合約範本建構顧問。",
        "⚠️ 此為一般性範本框架,正式使用前請由律師審閱。",
        "", `合約需求：${v.contract}`,
        v.context && `背景：${v.context}`,
        "", "### 1. 條款架構",
        "此合約類型應包含的條款清單(必要/建議/選用),用表格呈現",
        "", "### 2. 關鍵條款重點",
        "標的/價金/履約/責任/終止等關鍵條款的撰寫要點",
        "", "### 3. 風險防範",
        "保護己方的條款 + 常見爭議的預防",
        "", "### 4. 客製化指引",
        "可變欄位 + 不同情境的調整 + 該諮詢律師處。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a contract template builder.",
        "⚠️ General template framework — have a lawyer review before formal use.",
        "", `Contract need: ${v.contract}`,
        v.context && `Context: ${v.context}`,
        "", "### 1. Clause Structure — clause list this contract type should include (required/recommended/optional), table",
        "### 2. Key Clause Drafting Points — drafting focus for subject/price/performance/liability/termination",
        "### 3. Risk Protection — clauses protecting your side + prevention of common disputes",
        "### 4. Customization Guide — variable fields + adjustments per scenario + items to consult a lawyer. Respond in English.",
      ],
    }),
  },
  termsUpdateAdvisor: {
    inputs: [
      field("terms", ["現有條款描述", "Current Terms Description"], { required: true, placeholder: ["服務類型、現有條款重點、上次更新時間", "Service type, current terms focus, last update date"] }),
      field("trigger", ["更新誘因（選填）", "Update Trigger (optional)"], { type: "text", placeholder: ["例：新功能、法規變動、業務調整", "e.g. new feature, regulatory change, business change"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位服務條款更新顧問。",
        "⚠️ 此為一般性建議,正式條款請由律師審閱。",
        "", `現有條款：${v.terms}`,
        v.trigger && `更新誘因：${v.trigger}`,
        "", "### 1. 條款審查",
        "依適用性/合規/清晰度/風險審查現有條款,用表格呈現需更新項目",
        "", "### 2. 法規對應",
        "相關法規變動(個資/消保/平台規範)的對應更新重點",
        "", "### 3. 用戶友善溝通",
        "重大變更的通知策略 + 生效緩衝 + 易讀摘要",
        "", "### 4. 執行清單",
        "更新流程 + 版本控管 + 同意取得。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a terms of service update advisor.",
        "⚠️ General guidance only — have a lawyer review formal terms.",
        "", `Current terms: ${v.terms}`,
        v.trigger && `Update trigger: ${v.trigger}`,
        "", "### 1. Terms Review — review by applicability/compliance/clarity/risk, table of items to update",
        "### 2. Regulatory Alignment — update focus for relevant regulatory changes (privacy/consumer/platform rules)",
        "### 3. User-Friendly Communication — notification strategy for material changes + effective-date buffer + plain-language summary",
        "### 4. Execution Checklist — update process + version control + consent capture. Respond in English.",
      ],
    }),
  },
  corporateGovernanceAdvisor: {
    inputs: [
      field("org", ["組織描述", "Organization Description"], { required: true, placeholder: ["組織型態、規模、股東結構、現有治理", "Entity type, size, ownership, current governance"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：募資準備、合規、董事會建置", "e.g. fundraising prep, compliance, board setup"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位企業治理框架顧問。",
        "⚠️ 此為一般性建議,法定義務請諮詢律師/會計師。",
        "", `組織描述：${v.org}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 治理結構設計",
        "董事會/監察/委員會的結構與職責,用 ```mermaid flowchart 呈現治理架構",
        "", "### 2. 董事會職責規範",
        "董事會職權 / 決策矩陣 / 利益衝突迴避",
        "", "### 3. 合規監控機制",
        "合規清單 + 揭露義務 + 內控重點",
        "", "### 4. 落地路線圖",
        "治理建置優先序 + 文件清單。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a corporate governance framework advisor.",
        "⚠️ General guidance only — consult a lawyer/accountant for statutory duties.",
        "", `Organization: ${v.org}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Governance Structure — board/supervisory/committee structure and responsibilities, ```mermaid flowchart of governance architecture",
        "### 2. Board Responsibility Standards — board authority / decision matrix / conflict-of-interest avoidance",
        "### 3. Compliance Monitoring — compliance checklist + disclosure duties + internal control focus",
        "### 4. Implementation Roadmap — governance setup priorities + document list. Respond in English.",
      ],
    }),
  },
  mspAgreementBuilder: {
    inputs: [
      field("service", ["托管服務描述", "Managed Service Description"], { required: true, placeholder: ["服務範圍、客戶、SLA 需求、計費模式", "Service scope, client, SLA needs, billing model"] }),
      field("concern", ["關注（選填）", "Concern (optional)"], { type: "text", placeholder: ["例：責任上限、停機賠償、資料", "e.g. liability cap, downtime credits, data"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位托管服務協議建構顧問。",
        "⚠️ 此為一般性框架,正式合約請由律師審閱。",
        "", `托管服務：${v.service}`,
        v.concern && `關注：${v.concern}`,
        "", "### 1. 服務範圍定義",
        "服務內容/範圍邊界/排除項目,用表格呈現",
        "", "### 2. SLA 設計",
        "可用性/回應/解決時間的 SLA + 賠償(service credit)機制",
        "", "### 3. 責任與風險條款",
        "責任上限 / 資料保護 / 終止 / 轉換協助",
        "", "### 4. 檢視清單",
        "簽約前確認 + 該由律師確認處。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a managed service agreement builder.",
        "⚠️ General framework only — have a lawyer review the formal contract.",
        "", `Managed service: ${v.service}`,
        v.concern && `Concern: ${v.concern}`,
        "", "### 1. Service Scope Definition — service content/scope boundaries/exclusions, table",
        "### 2. SLA Design — availability/response/resolution SLAs + service credit mechanism",
        "### 3. Liability & Risk Clauses — liability cap / data protection / termination / transition assistance",
        "### 4. Review Checklist — pre-signing confirmation + items for lawyer review. Respond in English.",
      ],
    }),
  },
  ipRiskAssessmentAdvisor: {
    inputs: [
      field("ip", ["IP 資產描述", "IP Asset Description"], { required: true, placeholder: ["產品、技術、品牌、現有 IP、行業", "Product, technology, brand, existing IP, industry"] }),
      field("concern", ["關注（選填）", "Concern (optional)"], { type: "text", placeholder: ["例：侵權風險、保護、自由實施", "e.g. infringement risk, protection, freedom to operate"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位智財風險評估顧問。",
        "⚠️ 此為一般性分析,正式 IP 事務請諮詢專利/商標律師。",
        "", `IP 資產：${v.ip}`,
        v.concern && `關注：${v.concern}`,
        "", "### 1. IP 資產盤點",
        "專利/商標/著作/營業秘密的盤點與保護狀態,用表格呈現",
        "", "### 2. 侵權風險識別",
        "可能的侵權風險(自身侵權他人/被侵權)+ 風險等級",
        "輸出 ```chart 長條圖顯示各 IP 面向的風險評分。",
        "", "### 3. IP 策略組合",
        "保護優先序 + 申請/維護/防禦策略",
        "", "### 4. 行動建議",
        "優先行動 + 該諮詢律師處。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are an IP risk assessment advisor.",
        "⚠️ General analysis only — consult a patent/trademark attorney for formal IP matters.",
        "", `IP assets: ${v.ip}`,
        v.concern && `Concern: ${v.concern}`,
        "", "### 1. IP Asset Inventory — inventory of patents/trademarks/copyrights/trade secrets and protection status, table",
        "### 2. Infringement Risk Identification — possible infringement risks (you infringing others/being infringed) + risk level. ```chart bar chart of risk scores per IP dimension.",
        "### 3. IP Strategy Portfolio — protection priority + filing/maintenance/defense strategy",
        "### 4. Recommendations — priority actions + items to consult an attorney. Respond in English.",
      ],
    }),
  },
  employmentTermination: {
    inputs: [
      field("situation", ["終止情境描述", "Termination Situation Description"], { required: true, placeholder: ["終止原因、職位、年資、地區", "Reason, role, tenure, region"] }),
      field("concern", ["關注（選填）", "Concern (optional)"], { type: "text", placeholder: ["例：資遣費、合規、爭議風險", "e.g. severance, compliance, dispute risk"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位離職/終止勞動關係顧問。",
        "⚠️ 此為一般性流程建議,具體個案請諮詢勞動法律師。",
        "", `終止情境：${v.situation}`,
        v.concern && `關注：${v.concern}`,
        "", "### 1. 終止流程設計",
        "合規的終止步驟,用 ```mermaid flowchart 呈現流程",
        "", "### 2. 法規合規確認",
        "預告期 / 資遣費 / 通報義務 / 文件要點",
        "", "### 3. 爭議風險防範",
        "易引發爭議之處 + 證據保存 + 溝通原則",
        "", "### 4. 執行清單",
        "離職面談 + 交接 + 權限回收 + 文件清單。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are an employment termination advisor.",
        "⚠️ General process guidance — consult an employment lawyer for specific cases.",
        "", `Termination situation: ${v.situation}`,
        v.concern && `Concern: ${v.concern}`,
        "", "### 1. Termination Process — compliant termination steps, ```mermaid flowchart of process",
        "### 2. Compliance Confirmation — notice period / severance / reporting duties / documentation",
        "### 3. Dispute Risk Prevention — dispute-prone areas + evidence retention + communication principles",
        "### 4. Execution Checklist — exit interview + handover + access revocation + document list. Respond in English.",
      ],
    }),
  },
};
