import type { AgentOverride } from "../types";
import { bilingual, field } from "./helpers";

/** operations category agent overrides. See ./index.ts for how these merge. */
export const OPERATIONS_OVERRIDES: Record<string, AgentOverride> = {
  // ── 209. SOP 生成器 ──────────────────────────────────────────────────────
  sopgenerator: {
    inputs: [
      { key: "process", label: "業務流程描述", labelEn: "Business Process Description", type: "textarea", required: true, placeholder: "要文件化的流程：目的、步驟、參與者、頻率", placeholderEn: "Process to document: purpose, steps, participants, frequency" },
      { key: "audience", label: "執行者 / 受眾", labelEn: "Performers / Audience", type: "text", required: true, placeholder: "誰會執行這個 SOP？經驗程度？", placeholderEn: "Who will perform this SOP? Experience level?" },
      { key: "risk", label: "風險 / 合規考量（選填）", labelEn: "Risk / Compliance (optional)", type: "text", required: false, placeholder: "例：涉及金流、個資、安全", placeholderEn: "e.g. involves payments, personal data, safety" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位流程文件化專家，撰寫清晰、可執行、防呆的標準作業程序（SOP）。",
      "", `流程：${v.process}`, `執行者：${v.audience}`,
      v.risk ? `風險/合規：${v.risk}` : "",
      "", "### 1. 流程概覽",
      "目的 / 適用範圍 / 觸發條件 / 負責角色 / 預估時間",
      "用 ```mermaid flowchart TD 呈現流程步驟。",
      "", "### 2. 步驟分解",
      "編號步驟清單，每步：動作 / 負責人 / 工具/系統 / 預期產出 / 注意事項",
      "", "### 3. 風險控管",
      "關鍵控制點 / 常見錯誤與防呆 / 例外處理流程",
      "", "### 4. KPI 設計",
      "衡量此流程的 3-4 個指標 + 目標值",
      "", "### 5. 正式 SOP 文件",
      "輸出可直接使用的完整 SOP（含版本/編號/標題/各章節）。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a process documentation expert writing clear, executable, foolproof Standard Operating Procedures.",
      "", `Process: ${v.process}`, `Performers: ${v.audience}`,
      v.risk ? `Risk/compliance: ${v.risk}` : "",
      "", "### 1. Process Overview — purpose / scope / trigger / responsible roles / estimated time. ```mermaid flowchart TD of steps.",
      "### 2. Step Decomposition — numbered steps: action / owner / tools / expected output / notes",
      "### 3. Risk Control — key control points / common errors & safeguards / exception handling",
      "### 4. KPI Design — 3–4 metrics + targets",
      "### 5. Formal SOP Document — complete ready-to-use SOP (version/number/title/sections). Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 216. 採購談判指揮官 ──────────────────────────────────────────────────
  procurementnegotiation: {
    inputs: [
      { key: "context", label: "採購情境", labelEn: "Procurement Context", type: "textarea", required: true, placeholder: "採購項目、目前供應商、合約規模、採購頻率", placeholderEn: "Item, current supplier, contract scale, frequency" },
      { key: "goal", label: "談判目標", labelEn: "Negotiation Goal", type: "text", required: true, placeholder: "例：降價、延長帳期、提升 SLA、綁定保固", placeholderEn: "e.g. price cut, extended terms, better SLA, warranty" },
      { key: "leverage", label: "籌碼 / 限制（選填）", labelEn: "Leverage / Constraints (optional)", type: "text", required: false, placeholder: "採購量、替代供應商、轉換成本", placeholderEn: "Volume, alternatives, switching cost" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位採購談判指揮官,協助買方爭取最佳條件並制定完整談判方案。",
      "", `採購情境：${v.context}`, `目標：${v.goal}`,
      v.leverage ? `籌碼/限制：${v.leverage}` : "",
      "", "### 1. 市場行情",
      "此類採購的合理價格範圍 / 影響定價因素 / 市場供需態勢",
      "", "### 2. BATNA 分析",
      "買方 BATNA / 供應商可能 BATNA / 談判區間（ZOPA）",
      "", "### 3. 談判戰術",
      "開場錨定 / 讓步階梯 / 5 個適用戰術 + 使用時機",
      "", "### 4. 談判指揮方案",
      "完整開場白（可直接說）/ 3 個情境應對劇本 / 關鍵條款攻略表 / 成交與簽約檢核清單。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a procurement negotiation commander helping buyers secure the best terms with a complete negotiation plan.",
      "", `Procurement context: ${v.context}`, `Goal: ${v.goal}`,
      v.leverage ? `Leverage/constraints: ${v.leverage}` : "",
      "", "### 1. Market Intelligence — fair price range / pricing factors / supply-demand dynamics",
      "### 2. BATNA Analysis — buyer's BATNA / supplier's likely BATNA / ZOPA",
      "### 3. Negotiation Tactics — opening anchor / concession ladder / 5 tactics + timing",
      "### 4. Command Plan — full opening (ready to say) / 3 scenario playbooks / key-clause table / closing & signing checklist. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 219. 供應商評估系統 ──────────────────────────────────────────────────
  supplierevaluator: {
    inputs: [
      { key: "supplier", label: "供應商資訊", labelEn: "Supplier Info", type: "textarea", required: true, placeholder: "供應商、提供品項、合作規模、重要性", placeholderEn: "Supplier, items provided, scale, importance" },
      { key: "purpose", label: "評估目的", labelEn: "Evaluation Purpose", type: "text", required: true, placeholder: "例：新供應商評選、定期稽核、續約評估", placeholderEn: "e.g. new supplier selection, periodic audit, renewal" },
      { key: "criteria", label: "重點考量（選填）", labelEn: "Key Considerations (optional)", type: "text", required: false, placeholder: "品質、交期、成本、ESG、財務", placeholderEn: "Quality, delivery, cost, ESG, financial" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位供應商管理顧問,建立系統化的供應商評估與管理體系。",
      "", `供應商：${v.supplier}`, `目的：${v.purpose}`,
      v.criteria ? `重點：${v.criteria}` : "",
      "", "### 1. 多維評分卡",
      "5-7 個評估維度（品質/交期/成本/服務/財務穩定/合規）+ 權重 + 評分標準,用表格呈現",
      "輸出 ```chart 長條圖顯示各維度權重。",
      "", "### 2. 風險盡調",
      "供應商風險盤點（財務/集中度/合規/ESG）+ 各風險等級 + 盡調文件清單",
      "", "### 3. 談判策略",
      "依評估結果的談判重點 + 籌碼分析 + 關鍵條款建議",
      "", "### 4. 關係管理架構",
      "供應商分級 / 定期檢視機制 / 績效追蹤指標 / 改善與退場機制。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a supplier management consultant building a systematic supplier evaluation and management framework.",
      "", `Supplier: ${v.supplier}`, `Purpose: ${v.purpose}`,
      v.criteria ? `Focus: ${v.criteria}` : "",
      "", "### 1. Multi-Dimensional Scorecard — 5–7 dimensions (quality/delivery/cost/service/financial stability/compliance) + weights + criteria, table. ```chart bar chart of weights.",
      "### 2. Risk Due Diligence — risk inventory (financial/concentration/compliance/ESG) + risk levels + DD document checklist",
      "### 3. Negotiation Strategy — focus based on evaluation + leverage analysis + key clause recommendations",
      "### 4. Relationship Management — supplier tiering / review mechanism / performance metrics / improvement & exit. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 221. 供應商選商決策 ──────────────────────────────────────────────────
  vendorselection: {
    inputs: [
      { key: "needs", label: "採購需求", labelEn: "Procurement Needs", type: "textarea", required: true, placeholder: "要採購什麼、規格、預算、時程要求", placeholderEn: "What to procure, specs, budget, timeline" },
      { key: "vendors", label: "候選供應商（選填）", labelEn: "Candidate Vendors (optional)", type: "textarea", required: false, placeholder: "已詢價的供應商與報價", placeholderEn: "Vendors quoted and their prices" },
      { key: "priority", label: "決策優先（選填）", labelEn: "Decision Priority (optional)", type: "text", required: false, placeholder: "例：成本優先/品質優先/風險最小", placeholderEn: "e.g. cost-first/quality-first/risk-minimal" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位採購決策顧問,用三維評估做出理性的選商決策。",
      "", `需求：${v.needs}`,
      v.vendors ? `候選供應商：${v.vendors}` : "",
      v.priority ? `優先：${v.priority}` : "",
      "", "### 1. 評估維度與權重",
      "技術 / 財務 / 風險三大維度的子項與權重設計",
      "", "### 2. 三維評估矩陣",
      "對候選供應商評分（技術契合/財務條件/風險水平),用加權矩陣算總分並排序,用表格呈現",
      "輸出 ```chart 長條圖顯示各供應商加權總分。",
      "", "### 3. 風險與敏感度",
      "各候選的主要風險 / 哪個維度最影響結論",
      "", "### 4. 選商決策建議",
      "推薦供應商 + 理由 / 議價空間 / 合約注意事項 / 備案。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a procurement decision consultant making rational vendor selections via 3-dimensional assessment.",
      "", `Needs: ${v.needs}`,
      v.vendors ? `Candidates: ${v.vendors}` : "",
      v.priority ? `Priority: ${v.priority}` : "",
      "", "### 1. Dimensions & Weights — technical / financial / risk dimensions with sub-items and weights",
      "### 2. 3D Assessment Matrix — score candidates (technical fit/financial terms/risk level), weighted matrix total and ranking, table. ```chart bar chart.",
      "### 3. Risk & Sensitivity — main risks per candidate / which dimension most affects the conclusion",
      "### 4. Selection Recommendation — recommended vendor + rationale / negotiation room / contract notes / backup. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 237. 風險應對劇本師 ──────────────────────────────────────────────────
  riskPlaybook: {
    inputs: [
      { key: "risks", label: "風險清單 / 情境", labelEn: "Risk Inventory / Scenarios", type: "textarea", required: true, placeholder: "已識別的風險,或想評估的業務情境", placeholderEn: "Identified risks, or business scenario to assess" },
      { key: "business", label: "業務背景", labelEn: "Business Context", type: "text", required: true, placeholder: "公司、行業、規模", placeholderEn: "Company, industry, size" },
      { key: "focus", label: "重點領域（選填）", labelEn: "Focus Area (optional)", type: "text", required: false, placeholder: "例：營運/財務/資安/供應鏈", placeholderEn: "e.g. operational/financial/cybersecurity/supply chain" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位風險管理指揮官,建立完整的風險應對劇本。",
      "", `風險/情境：${v.risks}`, `業務：${v.business}`,
      v.focus ? `重點：${v.focus}` : "",
      "", "### 1. 優先排序矩陣",
      "用「機率 × 影響」矩陣評估各風險,用表格：風險/機率/影響/風險等級/類別",
      "輸出 ```chart 長條圖顯示各風險嚴重度。",
      "", "### 2. 緩解策略",
      "每個重大風險的緩解策略(規避/降低/轉移/接受)+ 具體措施 + 負責人",
      "", "### 3. 應急計畫",
      "TOP 3 風險的應急反應計畫(觸發條件→即時行動→恢復路徑)",
      "", "### 4. 危機指揮架構",
      "危機分級 / 指揮鏈 / 啟動條件 / KRI 監控清單。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a risk management commander building a complete risk response playbook.",
      "", `Risks/scenarios: ${v.risks}`, `Business: ${v.business}`,
      v.focus ? `Focus: ${v.focus}` : "",
      "", "### 1. Priority Matrix — probability × impact matrix, table: risk/probability/impact/level/category. ```chart bar chart of severity.",
      "### 2. Mitigation Strategy — per major risk: strategy (avoid/reduce/transfer/accept) + measures + owner",
      "### 3. Contingency Plans — top 3 risks: trigger→immediate action→recovery path",
      "### 4. Crisis Command Structure — crisis tiers / chain of command / activation criteria / KRI monitoring list. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 274. 專案風險管理師 ──────────────────────────────────────────────────
  projectRiskManager: {
    inputs: [
      { key: "project", label: "專案描述", labelEn: "Project Description", type: "textarea", required: true, placeholder: "專案目標、範圍、時程、團隊、預算", placeholderEn: "Project goal, scope, timeline, team, budget" },
      { key: "concern", label: "主要顧慮", labelEn: "Main Concerns", type: "text", required: true, placeholder: "已意識到的風險或不確定性", placeholderEn: "Known risks or uncertainties" },
      { key: "stage", label: "專案階段（選填）", labelEn: "Project Stage (optional)", type: "text", required: false, placeholder: "規劃 / 執行中 / 收尾", placeholderEn: "Planning / in progress / closing" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位專案風險管理師,建立完整的風險管理機制。",
      "", `專案：${v.project}`, `顧慮：${v.concern}`,
      v.stage ? `階段：${v.stage}` : "",
      "", "### 1. 風險識別登錄",
      "依類別識別風險(範圍/時程/成本/資源/技術/外部),建立風險登錄表",
      "", "### 2. 影響機率矩陣",
      "用表格評估每個風險：風險/機率/影響/風險分數/負責人",
      "輸出 ```chart 長條圖顯示各風險分數。",
      "", "### 3. 應急計畫",
      "TOP 5 風險的應對策略(規避/降低/轉移/接受)+ 應急方案 + 觸發條件",
      "", "### 4. 監控機制",
      "風險審查節律 / 預警指標 / 風險溝通機制 / 風險登錄更新流程。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a project risk manager building a complete risk management mechanism.",
      "", `Project: ${v.project}`, `Concerns: ${v.concern}`,
      v.stage ? `Stage: ${v.stage}` : "",
      "", "### 1. Risk Identification Register — identify risks by category (scope/schedule/cost/resource/technical/external), build register",
      "### 2. Impact-Probability Matrix — table: risk/probability/impact/risk score/owner. ```chart bar chart of risk scores.",
      "### 3. Contingency Plans — top 5 risks: response (avoid/reduce/transfer/accept) + contingency + triggers",
      "### 4. Monitoring — risk review cadence / early warning indicators / risk communication / register update process. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 285. 專案章程生成器 ──────────────────────────────────────────────────
  projectCharterBuilder: {
    inputs: [
      { key: "project", label: "專案描述", labelEn: "Project Description", type: "textarea", required: true, placeholder: "專案目標、背景、範圍、預期成果", placeholderEn: "Project goal, background, scope, expected outcomes" },
      { key: "stakeholders", label: "利害關係人 / 資源", labelEn: "Stakeholders / Resources", type: "text", required: true, placeholder: "贊助者、團隊、預算、時程", placeholderEn: "Sponsor, team, budget, timeline" },
      { key: "constraints", label: "限制（選填）", labelEn: "Constraints (optional)", type: "text", required: false, placeholder: "時間、預算、技術、相依", placeholderEn: "Time, budget, tech, dependencies" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位專案管理顧問,撰寫清晰、可對齊的專案章程。",
      "", `專案：${v.project}`, `利害關係人/資源：${v.stakeholders}`,
      v.constraints ? `限制：${v.constraints}` : "",
      "", "### 1. 章程文件",
      "專案目的 / 目標(SMART)/ 範圍(In/Out)/ 成功標準 / 主要交付物 / 假設與限制",
      "", "### 2. 里程碑計畫",
      "關鍵里程碑與時程,用 ```mermaid gantt 呈現",
      "", "### 3. 利害關係人矩陣",
      "用表格：關係人 / 角色 / 影響力 / 期望 / 溝通方式",
      "", "### 4. 啟動議程",
      "Kickoff 會議議程 + 角色職責(RACI 概要)+ 首要風險。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a project management consultant writing clear, alignment-driving project charters.",
      "", `Project: ${v.project}`, `Stakeholders/resources: ${v.stakeholders}`,
      v.constraints ? `Constraints: ${v.constraints}` : "",
      "", "### 1. Charter Document — purpose / SMART objectives / scope (In/Out) / success criteria / key deliverables / assumptions and constraints",
      "### 2. Milestone Plan — key milestones and timeline, ```mermaid gantt",
      "### 3. Stakeholder Matrix — table: stakeholder / role / influence / expectations / communication",
      "### 4. Kickoff Agenda — kickoff meeting agenda + role responsibilities (RACI overview) + top risks. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 325. 專案組合管理師 ──────────────────────────────────────────────────
  projectPortfolioManager: {
    inputs: [
      { key: "projects", label: "專案清單", labelEn: "Project List", type: "textarea", required: true, placeholder: "現有/規劃中的專案(目標、規模、狀態)", placeholderEn: "Current/planned projects (goal, size, status)" },
      { key: "resources", label: "資源狀況", labelEn: "Resource Situation", type: "text", required: true, placeholder: "團隊、預算、時間限制", placeholderEn: "Team, budget, time constraints" },
      { key: "goal", label: "組合目標", labelEn: "Portfolio Goal", type: "text", required: false, placeholder: "例：聚焦高價值、平衡風險、加快交付", placeholderEn: "e.g. focus high-value, balance risk, faster delivery" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位專案組合管理顧問,協助組織做出最佳的專案投資決策。",
      "", `專案清單：${v.projects}`, `資源狀況：${v.resources}`,
      v.goal ? `組合目標：${v.goal}` : "",
      "", "### 1. 專案優先排序",
      "用「策略契合 × 價值 × 可行性」評估各專案,加權排序,用表格呈現",
      "輸出 ```chart 長條圖顯示各專案綜合分數。",
      "", "### 2. 資源衝突診斷",
      "識別資源衝突(人力/預算/時間)+ 瓶頸資源 + 過度承諾的風險",
      "", "### 3. 組合平衡決策",
      "建議的專案組合(做/暫緩/停止)+ 風險與報酬平衡 + 資源重配置",
      "", "### 4. 治理機制",
      "組合檢視節律 / 階段關卡 / 專案健康度監控指標。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a project portfolio management consultant helping make optimal project investment decisions.",
      "", `Project list: ${v.projects}`, `Resource situation: ${v.resources}`,
      v.goal ? `Portfolio goal: ${v.goal}` : "",
      "", "### 1. Project Prioritization — assess each by 'strategic fit × value × feasibility', weighted ranking, table. ```chart bar chart of overall scores.",
      "### 2. Resource Conflict Diagnostic — identify conflicts (people/budget/time) + bottleneck resources + over-commitment risk",
      "### 3. Portfolio Balancing — recommended portfolio (go/hold/stop) + risk-reward balance + resource reallocation",
      "### 4. Governance — portfolio review cadence / stage gates / project health monitoring metrics. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  businessContinuity: {
    inputs: [
      field("business", ["業務描述", "Business Description"], { required: true, placeholder: ["公司、關鍵業務、營運依賴、現有應變", "Company, critical operations, dependencies, current preparedness"] }),
      field("concern", ["主要風險（選填）", "Main Risks (optional)"], { type: "text", placeholder: ["例：天災、資安、供應中斷、關鍵人員", "e.g. disaster, cyber, supply disruption, key person"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位業務持續計畫(BCP)顧問。",
        "", `業務：${v.business}`,
        v.concern && `主要風險：${v.concern}`,
        "", "### 1. 關鍵流程識別",
        "盤點關鍵業務流程 + 營運依賴 + 業務衝擊分析(BIA)",
        "輸出 ```chart 長條圖顯示各流程的中斷衝擊。",
        "", "### 2. 中斷情境",
        "主要中斷情境 + 可能性與影響 + 連鎖效應",
        "", "### 3. 復原目標設計",
        "各關鍵流程的 RTO(復原時間)與 RPO(資料復原點)+ 復原策略",
        "", "### 4. 持續計畫",
        "應變組織 + 復原步驟 + 演練機制 + 溝通計畫。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a Business Continuity Planning (BCP) consultant.",
        "", `Business: ${v.business}`,
        v.concern && `Main risks: ${v.concern}`,
        "", "### 1. Critical Process Identification — inventory critical processes + dependencies + Business Impact Analysis (BIA). ```chart bar chart of disruption impact per process.",
        "### 2. Disruption Scenarios — main scenarios + likelihood and impact + cascading effects",
        "### 3. Recovery Objectives — RTO (recovery time) and RPO (recovery point) per critical process + recovery strategy",
        "### 4. Continuity Plan — response org + recovery steps + drill mechanism + communication plan. Respond in English.",
      ],
    }),
  },
  escalationMatrix: {
    inputs: [
      field("context", ["組織 / 流程描述", "Organization / Process Description"], { required: true, placeholder: ["團隊、決策類型、現有升級問題、痛點", "Team, decision types, current escalation issues, pain points"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：加快決策、釐清權限、降卡關", "e.g. faster decisions, clarify authority, reduce stalls"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位問題升級矩陣設計師。",
        "", `組織/流程：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 升級分級設計",
        "問題分級(嚴重度/影響)+ 各級對應的決策層級,用表格呈現",
        "", "### 2. 升級路徑",
        "升級觸發條件與路徑,用 ```mermaid flowchart 呈現升級決策樹",
        "", "### 3. 權責與時效",
        "各層級的決策權限 + 回應時效(SLA)+ 避免過度/不足升級",
        "", "### 4. 落地建議",
        "升級機制溝通 + 監控與檢討。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are an escalation matrix framework designer.",
        "", `Organization/process: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Escalation Tiering — issue tiering (severity/impact) + decision level per tier, table",
        "### 2. Escalation Path — escalation triggers and paths, ```mermaid flowchart of escalation decision tree",
        "### 3. Authority & Timing — decision authority per level + response SLA + avoid over/under-escalation",
        "### 4. Implementation — escalation mechanism communication + monitoring and review. Respond in English.",
      ],
    }),
  },
  changeControlAdvisor: {
    inputs: [
      field("context", ["變更情境描述", "Change Description"], { required: true, placeholder: ["變更類型、影響系統、風險、團隊、現有流程", "Change type, affected systems, risk, team, current process"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：降低變更風險、加速、合規", "e.g. reduce change risk, accelerate, compliance"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位變更管理(Change Control)顧問。",
        "", `變更情境：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 變更分類與流程",
        "依風險分類(標準/一般/緊急)的審批流程,用 ```mermaid flowchart 呈現",
        "", "### 2. 風險評估與審批",
        "變更風險評估維度 + 審批層級 + CAB 機制",
        "", "### 3. 執行與回滾",
        "執行檢查清單 + 回滾計畫 + 變更窗口",
        "", "### 4. 驗證與改善",
        "變更後驗證 + 失敗分析 + 流程持續改善。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a change control advisor.",
        "", `Change: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Change Classification & Process — approval process by risk classification (standard/normal/emergency), ```mermaid flowchart",
        "### 2. Risk Assessment & Approval — change risk dimensions + approval levels + CAB mechanism",
        "### 3. Execution & Rollback — execution checklist + rollback plan + change window",
        "### 4. Validation & Improvement — post-change validation + failure analysis + continuous process improvement. Respond in English.",
      ],
    }),
  },
};
