import type { AgentOverride } from "../types";
import { bilingual, field } from "./helpers";

/** operations category agent overrides. See ./index.ts for how these merge. */
export const OPERATIONS_OVERRIDES: Record<string, AgentOverride> = {
  // ── 209. SOP 生成器 ──────────────────────────────────────────────────────
  sopgenerator: {
    inputs: [
      { key: "process", label: "業務流程描述", labelEn: "Business Process Description", type: "textarea", required: true, placeholder: "要文件化的流程：目的、步驟、參與者、頻率", placeholderEn: "Process to document: purpose, steps, participants, frequency" },
      { key: "audience", label: "執行者 / 受眾", labelEn: "Performers / Audience", type: "text", required: true, placeholder: "誰會執行這個 SOP？經驗程度？", placeholderEn: "Who will perform this SOP? Experience level?" },
      { key: "risk", label: "風險 / 合規考量（選填）", labelEn: "Risk / Compliance (optional)", type: "text", required: false, placeholder: "例：涉及金流、個資、安全", placeholderEn: "e.g. involves payments, personal data, safety" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位流程文件化專家，撰寫清晰、可執行、防呆的標準作業程序（SOP）。",
      "", `流程：${v.process}`, `執行者：${v.audience}`,
      v.risk ? `風險/合規：${v.risk}` : "",
      "", "### 1. 流程概覽",
      "目的 / 適用範圍 / 觸發條件 / 負責角色 / 預估時間",
      "用 ```mermaid flowchart TD 呈現流程步驟。",
      "", "### 2. 步驟分解",
      "編號步驟清單，每步：動作 / 負責人 / 工具/系統 / 預期產出 / 注意事項",
      "", "### 3. 風險控管",
      "關鍵控制點 / 常見錯誤與防呆 / 例外處理流程",
      "", "### 4. KPI 設計",
      "衡量此流程的 3-4 個指標 + 目標值",
      "", "### 5. 正式 SOP 文件",
      "輸出可直接使用的完整 SOP（含版本/編號/標題/各章節）。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a process documentation expert writing clear, executable, foolproof Standard Operating Procedures.",
      "", `Process: ${v.process}`, `Performers: ${v.audience}`,
      v.risk ? `Risk/compliance: ${v.risk}` : "",
      "", "### 1. Process Overview — purpose / scope / trigger / responsible roles / estimated time. ```mermaid flowchart TD of steps.",
      "### 2. Step Decomposition — numbered steps: action / owner / tools / expected output / notes",
      "### 3. Risk Control — key control points / common errors & safeguards / exception handling",
      "### 4. KPI Design — 3–4 metrics + targets",
      "### 5. Formal SOP Document — complete ready-to-use SOP (version/number/title/sections). Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 216. 採購談判指揮官 ──────────────────────────────────────────────────
  procurementnegotiation: {
    inputs: [
      { key: "context", label: "採購情境", labelEn: "Procurement Context", type: "textarea", required: true, placeholder: "採購項目、目前供應商、合約規模、採購頻率", placeholderEn: "Item, current supplier, contract scale, frequency" },
      { key: "goal", label: "談判目標", labelEn: "Negotiation Goal", type: "text", required: true, placeholder: "例：降價、延長帳期、提升 SLA、綁定保固", placeholderEn: "e.g. price cut, extended terms, better SLA, warranty" },
      { key: "leverage", label: "籌碼 / 限制（選填）", labelEn: "Leverage / Constraints (optional)", type: "text", required: false, placeholder: "採購量、替代供應商、轉換成本", placeholderEn: "Volume, alternatives, switching cost" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位採購談判指揮官,協助買方爭取最佳條件並制定完整談判方案。",
      "", `採購情境：${v.context}`, `目標：${v.goal}`,
      v.leverage ? `籌碼/限制：${v.leverage}` : "",
      "", "### 1. 市場行情",
      "此類採購的合理價格範圍 / 影響定價因素 / 市場供需態勢",
      "", "### 2. BATNA 分析",
      "買方 BATNA / 供應商可能 BATNA / 談判區間（ZOPA）",
      "", "### 3. 談判戰術",
      "開場錨定 / 讓步階梯 / 5 個適用戰術 + 使用時機",
      "", "### 4. 談判指揮方案",
      "完整開場白（可直接說）/ 3 個情境應對劇本 / 關鍵條款攻略表 / 成交與簽約檢核清單。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a procurement negotiation commander helping buyers secure the best terms with a complete negotiation plan.",
      "", `Procurement context: ${v.context}`, `Goal: ${v.goal}`,
      v.leverage ? `Leverage/constraints: ${v.leverage}` : "",
      "", "### 1. Market Intelligence — fair price range / pricing factors / supply-demand dynamics",
      "### 2. BATNA Analysis — buyer's BATNA / supplier's likely BATNA / ZOPA",
      "### 3. Negotiation Tactics — opening anchor / concession ladder / 5 tactics + timing",
      "### 4. Command Plan — full opening (ready to say) / 3 scenario playbooks / key-clause table / closing & signing checklist. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 219. 供應商評估系統 ──────────────────────────────────────────────────
  supplierevaluator: {
    inputs: [
      { key: "supplier", label: "供應商資訊", labelEn: "Supplier Info", type: "textarea", required: true, placeholder: "供應商、提供品項、合作規模、重要性", placeholderEn: "Supplier, items provided, scale, importance" },
      { key: "purpose", label: "評估目的", labelEn: "Evaluation Purpose", type: "text", required: true, placeholder: "例：新供應商評選、定期稽核、續約評估", placeholderEn: "e.g. new supplier selection, periodic audit, renewal" },
      { key: "criteria", label: "重點考量（選填）", labelEn: "Key Considerations (optional)", type: "text", required: false, placeholder: "品質、交期、成本、ESG、財務", placeholderEn: "Quality, delivery, cost, ESG, financial" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位供應商管理顧問,建立系統化的供應商評估與管理體系。",
      "", `供應商：${v.supplier}`, `目的：${v.purpose}`,
      v.criteria ? `重點：${v.criteria}` : "",
      "", "### 1. 多維評分卡",
      "5-7 個評估維度（品質/交期/成本/服務/財務穩定/合規）+ 權重 + 評分標準,用表格呈現",
      "輸出 ```chart 長條圖顯示各維度權重。",
      "", "### 2. 風險盡調",
      "供應商風險盤點（財務/集中度/合規/ESG）+ 各風險等級 + 盡調文件清單",
      "", "### 3. 談判策略",
      "依評估結果的談判重點 + 籌碼分析 + 關鍵條款建議",
      "", "### 4. 關係管理架構",
      "供應商分級 / 定期檢視機制 / 績效追蹤指標 / 改善與退場機制。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a supplier management consultant building a systematic supplier evaluation and management framework.",
      "", `Supplier: ${v.supplier}`, `Purpose: ${v.purpose}`,
      v.criteria ? `Focus: ${v.criteria}` : "",
      "", "### 1. Multi-Dimensional Scorecard — 5–7 dimensions (quality/delivery/cost/service/financial stability/compliance) + weights + criteria, table. ```chart bar chart of weights.",
      "### 2. Risk Due Diligence — risk inventory (financial/concentration/compliance/ESG) + risk levels + DD document checklist",
      "### 3. Negotiation Strategy — focus based on evaluation + leverage analysis + key clause recommendations",
      "### 4. Relationship Management — supplier tiering / review mechanism / performance metrics / improvement & exit. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 221. 供應商選商決策 ──────────────────────────────────────────────────
  vendorselection: {
    inputs: [
      { key: "needs", label: "採購需求", labelEn: "Procurement Needs", type: "textarea", required: true, placeholder: "要採購什麼、規格、預算、時程要求", placeholderEn: "What to procure, specs, budget, timeline" },
      { key: "vendors", label: "候選供應商（選填）", labelEn: "Candidate Vendors (optional)", type: "textarea", required: false, placeholder: "已詢價的供應商與報價", placeholderEn: "Vendors quoted and their prices" },
      { key: "priority", label: "決策優先（選填）", labelEn: "Decision Priority (optional)", type: "text", required: false, placeholder: "例：成本優先/品質優先/風險最小", placeholderEn: "e.g. cost-first/quality-first/risk-minimal" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位採購決策顧問,用三維評估做出理性的選商決策。",
      "", `需求：${v.needs}`,
      v.vendors ? `候選供應商：${v.vendors}` : "",
      v.priority ? `優先：${v.priority}` : "",
      "", "### 1. 評估維度與權重",
      "技術 / 財務 / 風險三大維度的子項與權重設計",
      "", "### 2. 三維評估矩陣",
      "對候選供應商評分（技術契合/財務條件/風險水平),用加權矩陣算總分並排序,用表格呈現",
      "輸出 ```chart 長條圖顯示各供應商加權總分。",
      "", "### 3. 風險與敏感度",
      "各候選的主要風險 / 哪個維度最影響結論",
      "", "### 4. 選商決策建議",
      "推薦供應商 + 理由 / 議價空間 / 合約注意事項 / 備案。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a procurement decision consultant making rational vendor selections via 3-dimensional assessment.",
      "", `Needs: ${v.needs}`,
      v.vendors ? `Candidates: ${v.vendors}` : "",
      v.priority ? `Priority: ${v.priority}` : "",
      "", "### 1. Dimensions & Weights — technical / financial / risk dimensions with sub-items and weights",
      "### 2. 3D Assessment Matrix — score candidates (technical fit/financial terms/risk level), weighted matrix total and ranking, table. ```chart bar chart.",
      "### 3. Risk & Sensitivity — main risks per candidate / which dimension most affects the conclusion",
      "### 4. Selection Recommendation — recommended vendor + rationale / negotiation room / contract notes / backup. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 237. 風險應對劇本師 ──────────────────────────────────────────────────
  riskPlaybook: {
    inputs: [
      { key: "risks", label: "風險清單 / 情境", labelEn: "Risk Inventory / Scenarios", type: "textarea", required: true, placeholder: "已識別的風險,或想評估的業務情境", placeholderEn: "Identified risks, or business scenario to assess" },
      { key: "business", label: "業務背景", labelEn: "Business Context", type: "text", required: true, placeholder: "公司、行業、規模", placeholderEn: "Company, industry, size" },
      { key: "focus", label: "重點領域（選填）", labelEn: "Focus Area (optional)", type: "text", required: false, placeholder: "例：營運/財務/資安/供應鏈", placeholderEn: "e.g. operational/financial/cybersecurity/supply chain" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位風險管理指揮官,建立完整的風險應對劇本。",
      "", `風險/情境：${v.risks}`, `業務：${v.business}`,
      v.focus ? `重點：${v.focus}` : "",
      "", "### 1. 優先排序矩陣",
      "用「機率 × 影響」矩陣評估各風險,用表格：風險/機率/影響/風險等級/類別",
      "輸出 ```chart 長條圖顯示各風險嚴重度。",
      "", "### 2. 緩解策略",
      "每個重大風險的緩解策略(規避/降低/轉移/接受)+ 具體措施 + 負責人",
      "", "### 3. 應急計畫",
      "TOP 3 風險的應急反應計畫(觸發條件→即時行動→恢復路徑)",
      "", "### 4. 危機指揮架構",
      "危機分級 / 指揮鏈 / 啟動條件 / KRI 監控清單。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a risk management commander building a complete risk response playbook.",
      "", `Risks/scenarios: ${v.risks}`, `Business: ${v.business}`,
      v.focus ? `Focus: ${v.focus}` : "",
      "", "### 1. Priority Matrix — probability × impact matrix, table: risk/probability/impact/level/category. ```chart bar chart of severity.",
      "### 2. Mitigation Strategy — per major risk: strategy (avoid/reduce/transfer/accept) + measures + owner",
      "### 3. Contingency Plans — top 3 risks: trigger→immediate action→recovery path",
      "### 4. Crisis Command Structure — crisis tiers / chain of command / activation criteria / KRI monitoring list. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 274. 專案風險管理師 ──────────────────────────────────────────────────
  projectRiskManager: {
    inputs: [
      { key: "project", label: "專案描述", labelEn: "Project Description", type: "textarea", required: true, placeholder: "專案目標、範圍、時程、團隊、預算", placeholderEn: "Project goal, scope, timeline, team, budget" },
      { key: "concern", label: "主要顧慮", labelEn: "Main Concerns", type: "text", required: true, placeholder: "已意識到的風險或不確定性", placeholderEn: "Known risks or uncertainties" },
      { key: "stage", label: "專案階段（選填）", labelEn: "Project Stage (optional)", type: "text", required: false, placeholder: "規劃 / 執行中 / 收尾", placeholderEn: "Planning / in progress / closing" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位專案風險管理師,建立完整的風險管理機制。",
      "", `專案：${v.project}`, `顧慮：${v.concern}`,
      v.stage ? `階段：${v.stage}` : "",
      "", "### 1. 風險識別登錄",
      "依類別識別風險(範圍/時程/成本/資源/技術/外部),建立風險登錄表",
      "", "### 2. 影響機率矩陣",
      "用表格評估每個風險：風險/機率/影響/風險分數/負責人",
      "輸出 ```chart 長條圖顯示各風險分數。",
      "", "### 3. 應急計畫",
      "TOP 5 風險的應對策略(規避/降低/轉移/接受)+ 應急方案 + 觸發條件",
      "", "### 4. 監控機制",
      "風險審查節律 / 預警指標 / 風險溝通機制 / 風險登錄更新流程。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a project risk manager building a complete risk management mechanism.",
      "", `Project: ${v.project}`, `Concerns: ${v.concern}`,
      v.stage ? `Stage: ${v.stage}` : "",
      "", "### 1. Risk Identification Register — identify risks by category (scope/schedule/cost/resource/technical/external), build register",
      "### 2. Impact-Probability Matrix — table: risk/probability/impact/risk score/owner. ```chart bar chart of risk scores.",
      "### 3. Contingency Plans — top 5 risks: response (avoid/reduce/transfer/accept) + contingency + triggers",
      "### 4. Monitoring — risk review cadence / early warning indicators / risk communication / register update process. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 285. 專案章程生成器 ──────────────────────────────────────────────────
  projectCharterBuilder: {
    inputs: [
      { key: "project", label: "專案描述", labelEn: "Project Description", type: "textarea", required: true, placeholder: "專案目標、背景、範圍、預期成果", placeholderEn: "Project goal, background, scope, expected outcomes" },
      { key: "stakeholders", label: "利害關係人 / 資源", labelEn: "Stakeholders / Resources", type: "text", required: true, placeholder: "贊助者、團隊、預算、時程", placeholderEn: "Sponsor, team, budget, timeline" },
      { key: "constraints", label: "限制（選填）", labelEn: "Constraints (optional)", type: "text", required: false, placeholder: "時間、預算、技術、相依", placeholderEn: "Time, budget, tech, dependencies" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位專案管理顧問,撰寫清晰、可對齊的專案章程。",
      "", `專案：${v.project}`, `利害關係人/資源：${v.stakeholders}`,
      v.constraints ? `限制：${v.constraints}` : "",
      "", "### 1. 章程文件",
      "專案目的 / 目標(SMART)/ 範圍(In/Out)/ 成功標準 / 主要交付物 / 假設與限制",
      "", "### 2. 里程碑計畫",
      "關鍵里程碑與時程,用 ```mermaid gantt 呈現",
      "", "### 3. 利害關係人矩陣",
      "用表格：關係人 / 角色 / 影響力 / 期望 / 溝通方式",
      "", "### 4. 啟動議程",
      "Kickoff 會議議程 + 角色職責(RACI 概要)+ 首要風險。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a project management consultant writing clear, alignment-driving project charters.",
      "", `Project: ${v.project}`, `Stakeholders/resources: ${v.stakeholders}`,
      v.constraints ? `Constraints: ${v.constraints}` : "",
      "", "### 1. Charter Document — purpose / SMART objectives / scope (In/Out) / success criteria / key deliverables / assumptions and constraints",
      "### 2. Milestone Plan — key milestones and timeline, ```mermaid gantt",
      "### 3. Stakeholder Matrix — table: stakeholder / role / influence / expectations / communication",
      "### 4. Kickoff Agenda — kickoff meeting agenda + role responsibilities (RACI overview) + top risks. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 325. 專案組合管理師 ──────────────────────────────────────────────────
  projectPortfolioManager: {
    inputs: [
      { key: "projects", label: "專案清單", labelEn: "Project List", type: "textarea", required: true, placeholder: "現有/規劃中的專案(目標、規模、狀態)", placeholderEn: "Current/planned projects (goal, size, status)" },
      { key: "resources", label: "資源狀況", labelEn: "Resource Situation", type: "text", required: true, placeholder: "團隊、預算、時間限制", placeholderEn: "Team, budget, time constraints" },
      { key: "goal", label: "組合目標", labelEn: "Portfolio Goal", type: "text", required: false, placeholder: "例：聚焦高價值、平衡風險、加快交付", placeholderEn: "e.g. focus high-value, balance risk, faster delivery" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位專案組合管理顧問,協助組織做出最佳的專案投資決策。",
      "", `專案清單：${v.projects}`, `資源狀況：${v.resources}`,
      v.goal ? `組合目標：${v.goal}` : "",
      "", "### 1. 專案優先排序",
      "用「策略契合 × 價值 × 可行性」評估各專案,加權排序,用表格呈現",
      "輸出 ```chart 長條圖顯示各專案綜合分數。",
      "", "### 2. 資源衝突診斷",
      "識別資源衝突(人力/預算/時間)+ 瓶頸資源 + 過度承諾的風險",
      "", "### 3. 組合平衡決策",
      "建議的專案組合(做/暫緩/停止)+ 風險與報酬平衡 + 資源重配置",
      "", "### 4. 治理機制",
      "組合檢視節律 / 階段關卡 / 專案健康度監控指標。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a project portfolio management consultant helping make optimal project investment decisions.",
      "", `Project list: ${v.projects}`, `Resource situation: ${v.resources}`,
      v.goal ? `Portfolio goal: ${v.goal}` : "",
      "", "### 1. Project Prioritization — assess each by 'strategic fit × value × feasibility', weighted ranking, table. ```chart bar chart of overall scores.",
      "### 2. Resource Conflict Diagnostic — identify conflicts (people/budget/time) + bottleneck resources + over-commitment risk",
      "### 3. Portfolio Balancing — recommended portfolio (go/hold/stop) + risk-reward balance + resource reallocation",
      "### 4. Governance — portfolio review cadence / stage gates / project health monitoring metrics. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  businessContinuity: {
    inputs: [
      field("business", ["業務描述", "Business Description"], { required: true, placeholder: ["公司、關鍵業務、營運依賴、現有應變", "Company, critical operations, dependencies, current preparedness"] }),
      field("concern", ["主要風險（選填）", "Main Risks (optional)"], { type: "text", placeholder: ["例：天災、資安、供應中斷、關鍵人員", "e.g. disaster, cyber, supply disruption, key person"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位業務持續計畫(BCP)顧問。",
        "", `業務：${v.business}`,
        v.concern && `主要風險：${v.concern}`,
        "", "### 1. 關鍵流程識別",
        "盤點關鍵業務流程 + 營運依賴 + 業務衝擊分析(BIA)",
        "輸出 ```chart 長條圖顯示各流程的中斷衝擊。",
        "", "### 2. 中斷情境",
        "主要中斷情境 + 可能性與影響 + 連鎖效應",
        "", "### 3. 復原目標設計",
        "各關鍵流程的 RTO(復原時間)與 RPO(資料復原點)+ 復原策略",
        "", "### 4. 持續計畫",
        "應變組織 + 復原步驟 + 演練機制 + 溝通計畫。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a Business Continuity Planning (BCP) consultant.",
        "", `Business: ${v.business}`,
        v.concern && `Main risks: ${v.concern}`,
        "", "### 1. Critical Process Identification — inventory critical processes + dependencies + Business Impact Analysis (BIA). ```chart bar chart of disruption impact per process.",
        "### 2. Disruption Scenarios — main scenarios + likelihood and impact + cascading effects",
        "### 3. Recovery Objectives — RTO (recovery time) and RPO (recovery point) per critical process + recovery strategy",
        "### 4. Continuity Plan — response org + recovery steps + drill mechanism + communication plan. Respond in English.",
      ],
    }),
  },
  escalationMatrix: {
    inputs: [
      field("context", ["組織 / 流程描述", "Organization / Process Description"], { required: true, placeholder: ["團隊、決策類型、現有升級問題、痛點", "Team, decision types, current escalation issues, pain points"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：加快決策、釐清權限、降卡關", "e.g. faster decisions, clarify authority, reduce stalls"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位問題升級矩陣設計師。",
        "", `組織/流程：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 升級分級設計",
        "問題分級(嚴重度/影響)+ 各級對應的決策層級,用表格呈現",
        "", "### 2. 升級路徑",
        "升級觸發條件與路徑,用 ```mermaid flowchart 呈現升級決策樹",
        "", "### 3. 權責與時效",
        "各層級的決策權限 + 回應時效(SLA)+ 避免過度/不足升級",
        "", "### 4. 落地建議",
        "升級機制溝通 + 監控與檢討。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are an escalation matrix framework designer.",
        "", `Organization/process: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Escalation Tiering — issue tiering (severity/impact) + decision level per tier, table",
        "### 2. Escalation Path — escalation triggers and paths, ```mermaid flowchart of escalation decision tree",
        "### 3. Authority & Timing — decision authority per level + response SLA + avoid over/under-escalation",
        "### 4. Implementation — escalation mechanism communication + monitoring and review. Respond in English.",
      ],
    }),
  },
  changeControlAdvisor: {
    inputs: [
      field("context", ["變更情境描述", "Change Description"], { required: true, placeholder: ["變更類型、影響系統、風險、團隊、現有流程", "Change type, affected systems, risk, team, current process"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：降低變更風險、加速、合規", "e.g. reduce change risk, accelerate, compliance"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位變更管理(Change Control)顧問。",
        "", `變更情境：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 變更分類與流程",
        "依風險分類(標準/一般/緊急)的審批流程,用 ```mermaid flowchart 呈現",
        "", "### 2. 風險評估與審批",
        "變更風險評估維度 + 審批層級 + CAB 機制",
        "", "### 3. 執行與回滾",
        "執行檢查清單 + 回滾計畫 + 變更窗口",
        "", "### 4. 驗證與改善",
        "變更後驗證 + 失敗分析 + 流程持續改善。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a change control advisor.",
        "", `Change: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Change Classification & Process — approval process by risk classification (standard/normal/emergency), ```mermaid flowchart",
        "### 2. Risk Assessment & Approval — change risk dimensions + approval levels + CAB mechanism",
        "### 3. Execution & Rollback — execution checklist + rollback plan + change window",
        "### 4. Validation & Improvement — post-change validation + failure analysis + continuous process improvement. Respond in English.",
      ],
    }),
  },
  operationsRiskManager: {
    inputs: [
      field("context", ["營運流程描述", "Operations Process Description"], { required: true, placeholder: ["關鍵流程、現有風險、依賴、痛點", "Key processes, existing risks, dependencies, pain points"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：降低中斷、合規、韌性", "e.g. reduce disruption, compliance, resilience"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位營運風險管理師。",
        "", `營運流程：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 風險識別",
        "業務流程的風險點(流程/人員/系統/外部)識別,用表格呈現",
        "", "### 2. 風險矩陣",
        "依可能性 x 影響建立風險矩陣 + 優先排序",
        "輸出 ```chart 長條圖顯示各風險的風險值。",
        "", "### 3. 應急預案設計",
        "高優先風險的緩解與應急預案",
        "", "### 4. 監控與優化",
        "風險預警指標 + 定期檢視 + 持續改善。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are an operations risk manager.",
        "", `Operations process: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Risk Identification — identify risk points in business processes (process/people/systems/external), table",
        "### 2. Risk Matrix — build risk matrix by likelihood x impact + prioritization. ```chart bar chart of risk scores.",
        "### 3. Contingency Plan Design — mitigation and contingency plans for high-priority risks",
        "### 4. Monitoring & Optimization — risk early-warning indicators + periodic review + continuous improvement. Respond in English.",
      ],
    }),
  },
  supplyChainRiskRadar: {
    inputs: [
      field("context", ["供應鏈描述", "Supply Chain Description"], { required: true, placeholder: ["關鍵供應商、地區、品類、現有風險", "Key suppliers, regions, categories, existing risks"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：降低中斷、找替代、韌性", "e.g. reduce disruption, find alternatives, resilience"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位供應鏈風險雷達。",
        "", `供應鏈：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 風險節點掃描",
        "供應鏈各節點的中斷風險(地緣/單一來源/天災/財務)識別,用表格呈現",
        "輸出 ```chart 長條圖顯示各節點風險評分。",
        "", "### 2. 中斷影響評估",
        "高風險節點中斷的影響路徑,用 ```mermaid flowchart 呈現",
        "", "### 3. 替代供應商建議",
        "關鍵品類的替代來源 + 多元化策略",
        "", "### 4. 韌性與監控",
        "緩衝庫存 + 預警機制 + 應變預案。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a supply chain risk radar.",
        "", `Supply chain: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Risk Node Scan — disruption risks per node (geopolitical/single-source/disaster/financial), table. ```chart bar chart of risk score per node.",
        "### 2. Disruption Impact Assessment — impact path of high-risk node disruption, ```mermaid flowchart",
        "### 3. Alternative Sourcing Advice — alternative sources for key categories + diversification strategy",
        "### 4. Resilience & Monitoring — buffer stock + early warning + contingency plan. Respond in English.",
      ],
    }),
  },
  warehouseLayoutOptimizer: {
    inputs: [
      field("context", ["倉庫描述", "Warehouse Description"], { required: true, placeholder: ["倉庫規模、品項、出貨頻率、現有佈局、痛點", "Warehouse size, SKUs, shipment frequency, current layout, pain points"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：縮短揀貨、提升吞吐、空間", "e.g. shorten picking, boost throughput, space"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位倉庫佈局優化系統。",
        "", `倉庫描述：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 出貨頻率分析",
        "依出貨頻率的 ABC 分類,用表格呈現",
        "輸出 ```chart 長條圖顯示各品類出貨頻率。",
        "", "### 2. 貨架佈局優化",
        "高頻品就近原則 + 動線設計,用 ```mermaid flowchart 呈現揀貨動線",
        "", "### 3. 揀貨路徑縮短",
        "揀貨策略(分區/批次/路徑)優化 + 預期省時",
        "", "### 4. 落地建議",
        "佈局調整步驟 + 衡量 + 持續優化。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a warehouse layout optimizer.",
        "", `Warehouse: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Shipment Frequency Analysis — ABC classification by shipment frequency, table. ```chart bar chart of shipment frequency per category.",
        "### 2. Shelf Layout Optimization — high-frequency-items-nearby principle + flow design, ```mermaid flowchart of picking flow",
        "### 3. Picking Path Reduction — picking strategy (zone/batch/route) optimization + expected time savings",
        "### 4. Implementation Recommendations — layout adjustment steps + measurement + continuous optimization. Respond in English.",
      ],
    }),
  },
  incidentResponseOrchestrator: {
    inputs: [
      field("context", ["事故回應現況描述", "Incident Response Status Description"], { required: true, placeholder: ["團隊、事故類型、現有流程、工具、痛點", "Teams, incident types, current process, tools, pain points"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：縮短 MTTR、跨團隊協調、追蹤", "e.g. reduce MTTR, cross-team coordination, tracking"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位事故回應編排顧問。",
        "", `事故回應現況：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 回應流程編排",
        "跨團隊事故回應流程,用 ```mermaid flowchart 呈現(偵測→分級→召集→緩解→復原)",
        "", "### 2. 角色與升級",
        "事故指揮/溝通/技術角色 + 升級矩陣,用表格呈現",
        "", "### 3. 進度追蹤",
        "修復進度追蹤 + 狀態同步 + 溝通模板",
        "", "### 4. 持續改善",
        "事後檢討 + 流程優化 + 演練。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are an incident response orchestrator advisor.",
        "", `Incident response status: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Response Flow Orchestration — cross-team response flow, ```mermaid flowchart (detect→triage→assemble→mitigate→recover)",
        "### 2. Roles & Escalation — incident commander/communications/technical roles + escalation matrix, table",
        "### 3. Progress Tracking — remediation progress tracking + status sync + communication templates",
        "### 4. Continuous Improvement — postmortem + process optimization + drills. Respond in English.",
      ],
    }),
  },
  deploymentRollbackAdvisor: {
    inputs: [
      field("context", ["部署 / 異常描述", "Deployment / Anomaly Description"], { required: true, placeholder: ["部署方式、異常指標、影響、回滾能力", "Deployment method, anomaly metrics, impact, rollback capability"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：判斷回滾、降風險、快速復原", "e.g. rollback decision, reduce risk, fast recovery"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位部署回滾決策顧問。",
        "", `部署/異常：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 異常評估",
        "部署後異常指標評估(錯誤/延遲/業務)+ 嚴重度,用表格呈現",
        "", "### 2. 回滾決策",
        "回滾 vs 修復前滾的決策準則,用 ```mermaid flowchart 呈現決策樹",
        "", "### 3. 回滾策略",
        "回滾方式(藍綠/金絲雀/版本)+ 資料相容 + 風險",
        "", "### 4. 復原與檢討",
        "復原驗證 + 事後檢討 + 預防。全程使用繁體中文(技術詞用英文)。",
      ],
      en: (v) => [
        "You are a deployment rollback advisor.",
        "", `Deployment/anomaly: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Anomaly Assessment — post-deploy anomaly metrics (error/latency/business) + severity, table",
        "### 2. Rollback Decision — rollback vs fix-forward decision criteria, ```mermaid flowchart of decision tree",
        "### 3. Rollback Strategy — rollback method (blue-green/canary/versioned) + data compatibility + risks",
        "### 4. Recovery & Review — recovery validation + postmortem + prevention. Respond in English.",
      ],
    }),
  },
  changeManagementSummarizer: {
    inputs: [
      field("context", ["變更描述", "Change Description"], { required: true, placeholder: ["變更內容、影響系統、利害關係人、時程", "Change content, affected systems, stakeholders, timeline"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：影響摘要、通知、降風險", "e.g. impact summary, notification, reduce risk"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位變更管理摘要顧問。",
        "", `變更描述：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 變更影響摘要",
        "變更的影響範圍/風險/相依,用表格呈現",
        "", "### 2. 利害關係人通知",
        "各利害關係人的通知內容與管道,用表格呈現(對象/重點/時機)",
        "", "### 3. 風險與回滾",
        "變更風險 + 回滾準備 + 驗證點",
        "", "### 4. 溝通模板",
        "變更通知模板(可直接用)。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a change management summarizer advisor.",
        "", `Change: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Change Impact Summary — scope/risk/dependencies of the change, table",
        "### 2. Stakeholder Notification — notification content and channels per stakeholder, table (audience/key points/timing)",
        "### 3. Risk & Rollback — change risk + rollback readiness + validation points",
        "### 4. Communication Template — change notification template (ready to use). Respond in English.",
      ],
    }),
  },
  processComplianceMonitor: {
    inputs: [
      field("context", ["流程 / 規範描述", "Process / Standards Description"], { required: true, placeholder: ["業務流程、SOP/規範、現有監控、痛點", "Business processes, SOP/standards, current monitoring, pain points"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：合規監控、找偏差、稽核", "e.g. compliance monitoring, find deviations, audit"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位流程合規監控顧問。",
        "", `流程/規範：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 合規監控設計",
        "該監控的合規點(SOP 遵循/必要步驟/核可/留痕),用表格呈現",
        "", "### 2. 偏差偵測",
        "流程偏差的偵測方法,用 ```mermaid flowchart 呈現監控流程",
        "", "### 3. 處置與升級",
        "偏差的處置與升級 + 例外管理",
        "", "### 4. 持續改善",
        "合規指標 + 稽核 + 流程優化。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a process compliance monitor advisor.",
        "", `Process/standards: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Compliance Monitoring Design — compliance points to monitor (SOP adherence/required steps/approvals/audit trail), table",
        "### 2. Deviation Detection — methods to detect process deviations, ```mermaid flowchart of monitoring flow",
        "### 3. Handling & Escalation — deviation handling and escalation + exception management",
        "### 4. Continuous Improvement — compliance metrics + audit + process optimization. Respond in English.",
      ],
    }),
  },
  supplierRiskScorer: {
    inputs: [
      field("context", ["供應商描述", "Supplier Description"], { required: true, placeholder: ["供應商、整合/服務、依賴度、現有評估", "Suppliers, integration/service, dependency, current assessment"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：風險評分、分級、監控", "e.g. risk scoring, tiering, monitoring"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位供應商風險評分顧問。",
        "", `供應商：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 風險維度",
        "多維度風險(財務/營運/資安/合規/集中度)評分框架,用表格呈現",
        "", "### 2. 風險評分",
        "各供應商的加權風險評分與分級",
        "輸出 ```chart 長條圖顯示各供應商風險評分。",
        "", "### 3. 高風險處置",
        "高風險供應商的處置(監控/備援/退場)",
        "", "### 4. 治理機制",
        "定期評分 + 監控 + 應變預案。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a supplier risk scorer advisor.",
        "", `Suppliers: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Risk Dimensions — multi-dimensional risk (financial/operational/security/compliance/concentration) scoring framework, table",
        "### 2. Risk Scoring — weighted risk score and tiering per supplier. ```chart bar chart of risk score per supplier.",
        "### 3. High-Risk Handling — handling for high-risk suppliers (monitoring/backup/exit)",
        "### 4. Governance Mechanism — periodic scoring + monitoring + contingency plan. Respond in English.",
      ],
    }),
  },
  contractComplianceTracker: {
    inputs: [
      field("context", ["合約描述", "Contract Description"], { required: true, placeholder: ["合約類型、義務、期限、現有追蹤、痛點", "Contract types, obligations, terms, current tracking, pain points"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：追履約、防違約、到期管理", "e.g. track fulfillment, prevent breach, expiry management"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位合約合規追蹤顧問。",
        "⚠️ 此為一般性建議,法律疑慮請諮詢律師。",
        "", `合約描述：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 義務追蹤",
        "合約關鍵義務/里程碑/到期日的追蹤清單,用表格呈現",
        "", "### 2. 違約風險識別",
        "履約落差與違約風險 + 等級",
        "", "### 3. 到期與續約",
        "到期義務/自動續約/通知期的管理,用 ```mermaid flowchart 呈現追蹤流程",
        "", "### 4. 治理機制",
        "提醒機制 + 文件留存 + 定期檢視。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a contract compliance tracker advisor.",
        "⚠️ General guidance only — consult a lawyer for legal concerns.",
        "", `Contract: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Obligation Tracking — tracking list of key obligations/milestones/expiry dates, table",
        "### 2. Breach Risk Identification — fulfillment gaps and breach risks + level",
        "### 3. Expiry & Renewal — management of expiring obligations/auto-renewal/notice periods, ```mermaid flowchart of tracking flow",
        "### 4. Governance Mechanism — reminder mechanism + document retention + periodic review. Respond in English.",
      ],
    }),
  },
  auditTrailSummarizer: {
    inputs: [
      field("context", ["稽核軌跡描述", "Audit Trail Description"], { required: true, placeholder: ["系統、操作類型、稽核量、合規需求", "System, operation types, audit volume, compliance needs"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：摘要、找異常、合規報告", "e.g. summarize, find anomalies, compliance report"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位稽核軌跡摘要顧問。",
        "", `稽核軌跡：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 軌跡摘要",
        "操作軌跡的摘要維度(誰/何時/做了什麼/影響),用表格呈現",
        "", "### 2. 高風險行為標記",
        "異常/高風險操作(越權/異常時段/敏感資料)識別",
        "輸出 ```chart 長條圖顯示各風險類型事件數。",
        "", "### 3. 合規對應",
        "與合規要求的對應 + 留存與不可竄改",
        "", "### 4. 報告與告警",
        "稽核報告結構 + 即時告警。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are an audit trail summarizer advisor.",
        "", `Audit trail: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Trail Summary — summary dimensions of operation trail (who/when/what/impact), table",
        "### 2. High-Risk Behavior Flagging — identify anomalous/high-risk operations (privilege escalation/off-hours/sensitive data). ```chart bar chart of event count per risk type.",
        "### 3. Compliance Mapping — mapping to compliance requirements + retention and tamper-resistance",
        "### 4. Reporting & Alerts — audit report structure + real-time alerts. Respond in English.",
      ],
    }),
  },
  resourceUtilizationBalancer: {
    inputs: [
      field("context", ["資源 / 團隊描述", "Resources / Teams Description"], { required: true, placeholder: ["團隊、資源(人力/設備/產能)、負載、痛點", "Teams, resources (people/equipment/capacity), load, pain points"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：均衡利用、提升效率、消除閒置", "e.g. balance utilization, improve efficiency, eliminate idle"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位資源使用率均衡器。",
        "", `資源/團隊：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 使用率診斷",
        "各團隊/資源的使用率(過載/閒置/瓶頸)診斷,用表格呈現",
        "輸出 ```chart 長條圖顯示各團隊資源使用率。",
        "", "### 2. 失衡識別",
        "過載與閒置的失衡點 + 根因",
        "", "### 3. 均衡配置",
        "跨團隊資源再分配建議 + 彈性調度",
        "", "### 4. 效率提升",
        "整體利用率提升行動 + 監控指標。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a resource utilization balancer.",
        "", `Resources/teams: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Utilization Diagnostic — utilization per team/resource (overload/idle/bottleneck), table. ```chart bar chart of resource utilization per team.",
        "### 2. Imbalance Identification — overload vs idle imbalance points + root cause",
        "### 3. Balanced Allocation — cross-team resource reallocation recommendations + flexible scheduling",
        "### 4. Efficiency Improvement — overall utilization improvement actions + monitoring metrics. Respond in English.",
      ],
    }),
  },
  logisticsRouteOptimizer: {
    inputs: [
      field("context", ["配送描述", "Delivery Description"], { required: true, placeholder: ["配送點、車輛、時窗、成本、限制", "Stops, vehicles, time windows, costs, constraints"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：降運費、縮交期、效率", "e.g. reduce freight, shorten lead time, efficiency"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位物流路徑優化器。",
        "", `配送：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 路線優化", "多點配送路線優化原則與約束,用表格呈現",
        "輸出 ```chart 長條圖顯示優化前後里程/成本。",
        "", "### 2. 成本與交期", "運輸成本與交貨時間的平衡",
        "", "### 3. 動態調整", "即時調度與異常處理",
        "", "### 4. 落地", "工具 + 衡量。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a logistics route optimizer.",
        "", `Delivery: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Route Optimization — multi-stop route optimization principles and constraints, table. ```chart bar chart of mileage/cost before vs after.",
        "### 2. Cost & Lead Time — balance freight cost and delivery time",
        "### 3. Dynamic Adjustment — real-time scheduling and exception handling",
        "### 4. Implementation — tooling + measurement. Respond in English.",
      ],
    }),
  },
  inventoryReorderAdvisor: {
    inputs: [
      field("context", ["庫存描述", "Inventory Description"], { required: true, placeholder: ["品項、消耗率、前置期、季節性", "SKUs, consumption rate, lead time, seasonality"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：補貨時機、數量、避免缺貨", "e.g. reorder timing, quantity, avoid stockout"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位庫存再訂購顧問。",
        "", `庫存：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 消耗分析", "庫存消耗速率分析,用表格呈現",
        "輸出 ```chart 長條圖顯示各品項建議補貨量。",
        "", "### 2. 補貨時機", "最佳補貨時機與再訂購點",
        "", "### 3. 補貨數量", "經濟訂購量與安全庫存",
        "", "### 4. 監控", "缺貨/呆滯預警。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are an inventory reorder advisor.",
        "", `Inventory: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Consumption Analysis — inventory consumption rate analysis, table. ```chart bar chart of recommended reorder quantity per SKU.",
        "### 2. Reorder Timing — optimal reorder timing and reorder point",
        "### 3. Reorder Quantity — economic order quantity and safety stock",
        "### 4. Monitoring — stockout/dead-stock alerts. Respond in English.",
      ],
    }),
  },
  contractExecutionTracker: {
    inputs: [
      field("context", ["合約執行描述", "Contract Execution Description"], { required: true, placeholder: ["合約、里程碑、義務、到期日、責任人", "Contracts, milestones, obligations, due dates, owners"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：追進度、提醒義務、合規", "e.g. track progress, remind obligations, compliance"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位合約執行追蹤器。",
        "", `合約執行：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 里程碑追蹤", "合約里程碑執行進度,用表格呈現(里程碑/狀態/到期/責任人)",
        "", "### 2. 義務提醒", "即將到期義務與提前量,用 ```mermaid flowchart 呈現追蹤流程",
        "", "### 3. 風險提示", "逾期/違約風險",
        "", "### 4. 機制", "提醒 + 文件 + 檢視。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a contract execution tracker.",
        "", `Contract execution: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Milestone Tracking — contract milestone execution progress, table (milestone/status/due/owner)",
        "### 2. Obligation Reminders — upcoming obligations and lead time, ```mermaid flowchart of tracking process",
        "### 3. Risk Alerts — overdue/breach risk",
        "### 4. Mechanism — reminders + documents + review. Respond in English.",
      ],
    }),
  },
  qualityNonconformanceAI: {
    inputs: [
      field("context", ["品質不良描述", "Quality Defect Description"], { required: true, placeholder: ["不良數據、產線、缺陷類型、影響", "Defect data, production line, defect types, impact"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：根因、改善、降不良", "e.g. root cause, improvement, reduce defects"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位品質不符合項分析器。",
        "", `品質不良：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 不良分析", "不良數據的分類與帕累托,用表格呈現",
        "輸出 ```chart 長條圖顯示各缺陷類型佔比。",
        "", "### 2. 根因報告", "根因分析(魚骨/5 Whys),用 ```mermaid flowchart 呈現因果",
        "", "### 3. 改善行動", "矯正與預防措施(CAPA)",
        "", "### 4. 監控", "品質指標 + 持續改善。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a quality nonconformance AI.",
        "", `Quality defects: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Defect Analysis — defect data classification and Pareto, table. ```chart bar chart of defect type share.",
        "### 2. Root Cause Report — root cause analysis (fishbone/5 Whys), ```mermaid flowchart of cause-effect",
        "### 3. Improvement Actions — corrective and preventive actions (CAPA)",
        "### 4. Monitoring — quality metrics + continuous improvement. Respond in English.",
      ],
    }),
  },
  warehouseSlottingAI: {
    inputs: [
      field("context", ["倉庫描述", "Warehouse Description"], { required: true, placeholder: ["倉庫、品項、出貨頻率、儲位、痛點", "Warehouse, SKUs, shipment frequency, slots, pain points"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：揀貨效率、空間、動線", "e.g. picking efficiency, space, flow"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位倉庫儲位規劃助手。",
        "", `倉庫：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 儲位分析", "依出貨頻率的 ABC 分類與儲位,用表格呈現",
        "輸出 ```chart 長條圖顯示各品類出貨頻率。",
        "", "### 2. 儲位優化", "高頻就近 + 動線,用 ```mermaid flowchart 呈現揀貨動線",
        "", "### 3. 空間利用", "空間利用率提升",
        "", "### 4. 落地", "調整步驟 + 衡量。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a warehouse slotting AI.",
        "", `Warehouse: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Slotting Analysis — ABC classification by shipment frequency and slots, table. ```chart bar chart of shipment frequency per category.",
        "### 2. Slotting Optimization — high-frequency-nearby + flow, ```mermaid flowchart of picking flow",
        "### 3. Space Utilization — improve space utilization",
        "### 4. Implementation — adjustment steps + measurement. Respond in English.",
      ],
    }),
  },
  deliveryExceptionHandler: {
    inputs: [
      field("context", ["交貨異常描述", "Delivery Exception Description"], { required: true, placeholder: ["異常類型、影響訂單、客戶、現有流程", "Exception types, affected orders, customers, current process"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：通知、補救、降影響", "e.g. notify, remedy, reduce impact"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位交貨異常處理器。",
        "", `交貨異常：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 異常分類", "交貨異常類型與嚴重度,用表格呈現",
        "", "### 2. 客戶通知", "各異常的客戶通知內容(可直接用)",
        "", "### 3. 補救方案", "依嚴重度的補救方案,用 ```mermaid flowchart 呈現處理流程",
        "", "### 4. 預防", "根因 + 預防機制。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a delivery exception handler.",
        "", `Delivery exception: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Exception Classification — delivery exception types and severity, table",
        "### 2. Customer Notification — customer notification content per exception (ready to use)",
        "### 3. Remedy Plan — remedy plan by severity, ```mermaid flowchart of handling process",
        "### 4. Prevention — root cause + prevention mechanism. Respond in English.",
      ],
    }),
  },
  facilityMaintenanceScheduler: {
    inputs: [
      field("context", ["設施 / 設備描述", "Facility / Equipment Description"], { required: true, placeholder: ["設備、使用紀錄、故障歷史、維護現況", "Equipment, usage records, failure history, maintenance status"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：預防維護、降停機、排程", "e.g. preventive maintenance, reduce downtime, scheduling"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位設施維護排程助手。",
        "", `設施/設備：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 維護需求", "依使用紀錄的維護需求,用表格呈現",
        "", "### 2. 預防維護排程", "預防性維護排程,用 ```mermaid gantt 呈現",
        "", "### 3. 優先序", "依關鍵性與風險排序",
        "", "### 4. 落地", "資源 + 監控 + 備件。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a facility maintenance scheduler.",
        "", `Facility/equipment: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Maintenance Needs — maintenance needs by usage records, table",
        "### 2. Preventive Maintenance Schedule — preventive maintenance schedule, ```mermaid gantt",
        "### 3. Priority — ranked by criticality and risk",
        "### 4. Implementation — resources + monitoring + spare parts. Respond in English.",
      ],
    }),
  },
  complianceChecklistEngine: {
    inputs: [
      field("context", ["法規 / 業務描述", "Regulation / Business Description"], { required: true, placeholder: ["適用法規、業務、流程、地區", "Applicable regulations, business, processes, region"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：合規清單、稽核準備、降風險", "e.g. compliance checklist, audit prep, reduce risk"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位法規遵循檢查引擎。",
        "⚠️ 此為一般性建議,正式合規請諮詢專業。",
        "", `法規/業務：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 合規檢查清單", "針對特定法規的操作合規檢查清單,用表格呈現",
        "", "### 2. 稽核準備", "稽核準備文件與證據",
        "", "### 3. 缺口與風險", "合規缺口 + 風險等級",
        "", "### 4. 機制", "持續合規 + 責任。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a compliance checklist engine.",
        "⚠️ General guidance only — consult professionals for formal compliance.",
        "", `Regulation/business: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Compliance Checklist — regulation-specific operational compliance checklist, table",
        "### 2. Audit Preparation — audit prep documents and evidence",
        "### 3. Gaps & Risk — compliance gaps + risk level",
        "### 4. Mechanism — continuous compliance + ownership. Respond in English.",
      ],
    }),
  },
  returnsMerchandiseAnalyzer: {
    inputs: [
      field("context", ["退貨數據描述", "Returns Data Description"], { required: true, placeholder: ["退貨數據、原因、產品、客群", "Returns data, reasons, products, segments"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：找系統問題、降退貨、改善", "e.g. find systemic issues, reduce returns, improve"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位退貨原因分析器。",
        "", `退貨數據：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 退貨分析", "退貨原因分類與帕累托,用表格呈現",
        "輸出 ```chart 長條圖顯示各退貨原因占比。",
        "", "### 2. 系統性問題", "重複出現的系統性問題",
        "", "### 3. 產品改善", "依退貨的產品改善建議",
        "", "### 4. 監控", "退貨率指標 + 預警。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a returns merchandise analyzer.",
        "", `Returns data: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Returns Analysis — returns reason classification and Pareto, table. ```chart bar chart of returns reason share.",
        "### 2. Systemic Issues — recurring systemic issues",
        "### 3. Product Improvement — product improvement recommendations from returns",
        "### 4. Monitoring — returns rate metrics + alerts. Respond in English.",
      ],
    }),
  },
  crossDockingOptimizer: {
    inputs: [
      field("context", ["越庫作業描述", "Cross-Docking Description"], { required: true, placeholder: ["進出貨、轉運、時窗、停留時間、痛點", "Inbound/outbound, transfers, time windows, dwell time, pain points"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：縮停留、提效、同步", "e.g. reduce dwell, efficiency, sync"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位越庫作業優化器。",
        "", `越庫作業：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 轉運分析", "進出貨同步與停留時間分析,用表格呈現",
        "", "### 2. 排程優化", "越庫排程優化,用 ```mermaid flowchart 呈現流程",
        "輸出 ```chart 長條圖顯示優化前後停留時間。",
        "", "### 3. 同步機制", "進出貨同步與月台調度",
        "", "### 4. 落地", "衡量 + 持續優化。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a cross-docking optimizer.",
        "", `Cross-docking: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Transfer Analysis — inbound/outbound sync and dwell time analysis, table",
        "### 2. Schedule Optimization — cross-docking schedule optimization, ```mermaid flowchart. ```chart bar chart of dwell time before vs after.",
        "### 3. Sync Mechanism — inbound/outbound sync and dock scheduling",
        "### 4. Implementation — measurement + continuous optimization. Respond in English.",
      ],
    }),
  },
  changeManagementCoach: {
    inputs: [
      field("context", ["組織變革描述", "Org Change Description"], { required: true, placeholder: ["變革內容、影響範圍、利害關係人、阻力", "Change content, scope, stakeholders, resistance"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：提升採用、降阻力、落地", "e.g. boost adoption, reduce resistance, land change"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位變革管理輔導教練。",
        "", `組織變革：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 變革策略", "依 ADKAR/Kotter 的變革策略,用 ```mermaid flowchart 呈現階段",
        "", "### 2. 利害關係人", "各群的立場與因應,用表格呈現",
        "", "### 3. 採用提升", "降阻力 + 溝通 + 賦能",
        "", "### 4. 衡量", "採用率指標 + 持續。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a change management coach.",
        "", `Org change: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Change Strategy — change strategy via ADKAR/Kotter, ```mermaid flowchart of stages",
        "### 2. Stakeholders — stance and response per group, table",
        "### 3. Adoption Lift — reduce resistance + communication + enablement",
        "### 4. Measurement — adoption metrics + sustainment. Respond in English.",
      ],
    }),
  },
  stakeholderMapperAI: {
    inputs: [
      field("context", ["利害關係人描述", "Stakeholder Description"], { required: true, placeholder: ["專案/變革、關係人、影響力、立場", "Project/change, stakeholders, influence, stance"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：映射、影響力策略、溝通", "e.g. mapping, influence strategy, communication"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位利害關係人映射 AI。",
        "", `利害關係人：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 關係人地圖", "影響力 x 利益的關係人地圖,用 ```mermaid flowchart 呈現",
        "", "### 2. 立場分佈", "各關係人的立場與影響力,用表格呈現",
        "", "### 3. 參與策略", "依象限的參與策略(管理/滿足/告知/監看)",
        "", "### 4. 溝通計畫", "各群的溝通內容與節律。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a stakeholder mapper AI.",
        "", `Stakeholders: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Stakeholder Map — influence x interest stakeholder map, ```mermaid flowchart",
        "### 2. Position Distribution — stance and influence per stakeholder, table",
        "### 3. Engagement Strategy — engagement strategy per quadrant (manage/satisfy/inform/monitor)",
        "### 4. Communication Plan — communication content and cadence per group. Respond in English.",
      ],
    }),
  },
  kpiDashboardDesigner: {
    inputs: [
      field("context", ["KPI / 受眾描述", "KPI / Audience Description"], { required: true, placeholder: ["KPI、受眾、決策需求、資料來源", "KPIs, audience, decision needs, data sources"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：支援決策、清晰視覺、可行動", "e.g. support decisions, clear visuals, actionable"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位 KPI 儀表板設計師。",
        "", `KPI/受眾：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 指標選擇", "依受眾與決策的關鍵指標,用表格呈現",
        "", "### 2. 視覺化設計", "各指標的視覺化形式建議",
        "輸出 ```chart 長條圖示範關鍵 KPI 呈現。",
        "", "### 3. 儀表板佈局", "分層與資訊架構",
        "", "### 4. 行動連結", "從儀表板到行動 + 警示。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a KPI dashboard designer.",
        "", `KPI/audience: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Metric Selection — key metrics by audience and decisions, table",
        "### 2. Visualization Design — visualization form recommendations per metric. ```chart bar chart demonstrating key KPI presentation.",
        "### 3. Dashboard Layout — layering and information architecture",
        "### 4. Action Linkage — dashboard-to-action + alerts. Respond in English.",
      ],
    }),
  },
  operationalRiskMapper: {
    inputs: [
      field("context", ["運營流程描述", "Operations Process Description"], { required: true, placeholder: ["流程、風險點、依賴、痛點", "Processes, risk points, dependencies, pain points"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：風險地圖、優先、緩解", "e.g. risk map, prioritize, mitigate"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位運營風險地圖工具。",
        "", `運營流程：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 風險點識別", "流程關鍵風險點,用表格呈現(風險/可能性/影響)",
        "", "### 2. 風險地圖", "風險分佈地圖,用 ```mermaid flowchart 呈現流程風險點",
        "輸出 ```chart 長條圖顯示各風險的風險值。",
        "", "### 3. 緩解優先", "依風險值排序的緩解",
        "", "### 4. 監控", "風險預警 + 檢視。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are an operational risk mapper.",
        "", `Operations process: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Risk Point Identification — key process risk points, table (risk/likelihood/impact)",
        "### 2. Risk Map — risk distribution map, ```mermaid flowchart of process risk points. ```chart bar chart of risk score per risk.",
        "### 3. Mitigation Priority — mitigation ranked by risk score",
        "### 4. Monitoring — risk early warning + review. Respond in English.",
      ],
    }),
  },
  businessContinuityPlanner: {
    inputs: [
      field("context", ["業務連續性描述", "Business Continuity Description"], { required: true, placeholder: ["關鍵業務、中斷風險、相依、RTO/RPO", "Critical functions, disruption risks, dependencies, RTO/RPO"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：連續性計畫、韌性、應變", "e.g. continuity plan, resilience, response"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位業務連續性規劃師。",
        "", `業務連續性：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 業務衝擊分析", "關鍵業務的衝擊分析(BIA)與 RTO/RPO,用表格呈現",
        "", "### 2. 連續性策略", "各情境的連續性策略,用 ```mermaid flowchart 呈現應變",
        "", "### 3. 應變預案", "中斷應變與復原步驟",
        "", "### 4. 演練", "演練計畫 + 維護。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a business continuity planner.",
        "", `Business continuity: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Business Impact Analysis — BIA of critical functions and RTO/RPO, table",
        "### 2. Continuity Strategy — continuity strategy per scenario, ```mermaid flowchart of response",
        "### 3. Contingency Plan — disruption response and recovery steps",
        "### 4. Drills — drill plan + maintenance. Respond in English.",
      ],
    }),
  },
};
