import type { AgentOverride } from "../types";
import { bilingual, field } from "./helpers";

/** ops category agent overrides. See ./index.ts for how these merge. */
export const OPS_OVERRIDES: Record<string, AgentOverride> = {
  // ── 164. 廠商談判策略師 ──────────────────────────────────────────────────
  vendornegotiation: {
    inputs: [
      { key: "procurement", label: "採購描述", labelEn: "Procurement Description", type: "textarea", required: true, placeholder: "採購項目、目前供應商、合約金額、採購頻率", placeholderEn: "Procurement item, current vendor, contract value, frequency" },
      { key: "goal", label: "談判目標", labelEn: "Negotiation Goal", type: "text", required: true, placeholder: "例：降價 15%、延長付款期、提升 SLA", placeholderEn: "e.g. 15% price reduction, extended payment terms, better SLA" },
      { key: "leverage", label: "我方籌碼 / 限制（選填）", labelEn: "Our Leverage / Constraints (optional)", type: "text", required: false, placeholder: "採購量、替代供應商、轉換成本", placeholderEn: "Purchase volume, alternative vendors, switching cost" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位採購談判策略師，協助買方爭取最佳廠商條件。",
      "", `採購：${v.procurement}`, `目標：${v.goal}`,
      v.leverage ? `籌碼/限制：${v.leverage}` : "",
      "", "### 1. 談判力分析",
      "買賣雙方力量平衡評估 / 我方籌碼盤點 / 供應商的痛點與壓力 / BATNA 分析",
      "", "### 2. 戰術設計",
      "開場錨定策略 / 讓步階梯（讓什麼換什麼）/ 適用的 5 個談判戰術 + 使用時機",
      "", "### 3. 關鍵條款攻略",
      "除價格外應爭取的條款（付款期/SLA/違約金/獨家/續約權），每項附目標值與底線，用表格呈現。",
      "", "### 4. 情境劇本",
      "3 個情境（供應商說沒空間/要求綁約/拖延）+ 應對話術",
      "", "### 5. 談判清單",
      "談判前準備 / 談判中檢核 / 簽約前確認。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a vendor negotiation strategist helping buyers secure the best terms.",
      "", `Procurement: ${v.procurement}`, `Goal: ${v.goal}`,
      v.leverage ? `Leverage/constraints: ${v.leverage}` : "",
      "", "### 1. Negotiation Power Analysis — buyer-seller power balance / our leverage inventory / vendor's pain points and pressures / BATNA",
      "### 2. Tactical Design — opening anchor / concession ladder (what to give for what) / 5 applicable tactics + when to use",
      "### 3. Key Clause Playbook — terms beyond price (payment/SLA/penalties/exclusivity/renewal), each with target and walk-away, table",
      "### 4. Scenario Scripts — 3 scenarios (vendor says no room / wants lock-in / stalls) + responses",
      "### 5. Negotiation Checklist — pre / during / pre-signing. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 168. 會議促進師 ──────────────────────────────────────────────────────
  meetingfacilitator: {
    inputs: [
      { key: "goal", label: "會議目標", labelEn: "Meeting Goal", type: "textarea", required: true, placeholder: "這場會議要達成什麼？決策/共識/腦力激盪/規劃？", placeholderEn: "What should this meeting achieve? Decision/alignment/brainstorm/planning?" },
      { key: "participants", label: "與會者", labelEn: "Participants", type: "text", required: true, placeholder: "人數、角色、是否有意見分歧或權力動態", placeholderEn: "Count, roles, any disagreements or power dynamics" },
      { key: "duration", label: "會議時長", labelEn: "Duration", type: "text", required: true, placeholder: "例：60 分鐘、半天工作坊", placeholderEn: "e.g. 60 minutes, half-day workshop" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位專業會議促進師，設計能產出明確成果的會議。",
      "", `目標：${v.goal}`, `與會者：${v.participants}`, `時長：${v.duration}`,
      "", "### 1. 議程設計",
      "依時長分段的議程（每段：時間 / 主題 / 目的 / 產出 / 促進方式），用表格呈現",
      "", "### 2. 促進技術",
      "依會議類型推薦 5 個促進技巧（如：靜默腦力激盪/點投票/魚缸/Parking Lot），每個附操作步驟",
      "", "### 3. 開場與收尾腳本",
      "開場白（建立目標與規則，可直接說）/ 收尾（確認決策與行動）",
      "", "### 4. 難題處理",
      "處理離題/主導者/沉默者/衝突的具體話術（各 1-2 句）",
      "", "### 5. 會後執行追蹤",
      "行動項目記錄模板 / 跟進機制 / 會議成效評估方式。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a professional meeting facilitator designing meetings that produce clear outcomes.",
      "", `Goal: ${v.goal}`, `Participants: ${v.participants}`, `Duration: ${v.duration}`,
      "", "### 1. Agenda Design — time-segmented agenda (time / topic / purpose / output / facilitation method), table",
      "### 2. Facilitation Techniques — 5 techniques for this meeting type (e.g. silent brainstorm/dot voting/fishbowl/parking lot) with steps",
      "### 3. Opening & Closing Scripts — opening (set goal and rules, ready to say) / closing (confirm decisions and actions)",
      "### 4. Difficult Situations — scripts for off-topic/dominator/silent/conflict (1–2 sentences each)",
      "### 5. Post-Meeting Tracking — action item template / follow-up mechanism / meeting effectiveness evaluation. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 171. 利害關係人地圖 ──────────────────────────────────────────────────
  stakeholdermapping: {
    inputs: [
      { key: "project", label: "專案 / 倡議描述", labelEn: "Project / Initiative Description", type: "textarea", required: true, placeholder: "專案目標、範圍、目前階段", placeholderEn: "Project goal, scope, current stage" },
      { key: "stakeholders", label: "已知利害關係人", labelEn: "Known Stakeholders", type: "textarea", required: true, placeholder: "列出相關的人/部門/組織（角色與立場）", placeholderEn: "List relevant people/departments/organizations (roles and stances)" },
      { key: "challenge", label: "主要挑戰（選填）", labelEn: "Main Challenge (optional)", type: "text", required: false, placeholder: "例：有人反對、需要跨部門配合、高層態度不明", placeholderEn: "e.g. opposition, cross-dept coordination, unclear leadership stance" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位專案治理顧問，協助有效管理利害關係人以推動專案成功。",
      "", `專案：${v.project}`, `利害關係人：${v.stakeholders}`,
      v.challenge ? `挑戰：${v.challenge}` : "",
      "", "### 1. 影響力地圖",
      "用「權力 × 利益」矩陣將每位利害關係人歸類（重點管理/保持滿意/保持告知/監控），用表格呈現：關係人 / 權力(高/低) / 利益(高/低) / 象限 / 目前立場(支持/中立/反對)",
      "", "### 2. 參與策略",
      "針對每個象限的參與策略 + 對關鍵人物（重點管理象限）的個別經營計畫",
      "", "### 3. 溝通計畫",
      "用表格：關係人 / 溝通訊息重點 / 頻率 / 管道 / 負責人",
      "", "### 4. 阻力管理",
      "反對者的顧慮分析 + 轉化策略 / 中立者的爭取策略 / 支持者的動員方式",
      "", "### 5. 風險預警",
      "利害關係人相關的 TOP 3 風險 + 早期信號 + 應對。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a project governance consultant helping manage stakeholders effectively for project success.",
      "", `Project: ${v.project}`, `Stakeholders: ${v.stakeholders}`,
      v.challenge ? `Challenge: ${v.challenge}` : "",
      "", "### 1. Influence Map — Power × Interest matrix classifying each stakeholder (Manage closely/Keep satisfied/Keep informed/Monitor), table: stakeholder / power (H/L) / interest (H/L) / quadrant / current stance (support/neutral/oppose)",
      "### 2. Engagement Strategy — strategy per quadrant + individual plan for key players (manage-closely quadrant)",
      "### 3. Communication Plan — table: stakeholder / key message / frequency / channel / owner",
      "### 4. Resistance Management — opponents' concerns + conversion strategy / winning over neutrals / mobilizing supporters",
      "### 5. Risk Watch — top 3 stakeholder-related risks + early signals + response. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 236. 物流優化顧問 ────────────────────────────────────────────────────
  logisticsOptimizer: {
    inputs: [
      { key: "shipping", label: "運送描述", labelEn: "Shipping Description", type: "textarea", required: true, placeholder: "貨物類型、運送範圍、頻率、現有物流方式", placeholderEn: "Cargo type, shipping scope, frequency, current logistics" },
      { key: "problem", label: "物流問題", labelEn: "Logistics Problems", type: "textarea", required: true, placeholder: "例：成本高、太慢、破損、追蹤差", placeholderEn: "e.g. high cost, slow, damage, poor tracking" },
      { key: "scale", label: "規模 / 預算（選填）", labelEn: "Scale / Budget (optional)", type: "text", required: false, placeholder: "月運量、物流預算", placeholderEn: "Monthly volume, logistics budget" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位物流優化顧問,協助企業降低成本並提升配送效率。",
      "", `運送：${v.shipping}`, `問題：${v.problem}`,
      v.scale ? `規模/預算：${v.scale}` : "",
      "", "### 1. 路線優化",
      "配送路線/網絡分析 / 倉儲布局建議 / 最後一哩優化",
      "", "### 2. 成本分析",
      "物流成本結構拆解 + 降本機會(3個)+ 估算節省",
      "輸出 ```chart 圓餅圖顯示物流成本結構。",
      "", "### 3. 供應商評選",
      "物流供應商評估維度 + 自營 vs 外包建議 + 談判要點",
      "", "### 4. 效率提升策略",
      "追蹤可視性 / 自動化機會 / 退貨逆物流 + 90 天改善計畫。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a logistics optimization consultant helping companies cut costs and improve delivery efficiency.",
      "", `Shipping: ${v.shipping}`, `Problems: ${v.problem}`,
      v.scale ? `Scale/budget: ${v.scale}` : "",
      "", "### 1. Route Optimization — delivery route/network analysis / warehouse layout / last-mile optimization",
      "### 2. Cost Analysis — logistics cost breakdown + 3 reduction opportunities + estimated savings. ```chart pie chart of cost structure.",
      "### 3. Carrier Selection — evaluation dimensions + in-house vs outsource + negotiation points",
      "### 4. Efficiency Strategy — tracking visibility / automation / returns reverse logistics + 90-day plan. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 247. 流程地圖設計師 ──────────────────────────────────────────────────
  processMapper: {
    inputs: [
      { key: "process", label: "業務流程描述", labelEn: "Business Process Description", type: "textarea", required: true, placeholder: "要視覺化的流程:步驟、參與者、輸入輸出", placeholderEn: "Process to map: steps, participants, inputs/outputs" },
      { key: "goal", label: "目的", labelEn: "Purpose", type: "text", required: true, placeholder: "例:找瓶頸、文件化、優化、自動化前準備", placeholderEn: "e.g. find bottlenecks, document, optimize, prep for automation" },
      { key: "pain", label: "已知痛點（選填）", labelEn: "Known Pain Points (optional)", type: "text", required: false, placeholder: "目前流程的問題", placeholderEn: "Current process problems" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位流程分析師,將業務流程視覺化並找出優化機會。",
      "", `流程：${v.process}`, `目的：${v.goal}`,
      v.pain ? `痛點：${v.pain}` : "",
      "", "### 1. 端對端流程視覺化",
      "用 ```mermaid flowchart TD 完整呈現流程(含決策點、分支、參與者泳道概念)",
      "", "### 2. 痛點標記",
      "標出瓶頸 / 重工 / 等待 / 手動環節 / 錯誤高發點,各附影響",
      "", "### 3. 價值分析",
      "各步驟分類(增值/不增值但必要/純浪費)+ 流程效率評估",
      "輸出 ```chart 長條圖顯示各步驟耗時或價值分布。",
      "", "### 4. 優化重設計建議",
      "簡化/合併/自動化/重排序建議 + 重設計後流程示意 + 預期改善。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a process analyst visualizing business processes and finding optimization opportunities.",
      "", `Process: ${v.process}`, `Purpose: ${v.goal}`,
      v.pain ? `Pain points: ${v.pain}` : "",
      "", "### 1. End-to-End Process Visualization — ```mermaid flowchart TD of the full process (decision points, branches, participant swimlane concept)",
      "### 2. Pain Point Marking — bottlenecks / rework / waiting / manual steps / error-prone points, with impact",
      "### 3. Value Analysis — classify steps (value-add/non-value-add necessary/pure waste) + process efficiency. ```chart bar chart.",
      "### 4. Optimization Redesign — simplify/merge/automate/reorder recommendations + redesigned flow + expected improvement. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 256. 產能規劃顧問 ────────────────────────────────────────────────────
  capacityPlanner: {
    inputs: [
      { key: "business", label: "業務描述", labelEn: "Business Description", type: "textarea", required: true, placeholder: "業務類型、產能單位(產線/人力/伺服器)、現有產能", placeholderEn: "Business type, capacity unit (line/labor/servers), current capacity" },
      { key: "demand", label: "需求情況", labelEn: "Demand Situation", type: "text", required: true, placeholder: "需求量、成長預期、季節性", placeholderEn: "Demand volume, growth expectation, seasonality" },
      { key: "constraints", label: "限制（選填）", labelEn: "Constraints (optional)", type: "text", required: false, placeholder: "預算、空間、人力、前置時間", placeholderEn: "Budget, space, labor, lead time" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位產能規劃顧問,協助企業平衡產能與需求。",
      "", `業務：${v.business}`, `需求：${v.demand}`,
      v.constraints ? `限制：${v.constraints}` : "",
      "", "### 1. 產能需求預測",
      "需求預測(保守/基本/樂觀)+ 所需產能換算 + 產能缺口/過剩分析",
      "輸出 ```chart 折線圖顯示需求 vs 產能。",
      "", "### 2. 資源配置優化",
      "產能擴充選項(加班/外包/自動化/擴廠)比較 + 成本效益",
      "", "### 3. 瓶頸解決方案",
      "識別產能瓶頸(限制理論)+ 解除瓶頸的具體行動",
      "", "### 4. 產能規劃建議",
      "短中期產能計畫 + 緩衝策略 + 監控指標。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a capacity planning consultant helping balance capacity with demand.",
      "", `Business: ${v.business}`, `Demand: ${v.demand}`,
      v.constraints ? `Constraints: ${v.constraints}` : "",
      "", "### 1. Capacity Demand Forecast — demand forecast (conservative/base/optimistic) + required capacity + gap/surplus analysis. ```chart line chart of demand vs capacity.",
      "### 2. Resource Allocation — capacity expansion options (overtime/outsource/automation/expansion) comparison + cost-benefit",
      "### 3. Bottleneck Solutions — identify bottlenecks (Theory of Constraints) + specific actions to relieve them",
      "### 4. Capacity Plan — short-mid-term plan + buffer strategy + monitoring metrics. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 266. 設施管理優化師 ──────────────────────────────────────────────────
  facilityOptimizer: {
    inputs: [
      { key: "facility", label: "設施現況描述", labelEn: "Facility Status Description", type: "textarea", required: true, placeholder: "設施類型(辦公室/廠房/門市)、面積、使用情況、痛點", placeholderEn: "Facility type (office/plant/store), area, usage, pain points" },
      { key: "goal", label: "優化目標", labelEn: "Optimization Goal", type: "text", required: true, placeholder: "例：提升空間效率、降低成本、改善體驗", placeholderEn: "e.g. improve space efficiency, cut cost, improve experience" },
      { key: "constraints", label: "限制（選填）", labelEn: "Constraints (optional)", type: "text", required: false, placeholder: "預算、不可變動的部分", placeholderEn: "Budget, immovable parts" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位設施管理顧問,協助企業優化空間與營運效率。",
      "", `設施現況：${v.facility}`, `目標：${v.goal}`,
      v.constraints ? `限制：${v.constraints}` : "",
      "", "### 1. 設施現況診斷",
      "空間使用率 / 動線效率 / 維護狀況 / 成本結構評估,指出主要問題",
      "", "### 2. 空間效率優化",
      "空間配置改善建議 / 共享與彈性空間 / 利用率提升方案",
      "輸出 ```chart 長條圖顯示各區域使用率或改善潛力。",
      "", "### 3. 維護計畫設計",
      "預防性維護排程 / 設備生命週期管理 / 供應商管理",
      "", "### 4. 成本與永續",
      "營運成本優化(能源/清潔/保全)+ 永續改善建議 + 實施優先序。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a facility management consultant helping optimize space and operational efficiency.",
      "", `Facility status: ${v.facility}`, `Goal: ${v.goal}`,
      v.constraints ? `Constraints: ${v.constraints}` : "",
      "", "### 1. Facility Diagnostic — space utilization / flow efficiency / maintenance status / cost structure, main problems",
      "### 2. Space Efficiency — layout improvements / shared & flexible space / utilization boost. ```chart bar chart of utilization or improvement potential by area.",
      "### 3. Maintenance Plan — preventive maintenance schedule / equipment lifecycle management / vendor management",
      "### 4. Cost & Sustainability — operating cost optimization (energy/cleaning/security) + sustainability improvements + priority. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 294. 倉儲效率優化師 ──────────────────────────────────────────────────
  warehouseOptimizer: {
    inputs: [
      { key: "warehouse", label: "倉儲現況描述", labelEn: "Warehouse Status Description", type: "textarea", required: true, placeholder: "倉庫規模、SKU 數、出貨量、現有流程、痛點", placeholderEn: "Warehouse size, SKU count, shipping volume, current process, pain points" },
      { key: "goal", label: "優化目標", labelEn: "Optimization Goal", type: "text", required: true, placeholder: "例：提升揀貨效率、降低錯誤、增加空間利用", placeholderEn: "e.g. improve picking efficiency, reduce errors, increase space utilization" },
      { key: "constraints", label: "限制（選填）", labelEn: "Constraints (optional)", type: "text", required: false, placeholder: "預算、空間、人力、系統", placeholderEn: "Budget, space, labor, systems" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位倉儲營運顧問,協助提升倉儲效率與準確度。",
      "", `倉儲現況：${v.warehouse}`, `目標：${v.goal}`,
      v.constraints ? `限制：${v.constraints}` : "",
      "", "### 1. 空間配置優化",
      "儲位規劃(ABC 分類/動線)/ 空間利用率提升 / 佈局改善建議",
      "輸出 ```chart 長條圖顯示各區域利用率或改善潛力。",
      "", "### 2. 揀貨流程改善",
      "揀貨策略(批量/分區/波次)/ 動線優化 / 減少錯誤的機制",
      "用 ```mermaid flowchart 呈現優化後揀貨流程。",
      "", "### 3. 庫存管理建議",
      "庫存準確度 / 盤點策略 / 補貨觸發 / 呆滯品處理",
      "", "### 4. 科技與衡量",
      "科技導入建議(WMS/條碼/自動化)+ 效率 KPI + 90 天改善計畫。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a warehouse operations consultant helping improve efficiency and accuracy.",
      "", `Warehouse status: ${v.warehouse}`, `Goal: ${v.goal}`,
      v.constraints ? `Constraints: ${v.constraints}` : "",
      "", "### 1. Space Layout Optimization — slotting (ABC classification/flow) / utilization improvement / layout recommendations. ```chart bar chart of utilization or improvement potential by area.",
      "### 2. Picking Process Improvement — picking strategy (batch/zone/wave) / flow optimization / error reduction. ```mermaid flowchart of optimized picking.",
      "### 3. Inventory Management — accuracy / counting strategy / replenishment triggers / dead stock handling",
      "### 4. Tech & Measurement — tech adoption (WMS/barcode/automation) + efficiency KPIs + 90-day plan. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 304. 廠商績效KPI設計師 ───────────────────────────────────────────────
  vendorKpiDesigner: {
    inputs: [
      { key: "vendor", label: "供應商 / 採購描述", labelEn: "Vendor / Procurement Description", type: "textarea", required: true, placeholder: "供應商類型、提供品項/服務、合約規模、合作目標", placeholderEn: "Vendor type, items/services, contract scale, partnership goals" },
      { key: "priority", label: "管理重點", labelEn: "Management Priority", type: "text", required: true, placeholder: "例：品質、交期、成本、服務、創新", placeholderEn: "e.g. quality, delivery, cost, service, innovation" },
      { key: "issue", label: "現有問題（選填）", labelEn: "Current Issues (optional)", type: "text", required: false, placeholder: "目前供應商管理的痛點", placeholderEn: "Current vendor management pain points" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位供應商績效管理顧問,設計能驅動廠商表現的 KPI 體系。",
      "", `供應商/採購：${v.vendor}`, `管理重點：${v.priority}`,
      v.issue ? `現有問題：${v.issue}` : "",
      "", "### 1. 管理目標設定",
      "依管理重點設定供應商管理目標(SMART)+ 與業務目標的連結",
      "", "### 2. KPI 框架設計",
      "依維度(品質/交期/成本/服務/合規)設計 KPI,用表格：KPI/定義/計算/目標值/權重",
      "輸出 ```chart 長條圖顯示各維度權重。",
      "", "### 3. 績效回顧機制",
      "定期回顧節律 / 評分卡 / 供應商分級 / 獎懲機制",
      "", "### 4. 改善與治理",
      "績效不佳的改善流程 / 升級機制 / 供應商發展計畫。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a vendor performance management consultant designing KPI systems that drive supplier performance.",
      "", `Vendor/procurement: ${v.vendor}`, `Management priority: ${v.priority}`,
      v.issue ? `Current issues: ${v.issue}` : "",
      "", "### 1. Goal Setting — SMART vendor management goals per priority + link to business goals",
      "### 2. KPI Framework — KPIs by dimension (quality/delivery/cost/service/compliance), table: KPI/definition/calculation/target/weight. ```chart bar chart of weights.",
      "### 3. Performance Review — review cadence / scorecard / vendor tiering / reward-penalty mechanism",
      "### 4. Improvement & Governance — underperformance improvement process / escalation / vendor development plan. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 314. 品質管理系統師 ──────────────────────────────────────────────────
  qualityManagementSystem: {
    inputs: [
      { key: "business", label: "業務描述", labelEn: "Business Description", type: "textarea", required: true, placeholder: "行業、產品/服務、規模、現有品質現況", placeholderEn: "Industry, product/service, scale, current quality state" },
      { key: "goal", label: "品質目標", labelEn: "Quality Goal", type: "text", required: true, placeholder: "例：ISO 認證、降低不良率、流程標準化", placeholderEn: "e.g. ISO certification, reduce defect rate, process standardization" },
      { key: "standard", label: "目標標準（選填）", labelEn: "Target Standard (optional)", type: "text", required: false, placeholder: "例：ISO 9001、行業特定標準", placeholderEn: "e.g. ISO 9001, industry-specific standard" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位品質管理顧問,協助企業建立可持續改善的品質系統。",
      "", `業務：${v.business}`, `品質目標：${v.goal}`,
      v.standard ? `目標標準：${v.standard}` : "",
      "", "### 1. 品質系統設計",
      "品質政策與目標 / 流程文件架構 / 品質職責 / 與目標標準的對照",
      "", "### 2. 流程標準化",
      "關鍵流程的標準化建議 / SOP 清單 / 品質控制點設計",
      "用 ```mermaid flowchart 呈現品質管理流程(PDCA)。",
      "", "### 3. 持續改善機制",
      "稽核機制 / 矯正與預防措施(CAPA)/ 品質指標與監控",
      "輸出 ```chart 長條圖顯示建議追蹤的品質 KPI。",
      "", "### 4. 導入路線圖",
      v.standard ? `針對 ${v.standard} 的認證準備步驟與時程` : "品質系統建置的階段化路線圖",
      "。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a quality management consultant helping build a continuously improving quality system.",
      "", `Business: ${v.business}`, `Quality goal: ${v.goal}`,
      v.standard ? `Target standard: ${v.standard}` : "",
      "", "### 1. Quality System Design — quality policy and objectives / process document architecture / quality responsibilities / mapping to target standard",
      "### 2. Process Standardization — standardization of key processes / SOP list / quality control points. ```mermaid flowchart of quality management (PDCA).",
      "### 3. Continuous Improvement — audit mechanism / corrective and preventive actions (CAPA) / quality metrics and monitoring. ```chart bar chart of recommended quality KPIs.",
      v.standard ? `### 4. Implementation Roadmap — ${v.standard} certification prep steps and timeline` : "### 4. Implementation Roadmap — phased quality system build roadmap",
      ". Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 332. 績效檢討會議設計師 ──────────────────────────────────────────────
  kpiReviewMeeting: {
    inputs: [
      { key: "goals", label: "業務目標 / KPI", labelEn: "Business Goals / KPIs", type: "textarea", required: true, placeholder: "要檢討的目標、KPI、現有數據", placeholderEn: "Goals to review, KPIs, current data" },
      { key: "team", label: "團隊 / 與會者", labelEn: "Team / Attendees", type: "text", required: true, placeholder: "參與部門、層級、會議頻率", placeholderEn: "Departments, levels, meeting frequency" },
      { key: "issue", label: "現有問題（選填）", labelEn: "Current Issues (optional)", type: "text", required: false, placeholder: "例：會議冗長、無結論、不追蹤", placeholderEn: "e.g. long meetings, no conclusions, no follow-up" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位營運會議設計顧問,設計高效、能驅動行動的 KPI 檢討會議。",
      "", `業務目標/KPI：${v.goals}`, `團隊/與會者：${v.team}`,
      v.issue ? `現有問題：${v.issue}` : "",
      "", "### 1. 會議框架",
      "KPI 檢討會議議程(回顧→分析→決策→行動)+ 時間分配 + 各段產出",
      "", "### 2. 數據呈現",
      "該追蹤的核心 KPI + 儀表板呈現建議(紅黃綠)+ 異常聚焦原則",
      "", "### 3. 分析與決策",
      "落後 KPI 的根因分析框架 / 決策引導問題 / 避免究責文化的引導",
      "", "### 4. 行動追蹤系統",
      "閉環行動追蹤(行動/負責人/期限/下次檢視)+ 會議成效衡量。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are an operations meeting design consultant designing efficient, action-driving KPI review meetings.",
      "", `Business goals/KPIs: ${v.goals}`, `Team/attendees: ${v.team}`,
      v.issue ? `Current issues: ${v.issue}` : "",
      "", "### 1. Meeting Framework — KPI review agenda (review→analyze→decide→act) + time allocation + output per segment",
      "### 2. Data Presentation — core KPIs to track + dashboard presentation (red-yellow-green) + exception focus principle",
      "### 3. Analysis & Decision — root cause framework for lagging KPIs / decision-guiding questions / blame-free facilitation",
      "### 4. Action Tracking System — closed-loop tracking (action/owner/deadline/next review) + meeting effectiveness measurement. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 342. 外包招標書生成師 ────────────────────────────────────────────────
  outsourcingRFP: {
    inputs: [
      { key: "needs", label: "採購需求", labelEn: "Procurement Needs", type: "textarea", required: true, placeholder: "要外包的項目、範圍、品質要求、預算、時程", placeholderEn: "Item to outsource, scope, quality requirements, budget, timeline" },
      { key: "type", label: "外包類型", labelEn: "Outsourcing Type", type: "text", required: true, placeholder: "例：IT 開發、客服、製造、行銷、物流", placeholderEn: "e.g. IT dev, customer service, manufacturing, marketing, logistics" },
      { key: "priority", label: "評選重點（選填）", labelEn: "Selection Priority (optional)", type: "text", required: false, placeholder: "例：成本/品質/經驗/速度", placeholderEn: "e.g. cost/quality/experience/speed" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位採購招標顧問,撰寫專業的招標書(RFP)並設計評選機制。",
      "", `採購需求：${v.needs}`, `外包類型：${v.type}`,
      v.priority ? `評選重點：${v.priority}` : "",
      "", "### 1. 招標書設計",
      "RFP 完整架構(背景/需求規格/範圍/交付/時程/預算/投標須知)+ 各章節要點",
      "", "### 2. 評選標準制定",
      "評選維度與權重(技術/經驗/成本/服務/風險)+ 評分標準,用表格呈現",
      "輸出 ```chart 圓餅圖顯示評選權重分配。",
      "", "### 3. 供應商評估框架",
      "供應商資格門檻 / 評估流程 / 必問問題 / 參考查核重點",
      "", "### 4. 招標執行",
      "招標時程 + 廠商說明會建議 + 議約與決標流程。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a procurement RFP consultant writing professional RFPs and designing selection mechanisms.",
      "", `Procurement needs: ${v.needs}`, `Outsourcing type: ${v.type}`,
      v.priority ? `Selection priority: ${v.priority}` : "",
      "", "### 1. RFP Design — full RFP structure (background/requirements spec/scope/deliverables/timeline/budget/bidding instructions) + key points",
      "### 2. Evaluation Criteria — dimensions and weights (technical/experience/cost/service/risk) + scoring, table. ```chart pie chart of weights.",
      "### 3. Vendor Assessment Framework — qualification thresholds / evaluation process / must-ask questions / reference check focus",
      "### 4. RFP Execution — timeline + bidder briefing + negotiation and award process. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  procurementStrategy: {
    inputs: [
      field("needs", ["採購需求", "Procurement Needs"], { required: true, placeholder: ["採購類別、規模、現有供應商、痛點", "Procurement category, scale, current suppliers, pain points"] }),
      field("goal", ["策略目標", "Strategy Goal"], { type: "text", required: true, placeholder: ["例：降成本、降風險、提升品質", "e.g. cut cost, reduce risk, improve quality"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位採購策略設計顧問。",
        "", `採購需求：${v.needs}`, `策略目標：${v.goal}`,
        "", "### 1. 需求分析",
        "採購支出分類(品類分析)+ 需求優先序 + 集中度風險",
        "輸出 ```chart 圓餅圖顯示採購支出分布。",
        "", "### 2. 市場與供應商策略",
        "供應市場分析 + 採購槓桿(集中/競標/長約)+ 供應商組合策略",
        "", "### 3. 成本優化計畫",
        "降本機會(談判/規格優化/替代/整合)+ 預估節省",
        "", "### 4. 執行與治理",
        "採購流程改善 + 供應商管理機制 + KPI。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a procurement strategy design consultant.",
        "", `Procurement needs: ${v.needs}`, `Strategy goal: ${v.goal}`,
        "", "### 1. Needs Analysis — spend categorization (category analysis) + needs priority + concentration risk. ```chart pie chart of spend distribution.",
        "### 2. Market & Supplier Strategy — supply market analysis + procurement levers (consolidation/bidding/long-term) + supplier portfolio strategy",
        "### 3. Cost Optimization — savings opportunities (negotiation/spec optimization/substitution/consolidation) + estimated savings",
        "### 4. Execution & Governance — procurement process improvement + supplier management + KPIs. Respond in English.",
      ],
    }),
  },
  demandForecaster: {
    inputs: [
      field("data", ["歷史銷售資料", "Historical Sales Data"], { required: true, placeholder: ["銷量歷史、季節性、趨勢、品項", "Sales history, seasonality, trends, SKUs"] }),
      field("context", ["業務背景", "Business Context"], { type: "text", required: true, placeholder: ["行業、通路、前置時間", "Industry, channels, lead time"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位需求預測規劃顧問。",
        "", `歷史銷售資料：${v.data}`, `業務背景：${v.context}`,
        "", "### 1. 需求預測模型",
        "適合的預測方法(趨勢/季節/移動平均)+ 預測結果(保守/基本/樂觀)",
        "輸出 ```chart 折線圖顯示需求預測。",
        "", "### 2. 預測假設與風險",
        "關鍵假設 + 影響準確度的因素 + 不確定性",
        "", "### 3. 補貨策略",
        "安全庫存 + 再訂購點 + 各品項分類的補貨策略",
        "", "### 4. 監控與優化",
        "預測準確度追蹤 + 模型優化機制。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a demand forecasting planning advisor.",
        "", `Historical sales data: ${v.data}`, `Business context: ${v.context}`,
        "", "### 1. Demand Forecast Model — suitable method (trend/seasonal/moving average) + forecast (conservative/base/optimistic). ```chart line chart of demand forecast.",
        "### 2. Assumptions & Risks — key assumptions + factors affecting accuracy + uncertainty",
        "### 3. Replenishment Strategy — safety stock + reorder points + replenishment strategy per SKU class",
        "### 4. Monitoring & Optimization — forecast accuracy tracking + model improvement. Respond in English.",
      ],
    }),
  },
  supplyChainMapping: {
    inputs: [
      field("chain", ["供應鏈描述", "Supply Chain Description"], { required: true, placeholder: ["供應商、生產、物流、關鍵物料", "Suppliers, production, logistics, critical materials"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：找風險、提升韌性、降成本", "e.g. find risks, improve resilience, cut cost"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位供應鏈地圖顧問。",
        "", `供應鏈：${v.chain}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 供應鏈節點視覺化",
        "用 ```mermaid flowchart 呈現供應鏈節點與流向(供應商→生產→倉儲→配送)",
        "", "### 2. 依賴識別",
        "關鍵依賴點(單一供應商/瓶頸/長前置)+ 集中度風險",
        "輸出 ```chart 長條圖顯示各節點風險。",
        "", "### 3. 韌性評估",
        "各節點的脆弱度 + 中斷影響評估",
        "", "### 4. 韌性提升建議",
        "多元化/備援/可視性的具體行動。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a supply chain mapping advisor.",
        "", `Supply chain: ${v.chain}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Node Visualization — ```mermaid flowchart of supply chain nodes and flows (suppliers→production→warehouse→distribution)",
        "### 2. Dependency Identification — critical dependencies (single supplier/bottleneck/long lead time) + concentration risk. ```chart bar chart of node risk.",
        "### 3. Resilience Assessment — vulnerability per node + disruption impact",
        "### 4. Resilience Recommendations — concrete diversification/redundancy/visibility actions. Respond in English.",
      ],
    }),
  },
  contractorManagement: {
    inputs: [
      field("needs", ["採購 / 承包需求", "Procurement / Contracting Needs"], { required: true, placeholder: ["承包項目、規模、現有承包商、痛點", "Contracted work, scale, current contractors, pain points"] }),
      field("priority", ["重點（選填）", "Priority (optional)"], { type: "text", placeholder: ["例：品質、成本、合規、交期", "e.g. quality, cost, compliance, timeline"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位承包商管理顧問。",
        "", `承包需求：${v.needs}`,
        v.priority && `重點：${v.priority}`,
        "", "### 1. 承包商評選框架",
        "評選維度與權重(資格/能力/成本/合規/風險),用表格呈現",
        "", "### 2. 合約管理",
        "關鍵合約條款(範圍/SLA/罰則/驗收/終止)+ 風險控管",
        "", "### 3. 績效追蹤計畫",
        "承包商 KPI + 驗收機制 + 定期檢視",
        "", "### 4. 關係與治理",
        "承包商分級 + 改善機制 + 合規(勞務/工安)確認。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a contractor management advisor.",
        "", `Contracting needs: ${v.needs}`,
        v.priority && `Priority: ${v.priority}`,
        "", "### 1. Contractor Selection Framework — evaluation dimensions and weights (qualification/capability/cost/compliance/risk), table",
        "### 2. Contract Management — key clauses (scope/SLA/penalties/acceptance/termination) + risk control",
        "### 3. Performance Tracking — contractor KPIs + acceptance mechanism + periodic review",
        "### 4. Relationship & Governance — contractor tiering + improvement mechanism + compliance (labor/safety). Respond in English.",
      ],
    }),
  },
  qualityAssurancePlanner: {
    inputs: [
      field("goals", ["品質目標", "Quality Goals"], { required: true, placeholder: ["產品/服務、品質目標、現有 QA、痛點", "Product/service, quality goals, current QA, pain points"] }),
      field("context", ["背景（選填）", "Context (optional)"], { type: "text", placeholder: ["行業、規模、標準", "Industry, scale, standards"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位品質保證(QA)規劃顧問。",
        "", `品質目標：${v.goals}`,
        v.context && `背景：${v.context}`,
        "", "### 1. QA 框架設計",
        "品質保證體系(預防/檢測/改善)+ 品質職責 + 品質標準",
        "", "### 2. 稽核機制",
        "稽核類型與頻率 + 檢核清單 + 不符合處理流程",
        "", "### 3. 缺陷預防",
        "根因分析(5 Why/魚骨圖)+ 預防措施 + 防呆設計",
        "", "### 4. 改善計畫",
        "持續改善機制(PDCA)+ 品質 KPI + 導入路線圖。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a Quality Assurance (QA) planning advisor.",
        "", `Quality goals: ${v.goals}`,
        v.context && `Context: ${v.context}`,
        "", "### 1. QA Framework — quality assurance system (prevent/detect/improve) + quality responsibilities + standards",
        "### 2. Audit Mechanism — audit types and frequency + checklists + non-conformance handling",
        "### 3. Defect Prevention — root cause analysis (5 Whys/fishbone) + preventive measures + mistake-proofing",
        "### 4. Improvement Plan — continuous improvement (PDCA) + quality KPIs + adoption roadmap. Respond in English.",
      ],
    }),
  },
  leanProcessAdvisor: {
    inputs: [
      field("process", ["流程描述", "Process Description"], { required: true, placeholder: ["流程步驟、參與者、耗時、痛點", "Process steps, participants, cycle time, pain points"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：降成本、提速、減錯", "e.g. cut cost, speed up, reduce errors"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位精實流程改善顧問。",
        "", `流程：${v.process}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 浪費識別診斷",
        "用 ```mermaid flowchart 呈現現有流程 + 標示七大浪費(等待/庫存/重工/多餘動作等)",
        "", "### 2. 價值流分析",
        "各步驟價值分類(增值/不增值但必要/純浪費)+ 流程效率",
        "輸出 ```chart 長條圖顯示各步驟耗時。",
        "", "### 3. 精實改善計畫",
        "消除浪費的具體行動 + 流程重設計",
        "", "### 4. 持續優化機制",
        "Kaizen / 標準化 / 視覺化管理 + 衡量指標。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a lean process improvement advisor.",
        "", `Process: ${v.process}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Waste Identification — ```mermaid flowchart of current process + mark the 7 wastes (waiting/inventory/rework/excess motion etc.)",
        "### 2. Value Stream Analysis — value classification per step (value-add/non-value-add necessary/pure waste) + process efficiency. ```chart bar chart of step time.",
        "### 3. Lean Improvement Plan — concrete waste-elimination actions + process redesign",
        "### 4. Continuous Optimization — Kaizen / standardization / visual management + metrics. Respond in English.",
      ],
    }),
  },
  qualityControlAdvisor: {
    inputs: [
      field("process", ["生產流程描述", "Production Process Description"], { required: true, placeholder: ["產品、生產流程、現有品管、品質問題", "Product, production process, current QC, quality issues"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：降不良率、穩定品質", "e.g. reduce defect rate, stabilize quality"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位品質管制(QC)顧問。",
        "", `生產流程：${v.process}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 品質指標設計",
        "關鍵品質指標(不良率/一次良率/客訴率)+ 管制點設計",
        "輸出 ```chart 長條圖顯示各環節不良分布。",
        "", "### 2. 缺陷預防機制",
        "進料/製程/出貨的品管設計 + SPC 統計製程管制 + 防呆",
        "", "### 3. 根因與矯正",
        "缺陷根因分析 + 矯正預防措施(CAPA)",
        "", "### 4. 持續改善計畫",
        "品質改善行動 + 監控機制 + 標準化。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a Quality Control (QC) advisor.",
        "", `Production process: ${v.process}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Quality Metric Design — key metrics (defect rate/first-pass yield/complaint rate) + control point design. ```chart bar chart of defect distribution per stage.",
        "### 2. Defect Prevention — QC design for incoming/in-process/outgoing + SPC statistical process control + mistake-proofing",
        "### 3. Root Cause & Correction — defect root cause analysis + corrective and preventive actions (CAPA)",
        "### 4. Continuous Improvement — quality improvement actions + monitoring + standardization. Respond in English.",
      ],
    }),
  },
  maintenancePlanner: {
    inputs: [
      field("equipment", ["設備狀態描述", "Equipment Status Description"], { required: true, placeholder: ["設備類型、數量、使用狀況、故障史", "Equipment type, count, usage, failure history"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：降故障、延壽、降成本", "e.g. reduce failures, extend life, cut cost"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位設備維護規劃顧問。",
        "", `設備狀態：${v.equipment}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 設備狀態診斷",
        "設備健康評估 + 故障模式分析 + 關鍵設備識別",
        "", "### 2. 預防性維護計畫",
        "維護策略(預防/預測/事後)選擇 + 維護排程,用 ```mermaid gantt 呈現",
        "", "### 3. 維護成本優化",
        "維護成本 vs 停機成本平衡 + 備品管理 + 外包判斷",
        "", "### 4. 監控與改善",
        "設備 KPI(可用率/MTBF/MTTR)+ 持續改善。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a maintenance planning advisor.",
        "", `Equipment status: ${v.equipment}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Equipment Diagnostic — equipment health assessment + failure mode analysis + critical equipment identification",
        "### 2. Preventive Maintenance Plan — strategy (preventive/predictive/reactive) selection + maintenance schedule, ```mermaid gantt",
        "### 3. Cost Optimization — maintenance cost vs downtime cost balance + spare parts management + outsource judgment",
        "### 4. Monitoring & Improvement — equipment KPIs (availability/MTBF/MTTR) + continuous improvement. Respond in English.",
      ],
    }),
  },
  operationsKpiDesigner: {
    inputs: [
      field("goals", ["營運目標", "Operational Goals"], { required: true, placeholder: ["營運目標、流程、現有衡量、痛點", "Operational goals, processes, current measures, pain points"] }),
      field("context", ["背景（選填）", "Context (optional)"], { type: "text", placeholder: ["行業、團隊、規模", "Industry, team, scale"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位營運 KPI 框架設計顧問。",
        "", `營運目標：${v.goals}`,
        v.context && `背景：${v.context}`,
        "", "### 1. KPI 體系設計",
        "依維度(效率/品質/成本/速度/可靠)設計營運 KPI,用表格:KPI/定義/計算/目標/頻率",
        "", "### 2. 指標串聯",
        "營運目標 → 流程 KPI → 個人指標的串聯",
        "", "### 3. 儀表板設計",
        "營運儀表板分層 + 視覺化(紅黃綠)+ 異常聚焦",
        "", "### 4. 績效追蹤機制",
        "檢視節律 + 行動追蹤 + 持續改善。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are an operations KPI framework design advisor.",
        "", `Operational goals: ${v.goals}`,
        v.context && `Context: ${v.context}`,
        "", "### 1. KPI System — operational KPIs by dimension (efficiency/quality/cost/speed/reliability), table: KPI/definition/calculation/target/frequency",
        "### 2. Cascading — operational goals → process KPIs → individual metrics",
        "### 3. Dashboard Design — operations dashboard layers + visualization (red-yellow-green) + exception focus",
        "### 4. Performance Tracking — review cadence + action tracking + continuous improvement. Respond in English.",
      ],
    }),
  },
  fleetManagementAdvisor: {
    inputs: [
      field("fleet", ["車隊描述", "Fleet Description"], { required: true, placeholder: ["車隊規模、車種、用途、現有成本、痛點", "Fleet size, vehicle types, usage, current cost, pain points"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：降成本、提升效率、減碳", "e.g. cut cost, improve efficiency, reduce emissions"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位車隊管理優化顧問。",
        "", `車隊：${v.fleet}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 車隊成本診斷",
        "成本結構拆解(燃油/維護/折舊/保險)+ 降本機會",
        "輸出 ```chart 圓餅圖顯示車隊成本結構。",
        "", "### 2. 路線效率優化",
        "路線規劃 / 派遣優化 / 閒置率降低",
        "", "### 3. 維護排程策略",
        "預防性維護排程 + 車輛生命週期管理 + 汰換決策",
        "", "### 4. 科技與衡量",
        "車隊管理系統/GPS/油耗監控建議 + 效率 KPI。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a fleet management optimization advisor.",
        "", `Fleet: ${v.fleet}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Fleet Cost Diagnostic — cost breakdown (fuel/maintenance/depreciation/insurance) + reduction opportunities. ```chart pie chart of cost structure.",
        "### 2. Route Efficiency — route planning / dispatch optimization / idle rate reduction",
        "### 3. Maintenance Scheduling — preventive maintenance schedule + vehicle lifecycle management + replacement decisions",
        "### 4. Tech & Measurement — fleet management system/GPS/fuel monitoring + efficiency KPIs. Respond in English.",
      ],
    }),
  },
  kaizenAdvisor: {
    inputs: [
      field("process", ["流程描述", "Process Description"], { required: true, placeholder: ["流程、團隊、現有問題、改善目標", "Process, team, current problems, improvement goals"] }),
      field("context", ["背景（選填）", "Context (optional)"], { type: "text", placeholder: ["行業、規模、文化", "Industry, scale, culture"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位持續改善(Kaizen)顧問。",
        "", `流程：${v.process}`,
        v.context && `背景：${v.context}`,
        "", "### 1. 改善機會識別",
        "用 ```mermaid flowchart 呈現現有流程 + 浪費與改善點",
        "", "### 2. 改善優先排序",
        "依影響×易行排序改善機會(快速贏優先),用表格呈現",
        "", "### 3. 精實優化循環",
        "Kaizen 循環設計(發現→分析→改善→標準化)+ 改善提案機制",
        "", "### 4. 文化與持續",
        "全員改善文化建立 + 改善追蹤 + 衡量指標。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a Kaizen continuous improvement advisor.",
        "", `Process: ${v.process}`,
        v.context && `Context: ${v.context}`,
        "", "### 1. Improvement Opportunity — ```mermaid flowchart of current process + waste and improvement points",
        "### 2. Improvement Prioritization — rank by impact × ease (quick wins first), table",
        "### 3. Lean Improvement Cycle — Kaizen cycle (find→analyze→improve→standardize) + improvement suggestion mechanism",
        "### 4. Culture & Continuity — org-wide improvement culture + improvement tracking + metrics. Respond in English.",
      ],
    }),
  },
  vendorNegotiationCoach: {
    inputs: [
      field("contract", ["合約條款", "Contract Terms"], { required: true, placeholder: ["採購項目、供應商、現有條款、目標", "Procurement item, vendor, current terms, goals"] }),
      field("leverage", ["籌碼（選填）", "Leverage (optional)"], { type: "text", placeholder: ["採購量、替代供應商、轉換成本", "Volume, alternatives, switching cost"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位供應商談判教練。",
        "", `合約條款：${v.contract}`,
        v.leverage && `籌碼：${v.leverage}`,
        "", "### 1. 談判力分析",
        "雙方力量平衡 + 我方籌碼 + 供應商壓力點 + BATNA",
        "", "### 2. 談判策略框架",
        "開場錨定 + 讓步階梯 + 適用戰術",
        "", "### 3. 最佳議價路徑",
        "關鍵條款的議價優先序 + 換取條件,用表格呈現",
        "", "### 4. 談判腳本",
        "開場白 + 情境應對 + 簽約前確認。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a vendor negotiation coach.",
        "", `Contract terms: ${v.contract}`,
        v.leverage && `Leverage: ${v.leverage}`,
        "", "### 1. Negotiation Power Analysis — power balance + our leverage + vendor pressure points + BATNA",
        "### 2. Negotiation Strategy Framework — opening anchor + concession ladder + applicable tactics",
        "### 3. Optimal Bargaining Path — bargaining priority for key clauses + trade-offs, table",
        "### 4. Negotiation Script — opening + scenario responses + pre-signing confirmation. Respond in English.",
      ],
    }),
  },
  incidentManagementAdvisor: {
    inputs: [
      field("process", ["業務流程描述", "Business Process Description"], { required: true, placeholder: ["系統/服務、事故類型、現有應變、團隊", "System/service, incident types, current response, team"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：縮短復原、減少重複事故", "e.g. faster recovery, reduce recurring incidents"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位事故管理規劃顧問。",
        "", `業務流程：${v.process}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 事故回應流程",
        "事故分級 + 回應流程(偵測→分流→處理→復原→結案),用 ```mermaid flowchart 呈現",
        "", "### 2. RCA 機制",
        "根因分析方法(5 Why/時間軸)+ 無責文化 + 事後檢討(postmortem)",
        "", "### 3. 角色與升級",
        "事故指揮 / 角色職責 / 升級路徑 / 溝通機制",
        "", "### 4. 改善計畫",
        "事故指標(MTTD/MTTR)+ 預防重複事故 + 持續改善。全程使用繁體中文(技術術語用英文)。",
      ],
      en: (v) => [
        "You are an incident management process advisor.",
        "", `Business process: ${v.process}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Incident Response Workflow — incident severity + response flow (detect→triage→handle→recover→close), ```mermaid flowchart",
        "### 2. RCA Mechanism — root cause analysis methods (5 Whys/timeline) + blameless culture + postmortem",
        "### 3. Roles & Escalation — incident command / role responsibilities / escalation path / communication",
        "### 4. Improvement Plan — incident metrics (MTTD/MTTR) + preventing recurrence + continuous improvement. Respond in English.",
      ],
    }),
  },
  continuousImprovementAdvisor: {
    inputs: [
      field("process", ["流程描述", "Process Description"], { required: true, placeholder: ["流程、團隊、現有問題、改善目標", "Process, team, current problems, improvement goals"] }),
      field("context", ["背景（選填）", "Context (optional)"], { type: "text", placeholder: ["行業、規模", "Industry, scale"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位持續優化顧問,用 PDCA 建立持續改善循環。",
        "", `流程：${v.process}`,
        v.context && `背景：${v.context}`,
        "", "### 1. 改善機會識別",
        "流程現況診斷 + 改善機會盤點 + 優先排序",
        "輸出 ```chart 長條圖顯示各改善機會的影響。",
        "", "### 2. PDCA 循環設計",
        "Plan-Do-Check-Act 循環設計 + 各階段重點 + 節律",
        "", "### 3. 改善行動",
        "TOP 3 改善的具體行動 + 負責人 + 衡量",
        "", "### 4. 持續機制",
        "改善文化 + 標準化 + 追蹤儀表板。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a continuous improvement advisor building PDCA improvement cycles.",
        "", `Process: ${v.process}`,
        v.context && `Context: ${v.context}`,
        "", "### 1. Improvement Opportunity — process diagnostic + opportunity inventory + prioritization. ```chart bar chart of impact.",
        "### 2. PDCA Cycle Design — Plan-Do-Check-Act cycle + focus per phase + cadence",
        "### 3. Improvement Actions — concrete actions for top 3 + owner + measurement",
        "### 4. Continuity Mechanism — improvement culture + standardization + tracking dashboard. Respond in English.",
      ],
    }),
  },
  sopReviewer: {
    inputs: [
      field("sop", ["現有 SOP 描述", "Existing SOP Description"], { required: true, placeholder: ["SOP 內容/範圍、最後更新、痛點", "SOP content/scope, last updated, pain points"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：更新過時、提升合規、簡化", "e.g. update outdated, improve compliance, simplify"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位 SOP 審查更新顧問。",
        "", `現有 SOP：${v.sop}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. SOP 健康度評估",
        "評估(清晰度/完整度/時效/可執行/合規),指出問題",
        "輸出 ```chart 長條圖顯示各維度評分。",
        "", "### 2. 過時流程識別",
        "已過時/與現況脫節/缺漏的環節",
        "", "### 3. 更新優先計畫",
        "依風險與影響排序的更新行動",
        "", "### 4. 維護機制",
        "SOP 更新頻率 + 版本控制 + 審查節律。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are an SOP review and update advisor.",
        "", `Existing SOP: ${v.sop}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. SOP Health Assessment — assess (clarity/completeness/currency/executability/compliance), identify problems. ```chart bar chart.",
        "### 2. Outdated Process Identification — outdated/disconnected/missing steps",
        "### 3. Update Priority Plan — update actions ranked by risk and impact",
        "### 4. Maintenance Mechanism — SOP update frequency + version control + review cadence. Respond in English.",
      ],
    }),
  },
  inventoryVisibilityAdvisor: {
    inputs: [
      field("inventory", ["庫存描述", "Inventory Description"], { required: true, placeholder: ["庫存規模、據點、系統、可見性痛點", "Inventory scale, locations, systems, visibility pain points"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：即時可見、跨點整合、降斷貨", "e.g. real-time visibility, cross-site integration, reduce stockouts"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位庫存可見性策略顧問。",
        "", `庫存：${v.inventory}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 數據整合策略",
        "各據點/通路庫存數據的整合方式 + 資料品質要求",
        "", "### 2. 即時可視化架構",
        "可視化架構建議,用 ```mermaid flowchart 呈現數據流",
        "", "### 3. 供應鏈透明度",
        "從供應商到終端的透明度提升 + 預警機制",
        "", "### 4. 導入計畫",
        "可見性工具/系統建議 + 導入路線圖 + KPI。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are an inventory visibility strategy advisor.",
        "", `Inventory: ${v.inventory}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Data Integration Strategy — integration of inventory data across sites/channels + data quality requirements",
        "### 2. Real-Time Visibility Architecture — visibility architecture, ```mermaid flowchart of data flow",
        "### 3. Supply Chain Transparency — transparency from supplier to endpoint + alert mechanism",
        "### 4. Implementation Plan — visibility tools/systems + adoption roadmap + KPIs. Respond in English.",
      ],
    }),
  },
  procurementAutomation: {
    inputs: [
      field("process", ["採購流程描述", "Procurement Process Description"], { required: true, placeholder: ["採購流程、量、現有工具、痛點", "Procurement process, volume, current tools, pain points"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：降人工、加速、降錯誤", "e.g. reduce manual work, speed up, reduce errors"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位採購自動化顧問。",
        "", `採購流程：${v.process}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 自動化機會識別",
        "採購各環節(請購/詢價/比價/下單/驗收/付款)的自動化機會",
        "用 ```mermaid flowchart 呈現自動化後流程。",
        "", "### 2. 工具選型評估",
        "依需求推薦工具類型(e-procurement/RPA/AI)+ 選型考量",
        "", "### 3. ROI 評估",
        "自動化的人時節省與效益估算",
        "輸出 ```chart 長條圖顯示各環節自動化效益。",
        "", "### 4. 導入路線圖",
        "用 ```mermaid gantt 規劃分階段導入。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a procurement automation advisor.",
        "", `Procurement process: ${v.process}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Automation Opportunity — automation opportunities across stages (requisition/RFQ/comparison/PO/receipt/payment). ```mermaid flowchart of automated process.",
        "### 2. Tool Selection — recommended tool types (e-procurement/RPA/AI) + selection criteria",
        "### 3. ROI Assessment — labor-hour savings and benefit estimate. ```chart bar chart of automation benefit per stage.",
        "### 4. Implementation Roadmap — ```mermaid gantt of phased adoption. Respond in English.",
      ],
    }),
  },
  operationsDigitalizationAdvisor: {
    inputs: [
      field("operations", ["營運描述", "Operations Description"], { required: true, placeholder: ["營運流程、現有數位化程度、痛點", "Operations processes, current digital maturity, pain points"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：流程數位化、即時數據、降成本", "e.g. digitalize processes, real-time data, cut cost"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位營運數位化顧問。",
        "", `營運：${v.operations}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 數位化機會評估",
        "營運各流程的數位化成熟度 + 最該優先的環節",
        "輸出 ```chart 長條圖顯示各流程數位化成熟度。",
        "", "### 2. 工具導入路線圖",
        "依需求推薦工具 + 用 ```mermaid gantt 規劃分階段導入",
        "", "### 3. 效率提升計畫",
        "數位化帶來的效率提升 + 自動化機會",
        "", "### 4. 變革與衡量",
        "員工採用 + 變革管理 + 數位化成效指標。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are an operations digitalization advisor.",
        "", `Operations: ${v.operations}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Digitalization Opportunity — digital maturity per operations process + priority areas. ```chart bar chart of maturity.",
        "### 2. Tool Adoption Roadmap — recommended tools + ```mermaid gantt of phased adoption",
        "### 3. Efficiency Improvement — efficiency gains from digitalization + automation opportunities",
        "### 4. Change & Measurement — employee adoption + change management + digitalization metrics. Respond in English.",
      ],
    }),
  },
  thirdPartyRiskAdvisor: {
    inputs: [
      field("context", ["供應商 / 合作方描述", "Vendor / Partner Description"], { required: true, placeholder: ["供應商類型、服務、資料存取、依賴程度", "Vendor type, service, data access, dependency level"] }),
      field("concern", ["關注（選填）", "Concern (optional)"], { type: "text", placeholder: ["例：資安、合規、營運中斷", "e.g. security, compliance, operational disruption"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位第三方風險管理顧問。",
        "", `供應商/合作方：${v.context}`,
        v.concern && `關注：${v.concern}`,
        "", "### 1. 風險分級",
        "依資料存取/關鍵性/合規影響為供應商分級,用表格呈現",
        "輸出 ```chart 長條圖顯示各風險面向評分。",
        "", "### 2. 盡職調查",
        "各級別的盡職調查項目(資安/財務/合規/營運)",
        "", "### 3. 合約與監控",
        "合約應有的條款(SLA/資安/退場)+ 持續監控",
        "", "### 4. 應變計畫",
        "供應商失效的應變 + 退場/替代方案。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a third-party risk management advisor.",
        "", `Vendor/partner: ${v.context}`,
        v.concern && `Concern: ${v.concern}`,
        "", "### 1. Risk Tiering — tier vendors by data access/criticality/compliance impact, table. ```chart bar chart of risk dimension scores.",
        "### 2. Due Diligence — due diligence items per tier (security/financial/compliance/operational)",
        "### 3. Contract & Monitoring — clauses the contract should have (SLA/security/exit) + continuous monitoring",
        "### 4. Contingency Plan — vendor failure contingency + exit/alternative options. Respond in English.",
      ],
    }),
  },
  contractorOnboardingAdvisor: {
    inputs: [
      field("context", ["外包 / 約聘描述", "Contractor Description"], { required: true, placeholder: ["角色、人數、合約類型、存取需求、期間", "Role, count, contract type, access needs, duration"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：快速上手、合規、資安", "e.g. fast ramp-up, compliance, security"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位外包人員導入顧問。",
        "", `外包/約聘：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 導入流程設計",
        "從合約到上工的導入步驟,用 ```mermaid flowchart 呈現",
        "", "### 2. 存取與資安",
        "最小權限原則 + 存取核發 + 資料保護 + NDA",
        "", "### 3. 合規確認",
        "雇傭關係界定(避免誤判)+ 稅務/法規重點",
        "", "### 4. 退場機制",
        "合約結束的退場清單(權限回收/資產/交接)。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a contractor onboarding advisor.",
        "", `Contractor: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Onboarding Process — steps from contract to start, ```mermaid flowchart",
        "### 2. Access & Security — least-privilege principle + access provisioning + data protection + NDA",
        "### 3. Compliance Confirmation — employment classification (avoid misclassification) + tax/regulatory focus",
        "### 4. Offboarding Mechanism — end-of-contract offboarding checklist (access revocation/assets/handover). Respond in English.",
      ],
    }),
  },
  workplaceErgonomics: {
    inputs: [
      field("context", ["工作環境描述", "Workplace Description"], { required: true, placeholder: ["工作類型、現有設置、人數、痛點(如久坐)", "Work type, current setup, headcount, pain points (e.g. sitting)"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：減少傷害、提升舒適、遠端設置", "e.g. reduce injury, improve comfort, remote setup"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位職場人體工學顧問。",
        "", `工作環境：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 風險評估",
        "現有設置的人體工學風險(姿勢/重複/視覺/環境),用表格呈現",
        "", "### 2. 改善建議",
        "桌椅/螢幕/鍵鼠/照明的調整 + 低成本做法",
        "", "### 3. 行為與習慣",
        "微休息 / 伸展 / 姿勢輪換的習慣養成",
        "", "### 4. 落地計畫",
        "推行步驟 + 遠端工作者的居家設置指引。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a workplace ergonomics advisor.",
        "", `Workplace: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Risk Assessment — ergonomic risks of current setup (posture/repetition/visual/environment), table",
        "### 2. Improvement Recommendations — desk/chair/monitor/keyboard-mouse/lighting adjustments + low-cost approaches",
        "### 3. Behavior & Habits — micro-breaks / stretching / posture rotation habit-building",
        "### 4. Rollout Plan — rollout steps + home-setup guide for remote workers. Respond in English.",
      ],
    }),
  },
  erpSelectionAdvisor: {
    inputs: [
      field("context", ["業務需求描述", "Business Requirements Description"], { required: true, placeholder: ["公司規模、流程、現有系統、痛點、預算", "Company size, processes, current systems, pain points, budget"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：整合系統、自動化、可擴展", "e.g. integrate systems, automate, scalability"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位 ERP 系統選型顧問。",
        "", `業務需求：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 需求釐清",
        "核心需求/必要模組/整合需求盤點,用表格呈現",
        "", "### 2. 選型評估框架",
        "評估維度(功能/成本/擴展/在地化/廠商)與加權,用表格呈現",
        "輸出 ```chart 長條圖顯示候選方案評分。",
        "", "### 3. 導入路線圖",
        "分階段導入計畫,用 ```mermaid gantt 呈現時程",
        "", "### 4. 風險與變革",
        "導入風險 + 變革管理 + 資料遷移。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are an ERP system selection advisor.",
        "", `Business requirements: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Requirements Clarification — core needs/required modules/integration needs inventory, table",
        "### 2. Selection Framework — evaluation dimensions (function/cost/scalability/localization/vendor) and weighting, table. ```chart bar chart of candidate scores.",
        "### 3. Implementation Roadmap — phased rollout plan, ```mermaid gantt of timeline",
        "### 4. Risk & Change — implementation risks + change management + data migration. Respond in English.",
      ],
    }),
  },
  automationBusinessCase: {
    inputs: [
      field("process", ["流程描述", "Process Description"], { required: true, placeholder: ["流程、現有人力/時間、頻率、痛點", "Process, current effort/time, frequency, pain points"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：省工時、減錯誤、可擴展", "e.g. save hours, reduce errors, scalability"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位自動化商業可行性顧問。",
        "", `流程描述：${v.process}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 自動化 ROI 計算",
        "現有成本 vs 自動化後成本 + 節省估算,用表格呈現",
        "輸出 ```chart 長條圖比較自動化前後成本。",
        "", "### 2. 建置成本評估",
        "建置/工具/維護成本 + 隱性成本",
        "", "### 3. 投資回收計畫",
        "回收期(payback)計算 + 敏感度",
        "", "### 4. 決策建議",
        "可行性結論 + 優先序 + 風險。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are an automation business case advisor.",
        "", `Process: ${v.process}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Automation ROI Calculation — current cost vs post-automation cost + savings estimate, table. ```chart bar chart comparing cost before/after automation.",
        "### 2. Build Cost Assessment — build/tooling/maintenance cost + hidden costs",
        "### 3. Payback Plan — payback period calculation + sensitivity",
        "### 4. Decision Recommendation — feasibility conclusion + priority + risks. Respond in English.",
      ],
    }),
  },
  disasterRecoveryPlanner: {
    inputs: [
      field("context", ["系統描述", "System Description"], { required: true, placeholder: ["關鍵系統、資料、現有備援、容忍度", "Critical systems, data, current redundancy, tolerance"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：降低停機、合規、業務連續", "e.g. reduce downtime, compliance, business continuity"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位災難復原規劃師。",
        "", `系統描述：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. RTO/RPO 設計",
        "各關鍵系統的 RTO/RPO 目標與分級,用表格呈現",
        "", "### 2. 復原流程規範",
        "災難復原流程,用 ```mermaid flowchart 呈現 + 角色與職責",
        "", "### 3. 備援架構",
        "備份/異地/故障切換策略 + 成本取捨",
        "", "### 4. 演練計畫",
        "定期演練計畫 + 檢核 + 持續改善。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a disaster recovery planner.",
        "", `System: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. RTO/RPO Design — RTO/RPO targets and tiering per critical system, table",
        "### 2. Recovery Procedure — disaster recovery process, ```mermaid flowchart + roles and responsibilities",
        "### 3. Redundancy Architecture — backup/off-site/failover strategy + cost trade-offs",
        "### 4. Drill Plan — regular drill plan + review + continuous improvement. Respond in English.",
      ],
    }),
  },
  procurementKpiDesigner: {
    inputs: [
      field("context", ["採購部門描述", "Procurement Description"], { required: true, placeholder: ["採購範圍、支出、供應商、現有指標", "Procurement scope, spend, suppliers, current metrics"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：節省、合規、供應商管理", "e.g. savings, compliance, supplier management"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位採購績效 KPI 設計師。",
        "", `採購部門：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. KPI 框架設計",
        "採購績效指標(節省/合規/週期/品質/風險)框架,用表格呈現",
        "輸出 ```chart 長條圖顯示各 KPI 維度權重。",
        "", "### 2. 節省追蹤機制",
        "成本節省的定義/計算/驗證(避免虛報)",
        "", "### 3. 供應商評分整合",
        "供應商計分卡與 KPI 的整合",
        "", "### 4. 落地與檢核",
        "數據來源 + 儀表板 + 檢核節律。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a procurement KPI framework designer.",
        "", `Procurement: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. KPI Framework — procurement metrics (savings/compliance/cycle/quality/risk) framework, table. ```chart bar chart of KPI dimension weights.",
        "### 2. Savings Tracking Mechanism — definition/calculation/validation of cost savings (avoid overstatement)",
        "### 3. Supplier Scorecard Integration — integration of supplier scorecard with KPIs",
        "### 4. Implementation & Review — data sources + dashboard + review cadence. Respond in English.",
      ],
    }),
  },
  iotOperationsAdvisor: {
    inputs: [
      field("context", ["IoT 部署描述", "IoT Deployment Description"], { required: true, placeholder: ["設備類型、數量、場景、現有監控、痛點", "Device types, count, scenario, current monitoring, pain points"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：遠端監控、預測維護、降停機", "e.g. remote monitoring, predictive maintenance, reduce downtime"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位物聯網運維顧問。",
        "", `IoT 部署：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 設備管理策略",
        "設備生命週期管理(佈署/更新/監控/退役),用表格呈現",
        "", "### 2. 遠端監控架構",
        "監控架構與資料流,用 ```mermaid flowchart 呈現",
        "", "### 3. 預測性維護",
        "預測維護的數據與模型方向 + 警示閾值",
        "", "### 4. 落地與安全",
        "落地優先序 + 設備安全 + 韌性。全程使用繁體中文(技術詞用英文)。",
      ],
      en: (v) => [
        "You are an IoT operations strategy advisor.",
        "", `IoT deployment: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Device Management Strategy — device lifecycle management (deploy/update/monitor/retire), table",
        "### 2. Remote Monitoring Architecture — monitoring architecture and data flow, ```mermaid flowchart",
        "### 3. Predictive Maintenance — data and model direction for predictive maintenance + alert thresholds",
        "### 4. Implementation & Security — rollout priority + device security + resilience. Respond in English.",
      ],
    }),
  },
  operationsAuditAdvisor: {
    inputs: [
      field("context", ["營運流程描述", "Operations Process Description"], { required: true, placeholder: ["流程、規模、現有指標、痛點", "Processes, scale, current metrics, pain points"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：找效率缺口、降成本、標準化", "e.g. find efficiency gaps, reduce cost, standardize"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位營運稽核顧問。",
        "", `營運流程：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 端對端流程稽核",
        "從頭到尾的流程稽核(效率/品質/成本/合規),用表格呈現",
        "", "### 2. 效率缺口識別",
        "瓶頸/浪費/重工/斷點識別,用 ```mermaid flowchart 呈現流程與卡點",
        "輸出 ```chart 長條圖顯示各環節效率評分。",
        "", "### 3. 改善優先行動",
        "依影響/成本排序的改善行動",
        "", "### 4. 持續改善",
        "監控指標 + 標準化 + 持續改善機制。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are an operations audit advisor.",
        "", `Operations process: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. End-to-End Process Audit — end-to-end audit (efficiency/quality/cost/compliance), table",
        "### 2. Efficiency Gap Identification — identify bottlenecks/waste/rework/breakpoints, ```mermaid flowchart of process and blockers. ```chart bar chart of efficiency score per stage.",
        "### 3. Improvement Priority Actions — improvement actions ranked by impact/cost",
        "### 4. Continuous Improvement — monitoring metrics + standardization + continuous improvement mechanism. Respond in English.",
      ],
    }),
  },
  sopAuditAdvisor: {
    inputs: [
      field("context", ["SOP 現況描述", "SOP Status Description"], { required: true, placeholder: ["SOP 範圍、數量、現況、痛點", "SOP scope, count, status, pain points"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：找缺口、更新、合規、易用", "e.g. find gaps, update, compliance, usability"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位 SOP 稽核顧問。",
        "", `SOP 現況：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. SOP 全面稽核",
        "從完整性/正確性/時效/易用/合規稽核,用表格呈現",
        "輸出 ```chart 長條圖顯示各 SOP 品質評分。",
        "", "### 2. 流程缺口識別",
        "缺漏/過時/矛盾/難執行的 SOP",
        "", "### 3. 改善建議",
        "各問題的改善行動 + 優先序",
        "", "### 4. 維護機制",
        "SOP 維護節律 + 版本控管 + 落地。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are an SOP audit and improvement advisor.",
        "", `SOP status: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Comprehensive SOP Audit — audit by completeness/accuracy/timeliness/usability/compliance, table. ```chart bar chart of quality score per SOP.",
        "### 2. Process Gap Identification — missing/outdated/contradictory/hard-to-execute SOPs",
        "### 3. Improvement Recommendations — improvement actions per issue + priority",
        "### 4. Maintenance Mechanism — SOP maintenance cadence + version control + adoption. Respond in English.",
      ],
    }),
  },
  supplyChainSourcing: {
    inputs: [
      field("context", ["採購 / 供應鏈描述", "Sourcing / Supply Chain Description"], { required: true, placeholder: ["採購品類、支出、現有供應商、痛點", "Categories, spend, current suppliers, pain points"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：降成本、多元化、降風險", "e.g. reduce cost, diversify, reduce risk"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位供應鏈採購策略師。",
        "", `採購/供應鏈：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 戰略採購分析",
        "品類支出分析 + 供應市場 + 槓桿點(Kraljic 矩陣),用表格呈現",
        "輸出 ```chart 長條圖顯示各品類支出占比。",
        "", "### 2. 供應商多元化",
        "單一來源風險 + 多元化策略 + 在地/近岸",
        "", "### 3. 成本優化路線圖",
        "成本優化槓桿(談判/整併/規格/TCO)",
        "", "### 4. 執行計畫",
        "採購行動優先序 + 風險控管 + 衡量。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a supply chain strategic sourcing advisor.",
        "", `Sourcing/supply chain: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Strategic Sourcing Analysis — category spend analysis + supply market + leverage points (Kraljic matrix), table. ```chart bar chart of spend share per category.",
        "### 2. Supplier Diversification — single-source risk + diversification strategy + local/near-shore",
        "### 3. Cost Optimization Roadmap — cost optimization levers (negotiation/consolidation/spec/TCO)",
        "### 4. Execution Plan — sourcing action priority + risk control + measurement. Respond in English.",
      ],
    }),
  },
  shiftsOptimizationEngine: {
    inputs: [
      field("context", ["排班需求描述", "Shift Requirements Description"], { required: true, placeholder: ["人數、班別、需求預測、員工偏好、法規", "Headcount, shifts, demand forecast, staff preferences, regulations"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：降加班、平衡、滿足需求", "e.g. reduce overtime, balance, meet demand"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位智能排班優化顧問。",
        "", `排班需求：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 需求與供給對齊",
        "需求預測 vs 人力供給的對齊分析,用表格呈現各時段缺口",
        "輸出 ```chart 長條圖顯示各時段需求 vs 排班人力。",
        "", "### 2. 排班優化",
        "兼顧覆蓋/偏好/公平/法規的排班原則 + 約束",
        "", "### 3. 加班成本控制",
        "降低加班的策略 + 彈性人力",
        "", "### 4. 落地建議",
        "排班流程 + 例外處理 + 衡量。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a shift optimization advisor.",
        "", `Shift requirements: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Demand-Supply Alignment — demand forecast vs staffing supply, table of gaps per time slot. ```chart bar chart of demand vs staffing per slot.",
        "### 2. Schedule Optimization — scheduling principles balancing coverage/preferences/fairness/regulations + constraints",
        "### 3. Overtime Cost Control — strategies to reduce overtime + flexible staffing",
        "### 4. Implementation — scheduling process + exception handling + measurement. Respond in English.",
      ],
    }),
  },
  knowledgeBaseAutoBuilder: {
    inputs: [
      field("context", ["知識來源描述", "Knowledge Source Description"], { required: true, placeholder: ["來源(Slack/文件/工單)、主題、團隊、現有 KB", "Sources (Slack/docs/tickets), topics, team, existing KB"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：建知識庫、減重複問、onboarding", "e.g. build KB, reduce repeat questions, onboarding"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位知識庫自動構建顧問。",
        "", `知識來源：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 知識萃取策略",
        "從各來源萃取知識的策略(對話/文件/工單→條目),用 ```mermaid flowchart 呈現流程",
        "", "### 2. 結構化分類",
        "知識庫的分類與條目模板,用表格呈現",
        "", "### 3. 品質與去重",
        "正確性把關 + 去重 + 時效標記",
        "", "### 4. 維護機制",
        "持續更新 + 擁有者 + 使用反饋迴圈。全程使用繁體中文。",
      ],
      en: (v) => [
        "You are a knowledge base auto-builder advisor.",
        "", `Knowledge sources: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Knowledge Extraction Strategy — strategy to extract knowledge from sources (threads/docs/tickets→entries), ```mermaid flowchart of process",
        "### 2. Structured Classification — KB taxonomy and entry templates, table",
        "### 3. Quality & Deduplication — accuracy control + deduplication + recency tagging",
        "### 4. Maintenance Mechanism — continuous update + ownership + usage feedback loop. Respond in English.",
      ],
    }),
  },
  apiGatewayHealthMonitor: {
    inputs: [
      field("context", ["API 閘道描述", "API Gateway Description"], { required: true, placeholder: ["閘道、流量、服務數、現有監控、症狀", "Gateway, traffic, services, current monitoring, symptoms"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：找瓶頸、提升可用、降延遲", "e.g. find bottlenecks, improve availability, reduce latency"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位 API 閘道健康監控顧問。",
        "", `API 閘道：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 健康指標設計",
        "該監控的閘道指標(延遲/錯誤率/吞吐/飽和度/限流),用表格呈現",
        "輸出 ```chart 長條圖顯示各指標健康評分。",
        "", "### 2. 瓶頸診斷",
        "效能瓶頸定位(上游/路由/認證/限流),用 ```mermaid flowchart 呈現診斷流程",
        "", "### 3. 修復建議",
        "針對瓶頸的修復(快取/連線池/超時/擴容)",
        "", "### 4. 告警與韌性",
        "告警閾值 + 降級 + SLO。全程使用繁體中文(技術詞用英文)。",
      ],
      en: (v) => [
        "You are an API gateway health monitor advisor.",
        "", `API gateway: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Health Metrics Design — gateway metrics to monitor (latency/error rate/throughput/saturation/rate limiting), table. ```chart bar chart of health score per metric.",
        "### 2. Bottleneck Diagnostic — locate bottlenecks (upstream/routing/auth/rate limit), ```mermaid flowchart of diagnostic process",
        "### 3. Remediation Recommendations — fixes for bottlenecks (caching/connection pooling/timeouts/scaling)",
        "### 4. Alerting & Resilience — alert thresholds + degradation + SLOs. Respond in English.",
      ],
    }),
  },
  vendorIntegrationAuditor: {
    inputs: [
      field("context", ["供應商整合描述", "Vendor Integration Description"], { required: true, placeholder: ["整合的第三方、資料存取、認證方式、規模", "Third parties integrated, data access, auth method, scale"] }),
      field("concern", ["關注（選填）", "Concern (optional)"], { type: "text", placeholder: ["例：安全、合規、資料外流", "e.g. security, compliance, data exfiltration"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位供應商整合審計顧問。",
        "", `供應商整合：${v.context}`,
        v.concern && `關注：${v.concern}`,
        "", "### 1. 整合盤點",
        "各第三方整合的資料存取/權限/認證盤點,用表格呈現",
        "", "### 2. 安全與合規稽核",
        "安全(金鑰/權限/傳輸)與合規(資料/DPA)風險,用 ```chart 長條圖顯示各整合風險評分",
        "", "### 3. 風險與修正",
        "高風險整合 + 修正建議",
        "", "### 4. 治理機制",
        "整合審查流程 + 監控 + 退場。全程使用繁體中文(技術詞用英文)。",
      ],
      en: (v) => [
        "You are a vendor integration auditor advisor.",
        "", `Vendor integration: ${v.context}`,
        v.concern && `Concern: ${v.concern}`,
        "", "### 1. Integration Inventory — inventory of data access/permissions/auth per third-party integration, table",
        "### 2. Security & Compliance Audit — security (keys/permissions/transport) and compliance (data/DPA) risks. ```chart bar chart of risk score per integration.",
        "### 3. Risks & Remediation — high-risk integrations + remediation recommendations",
        "### 4. Governance Mechanism — integration review process + monitoring + offboarding. Respond in English.",
      ],
    }),
  },
  slaBreachPredictor: {
    inputs: [
      field("context", ["SLA / 服務描述", "SLA / Service Description"], { required: true, placeholder: ["SLA 目標、服務、現有指標、歷史違約", "SLA targets, services, current metrics, past breaches"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：提前預警、降違約、優先處置", "e.g. early warning, reduce breaches, prioritize"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位 SLA 違約預測顧問。",
        "", `SLA/服務：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 違約風險指標",
        "可預測違約的領先指標(錯誤預算消耗/趨勢/積壓),用表格呈現",
        "輸出 ```chart 折線圖顯示錯誤預算消耗趨勢。",
        "", "### 2. 預測與預警",
        "違約風險預測邏輯 + 分級告警 + 觸發時機",
        "", "### 3. 處置建議",
        "高風險服務的提前處置行動",
        "", "### 4. 持續改善",
        "根因分析 + SLO 調整 + 韌性。全程使用繁體中文(技術詞用英文)。",
      ],
      en: (v) => [
        "You are an SLA breach predictor advisor.",
        "", `SLA/service: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Breach Risk Indicators — leading indicators predicting breach (error budget burn/trends/backlog), table. ```chart line chart of error budget burn trend.",
        "### 2. Prediction & Early Warning — breach risk prediction logic + tiered alerts + trigger timing",
        "### 3. Remediation Recommendations — proactive actions for high-risk services",
        "### 4. Continuous Improvement — root cause analysis + SLO adjustment + resilience. Respond in English.",
      ],
    }),
  },
  cloudCostAnomalyAlerts: {
    inputs: [
      field("context", ["雲端費用描述", "Cloud Cost Description"], { required: true, placeholder: ["雲端平台、服務、月費規模、現有監控", "Cloud platform, services, monthly spend, current monitoring"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：抓異常、降浪費、可預測", "e.g. catch anomalies, reduce waste, predictability"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位雲端費用異常告警顧問。",
        "", `雲端費用：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 異常偵測設計",
        "費用異常偵測維度(服務/標籤/趨勢/突增)與基準,用表格呈現",
        "輸出 ```chart 折線圖顯示費用趨勢與異常點。",
        "", "### 2. 浪費根因",
        "常見浪費根因(閒置/過度配置/孤兒資源/未用預留)",
        "", "### 3. 告警與處置",
        "告警分級 + 歸因 + 處置流程",
        "", "### 4. 成本治理",
        "標籤策略 + 預算 + FinOps 機制。全程使用繁體中文(技術詞用英文)。",
      ],
      en: (v) => [
        "You are a cloud cost anomaly alerts advisor.",
        "", `Cloud cost: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Anomaly Detection Design — cost anomaly dimensions (service/tag/trend/spike) and baselines, table. ```chart line chart of cost trend with anomaly points.",
        "### 2. Waste Root Causes — common waste causes (idle/over-provisioning/orphan resources/unused reservations)",
        "### 3. Alerting & Remediation — alert tiering + attribution + remediation process",
        "### 4. Cost Governance — tagging strategy + budgets + FinOps mechanism. Respond in English.",
      ],
    }),
  },
  onCallScheduleOptimizer: {
    inputs: [
      field("context", ["值班現況描述", "On-Call Status Description"], { required: true, placeholder: ["團隊人數、值班頻率、事故量、現有輪值", "Team size, on-call frequency, incident volume, current rotation"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：降疲勞、平衡負載、覆蓋", "e.g. reduce fatigue, balance load, coverage"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位值班排程優化顧問。",
        "", `值班現況：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 負載分析",
        "值班負載(事故量/夜間/週末)分布分析,用表格呈現",
        "輸出 ```chart 長條圖顯示各成員值班負載。",
        "", "### 2. 輪值優化",
        "降疲勞的輪值設計(週期/交接/follow-the-sun)+ 公平",
        "", "### 3. 覆蓋與升級",
        "主備覆蓋 + 升級路徑 + 補償機制",
        "", "### 4. 健康與落地",
        "值班健康指標 + 工具 + 持續改善。全程使用繁體中文(技術詞用英文)。",
      ],
      en: (v) => [
        "You are an on-call schedule optimizer advisor.",
        "", `On-call status: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Load Analysis — on-call load (incident volume/nights/weekends) distribution analysis, table. ```chart bar chart of on-call load per member.",
        "### 2. Rotation Optimization — fatigue-reducing rotation design (cycle/handover/follow-the-sun) + fairness",
        "### 3. Coverage & Escalation — primary-secondary coverage + escalation path + compensation mechanism",
        "### 4. Health & Implementation — on-call health metrics + tooling + continuous improvement. Respond in English.",
      ],
    }),
  },
  infraDriftDetector: {
    inputs: [
      field("context", ["基礎設施描述", "Infrastructure Description"], { required: true, placeholder: ["雲端、IaC 工具、環境、現有狀態管理", "Cloud, IaC tooling, environments, current state management"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：偵測漂移、合規、一致性", "e.g. detect drift, compliance, consistency"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位基礎設施漂移偵測顧問。",
        "", `基礎設施：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 漂移偵測策略",
        "該偵測的漂移類型(手動變更/未納管/設定偏移)與來源,用表格呈現",
        "", "### 2. 理想狀態對比",
        "IaC 理想狀態 vs 實際的對比方法,用 ```mermaid flowchart 呈現偵測流程",
        "", "### 3. 處置建議",
        "漂移的處置(納管/還原/接受)決策準則",
        "", "### 4. 預防機制",
        "IaC 治理 + 變更控制 + 持續偵測。全程使用繁體中文(技術詞用英文)。",
      ],
      en: (v) => [
        "You are an infrastructure drift detector advisor.",
        "", `Infrastructure: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Drift Detection Strategy — drift types to detect (manual changes/unmanaged/config drift) and sources, table",
        "### 2. Desired-State Comparison — method to compare IaC desired state vs actual, ```mermaid flowchart of detection flow",
        "### 3. Remediation Recommendations — decision criteria for drift handling (adopt/revert/accept)",
        "### 4. Prevention Mechanism — IaC governance + change control + continuous detection. Respond in English.",
      ],
    }),
  },
  serviceHealthDashboard: {
    inputs: [
      field("context", ["服務 / 監控描述", "Services / Monitoring Description"], { required: true, placeholder: ["服務數量、現有指標、利害關係人、痛點", "Number of services, current metrics, stakeholders, pain points"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：全局可視、週報、SLO", "e.g. global visibility, weekly report, SLOs"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位服務健康儀表板 AI。",
        "", `服務/監控：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 健康指標聚合",
        "多服務健康指標(可用/延遲/錯誤/飽和/SLO)的聚合設計,用表格呈現",
        "輸出 ```chart 長條圖顯示各服務健康評分。",
        "", "### 2. 儀表板分層",
        "高管/維運/工程的不同視角分層",
        "", "### 3. 週報結構",
        "運維狀態週報的結構與重點",
        "", "### 4. 告警與行動",
        "告警閾值 + 從儀表板到行動。全程使用繁體中文(技術詞用英文)。",
      ],
      en: (v) => [
        "You are a service health dashboard AI.",
        "", `Services/monitoring: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Health Metric Aggregation — aggregation design for multi-service health metrics (availability/latency/error/saturation/SLO), table. ```chart bar chart of health score per service.",
        "### 2. Dashboard Layering — different views for executives/ops/engineering",
        "### 3. Weekly Report Structure — structure and focus of operations status weekly report",
        "### 4. Alerting & Action — alert thresholds + dashboard-to-action. Respond in English.",
      ],
    }),
  },
  networkTopologyAnalyzer: {
    inputs: [
      field("context", ["網路拓撲描述", "Network Topology Description"], { required: true, placeholder: ["網路結構、節點、現有架構、痛點", "Network structure, nodes, current architecture, pain points"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：找單點故障、安全缺口、韌性", "e.g. find SPOF, security gaps, resilience"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位網路拓撲分析顧問。",
        "", `網路拓撲：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 拓撲結構分析",
        "網路拓撲結構,用 ```mermaid flowchart 呈現 + 關鍵節點",
        "", "### 2. 單點故障識別",
        "單點故障(SPOF)與冗餘缺口,用表格呈現",
        "", "### 3. 安全缺口",
        "分段/防火牆/暴露面的安全缺口",
        "輸出 ```chart 長條圖顯示各區域風險評分。",
        "", "### 4. 強化建議",
        "冗餘/分段/監控的強化行動。全程使用繁體中文(技術詞用英文)。",
      ],
      en: (v) => [
        "You are a network topology analyzer advisor.",
        "", `Network topology: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Topology Analysis — network topology, ```mermaid flowchart + critical nodes",
        "### 2. Single Point of Failure Identification — SPOFs and redundancy gaps, table",
        "### 3. Security Gaps — segmentation/firewall/exposure-surface gaps. ```chart bar chart of risk score per zone.",
        "### 4. Hardening Recommendations — redundancy/segmentation/monitoring hardening actions. Respond in English.",
      ],
    }),
  },
  alertFatigueReducer: {
    inputs: [
      field("context", ["告警現況描述", "Alerting Status Description"], { required: true, placeholder: ["告警量、來源、現有規則、誤報率、痛點", "Alert volume, sources, current rules, false-positive rate, pain points"] }),
      field("goal", ["目標（選填）", "Goal (optional)"], { type: "text", placeholder: ["例：降噪、合併冗餘、提升有效", "e.g. reduce noise, merge redundant, improve signal"] }),
    ],
    prompt: bilingual({
      zh: (v) => [
        "你是一位告警疲勞降低顧問。",
        "", `告警現況：${v.context}`,
        v.goal && `目標：${v.goal}`,
        "", "### 1. 告警有效性分析",
        "依可行性/誤報率/重複/嚴重度分析告警規則,用表格呈現",
        "輸出 ```chart 長條圖顯示各類告警量與誤報率。",
        "", "### 2. 冗餘合併",
        "可合併/去重/抑制的告警 + 關聯分組",
        "", "### 3. 規則優化",
        "閾值/分級/路由優化 + 可行動性原則",
        "", "### 4. 持續治理",
        "告警審查節律 + 噪音指標 + 改善。全程使用繁體中文(技術詞用英文)。",
      ],
      en: (v) => [
        "You are an alert fatigue reducer advisor.",
        "", `Alerting status: ${v.context}`,
        v.goal && `Goal: ${v.goal}`,
        "", "### 1. Alert Effectiveness Analysis — analyze alert rules by actionability/false-positive rate/duplication/severity, table. ```chart bar chart of volume and false-positive rate per alert type.",
        "### 2. Redundancy Merging — alerts to merge/dedupe/suppress + correlation grouping",
        "### 3. Rule Optimization — threshold/severity/routing optimization + actionability principle",
        "### 4. Continuous Governance — alert review cadence + noise metrics + improvement. Respond in English.",
      ],
    }),
  },
};
