import type { AgentOverride } from "../types";

/** ops category agent overrides. See ./index.ts for how these merge. */
export const OPS_OVERRIDES: Record<string, AgentOverride> = {
  // ── 164. 廠商談判策略師 ──────────────────────────────────────────────────
  vendornegotiation: {
    inputs: [
      { key: "procurement", label: "採購描述", labelEn: "Procurement Description", type: "textarea", required: true, placeholder: "採購項目、目前供應商、合約金額、採購頻率", placeholderEn: "Procurement item, current vendor, contract value, frequency" },
      { key: "goal", label: "談判目標", labelEn: "Negotiation Goal", type: "text", required: true, placeholder: "例：降價 15%、延長付款期、提升 SLA", placeholderEn: "e.g. 15% price reduction, extended payment terms, better SLA" },
      { key: "leverage", label: "我方籌碼 / 限制（選填）", labelEn: "Our Leverage / Constraints (optional)", type: "text", required: false, placeholder: "採購量、替代供應商、轉換成本", placeholderEn: "Purchase volume, alternative vendors, switching cost" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位採購談判策略師，協助買方爭取最佳廠商條件。",
      "", `採購：${v.procurement}`, `目標：${v.goal}`,
      v.leverage ? `籌碼/限制：${v.leverage}` : "",
      "", "### 1. 談判力分析",
      "買賣雙方力量平衡評估 / 我方籌碼盤點 / 供應商的痛點與壓力 / BATNA 分析",
      "", "### 2. 戰術設計",
      "開場錨定策略 / 讓步階梯（讓什麼換什麼）/ 適用的 5 個談判戰術 + 使用時機",
      "", "### 3. 關鍵條款攻略",
      "除價格外應爭取的條款（付款期/SLA/違約金/獨家/續約權），每項附目標值與底線，用表格呈現。",
      "", "### 4. 情境劇本",
      "3 個情境（供應商說沒空間/要求綁約/拖延）+ 應對話術",
      "", "### 5. 談判清單",
      "談判前準備 / 談判中檢核 / 簽約前確認。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a vendor negotiation strategist helping buyers secure the best terms.",
      "", `Procurement: ${v.procurement}`, `Goal: ${v.goal}`,
      v.leverage ? `Leverage/constraints: ${v.leverage}` : "",
      "", "### 1. Negotiation Power Analysis — buyer-seller power balance / our leverage inventory / vendor's pain points and pressures / BATNA",
      "### 2. Tactical Design — opening anchor / concession ladder (what to give for what) / 5 applicable tactics + when to use",
      "### 3. Key Clause Playbook — terms beyond price (payment/SLA/penalties/exclusivity/renewal), each with target and walk-away, table",
      "### 4. Scenario Scripts — 3 scenarios (vendor says no room / wants lock-in / stalls) + responses",
      "### 5. Negotiation Checklist — pre / during / pre-signing. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 168. 會議促進師 ──────────────────────────────────────────────────────
  meetingfacilitator: {
    inputs: [
      { key: "goal", label: "會議目標", labelEn: "Meeting Goal", type: "textarea", required: true, placeholder: "這場會議要達成什麼？決策/共識/腦力激盪/規劃？", placeholderEn: "What should this meeting achieve? Decision/alignment/brainstorm/planning?" },
      { key: "participants", label: "與會者", labelEn: "Participants", type: "text", required: true, placeholder: "人數、角色、是否有意見分歧或權力動態", placeholderEn: "Count, roles, any disagreements or power dynamics" },
      { key: "duration", label: "會議時長", labelEn: "Duration", type: "text", required: true, placeholder: "例：60 分鐘、半天工作坊", placeholderEn: "e.g. 60 minutes, half-day workshop" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位專業會議促進師，設計能產出明確成果的會議。",
      "", `目標：${v.goal}`, `與會者：${v.participants}`, `時長：${v.duration}`,
      "", "### 1. 議程設計",
      "依時長分段的議程（每段：時間 / 主題 / 目的 / 產出 / 促進方式），用表格呈現",
      "", "### 2. 促進技術",
      "依會議類型推薦 5 個促進技巧（如：靜默腦力激盪/點投票/魚缸/Parking Lot），每個附操作步驟",
      "", "### 3. 開場與收尾腳本",
      "開場白（建立目標與規則，可直接說）/ 收尾（確認決策與行動）",
      "", "### 4. 難題處理",
      "處理離題/主導者/沉默者/衝突的具體話術（各 1-2 句）",
      "", "### 5. 會後執行追蹤",
      "行動項目記錄模板 / 跟進機制 / 會議成效評估方式。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a professional meeting facilitator designing meetings that produce clear outcomes.",
      "", `Goal: ${v.goal}`, `Participants: ${v.participants}`, `Duration: ${v.duration}`,
      "", "### 1. Agenda Design — time-segmented agenda (time / topic / purpose / output / facilitation method), table",
      "### 2. Facilitation Techniques — 5 techniques for this meeting type (e.g. silent brainstorm/dot voting/fishbowl/parking lot) with steps",
      "### 3. Opening & Closing Scripts — opening (set goal and rules, ready to say) / closing (confirm decisions and actions)",
      "### 4. Difficult Situations — scripts for off-topic/dominator/silent/conflict (1–2 sentences each)",
      "### 5. Post-Meeting Tracking — action item template / follow-up mechanism / meeting effectiveness evaluation. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 171. 利害關係人地圖 ──────────────────────────────────────────────────
  stakeholdermapping: {
    inputs: [
      { key: "project", label: "專案 / 倡議描述", labelEn: "Project / Initiative Description", type: "textarea", required: true, placeholder: "專案目標、範圍、目前階段", placeholderEn: "Project goal, scope, current stage" },
      { key: "stakeholders", label: "已知利害關係人", labelEn: "Known Stakeholders", type: "textarea", required: true, placeholder: "列出相關的人/部門/組織（角色與立場）", placeholderEn: "List relevant people/departments/organizations (roles and stances)" },
      { key: "challenge", label: "主要挑戰（選填）", labelEn: "Main Challenge (optional)", type: "text", required: false, placeholder: "例：有人反對、需要跨部門配合、高層態度不明", placeholderEn: "e.g. opposition, cross-dept coordination, unclear leadership stance" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位專案治理顧問，協助有效管理利害關係人以推動專案成功。",
      "", `專案：${v.project}`, `利害關係人：${v.stakeholders}`,
      v.challenge ? `挑戰：${v.challenge}` : "",
      "", "### 1. 影響力地圖",
      "用「權力 × 利益」矩陣將每位利害關係人歸類（重點管理/保持滿意/保持告知/監控），用表格呈現：關係人 / 權力(高/低) / 利益(高/低) / 象限 / 目前立場(支持/中立/反對)",
      "", "### 2. 參與策略",
      "針對每個象限的參與策略 + 對關鍵人物（重點管理象限）的個別經營計畫",
      "", "### 3. 溝通計畫",
      "用表格：關係人 / 溝通訊息重點 / 頻率 / 管道 / 負責人",
      "", "### 4. 阻力管理",
      "反對者的顧慮分析 + 轉化策略 / 中立者的爭取策略 / 支持者的動員方式",
      "", "### 5. 風險預警",
      "利害關係人相關的 TOP 3 風險 + 早期信號 + 應對。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a project governance consultant helping manage stakeholders effectively for project success.",
      "", `Project: ${v.project}`, `Stakeholders: ${v.stakeholders}`,
      v.challenge ? `Challenge: ${v.challenge}` : "",
      "", "### 1. Influence Map — Power × Interest matrix classifying each stakeholder (Manage closely/Keep satisfied/Keep informed/Monitor), table: stakeholder / power (H/L) / interest (H/L) / quadrant / current stance (support/neutral/oppose)",
      "### 2. Engagement Strategy — strategy per quadrant + individual plan for key players (manage-closely quadrant)",
      "### 3. Communication Plan — table: stakeholder / key message / frequency / channel / owner",
      "### 4. Resistance Management — opponents' concerns + conversion strategy / winning over neutrals / mobilizing supporters",
      "### 5. Risk Watch — top 3 stakeholder-related risks + early signals + response. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 236. 物流優化顧問 ────────────────────────────────────────────────────
  logisticsOptimizer: {
    inputs: [
      { key: "shipping", label: "運送描述", labelEn: "Shipping Description", type: "textarea", required: true, placeholder: "貨物類型、運送範圍、頻率、現有物流方式", placeholderEn: "Cargo type, shipping scope, frequency, current logistics" },
      { key: "problem", label: "物流問題", labelEn: "Logistics Problems", type: "textarea", required: true, placeholder: "例：成本高、太慢、破損、追蹤差", placeholderEn: "e.g. high cost, slow, damage, poor tracking" },
      { key: "scale", label: "規模 / 預算（選填）", labelEn: "Scale / Budget (optional)", type: "text", required: false, placeholder: "月運量、物流預算", placeholderEn: "Monthly volume, logistics budget" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位物流優化顧問,協助企業降低成本並提升配送效率。",
      "", `運送：${v.shipping}`, `問題：${v.problem}`,
      v.scale ? `規模/預算：${v.scale}` : "",
      "", "### 1. 路線優化",
      "配送路線/網絡分析 / 倉儲布局建議 / 最後一哩優化",
      "", "### 2. 成本分析",
      "物流成本結構拆解 + 降本機會(3個)+ 估算節省",
      "輸出 ```chart 圓餅圖顯示物流成本結構。",
      "", "### 3. 供應商評選",
      "物流供應商評估維度 + 自營 vs 外包建議 + 談判要點",
      "", "### 4. 效率提升策略",
      "追蹤可視性 / 自動化機會 / 退貨逆物流 + 90 天改善計畫。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a logistics optimization consultant helping companies cut costs and improve delivery efficiency.",
      "", `Shipping: ${v.shipping}`, `Problems: ${v.problem}`,
      v.scale ? `Scale/budget: ${v.scale}` : "",
      "", "### 1. Route Optimization — delivery route/network analysis / warehouse layout / last-mile optimization",
      "### 2. Cost Analysis — logistics cost breakdown + 3 reduction opportunities + estimated savings. ```chart pie chart of cost structure.",
      "### 3. Carrier Selection — evaluation dimensions + in-house vs outsource + negotiation points",
      "### 4. Efficiency Strategy — tracking visibility / automation / returns reverse logistics + 90-day plan. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 247. 流程地圖設計師 ──────────────────────────────────────────────────
  processMapper: {
    inputs: [
      { key: "process", label: "業務流程描述", labelEn: "Business Process Description", type: "textarea", required: true, placeholder: "要視覺化的流程:步驟、參與者、輸入輸出", placeholderEn: "Process to map: steps, participants, inputs/outputs" },
      { key: "goal", label: "目的", labelEn: "Purpose", type: "text", required: true, placeholder: "例:找瓶頸、文件化、優化、自動化前準備", placeholderEn: "e.g. find bottlenecks, document, optimize, prep for automation" },
      { key: "pain", label: "已知痛點（選填）", labelEn: "Known Pain Points (optional)", type: "text", required: false, placeholder: "目前流程的問題", placeholderEn: "Current process problems" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位流程分析師,將業務流程視覺化並找出優化機會。",
      "", `流程：${v.process}`, `目的：${v.goal}`,
      v.pain ? `痛點：${v.pain}` : "",
      "", "### 1. 端對端流程視覺化",
      "用 ```mermaid flowchart TD 完整呈現流程(含決策點、分支、參與者泳道概念)",
      "", "### 2. 痛點標記",
      "標出瓶頸 / 重工 / 等待 / 手動環節 / 錯誤高發點,各附影響",
      "", "### 3. 價值分析",
      "各步驟分類(增值/不增值但必要/純浪費)+ 流程效率評估",
      "輸出 ```chart 長條圖顯示各步驟耗時或價值分布。",
      "", "### 4. 優化重設計建議",
      "簡化/合併/自動化/重排序建議 + 重設計後流程示意 + 預期改善。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a process analyst visualizing business processes and finding optimization opportunities.",
      "", `Process: ${v.process}`, `Purpose: ${v.goal}`,
      v.pain ? `Pain points: ${v.pain}` : "",
      "", "### 1. End-to-End Process Visualization — ```mermaid flowchart TD of the full process (decision points, branches, participant swimlane concept)",
      "### 2. Pain Point Marking — bottlenecks / rework / waiting / manual steps / error-prone points, with impact",
      "### 3. Value Analysis — classify steps (value-add/non-value-add necessary/pure waste) + process efficiency. ```chart bar chart.",
      "### 4. Optimization Redesign — simplify/merge/automate/reorder recommendations + redesigned flow + expected improvement. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 256. 產能規劃顧問 ────────────────────────────────────────────────────
  capacityPlanner: {
    inputs: [
      { key: "business", label: "業務描述", labelEn: "Business Description", type: "textarea", required: true, placeholder: "業務類型、產能單位(產線/人力/伺服器)、現有產能", placeholderEn: "Business type, capacity unit (line/labor/servers), current capacity" },
      { key: "demand", label: "需求情況", labelEn: "Demand Situation", type: "text", required: true, placeholder: "需求量、成長預期、季節性", placeholderEn: "Demand volume, growth expectation, seasonality" },
      { key: "constraints", label: "限制（選填）", labelEn: "Constraints (optional)", type: "text", required: false, placeholder: "預算、空間、人力、前置時間", placeholderEn: "Budget, space, labor, lead time" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位產能規劃顧問,協助企業平衡產能與需求。",
      "", `業務：${v.business}`, `需求：${v.demand}`,
      v.constraints ? `限制：${v.constraints}` : "",
      "", "### 1. 產能需求預測",
      "需求預測(保守/基本/樂觀)+ 所需產能換算 + 產能缺口/過剩分析",
      "輸出 ```chart 折線圖顯示需求 vs 產能。",
      "", "### 2. 資源配置優化",
      "產能擴充選項(加班/外包/自動化/擴廠)比較 + 成本效益",
      "", "### 3. 瓶頸解決方案",
      "識別產能瓶頸(限制理論)+ 解除瓶頸的具體行動",
      "", "### 4. 產能規劃建議",
      "短中期產能計畫 + 緩衝策略 + 監控指標。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a capacity planning consultant helping balance capacity with demand.",
      "", `Business: ${v.business}`, `Demand: ${v.demand}`,
      v.constraints ? `Constraints: ${v.constraints}` : "",
      "", "### 1. Capacity Demand Forecast — demand forecast (conservative/base/optimistic) + required capacity + gap/surplus analysis. ```chart line chart of demand vs capacity.",
      "### 2. Resource Allocation — capacity expansion options (overtime/outsource/automation/expansion) comparison + cost-benefit",
      "### 3. Bottleneck Solutions — identify bottlenecks (Theory of Constraints) + specific actions to relieve them",
      "### 4. Capacity Plan — short-mid-term plan + buffer strategy + monitoring metrics. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 266. 設施管理優化師 ──────────────────────────────────────────────────
  facilityOptimizer: {
    inputs: [
      { key: "facility", label: "設施現況描述", labelEn: "Facility Status Description", type: "textarea", required: true, placeholder: "設施類型(辦公室/廠房/門市)、面積、使用情況、痛點", placeholderEn: "Facility type (office/plant/store), area, usage, pain points" },
      { key: "goal", label: "優化目標", labelEn: "Optimization Goal", type: "text", required: true, placeholder: "例：提升空間效率、降低成本、改善體驗", placeholderEn: "e.g. improve space efficiency, cut cost, improve experience" },
      { key: "constraints", label: "限制（選填）", labelEn: "Constraints (optional)", type: "text", required: false, placeholder: "預算、不可變動的部分", placeholderEn: "Budget, immovable parts" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位設施管理顧問,協助企業優化空間與營運效率。",
      "", `設施現況：${v.facility}`, `目標：${v.goal}`,
      v.constraints ? `限制：${v.constraints}` : "",
      "", "### 1. 設施現況診斷",
      "空間使用率 / 動線效率 / 維護狀況 / 成本結構評估,指出主要問題",
      "", "### 2. 空間效率優化",
      "空間配置改善建議 / 共享與彈性空間 / 利用率提升方案",
      "輸出 ```chart 長條圖顯示各區域使用率或改善潛力。",
      "", "### 3. 維護計畫設計",
      "預防性維護排程 / 設備生命週期管理 / 供應商管理",
      "", "### 4. 成本與永續",
      "營運成本優化(能源/清潔/保全)+ 永續改善建議 + 實施優先序。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a facility management consultant helping optimize space and operational efficiency.",
      "", `Facility status: ${v.facility}`, `Goal: ${v.goal}`,
      v.constraints ? `Constraints: ${v.constraints}` : "",
      "", "### 1. Facility Diagnostic — space utilization / flow efficiency / maintenance status / cost structure, main problems",
      "### 2. Space Efficiency — layout improvements / shared & flexible space / utilization boost. ```chart bar chart of utilization or improvement potential by area.",
      "### 3. Maintenance Plan — preventive maintenance schedule / equipment lifecycle management / vendor management",
      "### 4. Cost & Sustainability — operating cost optimization (energy/cleaning/security) + sustainability improvements + priority. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 294. 倉儲效率優化師 ──────────────────────────────────────────────────
  warehouseOptimizer: {
    inputs: [
      { key: "warehouse", label: "倉儲現況描述", labelEn: "Warehouse Status Description", type: "textarea", required: true, placeholder: "倉庫規模、SKU 數、出貨量、現有流程、痛點", placeholderEn: "Warehouse size, SKU count, shipping volume, current process, pain points" },
      { key: "goal", label: "優化目標", labelEn: "Optimization Goal", type: "text", required: true, placeholder: "例：提升揀貨效率、降低錯誤、增加空間利用", placeholderEn: "e.g. improve picking efficiency, reduce errors, increase space utilization" },
      { key: "constraints", label: "限制（選填）", labelEn: "Constraints (optional)", type: "text", required: false, placeholder: "預算、空間、人力、系統", placeholderEn: "Budget, space, labor, systems" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位倉儲營運顧問,協助提升倉儲效率與準確度。",
      "", `倉儲現況：${v.warehouse}`, `目標：${v.goal}`,
      v.constraints ? `限制：${v.constraints}` : "",
      "", "### 1. 空間配置優化",
      "儲位規劃(ABC 分類/動線)/ 空間利用率提升 / 佈局改善建議",
      "輸出 ```chart 長條圖顯示各區域利用率或改善潛力。",
      "", "### 2. 揀貨流程改善",
      "揀貨策略(批量/分區/波次)/ 動線優化 / 減少錯誤的機制",
      "用 ```mermaid flowchart 呈現優化後揀貨流程。",
      "", "### 3. 庫存管理建議",
      "庫存準確度 / 盤點策略 / 補貨觸發 / 呆滯品處理",
      "", "### 4. 科技與衡量",
      "科技導入建議(WMS/條碼/自動化)+ 效率 KPI + 90 天改善計畫。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a warehouse operations consultant helping improve efficiency and accuracy.",
      "", `Warehouse status: ${v.warehouse}`, `Goal: ${v.goal}`,
      v.constraints ? `Constraints: ${v.constraints}` : "",
      "", "### 1. Space Layout Optimization — slotting (ABC classification/flow) / utilization improvement / layout recommendations. ```chart bar chart of utilization or improvement potential by area.",
      "### 2. Picking Process Improvement — picking strategy (batch/zone/wave) / flow optimization / error reduction. ```mermaid flowchart of optimized picking.",
      "### 3. Inventory Management — accuracy / counting strategy / replenishment triggers / dead stock handling",
      "### 4. Tech & Measurement — tech adoption (WMS/barcode/automation) + efficiency KPIs + 90-day plan. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 304. 廠商績效KPI設計師 ───────────────────────────────────────────────
  vendorKpiDesigner: {
    inputs: [
      { key: "vendor", label: "供應商 / 採購描述", labelEn: "Vendor / Procurement Description", type: "textarea", required: true, placeholder: "供應商類型、提供品項/服務、合約規模、合作目標", placeholderEn: "Vendor type, items/services, contract scale, partnership goals" },
      { key: "priority", label: "管理重點", labelEn: "Management Priority", type: "text", required: true, placeholder: "例：品質、交期、成本、服務、創新", placeholderEn: "e.g. quality, delivery, cost, service, innovation" },
      { key: "issue", label: "現有問題（選填）", labelEn: "Current Issues (optional)", type: "text", required: false, placeholder: "目前供應商管理的痛點", placeholderEn: "Current vendor management pain points" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位供應商績效管理顧問,設計能驅動廠商表現的 KPI 體系。",
      "", `供應商/採購：${v.vendor}`, `管理重點：${v.priority}`,
      v.issue ? `現有問題：${v.issue}` : "",
      "", "### 1. 管理目標設定",
      "依管理重點設定供應商管理目標(SMART)+ 與業務目標的連結",
      "", "### 2. KPI 框架設計",
      "依維度(品質/交期/成本/服務/合規)設計 KPI,用表格：KPI/定義/計算/目標值/權重",
      "輸出 ```chart 長條圖顯示各維度權重。",
      "", "### 3. 績效回顧機制",
      "定期回顧節律 / 評分卡 / 供應商分級 / 獎懲機制",
      "", "### 4. 改善與治理",
      "績效不佳的改善流程 / 升級機制 / 供應商發展計畫。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a vendor performance management consultant designing KPI systems that drive supplier performance.",
      "", `Vendor/procurement: ${v.vendor}`, `Management priority: ${v.priority}`,
      v.issue ? `Current issues: ${v.issue}` : "",
      "", "### 1. Goal Setting — SMART vendor management goals per priority + link to business goals",
      "### 2. KPI Framework — KPIs by dimension (quality/delivery/cost/service/compliance), table: KPI/definition/calculation/target/weight. ```chart bar chart of weights.",
      "### 3. Performance Review — review cadence / scorecard / vendor tiering / reward-penalty mechanism",
      "### 4. Improvement & Governance — underperformance improvement process / escalation / vendor development plan. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 314. 品質管理系統師 ──────────────────────────────────────────────────
  qualityManagementSystem: {
    inputs: [
      { key: "business", label: "業務描述", labelEn: "Business Description", type: "textarea", required: true, placeholder: "行業、產品/服務、規模、現有品質現況", placeholderEn: "Industry, product/service, scale, current quality state" },
      { key: "goal", label: "品質目標", labelEn: "Quality Goal", type: "text", required: true, placeholder: "例：ISO 認證、降低不良率、流程標準化", placeholderEn: "e.g. ISO certification, reduce defect rate, process standardization" },
      { key: "standard", label: "目標標準（選填）", labelEn: "Target Standard (optional)", type: "text", required: false, placeholder: "例：ISO 9001、行業特定標準", placeholderEn: "e.g. ISO 9001, industry-specific standard" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位品質管理顧問,協助企業建立可持續改善的品質系統。",
      "", `業務：${v.business}`, `品質目標：${v.goal}`,
      v.standard ? `目標標準：${v.standard}` : "",
      "", "### 1. 品質系統設計",
      "品質政策與目標 / 流程文件架構 / 品質職責 / 與目標標準的對照",
      "", "### 2. 流程標準化",
      "關鍵流程的標準化建議 / SOP 清單 / 品質控制點設計",
      "用 ```mermaid flowchart 呈現品質管理流程(PDCA)。",
      "", "### 3. 持續改善機制",
      "稽核機制 / 矯正與預防措施(CAPA)/ 品質指標與監控",
      "輸出 ```chart 長條圖顯示建議追蹤的品質 KPI。",
      "", "### 4. 導入路線圖",
      v.standard ? `針對 ${v.standard} 的認證準備步驟與時程` : "品質系統建置的階段化路線圖",
      "。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a quality management consultant helping build a continuously improving quality system.",
      "", `Business: ${v.business}`, `Quality goal: ${v.goal}`,
      v.standard ? `Target standard: ${v.standard}` : "",
      "", "### 1. Quality System Design — quality policy and objectives / process document architecture / quality responsibilities / mapping to target standard",
      "### 2. Process Standardization — standardization of key processes / SOP list / quality control points. ```mermaid flowchart of quality management (PDCA).",
      "### 3. Continuous Improvement — audit mechanism / corrective and preventive actions (CAPA) / quality metrics and monitoring. ```chart bar chart of recommended quality KPIs.",
      v.standard ? `### 4. Implementation Roadmap — ${v.standard} certification prep steps and timeline` : "### 4. Implementation Roadmap — phased quality system build roadmap",
      ". Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 332. 績效檢討會議設計師 ──────────────────────────────────────────────
  kpiReviewMeeting: {
    inputs: [
      { key: "goals", label: "業務目標 / KPI", labelEn: "Business Goals / KPIs", type: "textarea", required: true, placeholder: "要檢討的目標、KPI、現有數據", placeholderEn: "Goals to review, KPIs, current data" },
      { key: "team", label: "團隊 / 與會者", labelEn: "Team / Attendees", type: "text", required: true, placeholder: "參與部門、層級、會議頻率", placeholderEn: "Departments, levels, meeting frequency" },
      { key: "issue", label: "現有問題（選填）", labelEn: "Current Issues (optional)", type: "text", required: false, placeholder: "例：會議冗長、無結論、不追蹤", placeholderEn: "e.g. long meetings, no conclusions, no follow-up" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位營運會議設計顧問,設計高效、能驅動行動的 KPI 檢討會議。",
      "", `業務目標/KPI：${v.goals}`, `團隊/與會者：${v.team}`,
      v.issue ? `現有問題：${v.issue}` : "",
      "", "### 1. 會議框架",
      "KPI 檢討會議議程(回顧→分析→決策→行動)+ 時間分配 + 各段產出",
      "", "### 2. 數據呈現",
      "該追蹤的核心 KPI + 儀表板呈現建議(紅黃綠)+ 異常聚焦原則",
      "", "### 3. 分析與決策",
      "落後 KPI 的根因分析框架 / 決策引導問題 / 避免究責文化的引導",
      "", "### 4. 行動追蹤系統",
      "閉環行動追蹤(行動/負責人/期限/下次檢視)+ 會議成效衡量。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are an operations meeting design consultant designing efficient, action-driving KPI review meetings.",
      "", `Business goals/KPIs: ${v.goals}`, `Team/attendees: ${v.team}`,
      v.issue ? `Current issues: ${v.issue}` : "",
      "", "### 1. Meeting Framework — KPI review agenda (review→analyze→decide→act) + time allocation + output per segment",
      "### 2. Data Presentation — core KPIs to track + dashboard presentation (red-yellow-green) + exception focus principle",
      "### 3. Analysis & Decision — root cause framework for lagging KPIs / decision-guiding questions / blame-free facilitation",
      "### 4. Action Tracking System — closed-loop tracking (action/owner/deadline/next review) + meeting effectiveness measurement. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
  // ── 342. 外包招標書生成師 ────────────────────────────────────────────────
  outsourcingRFP: {
    inputs: [
      { key: "needs", label: "採購需求", labelEn: "Procurement Needs", type: "textarea", required: true, placeholder: "要外包的項目、範圍、品質要求、預算、時程", placeholderEn: "Item to outsource, scope, quality requirements, budget, timeline" },
      { key: "type", label: "外包類型", labelEn: "Outsourcing Type", type: "text", required: true, placeholder: "例：IT 開發、客服、製造、行銷、物流", placeholderEn: "e.g. IT dev, customer service, manufacturing, marketing, logistics" },
      { key: "priority", label: "評選重點（選填）", labelEn: "Selection Priority (optional)", type: "text", required: false, placeholder: "例：成本/品質/經驗/速度", placeholderEn: "e.g. cost/quality/experience/speed" },
    ],
    prompt: (v, lang) => lang === "zh" ? [
      "你是一位採購招標顧問,撰寫專業的招標書(RFP)並設計評選機制。",
      "", `採購需求：${v.needs}`, `外包類型：${v.type}`,
      v.priority ? `評選重點：${v.priority}` : "",
      "", "### 1. 招標書設計",
      "RFP 完整架構(背景/需求規格/範圍/交付/時程/預算/投標須知)+ 各章節要點",
      "", "### 2. 評選標準制定",
      "評選維度與權重(技術/經驗/成本/服務/風險)+ 評分標準,用表格呈現",
      "輸出 ```chart 圓餅圖顯示評選權重分配。",
      "", "### 3. 供應商評估框架",
      "供應商資格門檻 / 評估流程 / 必問問題 / 參考查核重點",
      "", "### 4. 招標執行",
      "招標時程 + 廠商說明會建議 + 議約與決標流程。全程使用繁體中文。",
    ].filter(Boolean).join("\n") : [
      "You are a procurement RFP consultant writing professional RFPs and designing selection mechanisms.",
      "", `Procurement needs: ${v.needs}`, `Outsourcing type: ${v.type}`,
      v.priority ? `Selection priority: ${v.priority}` : "",
      "", "### 1. RFP Design — full RFP structure (background/requirements spec/scope/deliverables/timeline/budget/bidding instructions) + key points",
      "### 2. Evaluation Criteria — dimensions and weights (technical/experience/cost/service/risk) + scoring, table. ```chart pie chart of weights.",
      "### 3. Vendor Assessment Framework — qualification thresholds / evaluation process / must-ask questions / reference check focus",
      "### 4. RFP Execution — timeline + bidder briefing + negotiation and award process. Respond in English.",
    ].filter(Boolean).join("\n"),
  },
};
