import type { AgentOverride } from "./types";

/**
 * Per-agent customisations, keyed by agent id. Anything you set here overrides
 * the generated defaults (inputs / prompt / model / labels). Everything else
 * falls back to the auto-generated metadata + generic prompt builder.
 *
 * This is the supported way to hand-tune an agent without editing the
 * auto-generated data.ts. See CONTRIBUTING.md.
 */
export const AGENT_OVERRIDES: Record<string, AgentOverride> = {
  // ── 1. 需求 Pipeline ─────────────────────────────────────────────────────
  pipeline: {
    inputs: [
      {
        key: "task",
        label: "專案需求描述",
        labelEn: "Project Requirement",
        type: "textarea",
        required: true,
        placeholder: "用一段話描述你想解決的問題或想建的功能…",
        placeholderEn: "Describe the problem to solve or feature to build in a paragraph…",
      },
      {
        key: "stakeholders",
        label: "利害關係人（選填）",
        labelEn: "Stakeholders (optional)",
        type: "text",
        required: false,
        placeholder: "例：產品經理、前端工程師、客服、行銷",
        placeholderEn: "e.g. PM, frontend engineer, customer support, marketing",
      },
      {
        key: "constraints",
        label: "限制條件（選填）",
        labelEn: "Constraints (optional)",
        type: "textarea",
        required: false,
        placeholder: "時程、預算、技術限制或不能動的系統…",
        placeholderEn: "Timeline, budget, tech constraints, or systems that can't change…",
      },
    ],
    prompt: (v, lang) =>
      lang === "zh"
        ? [
            "你是一位資深需求分析師，擅長將模糊需求拆解為清晰的工程規格。",
            "",
            `## 專案需求\n${v.task || "（未提供）"}`,
            v.stakeholders ? `\n## 利害關係人\n${v.stakeholders}` : "",
            v.constraints ? `\n## 限制條件\n${v.constraints}` : "",
            "",
            "請依序完成三個分析階段：",
            "",
            "### 階段一：需求理解（Analyst）",
            "- 核心問題定義（1-2 句）",
            "- 成功指標（可量化的 KPI，用 Markdown 表格列出）",
            "- 主要假設與風險",
            "",
            "### 階段二：使用者故事（Product）",
            "用標準格式寫出至少 5 條 User Stories：",
            "> 身為 [角色]，我希望 [功能]，以便 [目的]",
            "每條附上驗收條件（Acceptance Criteria）。",
            "",
            "### 階段三：實作優先序（Engineering）",
            "- 用 MoSCoW 法（Must/Should/Could/Won't）分類所有需求，以 Markdown 表格呈現",
            "- 指出技術風險與依賴項目",
            "- 建議 MVP 範圍（第一個可交付版本包含什麼）",
            "",
            "最後用 ```mermaid 畫出需求流程圖（flowchart TD）。",
            "全程使用繁體中文。",
          ]
            .filter(Boolean)
            .join("\n")
        : [
            "You are a senior requirements analyst who turns fuzzy ideas into engineering specs.",
            "",
            `## Project Requirement\n${v.task || "(not provided)"}`,
            v.stakeholders ? `\n## Stakeholders\n${v.stakeholders}` : "",
            v.constraints ? `\n## Constraints\n${v.constraints}` : "",
            "",
            "Complete three analysis phases in order:",
            "",
            "### Phase 1: Requirements Understanding (Analyst)",
            "- Core problem statement (1–2 sentences)",
            "- Success metrics (quantifiable KPIs in a Markdown table)",
            "- Key assumptions and risks",
            "",
            "### Phase 2: User Stories (Product)",
            "Write at least 5 user stories in standard format:",
            "> As a [role], I want [feature] so that [benefit]",
            "Each with acceptance criteria.",
            "",
            "### Phase 3: Implementation Priority (Engineering)",
            "- MoSCoW classification (Must/Should/Could/Won't) in a Markdown table",
            "- Technical risks and dependencies",
            "- Recommended MVP scope",
            "",
            "Finally output a ```mermaid flowchart TD showing the requirement flow.",
            "Respond entirely in English.",
          ]
            .filter(Boolean)
            .join("\n"),
  },

  // ── 2. 網站診斷 ──────────────────────────────────────────────────────────
  audit: {
    inputs: [
      {
        key: "url",
        label: "網站網址",
        labelEn: "Website URL",
        type: "text",
        required: true,
        placeholder: "https://example.com",
        placeholderEn: "https://example.com",
      },
      {
        key: "audience",
        label: "目標受眾",
        labelEn: "Target Audience",
        type: "text",
        required: true,
        placeholder: "例：台灣 B2B 中小企業主、30-45 歲",
        placeholderEn: "e.g. Taiwan B2B SME owners, age 30–45",
      },
      {
        key: "goals",
        label: "主要目標（選填）",
        labelEn: "Primary Goals (optional)",
        type: "textarea",
        required: false,
        placeholder: "增加詢價率、提高品牌信任感、降低跳出率…",
        placeholderEn: "Increase inquiry rate, build brand trust, reduce bounce rate…",
      },
    ],
    prompt: (v, lang) =>
      lang === "zh"
        ? [
            "你是一位擁有 10 年以上經驗的網站 UX/SEO 顧問。",
            "",
            `網址：${v.url}`,
            `目標受眾：${v.audience}`,
            v.goals ? `目標：${v.goals}` : "",
            "",
            "請對該網站進行專業診斷，分為三個部分：",
            "",
            "### 1. SEO 診斷",
            "評估以下項目（每項評分 1-10 並說明理由）：標題與 Meta 描述、URL 結構、內容品質與關鍵字、Core Web Vitals 預估、行動裝置友善度、結構化資料。",
            "用 Markdown 表格呈現評分表，最後給出 SEO 總評分（1-10）。",
            "輸出一個 ```chart 圓餅圖顯示各項分數分布。",
            "",
            "### 2. UX 診斷",
            "評估：首頁視覺衝擊力、資訊架構清晰度、CTA（行動呼籲）有效性、信任訊號（評價/案例/認證）、表單與轉換流程。",
            "同樣用表格評分。指出 3 個最嚴重的 UX 問題，每個附具體改善建議。",
            "",
            "### 3. 優先行動清單",
            "列出 TOP 5 改善項目，每項包含：問題、影響（高/中/低）、實施難度（高/中/低）、預估效益。",
            "用 Markdown 表格呈現，並標出最高 ROI 的那一項。",
            "全程使用繁體中文。",
          ]
            .filter(Boolean)
            .join("\n")
        : [
            "You are a senior UX/SEO consultant with 10+ years of experience.",
            "",
            `URL: ${v.url}`,
            `Target Audience: ${v.audience}`,
            v.goals ? `Goals: ${v.goals}` : "",
            "",
            "Audit the website across three sections:",
            "",
            "### 1. SEO Audit",
            "Rate each item 1–10 with reasoning: Title & Meta, URL structure, Content quality & keywords, Core Web Vitals estimate, Mobile-friendliness, Structured data.",
            "Present a scoring table in Markdown, then an overall SEO score. Output a ```chart pie chart of scores.",
            "",
            "### 2. UX Audit",
            "Rate: First impression, IA clarity, CTA effectiveness, Trust signals (reviews/cases/certs), Form & conversion flow.",
            "Scoring table, then identify the 3 most critical UX problems with specific fixes.",
            "",
            "### 3. Priority Action List",
            "Top 5 improvements: Issue / Impact (H/M/L) / Effort (H/M/L) / Estimated benefit.",
            "Markdown table, highlight the highest-ROI item.",
            "Respond entirely in English.",
          ]
            .filter(Boolean)
            .join("\n"),
  },

  // ── 3. 文案產生器 ─────────────────────────────────────────────────────────
  copy: {
    inputs: [
      {
        key: "brand",
        label: "品牌 / 產品名稱",
        labelEn: "Brand / Product Name",
        type: "text",
        required: true,
        placeholder: "例：AgentOS、美樂信科技、BrewBot",
        placeholderEn: "e.g. AgentOS, MLTech, BrewBot",
      },
      {
        key: "audience",
        label: "核心受眾",
        labelEn: "Target Audience",
        type: "text",
        required: true,
        placeholder: "例：台灣中小企業老闆、軟體新創 CTO",
        placeholderEn: "e.g. Taiwan SME owners, SaaS startup CTOs",
      },
      {
        key: "usp",
        label: "核心賣點（1-3 個）",
        labelEn: "Key Selling Points (1–3)",
        type: "textarea",
        required: true,
        placeholder: "讓你的產品與眾不同之處…",
        placeholderEn: "What makes your product different…",
      },
      {
        key: "tone",
        label: "語調風格（選填）",
        labelEn: "Tone of Voice (optional)",
        type: "text",
        required: false,
        placeholder: "例：專業權威、親切友善、簡潔有力、幽默",
        placeholderEn: "e.g. authoritative, friendly, concise, playful",
      },
    ],
    prompt: (v, lang) =>
      lang === "zh"
        ? [
            "你是一位精通 B2B/B2C 的資深行銷文案顧問。",
            "",
            `品牌名稱：${v.brand}`,
            `核心受眾：${v.audience}`,
            `核心賣點：${v.usp}`,
            v.tone ? `語調風格：${v.tone}` : "",
            "",
            "請並行產生以下四組文案（每組給出 2 個版本供選擇）：",
            "",
            "### Hero 文案",
            "主標題（≤12 字）+ 副標題（1-2 句，說明核心價值）+ CTA 按鈕文字（≤6 字）",
            "",
            "### Value Proposition",
            "三個價值主張，每個：圖示 emoji + 標題（≤8 字）+ 說明（2-3 句）",
            "",
            "### About / 品牌故事",
            "150-200 字，包含：品牌成立原因、解決什麼問題、對受眾的承諾",
            "",
            "### SEO Meta",
            "- Title tag（≤60 字元，含主要關鍵字）",
            "- Meta description（≤155 字元，含 CTA）",
            "- 建議關鍵字清單（10 個，依搜尋量高低排序）用表格呈現",
            "",
            "全程使用繁體中文。",
          ]
            .filter(Boolean)
            .join("\n")
        : [
            "You are a senior copywriter specialising in B2B and B2C marketing.",
            "",
            `Brand: ${v.brand}`,
            `Target Audience: ${v.audience}`,
            `Key Selling Points: ${v.usp}`,
            v.tone ? `Tone of Voice: ${v.tone}` : "",
            "",
            "Generate four copy sets in parallel (2 versions each for selection):",
            "",
            "### Hero Copy",
            "Headline (≤10 words) + Subheadline (1–2 sentences on core value) + CTA button text (≤5 words)",
            "",
            "### Value Proposition",
            "Three value props, each: emoji icon + Title (≤6 words) + Explanation (2–3 sentences)",
            "",
            "### About / Brand Story",
            "150–200 words: why brand was founded, what problem it solves, promise to audience",
            "",
            "### SEO Meta",
            "- Title tag (≤60 chars, include primary keyword)",
            "- Meta description (≤155 chars, include CTA)",
            "- Keyword list (10 keywords ranked by search volume, in a Markdown table)",
            "",
            "Respond entirely in English.",
          ]
            .filter(Boolean)
            .join("\n"),
  },

  // ── 4. 協作模擬 ──────────────────────────────────────────────────────────
  collab: {
    inputs: [
      {
        key: "project",
        label: "專案描述",
        labelEn: "Project Description",
        type: "textarea",
        required: true,
        placeholder: "這個專案要做什麼？解決什麼問題？",
        placeholderEn: "What does this project do? What problem does it solve?",
      },
      {
        key: "stage",
        label: "當前階段",
        labelEn: "Current Stage",
        type: "text",
        required: true,
        placeholder: "例：需求確認、設計完成、開發中、準備上線",
        placeholderEn: "e.g. requirements confirmed, design done, in development, pre-launch",
      },
      {
        key: "stack",
        label: "技術堆疊 / 工具（選填）",
        labelEn: "Tech Stack / Tools (optional)",
        type: "text",
        required: false,
        placeholder: "例：Next.js、Supabase、Figma、GitHub Actions",
        placeholderEn: "e.g. Next.js, Supabase, Figma, GitHub Actions",
      },
    ],
    prompt: (v, lang) =>
      lang === "zh"
        ? [
            "你將模擬一個真實的跨職能團隊協作流程（PM → 工程師 → QA），每個角色給出具體可執行的工作成果。",
            "",
            `專案：${v.project}`,
            `當前階段：${v.stage}`,
            v.stack ? `技術堆疊：${v.stack}` : "",
            "",
            "### 👔 PM（產品經理）產出",
            "1. 本階段的 2-3 個核心目標（SMART 格式）",
            "2. 功能清單與優先序（用 MoSCoW 表格）",
            "3. 對工程師的 Handoff 備忘錄（關鍵決策、設計稿連結佔位、邊界條件）",
            "",
            "### 💻 工程師（Lead Dev）產出",
            "1. 技術方案選擇與理由（用表格比較 2-3 個選項）",
            "2. 任務拆解（Sprint 任務清單，含預估點數）",
            "3. 對 QA 的 Handoff：主要功能、測試範圍、已知邊界情況",
            "",
            "### 🧪 QA（品保工程師）產出",
            "1. 測試計畫：功能測試 + 邊界測試 + 效能測試項目",
            "2. 至少 5 個關鍵測試案例（TC ID / 前提 / 步驟 / 預期結果）",
            "3. 上線放行標準（Go/No-Go checklist）",
            "",
            "用 ```mermaid sequenceDiagram 畫出三個角色的協作時序圖。",
            "全程使用繁體中文。",
          ]
            .filter(Boolean)
            .join("\n")
        : [
            "Simulate a real cross-functional team workflow (PM → Engineer → QA), each role delivering concrete, actionable artifacts.",
            "",
            `Project: ${v.project}`,
            `Current Stage: ${v.stage}`,
            v.stack ? `Tech Stack: ${v.stack}` : "",
            "",
            "### 👔 PM Output",
            "1. 2–3 phase objectives (SMART format)",
            "2. Feature list with priority (MoSCoW table)",
            "3. Engineering handoff memo (key decisions, design link placeholders, edge cases)",
            "",
            "### 💻 Engineer (Lead Dev) Output",
            "1. Technical solution comparison (table of 2–3 options with reasoning)",
            "2. Task breakdown (Sprint backlog with story points)",
            "3. QA handoff: main features, test scope, known edge cases",
            "",
            "### 🧪 QA Output",
            "1. Test plan: functional + boundary + performance",
            "2. At least 5 test cases (TC ID / Precondition / Steps / Expected result)",
            "3. Go/No-Go launch checklist",
            "",
            "Output a ```mermaid sequenceDiagram showing the collaboration timeline.",
            "Respond entirely in English.",
          ]
            .filter(Boolean)
            .join("\n"),
  },

  // ── 5. ROI 試算 ───────────────────────────────────────────────────────────
  roi: {
    inputs: [
      {
        key: "company",
        label: "公司名稱 / 規模 / 產業",
        labelEn: "Company Name / Size / Industry",
        type: "text",
        required: true,
        placeholder: "例：某製造業，員工 80 人，年營收約 1.2 億",
        placeholderEn: "e.g. Manufacturing company, 80 employees, annual revenue ~NT$120M",
      },
      {
        key: "processes",
        label: "目前主要流程（想導入 AI 的環節）",
        labelEn: "Current Processes (areas to automate with AI)",
        type: "textarea",
        required: true,
        placeholder: "例：客服回覆（每天 200 封信）、報表整理（每週 8 小時）、採購詢報價",
        placeholderEn: "e.g. Customer replies (200 emails/day), Report prep (8h/week), Procurement RFQ",
      },
      {
        key: "budget",
        label: "預估導入預算（選填）",
        labelEn: "Estimated AI Adoption Budget (optional)",
        type: "text",
        required: false,
        placeholder: "例：年度 50 萬、月費 3 萬、不確定",
        placeholderEn: "e.g. NT$500K/year, NT$30K/month, unsure",
      },
    ],
    prompt: (v, lang) =>
      lang === "zh"
        ? [
            "你是一位企業 AI 導入效益評估顧問，擅長以具體數字量化投資回報。",
            "",
            `公司資訊：${v.company}`,
            `目標流程：${v.processes}`,
            v.budget ? `預算：${v.budget}` : "",
            "",
            "請依以下架構輸出 ROI 試算報告：",
            "",
            "### 1. 現況成本估算",
            "針對每個流程：目前耗費人時（人/小時/月）× 時薪成本 = 月成本",
            "用 Markdown 表格列出，最下方加總。",
            "",
            "### 2. 導入 AI 後的效益估算",
            "每個流程的自動化率（保守 / 樂觀 / 激進）三情境，以表格呈現節省的人時與金額。",
            "輸出一個 ```chart 長條圖，比較三種情境的月節省金額。",
            "",
            "### 3. 導入成本估算",
            "硬體/訂閱/開發/訓練/維運 各項費用預估（依提供預算調整）",
            "",
            "### 4. ROI 計算",
            "公式：ROI = (年節省 - 年導入成本) / 年導入成本 × 100%",
            "三情境的回收期（月）用表格顯示。",
            "輸出一個 ```chart 折線圖，顯示 12 個月累積投資回收曲線（三情境）。",
            "",
            "### 5. 建議優先導入順序",
            "依 ROI 高低排序，列出 1-3 個最值得優先啟動的流程。",
            "全程使用繁體中文。",
          ]
            .filter(Boolean)
            .join("\n")
        : [
            "You are an enterprise AI adoption ROI consultant who quantifies returns with concrete numbers.",
            "",
            `Company: ${v.company}`,
            `Target Processes: ${v.processes}`,
            v.budget ? `Budget: ${v.budget}` : "",
            "",
            "Deliver an ROI analysis report:",
            "",
            "### 1. Current Cost Baseline",
            "Per process: current labor hours (people × hrs/month) × hourly cost = monthly cost. Markdown table with totals.",
            "",
            "### 2. AI-Enabled Savings",
            "Automation rate × 3 scenarios (conservative / realistic / aggressive). Table of hours saved and dollar value. Output a ```chart bar chart comparing monthly savings across scenarios.",
            "",
            "### 3. Adoption Cost Estimate",
            "Hardware / subscriptions / development / training / maintenance — itemized.",
            "",
            "### 4. ROI Calculation",
            "Formula: ROI = (Annual savings − Annual cost) / Annual cost × 100%. Payback period (months) per scenario in a table. Output a ```chart line chart showing 12-month cumulative ROI curve (3 scenarios).",
            "",
            "### 5. Priority Recommendation",
            "Top 1–3 processes to start first, ranked by ROI.",
            "Respond entirely in English.",
          ]
            .filter(Boolean)
            .join("\n"),
  },

  // ── 6. 轉型路線圖 ─────────────────────────────────────────────────────────
  roadmap: {
    inputs: [
      {
        key: "company",
        label: "公司名稱 / 行業 / 規模",
        labelEn: "Company / Industry / Size",
        type: "text",
        required: true,
        placeholder: "例：台灣傳產製造業，員工 150 人",
        placeholderEn: "e.g. Taiwan traditional manufacturer, 150 employees",
      },
      {
        key: "current",
        label: "現況描述",
        labelEn: "Current Situation",
        type: "textarea",
        required: true,
        placeholder: "目前數位化程度、使用哪些系統、遇到的痛點…",
        placeholderEn: "Current digitalization level, systems in use, pain points…",
      },
      {
        key: "goal",
        label: "期望目標 / 驅動因素",
        labelEn: "Goals / Drivers",
        type: "textarea",
        required: true,
        placeholder: "希望達成什麼？是什麼讓你決定要轉型？",
        placeholderEn: "What do you want to achieve? What's driving the transformation?",
      },
    ],
    prompt: (v, lang) =>
      lang === "zh"
        ? [
            "你是一位企業數位轉型顧問，專長是為傳統企業規劃務實可落地的 AI 轉型路線。",
            "",
            `公司資訊：${v.company}`,
            `現況：${v.current}`,
            `目標：${v.goal}`,
            "",
            "### 1. 數位成熟度評估",
            "在以下五個維度對該公司評分（1-5 分）：資料管理、流程自動化、人才能力、技術基礎、領導支持。",
            "用雷達圖文字描述 + Markdown 表格呈現，整體成熟度等級（初始/發展/成熟/領先）。",
            "",
            "### 2. 三階段轉型計畫",
            "**第一階段（0-6 個月）：奠基**",
            "- 核心行動（3-5 項，可立即啟動）",
            "- 關鍵里程碑",
            "- 所需資源",
            "",
            "**第二階段（6-18 個月）：加速**",
            "- 核心行動（3-5 項）",
            "- 預期效益",
            "",
            "**第三階段（18-36 個月）：領先**",
            "- 核心行動（3-5 項）",
            "- 競爭優勢",
            "",
            "用 ```mermaid gantt 繪製三階段時程圖。",
            "",
            "### 3. 風險審查",
            "列出 TOP 5 風險，每個包含：風險描述 / 可能性（H/M/L）/ 影響（H/M/L）/ 緩解措施。用表格呈現。",
            "全程使用繁體中文。",
          ]
            .filter(Boolean)
            .join("\n")
        : [
            "You are a digital transformation consultant who builds pragmatic AI roadmaps for traditional businesses.",
            "",
            `Company: ${v.company}`,
            `Current Situation: ${v.current}`,
            `Goals: ${v.goal}`,
            "",
            "### 1. Digital Maturity Assessment",
            "Score the company on 5 dimensions (1–5): Data management, Process automation, Talent capability, Tech infrastructure, Leadership support. Table + overall maturity level (Initial/Developing/Mature/Leading).",
            "",
            "### 2. Three-Phase Transformation Plan",
            "**Phase 1 (0–6 months): Foundation** — 3–5 immediate actions, milestones, resources needed",
            "**Phase 2 (6–18 months): Acceleration** — 3–5 actions, expected benefits",
            "**Phase 3 (18–36 months): Leadership** — 3–5 actions, competitive advantages",
            "Output a ```mermaid gantt chart for the three phases.",
            "",
            "### 3. Risk Review",
            "Top 5 risks: Description / Likelihood (H/M/L) / Impact (H/M/L) / Mitigation. Markdown table.",
            "Respond entirely in English.",
          ]
            .filter(Boolean)
            .join("\n"),
  },

  // ── 7. 競品分析 ───────────────────────────────────────────────────────────
  competitor: {
    inputs: [
      {
        key: "product",
        label: "你的產品 / 服務",
        labelEn: "Your Product / Service",
        type: "textarea",
        required: true,
        placeholder: "名稱、主要功能、目標客群、定價（若有）",
        placeholderEn: "Name, main features, target customers, pricing (if any)",
      },
      {
        key: "competitors",
        label: "競品清單（逗號或換行分隔）",
        labelEn: "Competitor List (comma or line separated)",
        type: "textarea",
        required: true,
        placeholder: "例：Notion、Confluence、Coda",
        placeholderEn: "e.g. Notion, Confluence, Coda",
      },
      {
        key: "market",
        label: "目標市場 / 地區",
        labelEn: "Target Market / Region",
        type: "text",
        required: false,
        placeholder: "例：台灣 B2B SaaS、東南亞中小企業",
        placeholderEn: "e.g. Taiwan B2B SaaS, SEA SMEs",
      },
    ],
    prompt: (v, lang) =>
      lang === "zh"
        ? [
            "你是一位競品分析策略師，以第三方客觀視角對產品競爭格局做全面分析。",
            "",
            `我方產品：${v.product}`,
            `競品：${v.competitors}`,
            v.market ? `目標市場：${v.market}` : "",
            "",
            "### 1. 各競品快速畫像",
            "每個競品：定位一句話 / 核心功能 3-5 點 / 定價策略 / 目標客群 / 主要優勢 / 主要弱點。",
            "用 Markdown 表格逐欄呈現所有競品（含我方產品）。",
            "",
            "### 2. 功能比較矩陣",
            "列出 8-12 個關鍵功能/能力，用 ✅ / ❌ / ⚠️（部分支援）標示每家是否具備。",
            "輸出一個 ```chart 長條圖比較各競品功能完整度得分。",
            "",
            "### 3. 定位地圖分析",
            "在「價格」vs「功能完整度」兩個維度上，用文字描述各品牌所在象限，說明競爭格局。",
            "",
            "### 4. 差異化機會",
            "指出 3-5 個「競品都沒做好、我方可突破」的機會點，每個附：機會描述 / 執行建議 / 預估影響。",
            "",
            "### 5. 銷售反制腳本",
            "針對客戶可能說「我用 XX 就好了」的每個競品，寫一段 2-3 句的應對話術。",
            "全程使用繁體中文。",
          ]
            .filter(Boolean)
            .join("\n")
        : [
            "You are a competitive strategy analyst delivering an objective, comprehensive competitive landscape review.",
            "",
            `Our Product: ${v.product}`,
            `Competitors: ${v.competitors}`,
            v.market ? `Target Market: ${v.market}` : "",
            "",
            "### 1. Competitor Snapshots",
            "Per competitor: positioning (1 sentence) / core features (3–5) / pricing strategy / target customers / key strengths / key weaknesses. Markdown table including our product.",
            "",
            "### 2. Feature Comparison Matrix",
            "8–12 key capabilities; ✅ / ❌ / ⚠️ (partial) per vendor. Output a ```chart bar chart of feature completeness scores.",
            "",
            "### 3. Positioning Map",
            "Price vs Feature Completeness quadrant analysis in text — describe where each brand sits and the competitive dynamics.",
            "",
            "### 4. Differentiation Opportunities",
            "3–5 gaps where competitors fall short and we can win: Opportunity / Action / Estimated impact.",
            "",
            "### 5. Sales Battle Cards",
            "For each competitor, 2–3 sentence response to 'Why not just use [X]?'",
            "Respond entirely in English.",
          ]
            .filter(Boolean)
            .join("\n"),
  },

  // ── 8. 社群月曆 ───────────────────────────────────────────────────────────
  social: {
    inputs: [
      {
        key: "brand",
        label: "品牌名稱 / 行業",
        labelEn: "Brand Name / Industry",
        type: "text",
        required: true,
        placeholder: "例：美樂信科技，企業 AI 顧問",
        placeholderEn: "e.g. MLTech, enterprise AI consulting",
      },
      {
        key: "audience",
        label: "目標受眾",
        labelEn: "Target Audience",
        type: "text",
        required: true,
        placeholder: "例：台灣 B2B 中小企業老闆、HR 主管",
        placeholderEn: "e.g. Taiwan B2B SME owners, HR directors",
      },
      {
        key: "themes",
        label: "本月主題 / 活動 / 產品",
        labelEn: "Monthly Theme / Events / Products",
        type: "textarea",
        required: true,
        placeholder: "例：新品發布、週年慶、秋季促銷、AI 趨勢系列",
        placeholderEn: "e.g. product launch, anniversary, AI trend series",
      },
      {
        key: "platforms",
        label: "目標平台（選填）",
        labelEn: "Target Platforms (optional)",
        type: "text",
        required: false,
        placeholder: "例：Facebook、LinkedIn、Instagram、LINE",
        placeholderEn: "e.g. Facebook, LinkedIn, Instagram, LINE",
      },
    ],
    prompt: (v, lang) =>
      lang === "zh"
        ? [
            "你是一位社群媒體策略師，專長為 B2B 和 B2C 品牌規劃高互動率的內容月曆。",
            "",
            `品牌：${v.brand}`,
            `受眾：${v.audience}`,
            `主題：${v.themes}`,
            v.platforms ? `平台：${v.platforms}` : "平台：Facebook、Instagram、LinkedIn",
            "",
            "請規劃一個完整的社群內容月曆（4 週，每週 3-4 篇貼文）：",
            "",
            "### 內容策略摘要",
            "本月核心訊息 / 內容柱（3-4 個主題類型）/ 語調指引",
            "",
            "### 完整月曆",
            "用 Markdown 表格：週次 / 日期建議 / 平台 / 貼文類型 / 主標題（≤20 字）/ 貼文正文（≤150 字）/ Hashtag（3-5 個）/ 附圖建議",
            "每週至少 1 篇有具體互動機制（問答、投票、挑戰）。",
            "",
            "### TOP 3 高潛力貼文",
            "從月曆中選出 3 篇最有傳播潛力的，給出完整貼文草稿（含 emoji、視覺建議）。",
            "",
            "### 數據追蹤建議",
            "每週追蹤的 3 個關鍵指標 + 如何根據成效調整策略。",
            "全程使用繁體中文。",
          ]
            .filter(Boolean)
            .join("\n")
        : [
            "You are a social media strategist who creates high-engagement content calendars for B2B and B2C brands.",
            "",
            `Brand: ${v.brand}`,
            `Audience: ${v.audience}`,
            `Monthly Themes: ${v.themes}`,
            v.platforms
              ? `Platforms: ${v.platforms}`
              : "Platforms: Facebook, Instagram, LinkedIn",
            "",
            "Create a full content calendar (4 weeks, 3–4 posts per week):",
            "",
            "### Content Strategy Summary",
            "Core monthly message / content pillars (3–4 types) / tone guidelines",
            "",
            "### Full Calendar",
            "Markdown table: Week / Suggested date / Platform / Post type / Headline (≤15 words) / Body copy (≤120 words) / Hashtags (3–5) / Visual suggestion. At least 1 interactive post per week (Q&A, poll, challenge).",
            "",
            "### Top 3 High-Potential Posts",
            "Select 3 most viral-worthy posts from the calendar; write full drafts (with emojis, visual notes).",
            "",
            "### Metrics to Track",
            "3 KPIs per week + how to adjust strategy based on performance.",
            "Respond entirely in English.",
          ]
            .filter(Boolean)
            .join("\n"),
  },

  // ── 9. 商業計畫審查 ───────────────────────────────────────────────────────
  bizreview: {
    inputs: [
      {
        key: "summary",
        label: "計畫摘要（電梯簡報）",
        labelEn: "Executive Summary (Elevator Pitch)",
        type: "textarea",
        required: true,
        placeholder: "用 3-5 句描述：你是誰、解決什麼問題、怎麼賺錢",
        placeholderEn: "3–5 sentences: who you are, what problem you solve, how you make money",
      },
      {
        key: "model",
        label: "商業模式",
        labelEn: "Business Model",
        type: "textarea",
        required: true,
        placeholder: "收費方式、客戶獲取管道、主要合作夥伴、成本結構…",
        placeholderEn: "Revenue model, customer acquisition, key partners, cost structure…",
      },
      {
        key: "market",
        label: "目標市場 / 市場規模",
        labelEn: "Target Market / Market Size",
        type: "text",
        required: true,
        placeholder: "例：台灣中小製造業，約 1.4 萬家，TAM 50 億",
        placeholderEn: "e.g. Taiwan SME manufacturers, ~14,000 firms, TAM NT$5B",
      },
      {
        key: "financials",
        label: "財務預測 / 重要假設",
        labelEn: "Financial Projections / Key Assumptions",
        type: "textarea",
        required: false,
        placeholder: "年度收入目標、主要假設（客單價、轉換率、月增速）",
        placeholderEn: "Annual revenue target, key assumptions (ARPU, conversion rate, MoM growth)",
      },
    ],
    prompt: (v, lang) =>
      lang === "zh"
        ? [
            "你是一位整合正反兩方觀點的資深商業顧問，提供平衡、深度的商業計畫評估。",
            "",
            `摘要：${v.summary}`,
            `商業模式：${v.model}`,
            `市場：${v.market}`,
            v.financials ? `財務：${v.financials}` : "",
            "",
            "### 1. 支持者審查（Pro）",
            "從支持者角度：核心優勢（3-5 點）/ 市場時機分析 / 競爭護城河 / 最有說服力的部分",
            "",
            "### 2. 挑戰者審查（Con）",
            "從批評者角度：關鍵風險（3-5 點）/ 假設是否成立 / 商業模式漏洞 / 最令人擔憂的部分",
            "",
            "### 3. 評分卡",
            "依以下八個維度評分（1-10）並給出理由：問題清晰度、解決方案獨特性、市場規模、商業模式可行性、競爭壁壘、團隊能力（依計畫描述）、財務合理性、執行風險。",
            "用 Markdown 表格呈現，最後給出總分與投資建議（強烈建議/有條件建議/需大幅修改/不建議）。",
            "輸出一個 ```chart 長條圖顯示八維評分。",
            "",
            "### 4. 前三大改善建議",
            "最優先需要補強的 3 件事，每件附：問題說明 / 建議行動 / 預期效果。",
            "全程使用繁體中文。",
          ]
            .filter(Boolean)
            .join("\n")
        : [
            "You are a balanced senior business advisor who integrates pro and con perspectives for deep business plan evaluation.",
            "",
            `Summary: ${v.summary}`,
            `Business Model: ${v.model}`,
            `Market: ${v.market}`,
            v.financials ? `Financials: ${v.financials}` : "",
            "",
            "### 1. Advocate Review (Pro)",
            "Core strengths (3–5) / market timing / competitive moat / most compelling elements",
            "",
            "### 2. Challenger Review (Con)",
            "Key risks (3–5) / assumption validity / business model gaps / most concerning elements",
            "",
            "### 3. Scorecard",
            "Rate 8 dimensions (1–10): Problem clarity / Solution uniqueness / Market size / Business model viability / Competitive moat / Team capability / Financial soundness / Execution risk. Markdown table + overall score + recommendation (Strongly recommend / Conditionally / Needs major rework / Not recommended). Output a ```chart bar chart of the 8 scores.",
            "",
            "### 4. Top 3 Improvements",
            "The 3 highest-priority improvements: Issue / Recommended action / Expected outcome.",
            "Respond entirely in English.",
          ]
            .filter(Boolean)
            .join("\n"),
  },

  // ── 10. 顧客反應模擬 ──────────────────────────────────────────────────────
  customersim: {
    inputs: [
      {
        key: "offer",
        label: "產品 / 服務 / 定價",
        labelEn: "Product / Service / Pricing",
        type: "textarea",
        required: true,
        placeholder: "描述你要推出的產品或方案，包含定價、主要特色",
        placeholderEn: "Describe your product or offer, including pricing and key features",
      },
      {
        key: "personas",
        label: "目標客群描述",
        labelEn: "Target Customer Segments",
        type: "textarea",
        required: true,
        placeholder: "例：中小企業主、採購主管、IT 部門、個人使用者",
        placeholderEn: "e.g. SME owner, procurement manager, IT dept, individual consumer",
      },
      {
        key: "scenario",
        label: "推出情境 / 渠道（選填）",
        labelEn: "Launch Scenario / Channel (optional)",
        type: "text",
        required: false,
        placeholder: "例：官網冷開發、業務拜訪、社群廣告、展覽現場",
        placeholderEn: "e.g. cold website launch, sales visit, social ads, trade show",
      },
    ],
    prompt: (v, lang) =>
      lang === "zh"
        ? [
            "你是一位精通消費者心理與市場反應的顧問，能模擬不同客群的真實反應。",
            "",
            `產品/服務：${v.offer}`,
            `目標客群：${v.personas}`,
            v.scenario ? `推出情境：${v.scenario}` : "",
            "",
            "### 四個顧客角色的即時反應",
            "依據提供的客群描述，定義 4 個代表性角色（含姓名、職稱、背景）。",
            "每個角色給出：",
            "- 第一反應（情緒 + 1-2 句話）",
            "- 主要顧慮（2-3 個）",
            "- 購買意願（1-10 分）+ 理由",
            "- 最可能問的 2 個問題",
            "用 Markdown 表格對比四個角色。",
            "",
            "### 流失風險分析",
            "哪個角色最可能流失？流失原因？改善建議（定價/功能/溝通方式）？",
            "輸出一個 ```chart 長條圖顯示四個角色的購買意願分數。",
            "",
            "### 傳播潛力分析",
            "哪個角色最可能主動推薦？他們會怎麼說？估算病毒係數（K-factor）。",
            "",
            "### 銷售建議",
            "針對每個角色：最佳切入話術（1-2 句）/ 主要反對意見的應對方式 / 成交時機判斷。",
            "全程使用繁體中文。",
          ]
            .filter(Boolean)
            .join("\n")
        : [
            "You are a consumer psychology and market response expert who simulates authentic customer reactions.",
            "",
            `Offer: ${v.offer}`,
            `Target Segments: ${v.personas}`,
            v.scenario ? `Launch Scenario: ${v.scenario}` : "",
            "",
            "### 4 Customer Persona Reactions",
            "Define 4 representative personas (name, title, background) from the segments provided. Per persona:",
            "- First reaction (emotion + 1–2 sentences)",
            "- Top 2–3 concerns",
            "- Purchase intent score (1–10) + rationale",
            "- 2 most likely questions asked",
            "Markdown table comparing all four.",
            "",
            "### Churn Risk Analysis",
            "Which persona is most likely to churn? Why? Improvement suggestions (pricing / features / messaging). Output a ```chart bar chart of purchase intent scores.",
            "",
            "### Viral Spread Analysis",
            "Which persona is most likely to refer others? What would they say? Estimate K-factor.",
            "",
            "### Sales Recommendations",
            "Per persona: best opening line (1–2 sentences) / how to handle top objection / signals that they're ready to buy.",
            "Respond entirely in English.",
          ]
            .filter(Boolean)
            .join("\n"),
  },
};
