#!/usr/bin/env node
/**
 * generate-agents.cjs
 *
 * Migrates the 999 agent definitions from the upstream MLSTech_official
 * `lib/tools-meta.ts` into `lib/agents/data.ts`.
 *
 * The upstream file is a plain object literal keyed by agent id:
 *   export const TOOLS_META: Record<string, ToolMeta> = { id: { label, desc, cat, labelEn, descEn }, ... }
 *
 * We do NOT hand-write 999 files. Instead we emit a single typed data module
 * that `lib/agents/index.ts` turns into full Agent objects (default inputs +
 * generic prompt builder) at runtime. To customise a single agent, override it
 * in `lib/agents/overrides.ts` — see CONTRIBUTING.md.
 *
 * Usage: node scripts/generate-agents.cjs [path-to-tools-meta.ts]
 */

const fs = require("fs");
const path = require("path");
const vm = require("vm");

const DEFAULT_SOURCE = path.resolve(
  __dirname,
  "..",
  "..",
  "..",
  "Web",
  "MLSTech_official",
  "lib",
  "tools-meta.ts"
);

const sourcePath = process.argv[2]
  ? path.resolve(process.argv[2])
  : DEFAULT_SOURCE;

const outPath = path.resolve(__dirname, "..", "lib", "agents", "data.ts");

// Categories declared by the design spec, plus `design` which exists in the
// real data. Keep in sync with lib/agents/types.ts.
const KNOWN_CATEGORIES = new Set([
  "product",
  "brand",
  "finance",
  "strategy",
  "marketing",
  "legal",
  "sales",
  "people",
  "ops",
  "dev",
  "content",
  "operations",
  "design",
]);

function loadToolsMeta(file) {
  if (!fs.existsSync(file)) {
    throw new Error(
      `Source file not found: ${file}\n` +
        `Pass the path explicitly: node scripts/generate-agents.cjs <path-to-tools-meta.ts>`
    );
  }
  const raw = fs.readFileSync(file, "utf8");

  // Strip TypeScript so the object literal can be evaluated as plain JS.
  // We assign to an undeclared `__RESULT__`, which (in sloppy mode) lands as a
  // property on the vm context's global object — unambiguous and not dependent
  // on how V8 wires up `globalThis` in a contextified object.
  let js = raw
    // `export const TOOLS_META: Record<string, ToolMeta> = {` -> `__RESULT__ = {`
    .replace(/export\s+const\s+TOOLS_META\s*:[^=]*=/, "__RESULT__ =")
    // drop the type alias line
    .replace(/export\s+type\s+ToolMeta\s*=.*$/m, "")
    // drop the trailing TOOL_COUNT export
    .replace(/export\s+const\s+TOOL_COUNT\s*=.*$/m, "");

  const context = { __RESULT__: null };
  vm.createContext(context);
  vm.runInContext(js, context, { filename: file });

  const meta = context.__RESULT__;
  if (!meta || typeof meta !== "object") {
    throw new Error("Failed to extract TOOLS_META from source file.");
  }
  return meta;
}

function esc(str) {
  // JSON.stringify gives us correctly escaped, quoted strings (handles
  // newlines, quotes, unicode). Good enough for emitting TS string literals.
  return JSON.stringify(str == null ? "" : String(str));
}

function main() {
  const meta = loadToolsMeta(sourcePath);
  const ids = Object.keys(meta);

  const seenCats = new Set();
  const records = [];

  for (const id of ids) {
    const m = meta[id] || {};
    const cat = m.cat || "operations";
    seenCats.add(cat);
    if (!KNOWN_CATEGORIES.has(cat)) {
      console.warn(`[warn] unknown category "${cat}" on agent "${id}"`);
    }
    records.push(
      `  { id: ${esc(id)}, label: ${esc(m.label)}, labelEn: ${esc(
        m.labelEn || m.label
      )}, desc: ${esc(m.desc)}, descEn: ${esc(m.descEn || m.desc)}, cat: ${esc(
        cat
      )} },`
    );
  }

  const header = `// AUTO-GENERATED by scripts/generate-agents.cjs — DO NOT EDIT BY HAND.
// Source: MLSTech_official/lib/tools-meta.ts (${ids.length} agents)
// Regenerate: npm run gen:agents
//
// To customise a single agent's inputs or prompt, add an entry to
// lib/agents/overrides.ts instead of editing this file.

import type { AgentMeta } from "./types";

export const AGENT_DATA: AgentMeta[] = [
`;

  const footer = `];

export const AGENT_COUNT = AGENT_DATA.length;
`;

  fs.writeFileSync(outPath, header + records.join("\n") + "\n" + footer, "utf8");

  console.log(
    `Wrote ${records.length} agents to ${path.relative(
      process.cwd(),
      outPath
    )}`
  );
  console.log(`Categories: ${[...seenCats].sort().join(", ")}`);
}

main();
